falco.yaml
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp

Signed-off-by: Michele Zuccala <michele@zuccala.com>
/kind feature
Not sure about the appropriate `/area` label here, could you please advise?
This PR adds support for customizable metadata fetching params that are going to be introduced with https://github.com/falcosecurity/libs/pull/40.
WIP because I'm planning to set the correct libs version and checksum once https://github.com/falcosecurity/libs/pull/40 gets merged.
For now it's set to the feature branch name on https://github.com/falcosecurity/libs in order for this PR to be easily tested. …

Add customizable metadata fetching params

---

scripts/falco-driver-loader

/kind bug
/area build
This PR set ```falco-driver-loader ``` ``` ENABLE_DOWNLOAD``` useful.
and try ```gcc``` version from high to low
before
```bash
$ls ./gcc-* | grep 'gcc-[0-9]\+' | sort -r
./gcc-9
./gcc-8
./gcc-3
./gcc-2
./gcc-11
./gcc-10
./gcc-1
```
now
```bash
$ ls ./gcc-* | grep 'gcc-[0-9]\+' | sort -n -r -k 2 -t - 
./gcc-11
./gcc-10
./gcc-9
./gcc-8
./gcc-3
./gcc-2
./gcc-1
```
Fixes #
```release-note
fix(scripts): correct lookup order when trying multiple `gcc` versions in the `falco-driver-loader` script
```

fix(scripts): correct lookup order when trying multiple `gcc` versions in the `falco-driver-loader` script

---

scripts/rpm/falco.service

Signed-off-by: Domenico Chirabino <chirabino@protonmail.com>
/kind bug
/area engine
**What this PR does**:
This PR set `StandardOutput` to `null` in the systemd unit configuration `falco.service`.
**Why we need it**
After the migration from initd to systemd (#1448), when falco is installed via systemd it writes to `/var/log/messages` by default.
The problem is not present when manually running Falco (without using systemd).
This is due to the default value in the systemd configuration: `DefaultStandardOutput=journal` (which falco inherits), so that Falco standard output is redirected to `/var/log/messages` (see https://manpages.debian.org/wheezy/systemd/systemd.conf.5.en.html).
At the time of writing a …

Systemd unit: Do not send falco alerts to /var/log/messages by default

---

cmake/modules/falcosecurity-libs.cmake

Signed-off-by: Michele Zuccala <michele@zuccala.com>
/kind feature
/area build
This PR bumps driver version to https://github.com/falcosecurity/libs/commit/5727c456ce22f3c1da8c3b1d7d6b6937a9b2126b since some useful PRs were merged there since last update.
Just to mention a few:
- https://github.com/falcosecurity/libs/pull/40
- https://github.com/falcosecurity/libs/pull/49
- https://github.com/falcosecurity/libs/pull/56
- https://github.com/falcosecurity/libs/pull/59
- https://github.com/falcosecurity/libs/pull/72
- https://github.com/falcosecurity/libs/pull/81
N/A
N/A …

Bump driver version to `5727c45`

---

falco.yaml
test/confs/psp.yaml
test/falco_test.py
test/falco_tests.yaml
userspace/engine/falco_engine.cpp
userspace/engine/formats.cpp
userspace/engine/formats.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h

/kind cleanup
/kind feature
/area engine
/area tests
Since the recent merge of https://github.com/falcosecurity/falco/pull/1714, `tags` and `source` fields are now part of both the grpc and json outputs. However, the semantic of the json output is not clear in some corner cases, such as when no tags are defined in a rule. Also, users can't configure whether to include `tags` in the json outputs or not, which instead is possible for the `output` field. Moreover, no test cases are yet present for asserting the expected outcome of these corner cases. These issues were reported in https://github.com/falcosecurity/falco/pull/1714#issuecomment-924800821 by @leodido …

update(outputs): add configuration option for tags in json outputs

---

proposals/20200901-artifacts-cleanup.md

/kind cleanup
Clarify that the `drivers/cleanup` job we needed when we were using Bintray to store the Falco drivers is not needed anymore. And that, its related proposal has been superseded by a newer one (already implemented and in place during the last year).
NONE
/milestone 0.30.0
```release-note
docs: clarify that previous Falco drivers will remain available at https://download.falco.org and no automated cleanup is run anymore
```

update(proposal): clarify that old drivers are not removed anymore

---

cmake/modules/falcosecurity-libs.cmake

Signed-off-by: Michele Zuccala <michele@zuccala.com>
/kind bug
/area build
This is a direct consequence of https://github.com/falcosecurity/libs/pull/90 and it's needed to unlock Falco 0.30.0 release.
```release-note
update: bump driver version to 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4
```

build(cmake): bump libs version to 3aa7a83

---

scripts/falco-driver-loader

Signed-off-by: David Windsor <dwindsor@secureworks.com>
/kind bug
/area build
Currently, SELinux prevents `falco-driver-loader` from calling `insmod` on falco .ko files. This is because the .ko files are mislabeled - they need to be relabeled `modules_object_t`:
```
type=AVC msg=audit(1634143507.210:1101): avc:  denied  { module_load } for  pid=15732 comm="insmod" path="/root/.falco/falco_centos_4.18.0-305.3.1.el8.x86_64_1.ko" …
```

Fix falco-driver-loader SELinux insmod denials

---

scripts/publish-deb
scripts/publish-rpm

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
Currently, Falco Linux packages are signed with SHA1. This prevents the installation of Falco on high-assurance systems that do not allow for the installation of packages without signatures made using SHA256.
Fixes #1751
**Special …

Sign Packages and Linux Repositories with SHA256.

---

cmake/modules/GetFalcoVersion.cmake

/kind bug
/area build
When FALCO_VERSION was provided via a CMake variable, the build would
eventually fail because the partial version variables hadn't been
populated. Move the creation of those outside the check of FALCO_VERSION
being set so they also happen when that is provided too.
Fixes: #1654
```release-note
NONE
```

build: always populate partial version variables

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h

`Signed-off-by: Federico Di Pierro <nierro92@gmail.com>`
/kind cleanup
/area engine
Avoid creating multiple methods to only route that m_default_ruleset to main method; properly use a default argument instead.
Fixes #
```release-note
NONE
```

style(userspace/engine): avoid creating multiple versions of methods only to assume default ruleset. Use a default argument instead.

---

test/falco_tests.yaml
test/rules/disabled_rule_using_enabled_flag_only.yaml
test/rules/enabled_rule_using_enabled_flag_only.yaml
test/rules/invalid_append_rule_without_condition.yaml
userspace/engine/lua/rule_loader.lua

Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
/kind bug
/area engine
This enables overwriting rules by specifying their name and the `enabled` field only, so that users can easily enable/disable already-defined rules. The expected behavior is to be able to overwrite rules like the following (example from @leogr):
```
- rule: A rule enabled by default
enabled: false
```
The following issues currently prevent this from being supported:
- Every rule is forced to either specify a `condition` or an `exception` field. However, this conceptually applies only to rules having `append` set as `true`.
- …

fix(userspace/engine): supporting enabled-only overwritten rules

---

test/falco_tests_exceptions.yaml
test/rules/exceptions/rule_exception_new_no_field_append.yaml
test/rules/exceptions/rule_exception_new_second_field_append.yaml
test/rules/exceptions/rule_exception_new_single_field_append.yaml
userspace/engine/falco_engine_version.h
userspace/engine/lua/rule_loader.lua

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
/area rules
> /area tests
PR introduces appending of new fully valid exception objects to existing rules.
Fixes #
```release-note
update: allow append of new exceptions …
```

Allow append of new exceptions to rules

---

cmake/modules/DownloadFakeIt.cmake

/kind cleanup
/area build
/area tests
While working on the unit tests for https://github.com/falcosecurity/falco/pull/1792, I discovered that our `FakeIt` mocking lib is currently broken due to an incompatibility with the version of `Catch2` our cmake setup depends on. 
Even though FakeIt is not used by our unit tests yet, I still believe this is a blocker for the future improvements of our testing suite.
The issue was caused by a macro renaming happened in `Catch2`. After doing some research, this PR seems to fix it: https://github.com/eranpeer/FakeIt/pull/195
**Special …

update(build): bump FakeIt version

---

rules/falco_rules.yaml

/area rules
Added additional binaries that are capable of remote file copy. These binaries are commonly used as a prerequisite to command and control.
N/A
N/A
```release-note
rule(Launch Remote File Copy Tools in Container): add additional binaries: curl and wget.
```

Add wget and curl to remote_file_copy_binaries

---

scripts/falco-driver-loader

Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
/kind bug
/area build
This fixes the `--clean` option of `falco-driver-loader`, which currently fails to remove the loaded kernel modules. The fail was caused by grabbing the wrong token from the output of `dkms status -m falco`.
```release-note
NONE
```

correctly clean loaded drivers in `falco-driver-loader`

---

rules/falco_rules.yaml
test/rules/tagged_rules.yaml

/kind feature
/area rules
This includes the `openat2` in the default rulesets, following up the recent merging of https://github.com/falcosecurity/libs/pull/80.
```release-note
rules: add support to openat2 in default ruleset
```

rules: add support to openat2 in default ruleset

---

userspace/falco/outputs_file.cpp

/kind bug
/area engine
This PR just throws an error if desired `output_file` failed to be created:
```
Mon Nov  8 11:00:01 2021: Falco version 0.30.0-19+f7893fb (driver version a03ccfda795f2ba711b80f69cb06869f2b63121b)
Mon Nov  8 11:00:01 2021: Falco initialized with configuration file ../falco.yaml
Mon Nov  8 11:00:01 2021: Loading rules from file ../rules/falco_rules.yaml:
Mon Nov  8 11:00:02 2021: Starting internal webserver, listening on port 8765
Mon Nov  8 11:00:10 2021: file: failed to open output file /home/federicoo/events.txt
11:00:10.602534779: Error File …
```

fix(userspace/falco): in case output_file cannot be opened, throw a falco exception

---

userspace/falco/webserver.cpp

/kind bug
/area engine
Do not strictly require "application/json" content-type string in k8s_audit_handler::handlePost(); instead, accept any Content-Type that has "application/json" in it.
Fixes #1702 
```release-note
fix(userspace/falco): accept 'Content-Type' header that contains "application/json", but it is not strictly equal to it
```

fix(userspace/falco): accept 'Content-Type' header that contains "application/json", but it is not strictly equal to it

---

rules/falco_rules.yaml

Signed-off-by: Calvin Bui <3604363+calvinbui@users.noreply.github.com>
> /kind bug
> /kind design
Fixes #
```release-note
Add the official Falco ECR repository to rules
```

Add ECR repository to rules

---

rules/falco_rules.yaml

Signed-off-by: Angelo Puglisi <angelopuglisi86@gmail.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Typo fix in rule output
Fixes #
```release-note
NONE
```

fix(rules): typo in "Create Symlink Over Sensitive Files" rule output

---

rules/falco_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
The `sensitive_mount` macro contains both the docker and cri-o sockets. If mounted inside a container, they can be used to escalate privileges, since they allow to communicate with daemon processes running as root. For exactly the same reason, also the containerd …

rules: add containerd socket to sensitive_mount macro

---

OWNERS

I would like propose myself as a maintainer of `falcosecurity/falco`.
After actively contributing to this repository over the past three months, I want to commit to spend my time working on it. I think my case meets the criteria of the _process for becoming a maintainer_ from [falcosecurity governance](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md#process-for-becoming-a-maintainer). As such, I would happily to take on the maintainer duties to support Falco's growth and to assist other contributors too. …

docs: add jasondellaluce to OWNERS

---

cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_engine_version.h
userspace/engine/falco_utils.cpp
userspace/engine/json_evt.cpp
userspace/engine/json_evt.h
userspace/falco/falco.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
Clean up --list output with better formatting and no duplicate sections across event sources.
```

Cleanup list fields

---

userspace/falco/falco.cpp

/kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area rules
> /area tests
This PR allows using the `--list` Falco option to selectively list fields related to sources introduced by plugins, for instance `--list=aws_cloudtrail`.
Fixes # …

chore: improve --list output using is_source_valid 

---

userspace/falco/falco_outputs.cpp
userspace/falco/outputs.h
userspace/falco/outputs_http.cpp

/kind bug
/area engine
The PR sets the http output Content-type header to a more meaningful value (text/plain) when json_output is disabled.
Fixes #1824 
```release-note
fix: set http output contenttype to text/plain when json output is disabled
```

fix: set http output contenttype to text/plain when json output is disabled

---

userspace/falco/falco.cpp

Signed-off-by: Federico Di Pierro nierro92@gmail.com
What type of PR is this?
/kind feature
Any specific area of the project related to this PR?
/area engine
What this PR does / why we need it:
Updates libs version and adds support for kernel side simple consumer.
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
```release-note
new: simpleconsumer filtering is now being done at kernel level
```

new(userspace/falco): add support for kernel side simple consumer

---

userspace/falco/outputs.proto
userspace/falco/outputs_grpc.cpp
userspace/falco/schema.proto

/kind design
/kind feature
/area engine
See https://github.com/falcosecurity/falco/issues/1826 for details about the issue.
This deprecates the `source` field in `outputs.proto`, and adds a `PLUGIN` entry in the source enum. The goal is to maintain backward compatibility for clients relying on old protobufs versions. Accordingly, a new string field for the event source is added. This is required by plugin system, as the source name is determined by the source plugin loaded and it's not enumerable anymore.
Fixes #1826 
```release-note
update: …
```

update: support non-enumerable event sources in gRPC outputs service

---

userspace/engine/lua/rule_loader.lua

When testing exceptions with a large number of auto-generated values we faced an issue with Falco validator memory starvation. That was due to the code performing string concatenation with ".." operator.  Due to the string immutability, each of such operations creates a new copy of the result string keeping the old one in the memory till the GC is run, and the GS won't run at least until the function returns. The above generates a snowball of allocated and unused memory. Rough estimates could give at least an N^2 growth rate. In our tests a ~1MB rules YAML required between 1-2 GB of memory to be parsed.
>/kind bug
> /kind design
> /area engine
fix memory …

replace ".." concatenation with table.concat

---

userspace/engine/json_evt.cpp

/kind bug
/area engine
Due to the changes of https://github.com/falcosecurity/falco/pull/1715, `json_event_formatter` does not format events properly when the JSON output is enabled. This is caused by the return value not being propagated properly. This seems to be what caused the issues of #1845.
Fixes #1845
This has been tested by building Falco locally from source. Running the following tests without the changes of this PR made me reproduce the issues of #1845, which now seem to be fixed.
```
mkdir build
cd build
cmake ..
make falco …
```

fix(engine): correctly format json output in json_event

---

userspace/falco/configuration.h

/kind cleanup
/kind design
/kind feature
/area engine
This PR cleans up the plugin configuration reading, and supports init configs defined in YAML format. With this, users can define the `init_config` fields either as a string, or as a YAML map. In the first case, the string is opaque and passed as-is to the plugin framework of `libs`. In the second case, the YAML is parsed and converted to a JSON string. This is useful for two purposes:
- Coupled with the feature of https://github.com/falcosecurity/libs/pull/175, this allows defining structured configuration data more easily, along with automatic validation and error checking
- Defining/overriding plugin init …

new(configuration): support defining plugin init config as a YAML

---

.circleci/config.yml
cmake/cpack/CMakeCPackOptions.cmake
docker/no-driver/Dockerfile

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
Currently, we distribute a static binary as `.tar.gz` which is build with musl libc. The build is as static as it gets but it's not possible to load plugins in such a build because they require dynamic loading to be available which cannot be enabled without a …

new(build): use a dynamic build for the bin/tgz distribution

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine_version.h

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

Field properties changes

---

falco.yaml

/area rules
Thanks to @kirin-13 [reporting](https://github.com/falcosecurity/charts/pull/302), this PR fixes a typo in the `falco.yaml` comments. It changes the priority level from `info` to `informational`.
```release-note
NONE
```

docs: fix priority level "info" to "informational"

---

rules/falco_rules.yaml

/area rules
As suggested by @karthikc911 we could avoid several false positives by removing the `apt-config` utility from debian packages monitoring list. I open this PR only because it could be useful to have it merged in Falco 0.31 but @karthikc911 had the original idea. For more details refer to [the original Pull Request](https://github.com/falcosecurity/falco/pull/1576) or to the [slack channel](https://kubernetes.slack.com/archives/CMWH3EH32/p1615341172249000). …

refactor: remove apt-config utility from debian_packages monitoring

---

cmake/modules/falcosecurity-libs.cmake
cmake/modules/plugins.cmake

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Updates plugins to latest versions; updated libs to latest version.
Fixes # …

build: bump driver version and updated plugins to latest versions adding platform name to artifact url

---

rules/falco_rules.yaml
rules/k8s_audit_rules.yaml
test/falco_k8s_audit_tests.yaml

/kind cleanup
/area rules
The `falco_hostnetwork_images` list is defined in `falco_rules.yaml` but it's unused in it.
This PR moves it to avoid the warning when using only `falco_rules.yaml`. 
```console
When reading rules content: 1 warnings:
list falco_hostnetwork_images not referred to by any rule/macro/list
```
NONE
The `falco_hostnetwork_images` list is only used in `k8s_audit_rules.yaml`.
```release-note
rule(list falco_hostnetwork_images): moved to …
```

move falco_hostnetwork_images list to k8s_audit_rules.yaml to avoid a warning

---

scripts/falco-driver-loader

/kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
This PR changes the try order for the kernel module installation.
Previously, the first attempt was to load an already installed module (if any) by using `modprobe`. However, that way would possibly load an older …

update(scripts/falco-driver-loader): load the latest version first

---

userspace/engine/lua/CMakeLists.txt
userspace/engine/lua/rule_loader.lua
userspace/engine/rules.cpp
userspace/engine/ruleset.cpp
userspace/falco/falco.cpp

/kind bug
> /kind design
/area build
/area engine
> /area rules
> /area tests
* Any load_rules warning is now printed (not only on verbose mode)
* Added back a "performance hit" comment when ruleset has a rule without evt.type
* Check for ignored events warning only when "-A" flag is not actually passed
* Fixed a lua CMakeLists issue that …

build: updated some warning strings; properly refresh lua files embedded in falco

---

rules/falco_rules.yaml

/area rules
This PR is a result of the bypass research published [~~here~~](https://github.com/blackberry/Falco-bypasses) (for now kept private). The research introduced several new bypass techniques and expanded on several already-known bypasses. 
This PR touches five existing rules and introduces one new rule.
This PR does not cover the bypasses found in the original research fully. Rather it follows a low-hanging fruit approach and focuses on syntactical fixes that do not require structural changes to the rule engine or kernel probes.
**Does this PR …

Bypass research issues

---

rules/falco_rules.yaml

/area rules
As suggested here by we must monitor also `execveat` events to check if a new process is spawned. 
Ref. #1857 
```release-note
rule(macro spawned_process): monitor also processes spawned by `execveat`
```

rule(falco_rules): update evt.type for spawned process macro

---

CMakeLists.txt
userspace/falco/falco.cpp

/kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Falco can be built with musl-libc but won't have plugin support in that case. Do not display the relevant option in the command line help. Likewise, do not include plugin directories as they cannot be used.
**Which issue(s) …

fix(build): do not show plugin options in musl optimized builds

---

.circleci/config.yml

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
This change allows Falco to be built and published in both static (with musl) and dynamic (with glibc) flavors for the binary package. Note that static is more compatible but lacks plugin support. …

new(build): publish both static and glibc binaries

---

cmake/modules/plugins.cmake
userspace/engine/ruleset.cpp

/kind bug
> /kind design
/area build
/area engine
> /area rules
> /area tests
Experimenting together with @jasondellaluce and @leogr  a possible solution for https://github.com/falcosecurity/plugins/issues/57
The issue was that `m_filter_all_event_types` was actually unused: for `syscalls` event source, we always have a …

fix(userspace/engine): actually make m_filter_all_event_types useful by properly using it as fallback when no filter event types is provided

---

cmake/modules/plugins.cmake
rules/aws_cloudtrail_rules.yaml
tests/engine/test_rulesets.cpp
userspace/engine/falco_engine.cpp
userspace/engine/rules.cpp
userspace/engine/ruleset.cpp
userspace/engine/ruleset.h

/kind bug
/area engine
/area tests
This completes the changes of https://github.com/falcosecurity/falco/pull/1875, by introducing protective logic on for the `evttypes()` method for the edge case of sources coming from plugins and `k8s_audit`. This prevents rules written from those sources to be unwillingly excluded from the rule index, which caused them to never match on any event.
This also bumps the plugin versions to the latest released versions, both in the CMake dependencies an in the `aws_cloudtrail_rules.yaml` ruleset.
Finally, semver check for required plugin versions has been added.
Fixes # …

fix: force-set evt.type for plugin source events

---

.circleci/config.yml

`Signed-off-by: Federico Di Pierro <nierro92@gmail.com>`
> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Centos8 is EoL since Dec 31th and its contents will be dropped on january 31th: https://www.centos.org/centos-linux-eol/
Fixes #
**Does …

build: dropped centos8 circleci build because it is useless

---

userspace/engine/lua/rule_loader.lua

/kind bug
On falco 0.31.0 I am seeing Informational rules being loaded when the priority in the config is set to only load Notice and above. 
Should fix falcosecurity/falco#1884.
I've not yet had the opportunity to test this resolves the bug, but I'm opening this to get feedback.
```release-note
fix for rules at the informational level being loaded at the notice level.
```

Fix for informational rules loaded at notice level

---

rules/falco_rules.yaml

Signed-off-by: Mac Chaffee <me@macchaffee.com>
/kind bug
/area rules
SSSD is a popular tool for getting Linux machines to interoperate with ActiveDirectory. Part of that process involves invoking `adcli` to update /etc/krb5.keytab periodically: https://github.com/SSSD/sssd/blob/a664e9ce08ca6c0f9eb2e260b25463eea9c7829b/src/providers/ad/ad_machine_pw_renewal.c#L30
Looks like we already have exceptions for some tools that update this file (`centrify_writing_krb`), but that exception doesn't include `adcli`
n/a
Here is an example false positive alert:
```
"16:34:45.928110723: Error …
```

Fix false-positive of sssd updating /etc/krb5.keytab

---

rules/falco_rules.yaml

Adds `npm` to `package_mgmt_binaries` for detection of "living off the land" style attacks that utilize NPM to pull down additional tooling/libraries
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Adds `npm` to the list of `package_management_binaries`. NodeJS is one of the most popular development languages in the world - and the …

Rule Update - Adds npm support to pkg mgt processes

---

rules/falco_rules.yaml

Polkit pkexec Local Privilege Escalation Vulnerability (CVE-2021-4034)
Co-authored-by: javery-sysdig <jason.avery@sysdig.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
This rule detects an attempt to exploit a privilege escalation vulnerability in …

rule(falco_rules): Polkit Local Privilege Escalation Vulnerability (CVE-2021-4034)

---

rules/falco_rules.yaml

Signed-off-by: pablopez <pablo.lopezzaldivar@sysdig.com>
/area rules
me and @pmusa found that some k8s clusters are using `kube-keepalive` instead of `keepalive`. This macro is affecting the katacoda lab for k8s environments. This change is not going to break anything, as it just extends the `proc.name` included in the rule condition. More info about it [here](https://github.com/aledbf/kube-keepalived-vip)
Example of the logs:
```
10:37:16.732178071: Error File below /etc opened for writing (user=root user_loginuid=-1 command=kube-keepalived --services-configmap=kube-system/vip-configmap parent=containerd-shim pcmdline=containerd-shim -namespace …
```

upgrade macro(keepalived_writing_conf)

---

cmake/modules/DownloadStringViewLite.cmake
cmake/modules/copy_files_to_build_dir.cmake
docker/local/rules/CMakeLists.txt
docker/local/traces/CMakeLists.txt
test/CMakeLists.txt
test/trace_files/CMakeLists.txt
test/trace_files/k8s_audit/CMakeLists.txt
test/trace_files/plugins/CMakeLists.txt
test/trace_files/psp/CMakeLists.txt

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
Several cmake changes to speed up/simplify builds for external projects and copying files from source-to-build …
```

Cmake speedups

---

CMakeLists.txt
cmake/modules/cxxopts.cmake
userspace/falco/CMakeLists.txt
userspace/falco/app_cmdline_options.cpp
userspace/falco/app_cmdline_options.h
userspace/falco/application.cpp
userspace/falco/application.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fixes #
```release-note
Replace direct getopt_long() cmdline option parsing with third-party cxxopts library.
```

Add cmdline opts library/initial falco application object

---

userspace/falco/configuration.h

/kind bug
/area engine
This fixes the bug of #1906. The error was related to a misuse of the `nlohmann` library during array construction when converting plugins init configs from YAML to JSON.
Fixes #1906
```release-note
fix(userspace/falco): correct plugins init config conversion from YAML to JSON
```

fix(userspace/falco): correct plugins init config conversion from YAML to JSON

---

userspace/engine/lua/modules/compiler.lua
userspace/engine/lua/rule_loader.lua

/kind cleanup
/area engine
This PR removes some pieces of Lua code that seem to be unused across the whole codebase, and perhaps are part of some unremoved legacy code.
```release-note
NONE
```

chore(userspace/engine): remove unused lua functions and state vars

---

cmake/modules/falcosecurity-libs.cmake

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
This PR brings the libs version up to date (to the time of writing), including the following:
- https://github.com/falcosecurity/libs/pull/235 
- https://github.com/falcosecurity/libs/pull/236 …

chore(build): update falco libs to b7eb0dd

---

rules/falco_rules.yaml

/kind bug
/kind feature
/area rules
This PR allows to whitelist specific containers to modify the shell config files.
When running on GKE with `COS_CONTAINERD` images, I get frequent messages about modified bash files, e.g.:
```
rule
Modify Shell Configuration File
container.id
host
fd.name
/var/lib/containerd/tmpmounts/containerd-mount584469562/root/.bashrc
```
Because this is a managed cluster, I can't influence what the nodes/host is doing and what processes might modify the bash config, so as a user, I'd …

Allow to whitelist shell config modifiers

---

rules/falco_rules.yaml

/kind feature
/area rules
This adds a new macro `user_known_mount_in_privileged_containers` which
allows the easier user-defined exclusions for the "Mount Launched in
Privileged Container" rule.
N/A
This would be cleaner with [exceptions](https://falco.org/docs/rules/exceptions/#rule-exceptions), but this feature is not used in the default ruleset yet, if I understand correctly.
```release-note
rule(Mount Launched in Privileged Container): added allowlist macro user_known_mount_in_privileged_containers.
```

Add user_known_mount_in_privileged_containers macro

---

README.md
brand/README.md

Adding plugin references to the documentation plus some minor improvements.
I haven't added a link to the plugin-sdk-cpp since it does not yet seem to be mature enough.
```release-note
NONE
```

docs: readme update and plugins

---

test/falco_tests_plugins.yaml
test/rules/plugins/cloudtrail_create_instances_exceptions.yaml
test/rules/plugins/cloudtrail_macro.yaml
userspace/engine/lua/rule_loader.lua

/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fix a bug where rules with unknown sources *and* exceptions, or macros with unknown sources, resulted in errors instead of warnings.
Fixes # …

Ignore unknown sources rules macros

---

cmake/modules/falcosecurity-libs.cmake
cmake/modules/plugins.cmake
test/plugins/test_extract.cpp
test/plugins/test_source.cpp
userspace/engine/json_evt.cpp
userspace/engine/json_evt.h

/kind cleanup
/kind feature
/area build
This bumps the libs version, and introduces some adaptations to comply with the new `extract()` filtercheck method interface introduced in https://github.com/falcosecurity/libs/pull/201.
In Falco, the K8S Audit source implementation always supported extracting list of values natively. Since the future of that implementation is to be refactored as a plugin, this PR only introduces simple method signature adaptations without refactoring the whole `json_evt` logic.
Fixes # …

update(build): bump libs to latest version

---

rules/k8s_audit_rules.yaml

EKS uses some users for its need which generate noise for this rule. 
Reference: https://docs.aws.amazon.com/eks/latest/userguide/default-roles-users.html
Co-authored-by: Alberto Pellitteri <alberto.pellitteri@sysdig.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
**What this PR does / why we …

rule(Disallowed K8s User): exclude allowed eks users

---

CHANGELOG.md
brand/README.md
docker/builder/root/usr/bin/scl_enable
proposals/20190826-grpc-outputs.md
proposals/20191030-api.md
proposals/20210501-plugin-system.md
userspace/engine/filter_macro_resolver.h
userspace/engine/lua/rule_loader.lua

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixing some typos found while browsing other projects shipping the rules.
Fixes #
Found by running the following command:
codespell -f -H -L aks,creat,chage -S .git
I can also add a GitHub …

Fix some typos

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/falco/falco.cpp
userspace/falco/webserver.cpp
userspace/falco/webserver.h

`falco_engine::process_event` gets called for every inspector event.
Profiling showed that std::map::find takes about 10% of `falco_engine::process_event`, and that can easily be improved by accessing the source by index.
https://gist.github.com/deepskyblue86/91ca71de9b464e5dcd87deac1b911a6d
| impl        | IR (just item access) | detail                                              |
|:------------|----------------------:|:----------------------------------------------------|
| original    |                  1450 | std::map::find                                      |
| vector      |                   150 | std::vector::at                                     |
> /kind bug
> /kind design
> /kind …

perf: change falco_engine::process_event to lookup sources by index

---

userspace/engine/falco_common.cpp
userspace/engine/falco_common.h
userspace/engine/stats_manager.cpp
userspace/falco/configuration.cpp
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/outputs_grpc.cpp

/kind cleanup
/area engine
This PR updates the Falco codebase to comply with the newest definitions of `falco_common` introduced in #1966. This also fixes the priority `info`/`informational` inconsistency that causes some bugs (e.g. gRPC enums).
```release-note
refactor: update definitions of falco_common
```

refactor: update definitions of falco_common

---

rules/k8s_audit_rules.yaml

This PR just fix the output in the rules K8s Serviceaccount Created/Deleted
Co-authored-by: AlbertoPellitteri <alberto.pellitteri@sysdig.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
This PR just fix the output in the rules K8s Serviceaccount …

Fixed ouput Rules K8s Serviceaccount Created/Deleted

---

rules/falco_rules.yaml
rules/k8s_audit_rules.yaml

/area rules
[Container threat detection](https://cloud.google.com/security-command-center/docs/how-to-use-container-threat-detection) is a feature of GCP security center that monitors cos nodes for changes and remote access attempts (it kinds of duplicate falco). It spawns a privileged DaemonSet in GKE clusters `kube-system` namespace, hence the need for  ignoring this image.
```release-note
NONE
```

rules: whitelist GCP's container threat detection image

---

.codespellignore
.github/workflows/codespell.yml
rules/okta_rules.yaml
userspace/engine/stats_manager.h

/kind cleanup
> /area tests
Folllow up to #1961 to prevent common typos to be added to the repo.
```release-note
NONE
```

Add codespell GitHub Action

---

cmake/modules/DownloadCatch.cmake

/kind bug
/area build
Upgrading catch2 addresses the problem reported in the following log:
```
In file included from /usr/include/signal.h:328,
from /home/leogr/code/github.com/falcosecurity/falco/build/catch2-prefix/include/catch.hpp:8007,
from /home/leogr/code/github.com/falcosecurity/falco/tests/test_base.cpp:18:
/home/leogr/code/github.com/falcosecurity/falco/build/catch2-prefix/include/catch.hpp:10791:58: error: call to non-'constexpr' function 'long int sysconf(int)'
10791 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
|                                                          ^~~~~~~~~~~
In file included from …
```

build(cmake): upgrade catch2 to 2.13.9

---

cmake/modules/falcosecurity-libs.cmake
tests/engine/test_filter_evttype_resolver.cpp
userspace/engine/filter_evttype_resolver.cpp
userspace/engine/filter_evttype_resolver.h
userspace/engine/filter_macro_resolver.cpp
userspace/engine/filter_macro_resolver.h
userspace/engine/indexed_vector.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_reader.h

/kind cleanup
/kind design
/area build
/area engine
```release-note
update(build): bump libs version to d6b75db133602dee81b4408902f2510275feae57
refactor(userspace/engine): use supported_operators helper from libsinsp filter parser
```

update: bump libs version and apply C++ best practices in engine

---

rules/falco_rules.yaml

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
/area rules
> /area tests
This PR adds a new rule for detecting if one or more powerful capabilities were granted to a container. Granting these capabilities to a container can ease escaping to the host in some circumstances, and I think it could also be used in lateral movements. I have …

new(rules): add rule to detect excessively capable container

---

cmake/modules/falcosecurity-libs.cmake
test/falco_tests_plugins.yaml
test/plugins/test_extract.cpp
test/plugins/test_source.cpp
userspace/falco/app_actions/list_plugins.cpp
userspace/falco/app_actions/load_plugins.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Port the plugins loading logic to new logic; it needs updated libs with this PR in: https://github.com/falcosecurity/libs/pull/274
Fixes # …

new(userspace/falco): use new plugin caps API

---

scripts/debian/postinst.in
scripts/debian/postrm.in
scripts/debian/prerm.in
scripts/falco-driver-loader
scripts/rpm/postinstall.in
scripts/rpm/postuninstall.in
scripts/rpm/preuninstall.in

/kind cleanup
/kind feature
/area build
This PR slightly modifies the behavior of the `falco-driver-loader` script. Now the cleaning phase enforces the deletion of the kernel module if it is still loaded. If the script is not able to detach the module, it waits until the user removes it manually. The user can do this by following some specific instructions that will be provided in the documentation... This is necessary to avoid incompatibility issues with driver versions, obtaining errors like the following:
```
Runtime error: Kernel module does not support PPM_IOCTL_GET_API_VERSION. Exiting.
```
This happens …

chore(falco_scripts): Update `falco-driver-loader` cleaning phase

---

rules/k8s_audit_rules.yaml

Fixes #1794.
/livez and /readyz don't require authentication and can generate a lot
of noise if the cluster is checked by an anonymous external
system.
Some k8s systems have those endpoints required to be anonymous, as per this
[link to an OpenShift
setup](http://static.open-scap.org/ssg-guides/ssg-ocp4-guide-cis.html#xccdf_org.ssgproject.content_rule_api_server_anonymous_auth).
> /kind bug
> /kind design
> Uncomment one (or more) `/area <>` …

rule(Anonymous Request Allowed): exclude {/livez, /readyz}

---

userspace/engine/CMakeLists.txt

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
`CURL_INCLUDE_DIR` is a leftover since now the correct include path is injected via libs.
Fixes #
```release-note
NONE
```

build(userspace/engine): cleanup unused include dir

---

userspace/falco/falco_outputs.cpp

/kind design
/kind feature
/area engine
Adds `hostname` as a field returned in json output
Fixes #1520 
I'm not normally a cpp developer, please bear with me 🙏 
I'm also definitely missing a docs update somewhere
```release-note
update: added `hostname` as a field in JSON output
```

Include origin host in output json

---

falco.yaml
userspace/falco/app_actions/create_signal_handlers.cpp
userspace/falco/app_actions/load_config.cpp
userspace/falco/app_actions/load_rules_files.cpp
userspace/falco/app_actions/print_support.cpp
userspace/falco/app_cmdline_options.cpp
userspace/falco/app_cmdline_options.h
userspace/falco/application.cpp
userspace/falco/application.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area rules
> /area tests
This PR adds a new config option `watch_config_files`, to allow it to trigger a Falco restart whenever a change is detected in the rules files or conf file.
Fixes # …

new(userspace/falco): added an option to listen to changes on the config file and rules files, and trigger a Falco reload

---

rules/falco_rules.yaml

This PR add a new rule to detect container escapes techniques (also used CVE-2022-0492 Linux Cgroup Container Escape Vulnerability) using new field available thread.cap_effective to check capabilities in the container which is part of the requirement for the exploitation. 
Reference: 
https://unit42.paloaltonetworks.com/cve-2022-0492-cgroups/
https://blog.trailofbits.com/2019/07/19/understanding-docker-container-escapes/
Co-authored-by: Lorenzo Susini <susinilorenzo1@gmail.com>
> /kind bug
> /kind design
> If contributing rules or changes to rules, please make sure to also uncomment one of …

New Rule Detect Linux Cgroup Container Escape Vulnerability (CVE-2022-0492)

---

rules/falco_rules.yaml

/area rules
Includes .ash_history in `rule: Delete or rename shell history`
Fixes #1605
```release-note
rule(macro truncate_shell_history): include .ash_history
rule(macro modify_shell_history): include .ash_history
```

Delete or rename shell history: .ash_history

---

test/falco_tests_plugins.yaml
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/falco/app_actions/load_rules_files.cpp

/kind cleanup
/kind feature
/area engine
This PR introduces a new `check_plugin_requirements` API  instead of the old `is_plugin_compatible` to check if a list of plugins satisfies all the version requirements.
```release-note
NONE
```

update(userspace/engine): introduce new `check_plugin_requirements` API

---

userspace/falco/app_actions/create_signal_handlers.cpp
userspace/falco/app_actions/daemonize.cpp
userspace/falco/app_actions/init_falco_engine.cpp
userspace/falco/app_actions/init_inspector.cpp
userspace/falco/app_actions/init_outputs.cpp
userspace/falco/app_actions/list_fields.cpp
userspace/falco/app_actions/list_plugins.cpp
userspace/falco/app_actions/load_config.cpp
userspace/falco/app_actions/load_plugins.cpp
userspace/falco/app_actions/load_rules_files.cpp
userspace/falco/app_actions/open_inspector.cpp
userspace/falco/app_actions/print_help.cpp
userspace/falco/app_actions/print_ignored_events.cpp
userspace/falco/app_actions/print_support.cpp
userspace/falco/app_actions/print_version.cpp
userspace/falco/app_actions/process_events.cpp
userspace/falco/app_actions/start_grpc_server.cpp
userspace/falco/app_actions/start_webserver.cpp
userspace/falco/app_actions/validate_rules_files.cpp
userspace/falco/application.cpp
userspace/falco/application.h
userspace/falco/falco.cpp

/kind cleanup
/kind feature
/area engine
This PR adds new methods `fatal`, `exit`, and `ok` to `run_result` struct in order to simplify the Falco termination phase.
```release-note
NONE
```

update(userspace/falco): improve falco termination

---

rules/falco_rules.yaml

Signed-off-by: beryxz <coppi.lore@gmail.com>
/kind feature
/area rules
While testing I noticed that the `Detect outbound connections to common miner pool ports` rule didn't work against "xmrig". The reason is that the `sendto` syscall is only used with the DNS server as shown:
```text
1336 xmrig (1980:12) > socket domain=2(AF_INET) type=526338 proto=0 
1337 xmrig (1980:12) < socket fd=14(<4>) 
1338 xmrig (1980:12) > bind fd=14(<4>) 
1339 xmrig (1980:12) < bind res=0 addr=0.0.0.0:0 
1340 xmrig (1980:12) > sendto fd=14(<4>0.0.0.0:0) size=38 tuple=0.0.0.0:38156->8.8.8.8:53 
1341 xmrig (1980:12) < sendto res=38 …
```

Improved detection for connections to miner pools

---

rules/falco_rules.yaml

Signed-off-by: Matan Monitz <mmonitz@gmail.com>
/kind bug
/area rules
lighttpd is spawning create-mime.conf.pl on startup, causing a false positive for "Run Shell Untrusted"
```release-note
lighttpd is spawning create-mime.conf.pl on startup, causing a false positive for "Run Shell Untrusted"
add `sh -c /usr/share/lighttpd/create-mime.conf.pl` to `known_shell_spawn_cmdlines` macro
```

known_shell_spawn_cmdlines - lighttpd

---

userspace/falco/app_actions/list_plugins.cpp

```
```
> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fix punctuation typo in output message when loading plugins.
Fixes #
```release-note
NONE …
```

chore(userspace/falco): fix punctuation typo in output message when loading plugins

---

scripts/falco-driver-loader

/kind bug
/kind feature
/area build
New versions of `dkms` have a new format for `dkms status -m`:
```
module/version: added
```
The other two formats that we support (as said in https://github.com/falcosecurity/falco/pull/1950) are:
```
module, version, kernel, architecture: installed
module/version, kernel, architecture: installed
```
With this PR we should support all `dkms` formats, we will see in the next future if a new format will come out... 
```release-note
NONE
```

fix(falco-scripts): remove driver versions with `dkms-3.0.3`

---

.circleci/config.yml
docker/falco/Dockerfile
docker/local/Dockerfile
docker/no-driver/Dockerfile
docker/tester/Dockerfile
docker/tester/root/runners/deb.Dockerfile
docker/tester/root/runners/rpm.Dockerfile
docker/tester/root/runners/tar.gz.Dockerfile
docker/tester/root/usr/bin/entrypoint
docker/ubi/Dockerfile
scripts/falco-driver-loader
scripts/publish-deb
scripts/publish-rpm

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
New dockerfiles are multiplatform ready: they can be pushed with `docker buildx` for various architectures.
Moreover, updated falco-driver-loader to support multiple architectures.
Fixes #1813
Fixes #1589 …

new(docker,scripts): port all docker images to be multiarch ready

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

fix(build): try to use root user for cimg/base

---

.circleci/config.yml

/kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Moreover, fixed subtle whitespace-bug in various buildx lines.
Fixes #
```release-note
NONE …
```

update(build): avoid double build of docker images when pushing to aws ecr

---

.circleci/config.yml

/kind feature
/area build
Added Circle CI job to build Falco for ARM64 platform. 
Fixes #1891 
```release-note
NONE
```

Circle CI build job for ARM64

---

cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h
userspace/falco/app_actions/load_plugins.cpp

```
```
/kind bug
> /kind design
/area build
/area engine
> /area rules
> /area tests
Fix falco compilation issuer with the new version of the libs. The issue is related to how the plugins are loaded by falco.
Fixes #
**Does this …

Fix falco compilation issues with new libs

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

fix(build): docker-container buildx engine does not support retagging images. Tag all images together.

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
/area rules
> /area tests
**What this PR does / why we need it**: Fixes a linting issue in the rules yaml
**Which issue(s) this PR fixes**: None
Fixes # 
**Does this PR introduce a user-facing change?**: No
```release-note
NONE
```

Correct linting issue in rules

---

scripts/falco-driver-loader

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
This is part of a bigger change on how we store drivers on s3 bucket.
Next changes need to be made in test-infra driverkit …

fix(scripts): fixed falco-driver-loader driver download url.

---

scripts/publish-deb

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
Newest Debian/Ubuntu versions look for this file instead of Release + Release.asc, hitting lots of 404 (and a retry on the old format).
Fixes # …

new(scripts): support InRelease file creation for publish-deb script.

---

.circleci/config.yml

Signed-off-by: Vicente J. Jiménez Miras <vjjmiras@gmail.com>
> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
This PR intends to update the signing of RPM packages to …
```

update(build): Switch from RSA/SHA1 to RSA/SHA256 signature in the RPM package

---

test/README.md
test/requirements.txt
test/run_regression_tests.sh

/kind bug
> /kind design
> /area build
> /area engine
> /area rules
/area tests
The [Falco manual](https://falco.org/docs/getting-started/source/#run-the-tests) and the README in the test directory tell how to run the Falco test suite locally. I think it's very valuable during development however the …

fix(tests): make run_regression_tests.sh work locally

---

docker/falco/Dockerfile
docker/local/Dockerfile
scripts/falco-driver-loader

/kind bug
/area build
This PR ensure falco-driver-loader supports Flatcar. There are two commits that address two parts of this:
1. fix the kernel module build with dkms, which currently doesn't work due to the driver-loader container having a glibc that is older than the kernel module build directory was compiled against. This is solved by relocating the build tools in the kernel module directory, to run using host linker.
2. when searching for pre-built kernel module/eBPF probe, use the /etc/os-release VERSION_ID field instead of kernel release. This is consistent with kernel-crawler output and the convention chosen in …

Flatcar driver loader support

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #2064
```release-note
NONE
```

fix(ci): sign arm64 rpm packages.

---

.circleci/config.yml

Signed-off-by: Vicente J. Jiménez Miras <vjjmiras@gmail.com>
/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

fix(ci): fix sign script - avoid interpreting '{*}$argv' too soon

---

rules/falco_rules.yaml

```
```
/kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
This PR updates the reverse shell detection rule to be triggered when a `dup2` or `dup3` is called. Before the falcosecurity/libs#385 the `dup2` and `dup3` events were sent to userspace as `dup` events.
**Which …

fix(rules): use exit event in reverse shell detection rule

---

test/README.md
test/run_regression_tests.sh

/kind bug
> /area build
> /area engine
> /area rules
/area tests
In an attempt to make it easier for people to run tests locally I messed up the bash script which currently does not report failed tests correctly. This reverts the change and adds correct instructions to the README about how to run it. As it turns out, I was missing an option or badly specified it before. …

fix(tests): make tests run locally (take 2)

---

rules/falco_rules.yaml
test/falco_tests_plugins.yaml
test/falco_traces.yaml.in

/kind bug
> /kind design
> /area build
> /area engine
/area rules
/area tests
Fixes #
/milestone 0.32.1
```release-note
rule(Redirect STDOUT/STDIN to Network Connection in Container): changed priority to NOTICE
```

fix: adapt regressions after dup change and version bump

---

test/falco_tests_plugins.yaml
test/rules/plugins/cloudtrail_macro.yaml
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_reader.cpp

/kind cleanup
/area engine
/area tests
Since being ported from Lua to C++, the Falco rule loader supported defining a `source` field in both rules and macros, meant to define compatibility with a specific event source. However, having source definitions in macros is not meaningful, and also the current implementation does not enforce any check during ruleset compilation (it just reads the value from the YAML). On the opposite, I think **not** defining a source for macros is the way to go. This would enable ruleset developers to create cross-source macros (for example, the `json` plugin can be used to build macros that are valid for all the json-based event sources …

refactor(userspace/engine): drop macro source field in rules and rule loader

---

.circleci/config.yml

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

new(circleci): enable integration tests for arm64.

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/logger.cpp
userspace/falco/logger.h

/kind cleanup
/kind feature
/area engine
This PR adds support to logs coming from libsinsp, which are now piped into the Falco logger. By default this is disabled in order to avoid breaking changes in the UX as for the messages printed to stderr. A new option `libs_logger` has been added in the `falco.yaml` configuration.
Fixes #2068
```release-note
update(userspace/falco): support libs logging
```

update(userspace/falco): support libs logging

---

rules/falco_rules.yaml

/area rules
**What this PR does / why we need it:**
Improving security posture and intrusion detection &  it needs careful tuning to ensure good signal-to-noise ratio. Falco alerts should eventually become alert-worthy. This PR consists in filtering a few "obvious" false-positives.
1. Based on our investigations and finding , Contact K8S API Server From Container" should be ignored for container images which are known "controllers".
2. Based on our investigations and finding , updated the rules to `write_etc_common` , `Launch Package Management Process in Container` , `falco_privileged_images`, `k8s_containers` , `postgres_running_wal_e` & `falco_sensitive_mount_containers`.
**Does this …

Falco Rules/Conditions update

---

userspace/falco/event_drops.cpp

Co-authored-by: Shane Lawrence <shane@lawrence.dev>
/kind bug
/kind cleanup
/area engine
First of all, I would to thank  @shane-lawrence for spotting this issue in #2111! Great catch!
As I said [here](https://github.com/falcosecurity/falco/pull/2112#issuecomment-1175101375) the `n_evts` fields, both in `kmod` and in `bpf` should be intended as "events seen by the drivers" so they should contain also the number of drops. This is for example what we do in our bpf probe after [this variable increment](https://github.com/falcosecurity/libs/blob/aa8589da33a63927505100340a1a4adfe1418a73/driver/bpf/plumbing_helpers.h …

fix(userspace): compute the `drop ratio` in the right way

---

rules/falco_rules.yaml

This PR fixes the condition of the "Launch Privileged Container" by adding a whitelist of Red Hat images, to reduce the noise and false positives.
Signed-off-by: Alessandro Brucato <alessandro.brucato@sysdig.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
This PR fixes the condition of the "Launch Privileged Container" by adding a whitelist of Red Hat images, to reduce the noise and false positives.
Too much noise and false positives.
Fixes #
**Special notes for …

Fixed condition rule Launch Privileged Container

---

userspace/falco/statsfilewriter.cpp
userspace/falco/statsfilewriter.h

/kind cleanup
/kind feature
/area engine
Looking at this [PR]() from @shane-lawrence I thought that we need a little bit of cleanup here, and moreover, it could be useful to have the `drop_percentage` computed on the global statistics and not only on the delta. I used the `nlohmann json` library just to simplify the output :) Let me know what you think about that 
```release-note
new: add a `drop_pct` referred to the global number of events
```

new: add a `drop_pct` referred to the global number of events

---

scripts/falco-driver-loader

Signed-off-by: Eric Engberg <eric.engberg@hardrockdigital.com>
**What type of PR is this?*
/kind bug
/area build
The url for downloading the prebuild eBPF driver is missing the ARCH in the path
Fixes #
```release-note
fix: Added ARCH to bpf download URL
```

fix: added arch to bpf download url

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/falco/app_actions/load_rules_files.cpp
userspace/falco/app_actions/print_support.cpp
userspace/falco/application.h

The only use of it was to include in --support output, which is
redundant as the support output already includes the full contents of
each rules file.
Additionally, it wasn't even being updated after the switch from lua
rules loading to c++ rules
loading (https://github.com/falcosecurity/falco/pull/1966/ or
surrounding PRs).
This will simplify follow-on changes to add a real "result" to rules
loading methods, as there will be fewer API variants to support.
> /kind bug
/kind cleanup
> /kind design
> /kind …

Remove required_engine_version from falco engine load_rules APIs

---

userspace/falco/app_actions/init_falco_engine.cpp
userspace/falco/app_actions/open_inspector.cpp

/kind feature
/area engine
This PR allows Falco to print some info when it starts:
* Which are the event sources enabled (maybe more than one in the next future)
* If Falco is using the BPF probe (as I wrote in the TODO we can extend this to every `scap` engine)
This is a possible output:
```
Sat Jul 16 10:23:11 2022: Falco version 0.32.1-14+ac9cd6d
Sat Jul 16 10:23:11 2022: Falco initialized with configuration file ../falco.yaml
Sat Jul 16 10:23:11 2022: Enabled sources: syscall
Sat Jul 16 10:23:11 2022: Loading rules from file ../rules/falco_rules.yaml
Sat Jul 16 10:23:11 2022: Starting internal webserver, listening on port 8765
Sat Jul 16 10:23:11 2022: Falco is …
```

new: print some info about eBPF and enabled sources when Falco starts

---

.circleci/config.yml

/kind cleanup
/area build
This allows for native-speed build of docker images, reducing CI time spent in docker buildx qemu cross build for arm64 up to 10x.
Fixes #
```release-note
NONE
```

cleanup(ci): natively builds docker images for x86_64 and arm64 and then use docker manifest to combine them

---

tests/engine/test_filter_evttype_resolver.cpp
userspace/falco/app_actions/process_events.cpp

/kind feature
/area build
/area engine
As explained here https://github.com/falcosecurity/libs/pull/490 when the userspace chooses to filter an event now the libraries return `SCAP_FILTERED_EVENT`, so we need to manage it also in Falco.
```release-note
NONE
```

new(userspace): support `SCAP_FILTERED_EVENT` return code

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Be more consistent with explicitly tagging rules that are disabled by default with `enabled: false`, should give some perf boosts as well. Spotted 3 rules eligible for cleanup. Are there more rules eligible …

cleanup(rules): cleanup rules disabled by default

---

userspace/falco/event_drops.cpp

Signed-off-by: incertum <melissa.kilby.oss@gmail.com>
/kind feature
/area engine
Add new output fields to event drop messages when using eBPF driver.
For more details see https://github.com/falcosecurity/libs/pull/414.
- Depends on https://github.com/falcosecurity/libs/pull/414.
- Subsequently needs bump of libs version dependency.
- https://github.com/falcosecurity/falco/issues/1403
For better clarity rename following 2 JSON stats output fields (this can be a breaking change for some end users)
- `n_drops_buffer` -> `n_drops_buffer_total` (anticipating confusion, therefore renaming for better clarity)
- `n_drops_pf` -> `n_drops_page_faults` (have seen this causing confusion, proposing to just type it out while we already have one breaking …

new(userspace/falco): extend buffer kernel side event drop metrics

---

userspace/falco/app_actions/load_rules_files.cpp
userspace/falco/app_actions/validate_rules_files.cpp

The latest released falco always prints full details on errors when
used with -r (read rules)/-V (validate rules). However #2098 changed
this to only print full details when verbose is true.
Fix the regression by always printing full details regardless of
verbose/-v.
/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
> …

fix: print full rule load errors/warnings without verbose/-v

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
/area rules
> /area tests
> /area CI
Be consistent with explicitly tagging rules that are disabled by default with `enabled: false`. See https://github.com/falcosecurity/falco/pull/2154. Used few bash one liners this …

cleanup(rules): cleanup rules disabled by default - 2

---

falco.yaml
userspace/falco/app_actions/init_outputs.cpp
userspace/falco/app_actions/process_events.cpp
userspace/falco/application.cpp
userspace/falco/configuration.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h

/kind feature
/area engine
This is an alternative to https://github.com/falcosecurity/falco/pull/2080, that makes the token-bucket alert rate limiter optional by default. When enabled, the output framework now uses one token bucket for each inspector. Once we have multi-source support, alerts coming from one source won't influence the rate limiting of the others. At the same time, this will also be thread-safe because each thread will be own its own token bucket.
Fixes #1333
```release-note
refactor(userspace/falco): make output rate limiter …
```

refactor(userspace/falco)!: make output rate limiter optional and output engine explicitly thread-safe

---

.github/workflows/codeql.yaml

/kind feature
/area CI
This PR recalls the one opened by @caniszczyk  here :point_right:  https://github.com/falcosecurity/falco/pull/1499 
Don't know why this has not been merged at the time, since I find it very useful for us :thinking: BTW I will try to reopen it now, thank you again @caniszczyk for your great job! I've just updated the version of some GH actions :) 
```release-note
new(CI): add CodeQL security scanning to Falco.
```

new(CI): add CodeQL security scanning to Falco.

---

.codespellignore
.github/workflows/codespell.yml

/kind bug
/kind cleanup
/area CI
The read-only acronym (`ro`)  is considered a typo by `codespell`, we now ignore it.
```release-note
NONE
```

fix(CI): codespell should ignore `ro` word

---

scripts/falco-driver-loader

/kind feature
/area engine
This PR introduces changes to the falco-driver-loader script.
to support multiple download URLs in the DRIVERS_REPO environment variable, and to store downloaded drivers in a folder that mirrors the download directory.
The DRIVERS_REPO environment variable can now be used to specify multiple download URLs by separating individual URLs by a comma. URLs will be attempted in order from first to last as specified. Once a successful download has been performed (per a successful result code from curl), any remaining URLs will not be attempted. This will allow, for example, users to specify their own custom driver repo URL without having to …

Falco driver loader enhancements

---

userspace/falco/event_drops.cpp
userspace/falco/falco.cpp
userspace/falco/grpc_server.cpp
userspace/falco/logger.cpp
userspace/falco/logger.h

/kind feature
/area engine
This changes the falco logger `log()` method to use the move semantics.
```release-note
update(userspace/falco): use move semantics in falco logger
```

update(userspace/falco): use move semantics in falco logger

---

rules/falco_rules.yaml

/kind feature
/area rules
Add new rule `Directory traversal monitored file read`.
Web applications can be vulnerable to directory traversal attacks that allow accessing files outside of the web app's root directory (e.g. Arbitrary File Read bugs). System directories like /etc are typically accessed via absolute paths. Access patterns outside of this (here path traversal) can be regarded as suspicious. This for example will allow monitoring the entire `/etc` directory. For instance while `/etc/passwd` is not regarded a sensitive file like `/etc/shadow` - reading `/etc/passwd` via directory …

new(rules): Directory traversal monitored file read

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/formats.cpp
userspace/engine/formats.h

/kind cleanup
/kind design
/area engine
This PR uses the `const` keyword with coherence across the falco engine interface and classes. Although this does not introduce any practical change, it is useful to make it more explicit which operations alter the state of the engine and which not.
```release-note
NONE
```

refactor(userspace/engine): increase const coherence in falco engine

---

falco.yaml
userspace/falco/app_actions/start_webserver.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/webserver.cpp
userspace/falco/webserver.h

/kind feature
/area engine
This improves the webserver by making the thread pool size configurable (by default equal to the number of online cores).
```release-note
update(userspace/falco): make webserver threadiness configurable
```

update(userspace/falco): make webserver threadiness configurable

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/stats_manager.cpp
userspace/engine/stats_manager.h

/kind feature
/area engine
This PR is focused on guaranteeing (and documenting) that concurrent access to `falco_engine::process_event()` is safe for different event sources.
Since the new plugin system got implemented, and due to the recent refactoring of the Falco engine for Falco v0.32, the engine is not internally split by event sources. This means that the engine contains multiple rulesets, each mapped 1-1 with an event source. Accordingly, it is possible to assume that `falco_engine::process_event()` is now thread-safe with some assumptions:
1. Each concurrent invoker must use a distinct and unique `source_idx`
2. Each concurrent invoker must not switch …

refactor(userspace/engine): strengthen and document thread-safety guarantees of falco_engine::process_event

---

userspace/falco/app_actions/create_signal_handlers.cpp
userspace/falco/app_actions/process_events.cpp
userspace/falco/application.cpp
userspace/falco/application.h
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h

/kind design
kind feature
/area engine
This PR refactors the signal handlers, and their effects, to be thread-safe. Thread-safety is not something we need right now, but it is preparatory for https://github.com/falcosecurity/falco/issues/2074.
Also, this defines a termination condition for the Falco output engine. Basically, a full queue would generally imply a deadlock for Falco, so we exit with an error in that case.
Fixes #
```release-note
refactor(userspace/falco): make signal handlers thread safe
```

refactor(userspace/falco): make signal handlers thread safe

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
/area rules
> /area tests
> /area CI
Still missed a whole bunch of `(never_true)` macros at the beginning of the condition or when `and (never_true)` was split across lines. …

cleanup(rules): cleanup rules disabled by default - 3

---

scripts/falco-driver-loader

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area rules
> /area tests
> /area CI
This PR is part of a wider effort to support any ubuntu flavor to build Falco drivers; see:
* https://github.com/falcosecurity/kernel-crawler/pull/38
* …

new(scripts): improved falco-driver-loader supporting any ubuntu flavor.

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
/area rules
> /area tests
> /area CI
- Continue cleanup, see https://github.com/falcosecurity/falco/pull/2168
- New field `fd.nameraw` used in `Directory traversal monitored file read` requires FALCO_ENGINE_VERSION change
Fixes #
**Special …

cleanup(rules): cleanup rules - 4

---

ADOPTERS.md

> /area build
> /area engine
> /area rules
> /area tests
> /area CI
Add StackRox to the list of adopters, under the section `Projects that use Falco libs`
Fixes #
```release-note
NONE
```

Add StackRox to adopters

---

.circleci/config.yml
cmake/modules/static-analysis.cmake

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
/area CI
Fixes #
```release-note
NONE
```

update(.circleci): re-enabled cppcheck

---

tests/CMakeLists.txt
tests/engine/test_plugin_requirements.cpp
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_engine_version.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_reader.cpp

/kind feature
/area engine
/area tests
This PR updates the rule engine to support multiple alternatives plugin version requirements definitions in rulesets. The problem was first mentioned in https://github.com/falcosecurity/plugins/pull/134#discussion_r935806326, and documented in the #2150 issue.
Given that a new feature is added, the rule engine version has been bumped (to v15). Moreover, unit tests have been introduced to make sure that the plugin version checks work as expected.
Fixes #2150
In this proposal, rulesets will be able to support the following syntax:
```yaml
- …
```

update(userspace/engine): support alternative plugin version requirements in checks

---

userspace/engine/filter_evttype_resolver.cpp
userspace/engine/filter_evttype_resolver.h
userspace/engine/filter_macro_resolver.cpp
userspace/engine/filter_macro_resolver.h
userspace/engine/indexed_vector.h
userspace/engine/json_evt.cpp
userspace/engine/json_evt.h
userspace/engine/rule_loader.cpp

> /kind design
/area engine
Improve rules loading/parsing performance
Fixes #
```release-note
NONE
```

improve falco files loading performance

---

test/falco_tests.yaml
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_reader.cpp

In #2098, we reworked how rules loading errors/warnings were returned
to provide a richer set of information, including locations/context
for the errors/warnings.
That did *not* include locations within condition expressions,
though. When parsing a condition expression resulted in a
warning/error, the location simply pointed to the condition property
of the rule.
This commit improves this to handle parse errors:
- When libsinsp::filter::parser::parse() throws an exception, use
get_pos() to get the position within the condition string.
- Add a new context() constructor that takes a filter pos_info instead
of a YAML::Mark.
Doing this required some small changes to the context struct,
though. Previously, the name (e.g. yaml filename) was held separate
from the list of locations. However, …

Support condition parse errors in rule loading results

---

userspace/falco/CMakeLists.txt
userspace/falco/app_actions/create_requested_paths.cpp
userspace/falco/application.cpp
userspace/falco/application.h

/kind feature
/area engine
It is also able to handle multipart paths, like /run/falco/falco/falco/falco.
Fixes #
```release-note
new(userspace/falco): automatically create paths for grpc unix socket and gvisor endpoint.
```

new(userspace/falco): create grpc unix socket and gvisor endpoint path automatically

---

userspace/engine/rule_reader.cpp

/kind bug
/area engine
The recursive function that reads rule exception values does not clear out the value list, so consecutive list-type exception values may end up containing in duplicate items.
The regression seems to be introduced in https://github.com/falcosecurity/falco/pull/2098
A minimum example to reproduce the issue is reported below:
```yaml
- rule: Sample Rule
desc: A sample rule
output: Sample output (type=%evt.type)
priority: ERROR
condition: >
evt.dir = <
exceptions:
- name: sample_exception
fields: [evt.type, proc.name]
comps: [in, in]
values:
- [[openat], [ls]]
```
This rule …

fix(userspace/engine): avoid reading duplicate exception values

---

falco.yaml
test/falco_test.py
tests/engine/test_falco_utils.cpp
userspace/falco/app_cmdline_options.cpp

According to the FHS 3.0 (https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html), transient UNIX-domain sockets should be placed under the directory /run, so this commit updates the implicit value generated by the application.
Signed-off-by: Vicente J. Jiménez Miras <vjjmiras@gmail.com>
/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
**What …

Replacing /tmp/gvisor.sock with /run/gvisor.sock

---

rules/falco_rules.yaml

This new rule help to detect vulnerability [CVE-2019-5736](https://nvd.nist.gov/vuln/detail/CVE-2019-5736)
Co-authored-by: wcc526 <wcc526@gmail.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
> /area CI
This PR helps on detecting …

Added rule to detect CVE-2019-5736

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_source.h

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area rules
> /area tests
> /area CI
Some small changes to rules matching that reduce cpu usage with high event volumes (> 1M syscalls/sec)
Fixes # …

Rules matching perf improvements

---

rules/falco_rules.yaml

Signed-off-by: Hi120ki <12624257+hi120ki@users.noreply.github.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
> /area CI
In GKE cluster, a system container `gce-pd-driver` that manages Persistent Disk is running.
But the rule `Mount Launched of Privileged Container` detects as false …

Add GKE default pod into allowlist in Mount Launched of Privileged Container rule 

---

userspace/falco/app_actions/process_events.cpp

/kind bug
/area engine
This PR checks the return value of the `open_live_inspector` method interrupting immediately the flow if the inspector is not opened
```release-note
NONE
```

fix(process_events): check the return value of `open_live_inspector`

---

falco.yaml
userspace/falco/CMakeLists.txt
userspace/falco/app_actions/compute_syscall_buffer_size.cpp
userspace/falco/app_actions/open_inspector.cpp
userspace/falco/app_actions/print_page_size.cpp
userspace/falco/app_cmdline_options.cpp
userspace/falco/app_cmdline_options.h
userspace/falco/application.cpp
userspace/falco/application.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind feature
As discussed in various places (https://github.com/falcosecurity/falco/pull/2164#issuecomment-1220479171, https://github.com/falcosecurity/falco/pull/2164#issuecomment-1220792012, https://github.com/falcosecurity/falco/issues/2208)  this PR adds the possibility to change the syscall buffer dimension through the Falco configuration file.
The approach used is the one described here https://github.com/falcosecurity/falco/issues/2208#issuecomment-1248354349. Users will have an array of indexes that map to precise buffer dimensions in bytes. You can find more information in the `falco.yaml` file, but just for simplicity I report them here:
```yaml
#
#
#
# …
```

new: configure syscall buffer dimension from Falco

---

rules/falco_rules.yaml

Signed-off-by: Kyle Smith Hanna <kyle.smithhanna@spyderbat.com>
/area rules
As I said in the issue, this PR adds the `proc.pid` to all the default rules, allowing for unique identification of rule trigger causes. It is not feasible without this change to combine Falco data with other data sources in most cases.
Fixes #2209
```release-note
added process IDs to default rules
```

Add PIDs to default rules

---

userspace/falco/app_actions/init_falco_engine.cpp

/kind bug
/area engine
Fix the gVisor format printing by changing the following:
1. clarify `vpid`/`vtid` consistent with the rest of Falco
2. use the same format for containers and gVisor
Fixes #
```release-note
fix(falco): clarify pid/tid and container info in gvisor
```

fix(falco): print container info and gvisor info in the same way

---

CMakeLists.txt
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/falco/app_actions/open_inspector.cpp
userspace/falco/app_cmdline_options.cpp
userspace/falco/app_cmdline_options.h

/kind feature
/area engine
This PR adds the possibility to start Falco with the modern BPF probe. This cmd line option MUST be used only during development, it is not production ready! For this reason, it is compiled out unless we use the `-DBUILD_FALCO_MODERN_BPF=ON` CMake option
```release-note
new(cmdline): add development support for modern BPF probe
```

new(cmdline): add development support for modern BPF probe

---

userspace/engine/falco_load_result.h
userspace/engine/falco_rule.h
userspace/engine/falco_source.h
userspace/engine/filter_evttype_resolver.h
userspace/engine/filter_macro_resolver.h
userspace/engine/filter_ruleset.h
userspace/engine/filter_warning_resolver.h
userspace/engine/indexed_vector.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_loader_collector.cpp
userspace/engine/rule_loader_collector.h
userspace/engine/rule_loader_compiler.h
userspace/engine/rule_loader_reader.h
userspace/engine/stats_manager.h
userspace/falco/application.cpp
userspace/falco/application.h
userspace/falco/stats_writer.h

/kind cleanup
/area engine
This cleans up the codebase by adding explicit constructors and initialization, and makes the copy/move semantics explicit  where missing. This should solve some tedious bugs and non-predictable behaviors (and make cppcheck happier).
```release-note
NONE
```

fix(userspace): add explicit constructors and initializations

---

userspace/falco/app_actions/load_rules_files.cpp
userspace/falco/app_actions/validate_rules_files.cpp
userspace/falco/application.h

/kind bug
/area engine
This fixes a regression. When validating rule files with the `-V` option, plugin requirements expressed by the ruleset where not checked.
```release-note
NONE
```

fix(userspace/falco): check plugin requirements when validating rule files

---

rules/falco_rules.yaml

/kind bug
/area rules
This adds the falco-no-driver images to the whitelist of the `k8s_containers` macro. Now that the official helm chart use the no-driver image as default, and considering the latest fixes the the libsinsp's k8s metadata client, Falco started alerting the `Contact K8S API Server From Container` rule noisy due to it detecting its own calls to the API server.
```release-note
rules(macro: k8s_containers): add falco no-driver images
```

fix(rules): add falco no-driver images to k8s_containers macro

---

scripts/debian/postinst.in
scripts/debian/postrm.in
scripts/debian/prerm.in
scripts/rpm/postinstall.in
scripts/rpm/postuninstall.in
scripts/rpm/preuninstall.in

/kind cleanup
/area build
This PR builds off the work introduced in #1448, which converted Falco's initscripts to a systemd unit. 
Currently, when removing, reinstalling, and/or upgrading the Falco package via DEB or RPM, the systemd unit file can be left in an unhygienic state and the user needs to perform a `sudo systemctl daemon-reload`.
This change re-introduces the falco service cleanup that the DEB and RPM packages perform for it's systemd unit when (re)installing and removing the packages.
Fixes #
* This change is in WIP at the moment, as the RPM-equivalent changes have not been committed …

cleanup(scripts): cleanup systemd unit in DEB + RPM packages

---

userspace/falco/app_actions/create_signal_handlers.cpp
userspace/falco/app_actions/process_events.cpp
userspace/falco/application.cpp
userspace/falco/application.h

/kind bug
/kind cleanup
/area engine
Signal handlers are used in Falco to force termination, hot reload, or output reloading. However, the current implementation is not stable for neither thread-safety and async-signal safety (more here: https://docs.oracle.com/cd/E19455-01/806-5257/gen-26/index.html). This PR refactors the way signals are handled to make sure it's safe both on single-threaded (e.g. capturing only syscalls) and multi-threaded use cases (e.g. multiple event sources in parallel).
Accordingly, the event source termination stage has been refactored to be more stable by using atomic values to check 1) that the event source has actually finished …

fix(userspace/falco): make termination and signal handlers more stable

---

cmake/cpack/CMakeCPackOptions.cmake
scripts/CMakeLists.txt
scripts/debian/falco.service
scripts/debian/falco_inject_kmod.service
scripts/rpm/falco.service
scripts/rpm/falco_inject_kmod.service

/kind bug
/area build
Trying to run the latest Falco deb/rpm package there is an issue:
Since this PR https://github.com/falcosecurity/falco/pull/2214, Falco service needs to write under `/sys/module/falco/parameters/g_buffer_bytes_dim`  the variable buffer dimension. The problem is that right now the path `/sys/module` is mounted read-only so Falco will fail with `Errno 30` in the attempt to write `/sys/module/falco/parameters/g_buffer_bytes_dim`:
```
Oct 07 23:41:26 ubuntu2204.localdomain falco[34605]: Falco version: 0.32.1-241+251b4d5 (x86_64)
Oct 07 23:41:26 ubuntu2204.localdomain falco[34605]: Fri Oct  7 23:41:26 2022: Falco version: 0.32.1-241+251b4d5 …
```

fix(falco_service): falco service needs to write under `/sys/module/falco`

---

userspace/engine/filter_warning_resolver.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/falco/app_actions/print_version.cpp
userspace/falco/app_cmdline_options.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/event_drops.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/grpc_server.cpp
userspace/falco/grpc_server.h
userspace/falco/outputs.h

/kind cleanup
/area engine
This fixes a bunch of warnings and performance-level suggestions reported by cppcheck.
```release-note
NONE
```

update(userspace): solve warnings and performance tips from cppcheck

---

test/falco_tests.yaml
userspace/engine/rule_loader_compiler.cpp
userspace/falco/app_actions/validate_rules_files.cpp

/kind bug
/kind cleanup
/area engine
This fixes two issues related to ruleset validation and error reporting:
1. Currently, when validating and loading rulesets we exit at the first error encountered. However, we didn't skip the "list/macro is unused" checks, which ended up flooding the loading result when encountering an error due to most/all macros and list being obviously unused. Plus, this was wrong logically because we can potentially encounter errors even before reaching the ruleset compilation step.
2. When printing validation result with json output enabled, we didn't fill-up the human-readable summary string. When encountering an error and making Falco …

fix(userspace): cleanup output of ruleset validation result

---

cmake/modules/driver.cmake

/kind release
/area build
This PR bumps the driver repo to the latest driver tag `3.0.1+driver`
```release-note
NONE
```

chore: use latest driver tag `3.0.1+driver`

---

userspace/falco/app_actions/print_syscall_events.cpp

/kind bug
/kind cleanup
/area engine
This fixes the `--list-syscall-events` option by making it print the right event list given the current new "interesting syscalls" model, and avoids using a deprecated libs api.
```release-note
update(userspace/falco): move on from deprecated libs API for printing event list
```

update(userspace/falco): move on from deprecated libs API for printing event list

---

userspace/falco/app_actions/process_events.cpp
userspace/falco/application.h
userspace/falco/semaphore.h

/kind bug
/area engine
When synchronizing with parallel event sources running in their own thread, the main thread was not put to sleep and consumed CPU with no purpose. Using a semaphore, we're able to let it sync with the additional threads only when at least one signals termination.
```release-note
NONE
```

fix(userspace/falco): avoid using CPU when main thread waits for parallel event sources

---

userspace/engine/falco_engine.cpp

The optimization in https://github.com/falcosecurity/falco/pull/2210 had a bug when the engine uses multiple sources at the same time--m_syscall_source is a pointer to an entry in the indexed vector m_sources, but if add_source is called multiple times, the vector is resized, which copies the structs but invalidates any pointer to the vector entries.
So instead of caching m_syscall_source in add_source(), cache it in process_events(). m_sources won't change once processing events starts.
/kind bug
> /kind design
> If contributing rules or changes to rules, please make sure to …

fix(engine): save syscall source only when processing events

---

scripts/falco-driver-loader

/kind cleanup
Currently, when falco-driver-loader is not able to fetch OS_NAME from multiple files under /etc, like `/etc/os-release`, it exit with an error.
I think that the best approach is trying to compile the requested driver in any case; consider that `TARGET_ID` is only really used to concatenate the correct name for the driver on the s3 bucket.
So, in case we are not able to fetch any TARGET_ID, just fallback at disabling `ENABLE_DOWNLOAD` and go on to compile the driver.
This is mostly useful when using `HOST_ROOT` but the `/etc/` folder is not a shared volume under it.
Fixes #
**Does …

fix(scripts): force falco-driver-loader script to try to compile the driver anyway even on unsupported platforms

---

userspace/falco/verify_engine_fields.sh

/kind bug
/kind cleanup
/area build
This improves the `verify_engine_fields.sh` script (used when building Falco) to just check for syscall-related fields. This aims to make developers' life easier when dealing with plugins (e.g. Falco build always fails if you load a plugin in your local falco.yaml file), which should not affect the built-in fields anyway.
```release-note
NONE
```

fix(userspace/falco): verify engine fields only for syscalls

---

userspace/engine/falco_engine.cpp

/kind bug
/area engine
Fixes the following:
```
falco/userspace/engine/falco_engine.cpp: In member function ‘std::unique_ptr<falco::load_result> falco_engine::load_rules_file(const string&)’:                                                                
falco/userspace/engine/falco_engine.cpp:240:19: error: redundant move in return statement [-Werror=redundant-move]                                                                                             
240 |   return std::move(res); …
```

fix(engine): fix warning about redundant std::move

---

userspace/falco/app_actions/init_falco_engine.cpp

/kind feature
/area engine
When running with gVisor on a host with containers, you probably want to print details with `container-gvisor`, when using kubernetes `kubernetes-gvisor`, as they're equivalent to `container` and `kubernetes` but add information useful for gVisor (currently vtid and vpid, but could be more). These can easily be used by the helm chart as well.
Also, remove the previous `if` that was trying to set this automatically. It is cleaner to specifiy the print format explicitly like we currently do with k8s.
**Which …

update(falco): add container-gvisor and kubernetes-gvisor print options

---

RELEASE.md

Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
> /area CI
Add more technical clarity to the release doc, see https://github.com/falcosecurity/falco/issues/2195
**Which issue(s) …

update(docs): add overview and versioning sections to falco release.md

---

rules/falco_rules.yaml

Signed-off-by: Alessandro Brucato <alessandro.brucato@sysdig.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
> /area CI
The ptrace system call can be used to alter a target's memory and execution which make it popular for injecting code. It is often used by malware for this purpose in order …

Rule: PTRACE attached to process

---

rules/falco_rules.yaml

/kind bug
> /area rules
`salt-minion` was added as a trusted process in https://github.com/falcosecurity/falco/commit/85f51cf38c504772e00cc8918442ba6323ec9b89 and https://github.com/falcosecurity/falco/commit/1feae90c74943a7152972d94a39ed80965c26614, this however does not cover [salt-call](https://docs.saltproject.io/en/latest/ref/cli/salt-call.html) which is also a saltstack component and used on minions to apply changes from client-side. It should also be a trusted process along-with salt-minion as part of Saltstack.
```release-note
rule(Read sensitive file …
```

rules: add salt-call as a trusted process

---

userspace/falco/webserver.h

/kind feature
/area engine
This PR enables zlib support for the cpp-httplib on which we base our `/healthz` webserver (see: https://github.com/yhirose/cpp-httplib#zlib-support).
```release-note
update(userspace/falco): enable using zlib with webserver
```

update(userspace/falco): enable using zlib with webserver

---

falco.yaml

/kind cleanup
This PR adds a config that can be used for debugging purposes, the `simulate_drops` config. This PR is just a proposal maybe there is a particular reason why we don't expose it directly to the user, any feedback is welcome :)
```release-note
new(config): explicitly add the `simulate_drops` config
```

new(config): explicitly add the `simulate_drops` config

---

tests/engine/test_filter_macro_resolver.cpp
tests/engine/test_rulesets.cpp
userspace/engine/evttype_index_ruleset.cpp
userspace/engine/evttype_index_ruleset.h
userspace/engine/filter_macro_resolver.cpp
userspace/engine/filter_macro_resolver.h
userspace/engine/filter_ruleset.h
userspace/engine/rule_loader_compiler.cpp

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area rules
> /area tests
> /area CI
Fixes #
```release-note
Also include exact locations for rule condition compile errors (missing macros, etc).
```

Rules result add compile condition context

---

userspace/engine/falco_source.h

In the copy constructor and assignment operator for falco_source, also copy the ruleset along with factories/name.
/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
> /area CI
Fixes # …

Also copy ruleset when copying falco source

---

scripts/falco-driver-loader

With current version, this error comes out while trying to run `falco-driver-loader` on RHEL 6:
```
Getting environment information
Detected an unsupported target system, please get in touch with the Falco community
```
because `/etc/os-release` file is not there.
Instead, `/etc/redhat-release` file is present (just like `/etc/centos-release` in older CentOS distros, already supported).
Tested on:
```
Linux rhel6.localdomain 2.6.32-754.el6.x86_64 #1 SMP Thu May 24 18:18:25 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Signed-off-by: gentooise <andrea.genuise@ibm.com>
**What type of PR is this?** not sure
**Any specific area of the project related to this PR?** not sure
**Special notes for your reviewer**: none
```release-note
Support older …
```

support older rhel distros in falco-driver-loader

---

rules/falco_rules.yaml

/kind feature
/area rules
I noticed the rules macro `private_key_or_password` didn't check for OpenSSH private keys so I added it.
Fixes #
```release-note
rules(macro: private_key_or_password): now also check for OpenSSH private keys 
```

rules: add OpenSSH private key to macro private_key_or_password

---

.circleci/config.yml

/kind bug
/area CI
This PR fixes the rpm sign job
```release-note
NONE
```

fix(ci): fix rpm sign job dependencies

---

rules/falco_rules.yaml

Signed-off-by: Alberto Pellitteri <albertopellitteri96@gmail.com>
Co-authored-by: Alessandro Brucato <alessandro.brucato@sysdig.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
> /area CI
Nowadays many attacks are interested in stealing credentials. Most of the researched credentials are …

Rule: detecting executions looking for AWS credentials

---

rules/falco_rules.yaml

Signed-off-by: Alberto Pellitteri <albertopellitteri96@gmail.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
> /area CI
The execution from /dev/shm rule detects file execution from the /dev/shm directory, which is a common location for threat actors to store their files. The shm device is …

Rule: detecting executions from /dev/shm

---

cmake/modules/cpp-httplib.cmake

/kind feature
/area build
Update cpp-httplib with the latest version. Fixes potential DoS issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49740 disclosed on 2022-10-31
Fixes #
```release-note
NONE
```

update(falco): update cpp-httplib to 0.11.3

---

RELEASE.md
userspace/falco/app_actions/print_support.cpp
userspace/falco/app_actions/print_version.cpp

/kind feature
/area engine
Since a few Falco versions we have fields indicating libs, drivers, plugin APIs and so forth. These should be reflected into the `--support` option of Falco. In addition, the `--version` command should contain the engine version as well in my opinion since users may want to easily check whether a rule file is compatible with their version of Falco without necessarily running against it.
Fixes #
```release-note
new(falco): add more …
```

new(falco): add more version fields to --support and --version

---

rules/falco_rules.yaml

/kind cleanup
/area rules
In the default rules I noticed the Falco containers where repeated in multiple rules. This creates a list and uses it instead which is similar to how the ibm_cloud_containers list is implemented and used.   
Fixes #
```release-note
rules: add Falco container lists
```

rules: use list of Falco containers instead of repeating them

---

.circleci/config.yml
.github/workflows/staticanalysis.yaml

/kind cleanup
/area CI
This PR moves the static analysis job from circle CI to GHA
```release-note
NONE
```

cleanup(ci): move static analysis job from circle CI to GHA

---

.circleci/config.yml
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
docker/builder/README.md
docker/builder/modern-falco-builder.Dockerfile
test/CMakeLists.txt

/kind feature
/area build
/area CI
This PR brings the necessary changes in the circle-ci jobs to build a Falco image for the modern bpf probe. I added a docker image that returns Falco packages as output (deb, rpm, tar).
This PR is the dual of https://github.com/falcosecurity/falco/pull/2282, the idea is to merge this for the release and leave the other PR open until Falco 0.34 is released so users can continue to test the modern probe if they want :) 
```release-note
update(ci): update ci jobs to generate Falco images with the modern BPF probe …
```

update(ci): update ci jobs to generate Falco images with the modern BPF probe

---

userspace/falco/app_actions/load_rules_files.cpp

/kind bug
/area engine
As reported by @Happy-Dude here https://github.com/falcosecurity/falco/issues/2326, when running Falco on `aarch64`, Falco logs a misleading error message. Take as an example the issue log:
```
Loaded rules match the following events: symlink, mkdir, unlink, dup2, rmdir, link, open, rename, creat
```
All these syscalls are not defined on `aarch64` architectures but Falco is not yet able to detect it! As a first step, I would fix the log just to let the user know what is happening under the hood. Obviously, this is not the final solution, which will require some changes in the libraries to detect this sort of behavior, for …

doc(userspace): provide users with a correct message when some syscalls are not defined

---

scripts/falco-driver-loader

Fixes #2334
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area rules
> /area tests
> /area CI
Fixes #2334
I used `--connect-timeout 5`, `--retry 3`, `--max-time 60` and `--retry-max-time 120`: curl …

chore(scripts/falco-driver-loader): improve curl resiliency

---

userspace/falco/app_actions/print_support.cpp
userspace/falco/app_actions/print_version.cpp
userspace/falco/app_cmdline_options.cpp
userspace/falco/app_cmdline_options.h
userspace/falco/application.h

/kind feature
/area engine
As per title. It's like a lighter `--support` option which only prints the `--version` data.
Fixes #
```release-note
new(falco): add --version-json to print version information in json format
```

new(falco): add --version-json to print version information in json format

---

userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_loader_reader.cpp

/kind bug
/kind cleanup
/area engine
The improvements involve:
- Catching all errors during the YAML rule parsing and validation phases, providing per-error context info where possible
- Properly compute rule condition context location on rule loader validation results
```release-note
fix(userspace/engine): improve rule loading validation results
```

fix(userspace/engine): improve rule loading validation results

---

docker/no-driver/Dockerfile

Signed-off-by: Thomas Labarussias <issif+github@gadz.org>
/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
> /area CI
This PR installs the package `ca-certificates` in the no-driver image.
Some plugins are calling external API (Okta, EKS, ...) and the requests …

install ca-certificates in falco:no-driver image

---

falco.yaml
userspace/falco/CMakeLists.txt
userspace/falco/app_actions/print_support.cpp
userspace/falco/app_actions/print_version.cpp
userspace/falco/app_actions/start_webserver.cpp
userspace/falco/application.h
userspace/falco/versions_info.cpp
userspace/falco/versions_info.h
userspace/falco/webserver.cpp
userspace/falco/webserver.h

/kind feature
/area engine
This PR adds a new webserver endopoint `/versions` that can be used to retrieve the versions of the internal Falco components. This can be specifically useful to get this information from a running instance of Falco from external tools, either locally or when deployed in Kubernetes.
Since this happens at runtime, the JSON response also includes the version of the loaded plugins.
```bash
curl http://localhost:8765/versions
```
```json
{
"default_driver_version": "4.0.0+driver",
"driver_api_version": "3.0.0",
"driver_schema_version": "2.0.0",
"engine_version": "15",
"falco_version": "0.33.1-119+806a0e8",
"libs_version": "0.10.0", …
```

new(userspace/falco): add webserver endpoint for retrieving internal version numbers

---

cmake/modules/falcosecurity-libs.cmake
userspace/falco/app_actions/open_inspector.cpp

/kind feature
/area build
Fixes #
```release-note
update(cmake): updated libs to 0.10.1 tag.
```

update(cmake): updated libs to latest 0.10.1 tag.

---

docker/falco/Dockerfile

/kind cleanup
/area build
/area CI
This PR fixes the Dockerfile we use for building the `falcosecurity/falco` image by trusting the latest GPG organization key used to sign packages available at `https://falco.org/repo/falcosecurity-packages.asc`. 
This is supposed to fix the current CI issues we have due to the GPG key currently being rotated.
```release-note
fix(docker/falco): trust latest GPG key
```

fix(docker/falco): trust latest GPG key

---

scripts/publish-deb
scripts/publish-rpm

/kind cleanup
/kind feature
/area CI
This PR adds a new `-s` optional parameter to the `publish-deb` and `publish-rpm` scripts that we use in our CI to upload and sign both dev and release packages on https://download.falco.org/?prefix=packages/. The flag is responsible of re-generating all the existing packages' signatures along with the newly-added ones.
```release-note
update(scripts): add option for regenerating signatures of all dev and release packages
```

update(scripts): add option for regenerating signatures of all dev and release packages

---

scripts/falco-driver-loader

Signed-off-by: Roberto Scolaro <roberto.scolaro21@gmail.com>
/kind bug
/area engine
Double quotes caused wrong variable expansion.
Fixes #
```release-note
NONE
```

fix(scripts): fixed incorrect bash var expansion

---

falco.yaml
userspace/falco/app_actions/open_inspector.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind feature
/area engine
This PR allows Falco to take advantage of a new modern BPF feature: to assign more than one CPU to a single ring buffer.
This feature is EXPERIMENTAL, and you can use it only with the modern BPF probe. With EXPERIMENTAL, we mean that this config could be changed or removed across releases.
You can find more info about the feature datil here: https://github.com/falcosecurity/libs/pull/820
To learn how to use this new config see `falco.yaml` file in the PR …

new(userspace/falco): [EXPERIMENTAL] allow modern bpf probe to assign more than one CPU to a single ring buffer

---

userspace/falco/configuration.cpp

/kind bug
/area engine
In this PR https://github.com/falcosecurity/falco/pull/2363 I introduced a new config for the modern probe. Before the last commit the `cpus_for_each_syscall_buffer` config wasn't under the `modern_bpf:` path, I forgot to adjust the path in the last changes :man_facepalming: 
```release-note
NONE
```

fix(userspace): use the right path for the `cpus_for_each_syscall_buffer` config

---

docker/builder/modern-falco-builder.Dockerfile

/kind cleanup
/area build
This PR performs 2 main actions on the modern-falco-builder to mitigate some issues with the Falco CI:
* It splits various `make` commands into different docker RUN instructions, in this way we can catch errors in single steps. With the previous approach :point_down: we were not able to catch failures when `make package` failed: the CI job was successful but the build failed https://app.circleci.com/pipelines/github/falcosecurity/falco/3647/workflows/1fca77ee-28c8-4a4c-8344-ff44f3db447f/jobs/31261
```docker
RUN source scl_source enable devtoolset-9; \
cmake ${CMAKE_OPTIONS} /source; \
make falco -j${MAKE_JOBS}; \
make package; \
make tests …
```

update(CI): mitigate frequent failure in CircleCI jobs

---

cmake/modules/plugins.cmake

/kind feature
/area build
Update default plugins to the latest versions.
/milestone 0.34.0
Fixes #
```release-note
build: upgrade k8saudit plugin to v0.5.0
build: upgrade cloudtrail plugin to v0.6.0
```

build(cmake/modules): bump k8saudit to 0.5.0 and cloudtrail to 0.6.0

---

scripts/CMakeLists.txt
scripts/debian/postinst.in
scripts/rpm/postinstall.in
scripts/systemd/falco-bpf.service
scripts/systemd/falco-custom.service
scripts/systemd/falco-kmod.service
scripts/systemd/falco-modern-bpf.service

/kind bug
/kind cleanup
/area engine
This PR solves some issues with `systemd` units. 
1. With the actual implementation `systemd restart` and `systemd condrestart` cause:
```
Transaction contains conflicting jobs 'restart' and 'stop' for falcoctl-artifact-follow.service. Probably contradicting requirement dependencies configured.
```
This issue is solved by removing the `Conflicts=` directive. The `Conflicts=` directive was here just to protect users from running more than one Falco instance with `systemd`, but since this causes issues we prefer to disable this behavior allowing to use `restart`/`condrestart` commands
2. The PR provides a new environment variable …

update(systemd): solve some issues with systemd unit

---

scripts/debian/postinst.in
scripts/falco-driver-loader
scripts/rpm/postinstall.in
scripts/systemd/falco-bpf.service

/kind bug
Reverts 308736280dc70289511111dd094e193639f72cff; we always need to use `insmod` to avoid weird situations (eg: multiple drivers being installed at the same time, and modprobe choosing the oldest one).
Moreover, for package/host installations, enforce the usage of dkms, with `--compile` flag.
Fixes #
```release-note
NONE
```

fix(scripts): driver loader insmod

---

cmake/cpack/debian/conffiles
cmake/modules/rules.cmake
docker/builder/modern-falco-builder.Dockerfile

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area tests
> /area CI
Fixes #
/milestone 0.34.0
```release-note
build: `/etc/falco/rules.available` has been deprecated
build: `application_rules.yaml` is not shipped anymore with Falco
BREAKING CHANGE: if you relied upon `application_rules.yaml` you can download it from …
```

build(cmake)!: deprecate `/etc/falco/rules.available`

---

scripts/debian/postinst.in
scripts/rpm/postinstall.in
scripts/systemd/falco-bpf.service

/kind bug
/area build
This PR reverts part of  [7a794b70a71896a3eb1971ca66cc0c19b9a104e6](https://github.com/falcosecurity/falco/commit/d5a7181fe1b7724e00790cb521bff99bde169d56): the falco-driver-loader should be used only in installation scripts otherwise we need separate units with high privileged to download/compile drivers
```release-note
fix(scripts): use falco-driver-loader only into install scripts
```

fix(scripts): use falco-driver-loader only into install scripts

---

scripts/CMakeLists.txt

/kind bug
Falcoctl config should be installed under /etc/falcoctl.
Fixes #
```release-note
NONE
```

fix(scripts): fixed falcoctl config install dir.

---

falco.yaml
userspace/falco/app_actions/load_rules_files.cpp
userspace/falco/configuration.cpp

/kind design
/area engine
This PR changes the `cpus_for_each_syscall_buffer` default value to `2`. In this way, the memory footprint of the modern bpf should be comparable with the other 2 drivers. See the thread here for more info :point_down: 
https://lore.kernel.org/bpf/CAEf4BzbYoGY2e_Nf1EOgzDdjGOLbSjJ5OmHRDFnYUA_VDYD6zQ@mail.gmail.com/T/#mdf8c6015b18a49edc95e4e7a8e4f7fcaf304cfc4
```release-note
update(userspace): change `modern_bpf.cpus_for_each_syscall_buffer` default value
```

update(userspace): change `modern_bpf.cpus_for_each_syscall_buffer` default value

---

userspace/falco/app_actions/open_inspector.cpp

/kind cleanup
When not run in `-A` mode, Falco will start dropping mode.
Dropping mode enables following logic in drivers:
* parameter passed to `start_dropping_mode` is the "sampling_ratio", ie: how much a second is "sampled"; if you pass `1` (what we are doing in Falco), you are saying that you want each second to be fully sampled; if you pass `2`, it means you want to sample each 0.5s, and so on.
* So, Falco is passing `1` basically disabling the sampling logic (that can be found here: https://github.com/falcosecurity/libs/blob/master/driver/main.c#L1695)
* instead, it is just enabling the dropping logic: …

cleanup(userspace/falco): do not enter dropping mode.

---

docker/no-driver/Dockerfile

/kind bug
> /kind design
/area build
> /area engine
> /area tests
> /area CI
The `falco-no-driver` image missed the `ca-certificates`. This PR installs them in the final build stage.
#2274 #2395
Fixes #
I've built and tested the new image locally and it seems that the certificate issues are gone. …

fix(dockerfile/no-driver): install ca-certificates

---

unit_tests/engine/test_filter_evttype_resolver.cpp
userspace/engine/filter_evttype_resolver.cpp
userspace/engine/filter_evttype_resolver.h
userspace/falco/app_actions/print_syscall_events.cpp

/kind feature
/area engine
This PR adds support for generic events usage in rules file. 
I set it as `new` instead of `fix` because this was a previous choice; nowadays, i think it might be useful to allow users to filter on generic events, like if people want to know if a `fchownat` happened.
Of course, you need to enable the `-A` switch to get all events (generic too)!
Moreover, all generic events are indexed under the same bucket (0 for enter and 1 for exit); again, this is a performance penalty, but users are already well educated about `-A` enforcing a perf penalty.
Fixes #2348
**Does this …

new(userspace,tests): add proper support for generic events indexing.

---

.github/workflows/images_bumper.yml

/kind feature
/area CI
Builder and Tester images aren't automatically pushed right now; they are manually pushed instead.
This PR  aims at making their build and push automatic upon any change to their docker/X folder.
Fixes #
```release-note
NONE
```

new(ci): added new workflow to automatic tag and publish new builder and tester images upon changes

---

unit_tests/engine/test_filter_evttype_resolver.cpp
userspace/engine/filter_evttype_resolver.cpp
userspace/engine/filter_evttype_resolver.h

/kind bug
/area engine
Thanks to @incertum findings we discovered that the current event type resolver had some uncovered corner cases (see: https://github.com/falcosecurity/libs/pull/854#issuecomment-1411151732). This mostly involved cases where rules conditions have an `evt.type` combined with `not` negation, so it should not be a big deal, however fixing it is crucial for the correctness and predictability of rules' indexing.
```release-note
fix(userspace/engine): correctly handle evttype indexing corner cases 
```

fix(userspace/engine): correctly handle evttype indexing corner cases 

---

unit_tests/CMakeLists.txt
unit_tests/falco/actions/test_select_event_sources.cpp
userspace/falco/CMakeLists.txt

/kind cleanup
/area build
/area tests
Following the effort of https://github.com/falcosecurity/falco/pull/2414, this PR adds a first suite of unit tests for Falco app's action `select_event_sources` (a low-hanging fruit compared to the others).
To do so, the CMake setup has been changed a bit due to the need of the gtest binary to be linked with the source code under userspace/falco (it was not so far, thus making all that code practically untestable if not header-only). The changes involve creating an intermediate `falco_application` static library target, which is then linked to the unit test binary and to the `falco` executable (which also compiles the falco.cpp …

update(unit_tests): add first action tests for select_event_sources

---

cmake/modules/falcosecurity-libs.cmake
docker/no-driver/Dockerfile
userspace/engine/falco_engine_version.h

> /kind bug
> /kind design
/kind release
> /area build
> /area engine
> /area tests
> /area CI
This PR cherrypicks the commits introduced by the following PRs:
* #2418 
* #2412 
to `release/0.34.x` branch.
Fixes #
```release-note
NONE
```

sync falco 0.34.1

---

cmake/modules/falcosecurity-libs.cmake

> /kind bug
> /kind design
/area build
> /area engine
> /area tests
> /area CI
Bump the `libs` version to [0.10.4](https://github.com/falcosecurity/libs/releases/tag/0.10.4).
Fixes #
The same changes have been introduced in the `0.34.x` branch, too. (https://github.com/falcosecurity/falco/pull/2422/commits/84ab4087705734bd4b425c1491e5633a53f28ae1) …

update(cmake): bumped libs to 0.10.4

---

userspace/engine/falco_engine.cpp

> /kind bug
> /area build
> /area engine
To make it possible to build the `engine` sources on Windows, a conditional compilation directive is introduced to prevent including the `<unistd.h>` header and defining `srandom` and `random` functions with Windows equivalent. 
```release-note
NONE
```

fix: define Windows equivalent for srandom and random functions

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
falco.yaml
userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/app/actions/init_inspectors.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind feature
/area engine
This PR bumps libs to latest master (https://github.com/falcosecurity/libs/commit/c8b0d6a8fdc1bb3ea9067bc2fdc3ae5858cff48f).
Moreover, it introduces a new `syscall_drop_failed` config option to instrument drivers to drop failed syscalls exit events, exposing the new feature impl by https://github.com/falcosecurity/libs/pull/834.
Fixes #
```release-note
new(cmake): bumped libs to c8b0d6a8fdc1bb3ea9067bc2fdc3ae5858cff48f
new(userspace): add a new `syscall_drop_failed` config option to drop failed syscalls exit events
```

new: driver drop failed

---

.github/workflows/ci.yml

/kind cleanup
/area CI
See https://github.com/falcosecurity/libs/pull/1029 and https://github.com/falcosecurity/libs/pull/1028
Fixes #
```release-note
NONE
```

cleanup(ci): properly set a concurrency for CI workflows.

---

unit_tests/falco/app/actions/test_configure_interesting_sets.cpp

/kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
/area tests
> /area CI
@jasondellaluce still getting errors locally with current master, e.g.
```
[----------] Global test environment tear-down
[==========] 30 tests from 9 test suites ran. (3009 ms total)
[  PASSED  ] 28 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] ConfigureInterestingSets.selection_not_allevents
[  FAILED  ] ConfigureInterestingSets.selection_allevents
2 FAILED TESTS
[]$ git status
nothing to …
```

cleanup(unit_tests): try making test_configure_interesting_sets more robust

---

userspace/engine/falco_engine.h
userspace/falco/app/actions/init_clients.cpp
userspace/falco/app/actions/init_falco_engine.cpp
userspace/falco/app/options.cpp
userspace/falco/app/options.h

/kind cleanup
/area engine
This follows up [#2328 add deprecation warning for Mesos](https://github.com/falcosecurity/falco/pull/2328) and completely removes the Mesos support from Falco.
/milestone 0.35.0
```release-note
update!: remove `--mesos-api`, `-pmesos`, and `-pm` command-line flags
BREAKING CHANGE: support for metadata enrichment from Mesos has been removed.
```

cleanup: remove Mesos support from Falco.

---

scripts/falco-driver-loader

/kind feature
Adds support in falco-driver-loader for al2022 and al2023.
Fixes #
```release-note
update(scripts): support al2022 and al2023 in falco-driver-loader.
```

update(scripts): updated falco-driver-loader to support al2022 and al2023

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
unit_tests/falco/app/actions/test_select_event_sources.cpp
userspace/engine/falco_common.h
userspace/engine/falco_engine_version.h
userspace/falco/app/actions/init_falco_engine.cpp
userspace/falco/app/actions/init_inspectors.cpp
userspace/falco/app/actions/load_plugins.cpp
userspace/falco/app/actions/process_events.cpp
userspace/falco/app/actions/select_event_sources.cpp
userspace/falco/app/state.h
userspace/falco/configuration.cpp

/kind cleanup
/area build
/area engine
This syncs Falco with the latest libs, and adapts the event source management logic to match the one of libsinsp. Moreover, we now make sure that the plugin loading order is preserved as in the Falco configuration. This allows for an optimal and more predictable event source management. Also, more explicit errors are thrown when events with unexpected event source are fetched during a capture (both live and offline).
```release-note
update: bump libs and adapt Falco to new libsinsp event source management …
```

update: bump libs and adapt Falco to new libsinsp event source management

---

unit_tests/falco/app/actions/test_configure_interesting_sets.cpp
userspace/falco/app/actions/configure_interesting_sets.cpp
userspace/falco/app/actions/print_ignored_events.cpp
userspace/falco/app/app.cpp
userspace/falco/app/app.h
userspace/falco/app/options.cpp

/kind cleanup
/kind design
/area engine
This PR segregates the logic behind the `-i`/`-A` ignored events in a single place. The set of ignored events is now set to be the one of the high-throughput I/O syscalls (that can be impactful for performance), but excluding those that are part of the base set of events required by libsinsp to collect its internal state.
Accordingly, this removes all mentions to the I/O syscalls set from the CLI helpers and comments. The fact that we chose that set as ignored should be an implementation detail that we don't leak as part of the tool's UX. This way, the output of `-i` is the only contract we have with users about which events …

update: improve control and UX of ignored events

---

.github/workflows/reusable_build_packages.yaml

/kind bug
/area CI
Moreover, fixed path to output packages from Falco `make package` target.
Fixes #
```release-note
NONE
```

chore(ci): properly install recent version of git (needed >= 2.18 by checkout action)

---

.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_publish_packages.yaml

/kind bug
/area CI
* A new job `fetch-version` was added to detect the Falco version, but not all dependent jobs were updated.
* Fixed downloading of artifacts since we were trying to use a wildcard which isn't really supported 😅
* Minor fix (security best practice) with handling the secret
Fixes #
```release-note
NONE
```

fix(ci): fetch version step, download rpms/debs, minor change

---

.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_publish_packages.yaml

/kind bug
/area CI
This fixes a couple things with the publish package pipeline
* Now different types of packages are extracted to different directories. In the current state, static overwrites bin!
* The static artifact is renamed before being uploaded to maintain consistency with the artifact names
Fixes #
```release-note
NONE
```

fix(ci): separate rpm/bin/bin-static/deb packages before publication, rename bin-static

---

scripts/falco-driver-loader

Closes 2517
Make wrapper now uses $TMPDIR if set.
/kind bug
> /kind design
/area build
> /area engine
> /area tests
> /area CI
Replaces hardcoded path for make wrapper, to allow building via falco-driver-loader on systems, where /tmp is mounted with noexec.
Fixes #2517
```release-note
update: `falco-driver-loader` now uses now uses $TMPDIR if set
```

falco-driver-loader add TMPDIR support

---

.github/workflows/master.yaml
.github/workflows/release.yaml
.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_publish_docker.yaml
.github/workflows/reusable_publish_packages.yaml
RELEASE.md

/kind feature
/area CI
In this new pipeline we need RC support for several reasons:
* We want to actually publish RCs before release for testing purposes
* Once we're in the release branch there was no way to test the latest version or to get a working image unless it is already released, which is painful, inconvenient and slows the release process
* We actually want to test the release flow and any new feature we add before we do an actual release :)
*How does it work?*
Once a maintainer clicks the release button on GitHub a tag is created and a GH release added as well. If the tag name is formatted like `x.y.z` the release is official, also if the "make latest" button is pressed the release is also latest (meaning that …

new(ci): add RC/prerelease support

---

.github/workflows/release.yaml
.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_publish_docker.yaml

/kind bug
/kind cleanup
/area CI
This is a refactor and fix of the container image publishing process. There are two major changes:
1. Images with arch-specific tags are pushed to Docker Hub (e.g. `:x86_64-0.35.0`). This is done because in order to create a multiarch (`index`, `manifest.list`) manifest easily we need manifests with the referenced digests already published. It is probably possible to do it without (buildx can do something similar) but it may involve a local registry or some more complicated process. I think this is fine for now.
2. Instead of building images multiple times and then publishing all of them, this one only builds one version …

fix(ci): simplify and fix multi-arch image publishing process

---

scripts/falco-driver-loader

/kind feature
This PR adds support for [talos](https://github.com/siderolabs/talos) in falco-driver-loader.
Part of the effort for prebuilt artifacts for talos: 
* https://github.com/falcosecurity/kernel-crawler/pull/131
* https://github.com/falcosecurity/test-infra/pull/1129
* https://github.com/falcosecurity/driverkit/pull/271
Fixes #
WIP because i first want to test that the kernelconfigdata we are fetching can correctly build a working driver.
```release-note
new(scripts): properly manage talos prebuilt drivers
```

new(scripts): updated falco-driver-loader to properly support talos.

---

.circleci/config.yml
cmake/modules/GetGitRevisionDescription.cmake

/kind bug
/area build
Given that we now support prereleases, we do want to exclude them from Falco version computation.
Fixes #
```release-note
NONE
```

fix(cmake): properly exclude prereleases when fetching latest tag from cmake

---

userspace/falco/app/actions/load_rules_files.cpp

/kind cleanup
/area engine
The `-A` flag is now supported with the modern bpf probe
```release-note
cleanup(actions): now modern bpf support `-A` flag
```

cleanup(actions): now modern bpf support `-A` flag

---

falco.yaml

* Improve documentation the `base_syscalls` option.
* Shuffles and re-words a few blurbs to help provide the user with context and actionable items
(no issue ticket filed)
cc @incertum @jasondellaluce for review, thanks for help!
No, since this is a net-new feature going into Falco `0.35`+
```release-note
NONE
```

docs: improve documentation and description of base_syscalls option

---

.github/workflows/reusable_build_docker.yaml

/kind bug
/area CI
We are being hit by https://github.com/docker/buildx/issues/1758.
Avoid using buildx (we aren't using any feature btw)
Fixes #
Refs  #2501 
```release-note
NONE
```

fix(ci): use normal docker to build docker images, instead of buildx.

---

.github/workflows/reusable_build_docker.yaml

/kind bug
/area CI
In `buildx` TARGET_ARCH was automatically set.
Now that we use plain `docker build`, we must set it.
Fixes #
```release-note
NONE
```

fix(ci): set docker TARGET_ARCH

---

.github/workflows/reusable_build_docker.yaml

/kind bug
/area CI
Normal (non buildx) docker does not support direct storing to tar.
CI.
Fixes #
```release-note
NONE
```

fix(ci): properly use `docker save` to store images.

---

.github/workflows/master.yaml
.github/workflows/release.yaml

/kind cleanup
/area CI
Originally, the reusable workflows were pinned on the `master` branch. This is ok-ish but since we have a release model based on release branches this means that if a PR gets into master that modifies the release process (e.g. by changing some compilation option) we may break releases and have issues when we try to issue a patch release.
Fixes #
```release-note
NONE
```

update(ci): use repo instead of master branch for reusable workflows

---

userspace/falco/app/actions/create_signal_handlers.cpp
userspace/falco/app/actions/process_events.cpp
userspace/falco/event_drops.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/outputs.h
userspace/falco/outputs_grpc.cpp
userspace/falco/stats_writer.cpp
userspace/falco/stats_writer.h

/kind bug
/kind cleanup
/area engine
Following up #2333, this makes sure that numeric values are formatted as numbers in the JSON outputs of the new metrics system.
cc @incertum
```release-note
fix(userspace/falco): properly format numeric values in metrics
```

fix(userspace/falco): properly format numeric values in metrics

---

userspace/falco/app/actions/process_events.cpp

/kind bug
/area engine
When in multi-source mode, any failure of one event source should cause the others to be forcefully terminated too. This PR solves a bug that caused Falco to hang on a semaphore when the `syscall` source was the one terminating with error.
Fixes #
```release-note
fix(userspace/falco): don't hang on terminating error when multi sourcing
```

fix(userspace/falco): don't hang on terminating error when multi sourcing

---

userspace/falco/app/actions/configure_interesting_sets.cpp

Co-authored-by: Roberto Scolaro <roberto.scolaro21@gmail.com>
/kind bug
/area engine
When we insert only one bad entry in the `base_syscall.custom_set` sequence (or a sequence of bad entries), Falco fails to output the "invalid syscalls" warning because it sees the custom set as empty, given that it crops the invalid values. This PR makes sure that the warning is always printed.
```release-note
chore(userspace/falco): always print invalid syscalls from custom set
```

chore(userspace/falco): always print invalid syscalls from custom set

---

falco.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Make it easier for adopters to understand and navigate Falco configs to achieve optimal deployment settings.
- re-arrange falco.yaml configs in logical categories
- add an index for logical categories
- move configs around without changing description content,
solely add a uniform header to each config
- indicate "Stable" or "Experimental" for most configs
to indicate current stability or …

cleanup(config): improve `falco.yaml` config

---

docker/builder/Dockerfile
docker/builder/modern-falco-builder.Dockerfile
docker/driver-loader/Dockerfile
docker/falco/Dockerfile
docker/local/Dockerfile
docker/no-driver/Dockerfile
docker/tester/Dockerfile
docker/ubi/Dockerfile

Closes #2591
/kind feature
/area build
/area CI
This PR changes nothing from a functional perspective. It adds
the standard image source label from the Open Containers label
spec. More info can be found [here](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys).
This will allow tools such as renovate to take advantage of changelogs
when the falco repository is updated.
Fixes #2591
N/A
```release-note
feat: add image source OCI label to docker images
```

feat: add image source OCI label to docker images

---

userspace/falco/app/actions/load_rules_files.cpp

/kind bug
/area engine
We have an egg-and-chicken problem here. We would like to check plugin requirements before loading any rule, so that we avoid having all the "unkwown field XXX" errors caused when a plugin is required but not loaded. On the other hand, we can't check the requirements before loading the rules file, because that's where the plugin dependencies are specified. This issue is visible only for dependencies over extractor plugins, due to the fact that if a source plugin is not loaded, its source will be unknown for the engine and so it will skip loading all of the rules to that source, to finally end up here and return a fatal error due to plugin …

fix(userspace/falco): report plugin deps rules issues in any case

---

docker/no-driver/Dockerfile

To supoprt the use of outputs that are documented in the falco
examples (e.g. jq piped to curl) I would like to propose including
these tools in the falco-no-driver image. They add a very minimal
size and dependency to the image but would make things a lot easier
for users getting started.
Closes #2580
Signed-off-by: Daniel Wright <danielwright@bitgo.com>
/kind feature 
/area build
/area ci
This PR adds the jq and curl packages to the falco-no-driver
Docker image. This will allow users who choose to use this
image to get up and running more quickly with the examples
listed in the documentation for outputs, such as the program
output. …

feat: add jq and curl to falco-no-driver docker image

---

userspace/engine/falco_engine.cpp

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
fix(userspace/engine): store alternatives as array in -L json output 
```

fix(userspace/engine): store alternatives as array in -L json output

---

userspace/falco/outputs_http.cpp

This commit will unquote URL's allowing them to be supported by
libcurl and eliminate any errors when a valid (quoted) URL is supplied
by a user.
Closes #2579
Signed-off-by: Daniel Wright danielwright@bitgo.com
/kind bug
/area engine
As mentioned in the associated issue, I was setting up some
values which contained special character as the URL had a
secret token in it, and wanted to quote to avoid any ambiguity
or issues when adding to a manifest. I encountered a libcurl
error that my valid (quoted) string was invalid.
Fixes #2579
N/A
N/A …

fix: unquote quoted URL's to avoid libcurl errors

---

cmake/modules/plugins.cmake

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
update(cmake): bump plugins to latest versions
```

update(cmake): bump plugin versions

---

README.md

/kind cleanup
> /kind design
See https://github.com/falcosecurity/evolution/pull/273
Fixes #
```release-note
NONE
```

docs(README.md): add scope/status badge and simply doc structure

---

.github/workflows/reusable_publish_packages.yaml

/kind bug
/area CI
New debian bookworm, release on 10th of June, dropped python2 package.
Instead, we need to install `python-is-python3` package that creates the symlink for `/usr/bin/python3` to `/usr/bin/python`.
Fixes CI.
Fixes #
```release-note
NONE
```

fix(ci): fixed publish deb packages with new debian bookworm

---

userspace/falco/app/actions/process_events.cpp

/kind cleanup
/area engine
```release-note
chore(userspace/falco): make source matching error more expressive
```

chore(userspace/falco): make source matching error more expressive

---

userspace/falco/stats_writer.cpp

/kind bug
/area engine
Switched to use `timer_settime` API in stats writer, as `setitimer` seems to have issues when built from our CI (glibc/gcc bugs?)
Fixes #2645 
```release-note
fix(userspace): switch to timer_settime API for stats writer.
```

fix(userspace): switch to timer_settime API for stats writer.

---

scripts/falco-driver-loader

/kind bug
> /area build
> /area engine
> /area tests
> /area CI
This corrects the `kernel_version` parsing for ubuntu flavors.
Fixes #
```release-note
fix(driver-loader): fix ubuntu kernel version parsing
```

fix(scripts/falco-driver-loader): fixed ubuntu kernel version

---

scripts/falco-driver-loader

/kind bug
Support debian `rt` and `cloud` flavors.
See https://github.com/falcosecurity/falco/issues/2625 issue for more info.
Basically, kernel-crawler is going to be fixed to properly output flavored debian kernels, see https://github.com/falcosecurity/kernel-crawler/pull/147.
For Falco 0.35.0, we are only supporting the normal (ie: the one without suffix) kernel flavor; with this patch we will support `rt` and `cloud` too.
Fixes #2625
```release-note
fix(scripts): fixed falco-driver-loader to manage debian kernel rt and cloud flavors.
```

fix(scripts): support debian kernel flavors other than normal in falco-driver-loader

---

userspace/falco/app/options.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
NONE
```

update(userspace/falco): improve cli flag description related to drivers

---

.github/workflows/reusable_build_packages.yaml
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h

/kind feature
/area build
/area engine
Bump falco to latest libs dev version https://github.com/falcosecurity/libs/commit/aeff81476d0dcd3bfe7002e8642163b6bd11094e
```release-note
NONE
```

chore: bump Falco to latest libs version

---

falco.yaml
userspace/engine/evttype_index_ruleset.cpp
userspace/engine/evttype_index_ruleset.h
userspace/engine/falco_common.cpp
userspace/engine/falco_common.h
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_engine_version.h
userspace/engine/falco_source.h
userspace/engine/filter_ruleset.h
userspace/falco/app/actions/init_falco_engine.cpp
userspace/falco/app/actions/process_events.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area tests
> /area CI
This PR adds a configuration key to Falco to let it match multiple rules on the same event, avoiding a well-known shadowing problem between rules. To not introduce breaking changes, the old behavior is kept and can still be used (expressed trough config). To implement this, Falco will simply continue trying to evaluate the condition of rules in the bucket of same evt.type rules, without …

new: allow falco to match multiple rules on same event

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/falco/app/actions/init_falco_engine.cpp
userspace/falco/app/actions/process_events.cpp

> /kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Since `process_event` could be called by multiple threads, passing the `rule_matching` strategy to the engine at each call rather than storing state inside it is better for thread safety.
Fixes #
```release-note
NONE
```

update(userspace/engine): make rule_matching strategy stateless 

---

scripts/falco-driver-loader

In https://github.com/falcosecurity/falco/pull/2043 we've added logic for relocating tools on Flatcar when running falco-driver-loader in kmod mode. This logic is relevant for BPF mode, too, which is currently broken on Flatcar. Call flatcar_relocate_tools in BPF mode, too.
cc: @jepio
/kind bug
> /area build
> /area engine
> /area tests
> /area CI
In #2043 we've added logic which ensures driver compilation works on Flatcar Container Linux. This logic was added for kmod only, and therefore BPF driver compilation is currently broken for Flatcar. This PR invokes …

Relocate tools on Flatcar in BPF mode

---

scripts/falco-driver-loader

/kind feature
> /area build
> /area engine
> /area tests
> /area CI
This PR adds the ability to specify explicit kernel release and version when running `falco-driver-loader`. This is important in cases where the Falco driver needs to be compiled for a kernel other than the currently-running kernel (such as when the kernel had been updated but not yet booted into).
Fixes #2658 
None
```release-note
feat: Allow specifying explicit kernel …
```

Allow specifying explicit kernel release and version for `falco-driver-loader`

---

scripts/systemd/falco-bpf.service
scripts/systemd/falco-custom.service
scripts/systemd/falco-kmod.service
scripts/systemd/falco-modern-bpf.service

/kind cleanup
This PR https://github.com/falcosecurity/falco/pull/2677 highlighted that we don't need this `--pidfile` option in our systemd units. At this point, I'm not even sure we want to keep this option at all @leogr @incertum...BTW In this PR I've just removed its usage in our systemd unit
```release-note
NONE
```

cleanup: remove unused `--pidfile` option from systemd units

---

.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_build_packages.yaml

/kind cleanup
/area CI
Github Actions have a default retention period of 90 days. However, some of our artifacts are used at build-time only to pass around artifacts between different CI jobs, thus we don't need them after the workflow is finished. In particular, `falco-images` weights ~4GB, which is a big waste of storage.
```release-note
NONE
```

update(ci): minimize retention days for build-only CI artifacts

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/outputs_http.cpp

/kind feature
/area engine
**What this PR does / why we need it**: Currently there is no mTLS option for the HTTP output, it would be more secure to have this feature.
**Which issue(s) this PR fixes**:  
Fixes https://github.com/falcosecurity/falco/issues/2632
```release-note
new(falco/config): add new configurations for http_output that allow mTLS
```

feat(userspace/outputs_http): Add option for mTLS

---

userspace/falco/app/actions/process_events.cpp

/kind cleanup
/area engine
This PR addresses some comments i left on another PR:
* https://github.com/falcosecurity/falco/pull/2739#discussion_r1305501094
* https://github.com/falcosecurity/falco/pull/2739#discussion_r1305503656
```release-note
NONE
```

cleanup: turn some warnings into errors

---

cmake/modules/driver-repo/CMakeLists.txt
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs-repo/CMakeLists.txt
cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
Whoever of us ever tried to build Falco with their own libs fork when testing changes in libs, had to hack a patch like this one. So for sake of completeness I'll propose supporting this natively in our cmake files. Example of how this could be used:
```
cmake -DFALCOSECURITY_LIBS_REPO=jasondellaluce/falco-libs ..
make falco -j4
...
```
```release-note
update(cmake): support building libs and driver from forks
```

update(cmake): support building libs and driver from forks

---

userspace/engine/falco_engine.cpp

/kind bug
/kind cleanup
/area engine
This solves a minor issue with old GCC versions.
```release-note
NONE
```

fix(userspace/engine): support both old and new gcc + std::move

---

scripts/falco-driver-loader

/kind bug
Fixes #2352
```release-note
falco-driver-loader --source-only now prints the values as env vars
```

fix: falco-driver-loader source-only print env vars

---

userspace/engine/falco_engine.cpp
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_loader_collector.cpp
userspace/engine/rule_loader_compiler.cpp

/kind bug
/area engine
In case we have a rule using an unknown source (e.g. when its plugin is not leaded), we have a bug that prevents appending to that rule. For example:
```yaml
- rule: Rule1
desc: NoDesc
condition: evt.type=open
priority: INFO
output: Never
source: mysource
- rule: Rule1
append: true
condition: or evt.type=openat
```
```release-note
fix(userspace/engine): support appending to unknown sources
```

fix(userspace/engine): support appending to unknown sources

---

userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/app/options.cpp

/kind bug
/kind cleanup
/area engine
This PR fixes the minimal build on Falco master that was broken and deprecates the `--userspace` option since it is no longer maintained 
```release-note
fix: restore Falco MINIMAL_BUILD and deprecate `userspace` option
```

fix: restore Falco MINIMAL_BUILD and deprecate `userspace` option

---

falco.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Add more info to the config descriptions, very minor addition.
Fixes #
```release-note
cleanup(config): add more info
```

cleanup(config): add more info

---

falco.yaml
userspace/falco/configuration.cpp

/kind cleanup
/area engine
This PR deprecates the rate limiter mechanism since it seems to be no longer used and moreover, it discards events, so one can potentially lose critical alerts. For this reason, it's not enabled by default.
See this discussion for more details https://github.com/falcosecurity/falco/pull/2711#discussion_r1281346149
```release-note
cleanup: deprecate rate limiter mechanism
```

cleanup: deprecate rate limiter mechanism

---

userspace/falco/app/restart_handler.cpp
userspace/falco/stats_writer.cpp

/kind bug
/area engine
Properly deletes metrics related timer upon leaving.
Fixes #2757 
How i tested the fix:
* set metrics enabled and interval 15s
* start Falco
* immediately (before 15s elapses) change interval to eg: 2m
* wait 
* you will receive just one stats after 2min (otherwise you would've received one after 15s since Falco started)
Did the same also playing a bit with the interval values, like restarting Falco 4-5 times in a row updating `metrics.interval` config value.
Everything was sane.
```release-note
fix(userspace/falco): …
```

fix(userspace/falco): properly delete metrics timer upon leaving.

---

.github/workflows/reusable_test_packages.yaml
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h

/kind feature
/area build
bump Falco to latest libs master
```release-note
NONE
```

chore: bump Falco to latest libs master

---

.github/workflows/reusable_test_packages.yaml

/kind bug
/area CI
This PR should allow us to build and run Falco e2e tests on our self-hosted arm64 runners
```release-note
NONE
```

ci: support tests on amazon-linux

---

unit_tests/falco/test_configuration.cpp
userspace/falco/yaml_helper.h

/kind feature
/area engine
/area tests
In order to allow the user to supply environment variables in standard
ways performed in other applications the get_scalar function has been
extended to support defining an environment variable in the format
`${FOO}`. Environment variables can be escaped via defining as `$${FOO}`. 
As this handles some additional complexity, a unit test has been  added 
to cover this new functionality
Fixes  #2561
```release-note
feat: support parsing of system environment variables in yaml
```

feat: support parsing of system environment variables in yaml

---

docker/no-driver/Dockerfile

/kind feature
/area build
Since we're updating the large image to Debian 12 I believe it makes sense to update the nodriver one as well. It's also slightly smaller (about ~30MB smaller).
I tested it with the *modern eBPF* probe and the (previously installed) kernel module.
Fixes #
```release-note
update(docker): the Falco no-driver image is now based on Debian 12
```

update(docker): use debian 12 slim for falco no driver

---

.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_publish_docker.yaml
docker/driver-loader-legacy/Dockerfile
docker/driver-loader-legacy/docker-entrypoint.sh
docker/falco/Dockerfile

/kind feature
/area build
/area CI
As per our discussion in https://github.com/falcosecurity/falco/issues/2489 and during yesterday's core maintainer call, I propose to:
* Upgrade the Falco base image with the one that seems to build the most kernels at the moment
* Still distribute the old one, marked as legacy, adding the necessary CI/CD job steps
Fixes #2489
```release-note
update!: the Falco base image is now based on Debian 12 with gcc 11-12
new: the legacy falco image is available as driver-loader-legacy
```

new(falco): update the Falco base image to debian 12

---

userspace/falco/stats_writer.cpp

/kind bug
/area engine
When running Falco with these changes in the default config:
```yaml
metrics:
enabled: true
interval: 5s
output_rule: false
output_file: ./falco_stats.json
resource_utilization_enabled: true
kernel_event_counters_enabled: true
libbpf_stats_enabled: true
convert_memory_to_mb: true
include_empty_values: false
```
it crashes with a segfault. The reason was that the `m_output` field of the stats writer was not initialized, but we tried to use it anyway in the collection stats phase
```release-note
NONE
```

fix(stats): always initialize m_output field

---

userspace/falco/falco_outputs.cpp

/kind bug
/area engine
Invoking `empty` in the concurrent queue will do nothing if not generating a warning for an unchecked ret value.
cc @incertum 
```release-note
NONE
```

fix(userspace/falco): clearing full output queue

---

userspace/falco/falco_outputs.cpp

/kind cleanup
/area engine
This PR allows a better termination and prints a single log in case the queue output limit is reached
```release-note
NONE
```

cleanup(userspace): thrown exceptions and avoid multiple logs

---

cmake/modules/falcosecurity-libs.cmake
falco.yaml

/kind feature
/area build
bump to the latest libs commit
```release-note
NONE
```

chore: bump to the latest libs

---

userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/app/options.cpp
userspace/falco/app/options.h
userspace/falco/stats_writer.cpp

/kind cleanup
/area engine
This PR removes the deprecated `--userspace` option as described here https://github.com/falcosecurity/falco/issues/2763#issue-1877825551
```release-note
cleanup(falco)!: remove `--userspace` support
```

[BREAKING CHANGE] cleanup(falco)!: remove `--userspace` support

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_rule.h
userspace/engine/filter_details_resolver.cpp
userspace/engine/filter_details_resolver.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_loader_compiler.cpp
userspace/engine/rule_loader_compiler.h
userspace/falco/app/actions/load_rules_files.cpp

/kind bug
/kind cleanup
/kind feature
/area engine
This is focused on the rules description feature of the `-l` and `-L` options, in the specific case of the JSON output. The goal is to be more consistent and print more information, which can be used by our automation and for debugging purposes (some of these have been asked for a while). High-level changes:
- The rule loader compiler has been modularized even more. It will be fairly easier to write unit tests on it now.
- For each rule, macro, or list, now also print the plugins they used among the ones currently loaded
- For each list, now also prints the final "compiled" list of items (after resolving all list …

update(userspace/engine): modularize rule compiler, fix and enrich rule descriptions

---

.github/workflows/ci.yml
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_engine_version.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_loader_collector.cpp
userspace/engine/rule_loader_reader.cpp
userspace/engine/rule_loader_reader.h
userspace/falco/grpc_server_impl.cpp
userspace/falco/version.proto
userspace/falco/versions_info.cpp

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
This PR convert the falco `engine_version` to semver. It does so while trying to deal with possible breaking changes with rules. In particular, if `required_engine_version` yaml field in rule is
- numeric, it is converted into a semver string by appending and prepending major and patch number (0.x.0)
- a string, it will be handled as a semver string
Fixes # …

update: engine_version in semver representation

---

falco.yaml
userspace/falco/app/actions/process_events.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind cleanup
/area engine
This PR removes deprecated `outputs.rate` and `outputs.max_burst` from Falco config
```release-note
cleanup(falco)!: remove `outputs.rate` and `outputs.max_burst` from Falco config
```

[BREAKING CHANGE] cleanup(falco)!: remove `outputs.rate` and `outputs.max_burst` from Falco config

---

.github/workflows/ci.yml
.github/workflows/codeql.yaml
.github/workflows/codespell.yml
.github/workflows/engine-version-weakcheck.yaml
.github/workflows/release.yaml
.github/workflows/reusable_build_dev.yaml
.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_fetch_version.yaml
.github/workflows/reusable_publish_docker.yaml
.github/workflows/reusable_publish_packages.yaml
.github/workflows/reusable_test_packages.yaml
.github/workflows/staticanalysis.yaml

/kind cleanup
/area CI
We have started pinning some GitHub actions to their hash, especially the ones that were based on `master`. We should pin all of them. In order to limit potential breakage I have left out the actions that need a major version upgrade (except for checkout) so we can handle them in a subsequent PR.
Fixes #
```release-note
NONE
```

chore(gha): pin versions to hashes

---

.github/workflows/reusable_publish_packages.yaml

/kind bug
/area CI
This should fix the package publishing error on master as we do not actually need CentOS 7 for publishing.
Fixes #
```release-note
NONE
```

fix(gha): use fedora instead of centos 7 for package publishing

---

CHANGELOG.md
proposals/20221129-artifacts-distribution.md
userspace/falco/atomic_signal_handler.h
userspace/falco/falco_outputs.h
userspace/falco/stats_writer.cpp

/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Workaround for older GLIBC versions (< 2.35), where calling timer_delete() with an invalid timer ID not returned by timer_create() causes a segfault because of a bug in GLIBC (https://sourceware.org/bugzilla/show_bug.cgi?id=28257).
See also https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1940296.
Also verified it on:
```
[vagrant@centos7 ~]$ uname -r
5.14.15-1.el7.elrepo.x86_64
ldd --version …
```

fix(userspace/falco): timer_delete() workaround due to bug in older GLIBC

---

falco.yaml
userspace/engine/falco_common.cpp
userspace/engine/falco_common.h
userspace/falco/app/actions/init_outputs.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/stats_writer.cpp

/kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Remove experimental outputs queue recovery strategies due to the `empty` strategy being buggy (unpredictable failures) in the underlying tbb libs. Just keeping the option that mirrors kernel-side event drops when the buffer between kernel space and user space is full makes the most sense.
https://github.com/falcosecurity/falco/issues/2864
Fixes #
**Special notes …

feat(userspace): remove experimental outputs queue recovery strategies

---

CHANGELOG.md
cmake/modules/falcosecurity-libs.cmake
falco.yaml
proposals/20221129-artifacts-distribution.md
userspace/engine/falco_common.cpp
userspace/engine/falco_common.h
userspace/falco/app/actions/init_outputs.cpp
userspace/falco/atomic_signal_handler.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/stats_writer.cpp

/kind release
Backports 
from master.
Please note that this PR also bumps the libs version to latest tag 0.13.2-rc1, the last commit is not cherry-picked since Falco master is no more compatible with libs 0.13.2-rc1
```release-note
NONE
```

sync: release 0.36.1

---

cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
This PR bumps libs to the latest available tag `0.13.2`. We need to open the PR directly against the release branch because Falco master doesn't work anymore with `0.13.2`
```release-note
NONE
```

chore: bump libs to the latest tag 0.13.2

---

CHANGELOG.md

/kind release
/area build
add changelog for 0.36.1
```release-note
NONE
```

new(docs): add changelog for 0.36.1

---

userspace/engine/rule_loader_compiler.cpp

/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
This fixes a memory leak: `compiler.compile()` allocates a `sinp_filter` but never destroys it.
Fixes #
```release-note
fix(userspace/engine): fix memory leak
```

fix(userspace/engine): fix memory leak

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h

/kind bug
/area build
This fixes a performance regression introduced in `falco -L` since the latest release, caused by the fact that we re-compile the whole set of loaded rules twice. 
```release-note
fix(userspace/engine): cache latest rules compilation output
```

fix(userspace/engine): cache latest rules compilation output

---

.github/workflows/scorecard.yaml

/kind bug
/area CI
As per attached screenshot, which is not supposed to happen:
I'm not completely sure what triggers it (but 99% is test-infra checking if repos need to be updated) but I believe it's safe to disable it for now.
Thanks @Andreagit97 @FedeDP for the heads up and taking a look at our pipelines!
Fixes #
```release-note
NONE
```

fix(gha): disable branch protection rule trigger for scorecard

---

unit_tests/engine/test_falco_utils.cpp
userspace/engine/falco_utils.cpp
userspace/engine/falco_utils.h
userspace/engine/json_evt.cpp

/kind cleanup
/area engine
Since https://github.com/falcosecurity/libs/pull/1478 , the Falco libs no longer provides the `uri` class. The only functionality that Falco ever needed from there is an utility function to decode an urlencoded string. Port this function to the Falco engine. This is necessary for removal of the legacy metadata/k8s client.
Fixes #
I don't have a strong opinion about whether this could live in its own `uri.h` file or is fine in `falco_utils.h`. If anyone has, let me know!
**Does this …

update(engine): port decode_uri in falco engine

---

userspace/falco/configuration.cpp

/kind cleanup
/area engine
This `init({});` in the falco_configuration constructor is unnecessary since when we call the action `load_config`, if we don't have a config file, we will call the same `init` we have just removed. This cleanup avoids calling `falco_configuration::init` 2 times
```release-note
NONE
```

cleanup(falco): remove `init` in the configuration constructor

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
falco.yaml
userspace/engine/falco_engine_version.h
userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/stats_writer.cpp

> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
See the corresponding libs PR https://github.com/falcosecurity/libs/pull/1433
https://github.com/falcosecurity/libs/issues/1347
Fixes #
```release-note
update(userspace/falco): add libsinsp state metrics option
```

update(userspace/falco): add libsinsp state metrics option

---

userspace/falco/CMakeLists.txt
userspace/falco/app/actions/actions.h
userspace/falco/app/actions/print_kernel_version.cpp
userspace/falco/app/app.cpp
userspace/falco/app/state.h

/kind feature
/area engine
This PR helps maintainers in triaging issues and users in reporting effective info on issues. The idea is to print the content of `/proc/version` in the Falco startup messages @FedeDP 
```
Mon Nov 27 15:48:06 2023: Falco version: 0.37.0-155+6095d10 (x86_64)
Mon Nov 27 15:48:06 2023: Falco initialized with configuration file: ../falco.yaml
Mon Nov 27 15:48:06 2023: System info: Linux version 6.2.0-37-generic (buildd@bos03-amd64-055) (x86_64-linux-gnu-gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2
Mon Nov 27 15:48:06 2023: Loading rules …
```

new(falco): print system info when Falco starts

---

unit_tests/engine/test_falco_utils.cpp
userspace/engine/falco_utils.cpp
userspace/engine/falco_utils.h

/kind cleanup
/area engine
For all the fans of "wax on, wax off" out there, I'm going to basically revert https://github.com/falcosecurity/falco/pull/2912 because the only calling function needed to be removed but I didn't realize. Less unreachable code to worry about.
Fixes #
```release-note
NONE
```

cleanup(falco): remove decode_uri as it is no longer used

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
This PR bumps Falco to `000d576` libs commit
```release-note
NONE
```

chore(falco): bump Falco to `000d576` libs commit

---

unit_tests/engine/test_filter_macro_resolver.cpp
userspace/engine/falco_engine.cpp
userspace/engine/filter_details_resolver.h
userspace/engine/filter_macro_resolver.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_loader_compiler.cpp
userspace/engine/stats_manager.h
userspace/falco/app/actions/create_requested_paths.cpp
userspace/falco/app/actions/print_version.cpp
userspace/falco/app/actions/process_events.cpp
userspace/falco/app/restart_handler.h
userspace/falco/app/state.h
userspace/falco/atomic_signal_handler.h
userspace/falco/configuration.h
userspace/falco/falco_outputs.cpp
userspace/falco/falco_semaphore.h
userspace/falco/stats_writer.cpp
userspace/falco/stats_writer.h

/kind cleanup
A Clang build revealed a number of warnings whose fix should increase the quality of the code.
Fixes #
```release-note
NONE
```

cleanup: fix several warnings from a Clang build

---

.github/workflows/ci.yml
.github/workflows/reusable_build_dev.yaml
.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_test_packages.yaml

/kind feature
/area build
Add the https://actuated.dev service to execute ARM64 GitHub Actions instead of our self hosted runner. Following the instructions on: https://actuated.dev/blog/arm-ci-cncf-ampere
Fixes #
```release-note
NONE
```

update(ci): enable actuated.dev

---

userspace/falco/app/restart_handler.cpp

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
* Monitor events of `IN_CLOSE_WRITE | IN_MOVE_SELF | IN_DELETE_SELF` type for rule files and events of `IN_CREATE | IN_DELETE | IN_MOVE` type for rule directories.
Fixes #2943
```release-note
update: now the `watch_config_files` config option monitors file/directory moving and …
```

feat(userspace/falco): monitor more types of events for rule directories and files

---

.gitignore
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h

/kind feature
/area build
This PR bumps Falco to the latest libs
```release-note
NONE
```

chore: bump falco to latest libs

---

unit_tests/falco/test_configuration.cpp
userspace/falco/yaml_helper.h

/kind feature
/area engine
Moreover, support env variable embedding another env variable.
Basically, this PR would allow us to use eg:
```
engine:
ebpf:
probe: /${HOME}/.falco/falco-bpf.o
```
in #2413.
Fixes #
```release-note
new(userspace): support env variable expansion in all yaml, even inside strings.
```

chore(unit_test,userspace): allow env var to get expanded in yaml even when part of a string

---

falco.yaml

/kind cleanup
Since #2918 is now merged, we can freely use env var.
This is more correct since eg: `falcoctl` will copy built drivers there: https://github.com/falcosecurity/falcoctl/blob/main/pkg/driver/type/bpf.go#L55.
Most of the time, both falcoctl and Falco will run as root, thus the env var will resolve to the current `/root/.falco/falco-bpf.o`.
But if user decides to eg: have a Falco user with reduced privileges, she/he will still be able to let falcoctl install its ebpf probe and then Falco would start without issues.
Example output without and with `sudo`:
```
Wed Dec 13 17:10:40 2023: Opening 'syscall' source with BPF probe. BPF probe path: …
```

chore(falco.yaml): use HOME env var for ebpf probe path.

---

unit_tests/falco/test_configuration.cpp

/kind cleanup
/area tests
Added more (crazy) tests to the new env var expansion feature.
Fixes #
```release-note
NONE
```

chore(unit_tests): added more tests for yaml env vars expansion.

---

unit_tests/engine/test_enable_rule.cpp
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h

Add alternate enable_* methods that allow enabling rulesets by ruleset id in addition to name. This might be used by some filter_rulesets to enable/disable rules on the fly via the falco engine.
> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area tests
> /area CI
Allow enabling rules by ruleset id in addition to name. In cases where the ruleset id is already know, this avoids a redundant lookup.
Fixes # …

Allow enabling rules by ruleset id in addition to name

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/outputs_http.cpp

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
This PR adds two new configuration options for the http output:
Fixes #2955
```release-note
feat(userspace/falco): falco administrators can now configure the http output to compress the data sent as well as enable keep alive for the connection. Two new fields (compress_uploads …
```

update(config): Improve http output, add compression and keep_alive

---

.github/workflows/reusable_test_packages.yaml

/kind bug
/area CI
It seems like falco driver loader integration tests do not work reliably on actuated arm64 node, even if:
* manually ssh-ing inside the node and running the tests works fine
* trying the tests on an ec2 arm64 node runs fine
See https://github.com/falcosecurity/falco/pull/2979 with lots of tests.
Fixes #
```release-note
NONE
```

chore(ci): revert #2961.

---

userspace/falco/app/actions/load_config.cpp

/kind cleanup
/area engine
When I tried to start the gVisor engine I read a deprecation notice but I realized it didn't tell me what to do. This adds a bit of description there.
Fixes #
```release-note
NONE
```

cleanup(engine): clarify deprecation notice for engines

---

falco.yaml
userspace/falco/app/actions/load_config.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Fixes #
@FedeDP included https://github.com/falcosecurity/falco/issues/2949
```release-note
update(config): clarify deprecation notices + list all env vars
```

update(config): clarify deprecation notices + list all env vars

---

unit_tests/engine/test_rule_loader.cpp
userspace/engine/falco_engine_version.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_loader_collector.cpp
userspace/engine/rule_loader_collector.h
userspace/engine/rule_loader_reader.cpp

/kind feature
/area engine
/area tests
This is a rather straightforward implementation of https://github.com/falcosecurity/falco/issues/1340#issuecomment-1710135769 . See the comment for examples.
It is now possible to use the `override` key in rules, lists and macros. Some fields can be overridden: for lists and macros there is only one field that we care about, while for rules, the following fields have been selected:
* Available for `append`: `{"condition", "output", "desc", "tags", "exceptions"}`
* Available for `replace`: `{"condition", "output", "desc", "priority", "tags", …

new(engine): add selective rule overrides

---

unit_tests/engine/test_add_source.cpp
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Add methods to return the various factories provided via add_source(). This allows not having to keep track of them outside of the engine.
Fixes #
```release-note
NONE
```

Add addl source related methods

---

unit_tests/engine/test_rule_loader.cpp
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_load_result.cpp
userspace/engine/falco_load_result.h
userspace/engine/rule_loader_collector.cpp
userspace/engine/rule_loader_reader.cpp
userspace/engine/rule_loader_reader.h
userspace/engine/rule_loading_messages.h
userspace/falco/app/actions/load_rules_files.cpp
userspace/falco/app/actions/validate_rules_files.cpp

/kind cleanup
/kind design
/area engine
/area tests
In this PR I propose to deprecate the `append` flag in the Falco rules. With `deprecate` I mean that we should log a warning when the `append` key is used suggesting the new `override` key. The flag shouldn't be removed until Falco 1.0.0 since it could cause a big breaking change between users (I'm open to other ideas, maybe we can wait for some release cycle). In this PR there are also some cleanups.
Side note: I'm not fully convinced by the fact that warnings in the rule loading are suppressed by default...if we introduce a warning I expect that users will see it by default since probably they need to take some …

update(rule_loader): deprecate the `append` flag in falco rules

---

falco.yaml

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
Let's discuss graduating `outputs_queue` to stable. If you define some reasonable limits the queue can still fill up to that limit, hence I believe it is a valuable config and supporting the queue capacity and possible future extensions in a stable manner reflects best practices.
@falcosecurity/falco-maintainers  
Fixes # …

update(config): graduate outputs_queue to stable

---

falco.yaml
userspace/falco/app/actions/load_config.cpp
userspace/falco/app/state.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind cleanup
/area engine
This PR renames the `none` engine config into `state_only`. The idea is that `none` should mean no engine enabled, but this is not the case. Even though the `nodriver` is a particular engine, it opens an inspector without generating events. **So the idea is to rename the `none` into `state_only` and leave the `none` config for future use cases**. 
For example `none` should be used when we want to run a source plugin like `k8saudit` without opening a syscall engine. Today we need to do something like this:
```bash
falco -c /etc/falco.yaml -r k8saudit.rules --disable-source=syscall
```
In the future, if we add the config `none` we could …

cleanup(falco.yaml): rename `none` in `nodriver`

---

unit_tests/engine/test_rule_loader.cpp
userspace/engine/rule_loader_compiler.cpp

/kind bug
/area engine
When the engine compiles list infos, we have a small bug for which we store forcefully-quoted strings in the engine's data structures instead of quoting them only at the time of their usage (at list refs resolution time). After investigating, this doesn't seem to affect the runtime-evaluated rules data structures, but it's clearly visible with the `-L` functionality and reproduced on list items that are YAML-escaped or contain spaces.
Example:
```yaml
- list: my_list
items: [non_escaped_val, "escaped val"]
```
```
$ falco -L -o json_output=true -r rules_sample | jq .
{
"lists": [
{
"details": {
"items_compiled": [
"non_escaped_val", …
```

fix(userspace/engine): avoid storing escaped strings in engine

---

cmake/modules/njson.cmake
userspace/engine/CMakeLists.txt

/kind bug
/area build
The include path of library `nlohmann-json` is wrong when the build is done with `USE_BUNDLED_NLOHMANN_JSON=OFF`. 
Fixes #
```release-note
NONE
```

fix: nlohmann_json lib include path

---

falco.yaml
userspace/falco/app/actions/load_config.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Let's discuss deprecating `syscall_event_drops`.
@falcosecurity/falco-maintainers 
https://github.com/falcosecurity/falco/issues/2910
Fixes #
```release-note
update!(config): soft deprecation of drop stats counters in `syscall_event_drops`
```

update!(config): soft deprecation of drop stats counters in `syscall_event_drops`

---

cmake/modules/njson.cmake
cmake/modules/rules.cmake
falco.yaml
userspace/engine/CMakeLists.txt
userspace/falco/app/actions/load_config.cpp
userspace/falco/stats_writer.cpp

Cherry picks:
* https://github.com/falcosecurity/falco/pull/3032
* https://github.com/falcosecurity/falco/pull/3033
* https://github.com/falcosecurity/falco/pull/3015
* https://github.com/falcosecurity/falco/pull/3034
from master.
Fixes #
```release-note
NONE
```

sync: release 0.37.x

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h
userspace/falco/logger.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
This adopts the new logger from libs.
Fixes #
```release-note
NONE
```

fix: adopt new libsinsp logger

---

docker/no-driver/Dockerfile.distroless

/kind bug
/area build
As per title. This allows all the dynamic libraries to be installed in the Wolfi image.
Fixes #
```release-note
NONE
```

fix(build): install libstdc++ in the Wolfi image

---

scripts/publish-deb
scripts/publish-rpm

/kind feature
/area CI
This PR limits the total amount of `deb-dev` and `rpm-dev` packages to 10GB. This is because in order to be updated we need to download all packages, check metadata and sync them with the bucket. GHA runners have less than 20GB space and they take time to download data. This retention seems reasonable.
Fixes #2862
```release-note
NONE
```

new(build): prune deb-dev and rpm-dev directories

---

docker/driver-loader-legacy/docker-entrypoint.sh
docker/driver-loader/docker-entrypoint.sh
docker/falco/docker-entrypoint.sh

Added option for insecure http driver download in the docker-entrypoint.sh script. By passing --http-insecure to the container via an argument, the flag is forwarded to the falcoctl driver install command.
> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area tests
> /area CI
Adds a simple functionality to the driverbuilder script which has not been enabled before
Feature has been available until the migration from script based …

added option for insecure http driver download

---

userspace/engine/falco_engine.cpp

/kind bug
/area engine
Fixes #3059 
```release-note
fix(userspace/engine): always consider all rules (even the ones below min_prio) in m_rule_stats_manager
```

fix(userspace/engine): always consider all rules (even the ones below min_prio) in m_rule_stats_manager

---

userspace/falco/grpc_request_context.h
userspace/falco/outputs_file.h
userspace/falco/outputs_grpc.h
userspace/falco/outputs_program.h
userspace/falco/outputs_stdout.h
userspace/falco/outputs_syslog.h

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
This PR adds missing override keywords.
They were detected by cppcheck.
Fixes #3063
```release-note
NONE
```

fix(c++): add missing overrides

---

userspace/engine/filter_macro_resolver.cpp
userspace/engine/filter_macro_resolver.h
userspace/engine/rule_loader_compiler.cpp
userspace/engine/rule_loader_compiler.h

/kind cleanup
/area engine
When loading large rulesets, I noticed a spike of allocations that could be mitigated with few changes.
```release-note
refactor(userspace/engine): reduce allocations during rules loading
```

refactor(userspace/engine): reduce allocations during rules loading

---

unit_tests/engine/test_add_source.cpp
unit_tests/engine/test_alt_rule_loader.cpp
userspace/engine/evttype_index_ruleset.h
userspace/engine/falco_common.h
userspace/engine/falco_engine.h
userspace/engine/filter_details_resolver.h
userspace/engine/rule_loader.h
userspace/falco/app/actions/process_events.cpp
userspace/falco/app/restart_handler.h
userspace/falco/falco_semaphore.h
userspace/falco/grpc_context.h
userspace/falco/grpc_request_context.cpp
userspace/falco/versions_info.h
userspace/falco/yaml_helper.h

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
/area tests
> /area CI
This PR adds missing explicit to single parameter constructors.
They were detected by cppcheck.
Fixes #3068 
```release-note
NONE
```

fix(c++): add missing explicit to single argument constructors

---

docker/driver-loader-legacy/docker-entrypoint.sh
docker/driver-loader/docker-entrypoint.sh
docker/falco/docker-entrypoint.sh

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area tests
> /area CI
Adds option for http-headers for driver download in docker images
Fixes #3070
No as empty header variable will not be processed
```release-note
NONE
```

Added http headers option for driver download in docker images

---

userspace/engine/falco_common.h
userspace/falco/app/state.h
userspace/falco/grpc_server.h
userspace/falco/stats_writer.cpp
userspace/falco/stats_writer.h
userspace/falco/versions_info.cpp
userspace/falco/versions_info.h

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
This PR refactors member variables initialization so that they are done in the constructor initialization list.
They were detected by cppcheck.
Fixes #3073 
```release-note
NONE
```

Improve class initialization

---

cmake/modules/CompilerFlags.cmake
unit_tests/engine/test_alt_rule_loader.cpp

/kind cleanup
/area build
Removes some compiler warnings.
1. Warns about overridden functions missing `override`.
2. Warns about some linker flags (`-Wl,-z,relro,-z,now`) being used on the compilation step.
Moreover, an unneeded warning suppression, `-Wno-class-memaccess`, has been removed.
Fixes #
```release-note
NONE
```

fix: Some compiler warnings

---

CMakeLists.txt
userspace/engine/CMakeLists.txt

/kind cleanup
/area build
/area engine
Library `falco_engine` links against library `sinsp` by means of a CMake variable (`FALCO_SINSP_LIBRARY`) that, in principle, could be changed in a preliminary CMake configuration for the build. This appears to be a leftover from the past that is no longer needed and can be simplified.
Also, a small adjustment in the include paths of `falco_engine` provides further simplification.
Fixes #
```release-note
NONE
```

cleanup: falco_engine deps and include paths

---

unit_tests/engine/test_enable_rule.cpp
unit_tests/engine/test_rule_loader.cpp
unit_tests/engine/test_rulesets.cpp
unit_tests/falco/app/actions/test_configure_interesting_sets.cpp
unit_tests/test_falco_engine.h
userspace/falco/app/options.cpp

/kind cleanup
/area tests
With this PR, tests that create a Falco engine to load rules will use the `test_falco_engine` fixture instead of creating their own. This removes duplication from the test codebase and also *allows the entire unit test suite to run with ASan and UBSan enabled*
Fixes #
```release-note
NONE
```

cleanup(tests): consolidate Falco engine and rule loader tests

---

unit_tests/engine/test_rule_loader.cpp
userspace/falco/app/actions/print_support.cpp
userspace/falco/app/restart_handler.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
/area tests
> /area CI
This PR removes unused or unread variables. The former are variables declared but not initialized and the latter are initialized but both are not used or assigned but the new value is not used.
Reported by cppcheck.
Fixes #3096
```release-note
NONE
```

Cleanup variable use

---

unit_tests/engine/test_add_source.cpp
unit_tests/engine/test_alt_rule_loader.cpp
unit_tests/engine/test_plugin_requirements.cpp
unit_tests/engine/test_rulesets.cpp
unit_tests/falco/test_atomic_signal_handler.cpp
userspace/engine/evttype_index_ruleset.cpp

/kind cleanup
/area tests
Refactor test `AtomicSignalHandler.handle_once_wait_consistency` to make it simpler, especially in the management of threads, by avoiding using the `std::thread` object directly and relying on `std::future` returned by function `std::async`, instead.
A few changes from `std::shared_ptr`+`new` to `std::make_shared` have also been done.
Fixes #
```release-note
NONE
```

refactor: test AtomicSignalHandler.handle_once_wait_consistency

---

unit_tests/CMakeLists.txt
unit_tests/test_falco_engine.cpp
unit_tests/test_falco_engine.h

/kind cleanup
/area build
/area tests
Cleanup of the test fixture class `test_falco_engine` also separating the implementation from the header in its own cpp file.
Cleanup of the CMake script for the tests and upgrade GTest to 1.14.0.
Fixes #
```release-note
NONE
```

cleanup: falco_engine test fixture

---

proposals/20230620-anomaly-detection-framework.md

> /kind bug
/kind design
> /area build
> /area engine
> /area tests
> /area CI
Formalize an On Host Anomaly Detection Framework.
@falcosecurity/core-maintainers
Fixes #
```release-note
new(proposals): introduce on host anomaly detection framework
```

docs(proposals): introduce on host anomaly detection framework

---

CMakeLists.txt
cmake/modules/CompilerFlags.cmake
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h
userspace/engine/falco_source.h
userspace/engine/filter_macro_resolver.cpp
userspace/engine/filter_macro_resolver.h
userspace/engine/rule_loader_compiler.cpp
userspace/falco/app/actions/init_inspectors.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/stats_writer.cpp
userspace/falco/webserver.cpp
userspace/falco/webserver.h

/kind cleanup
/area engine
This follows up https://github.com/falcosecurity/libs/pull/1702 in libs by bumping the dependencies and by adapting the code. To continue the effort, raw pointers have been removed from the Falco app wherever possible too.
```release-note
NONE
```

refactor: bump libs and driver, and adopt unique pointers wherever possible

---

userspace/engine/evttype_index_ruleset.cpp
userspace/engine/evttype_index_ruleset.h
userspace/engine/falco_engine.cpp
userspace/engine/falco_utils.cpp
userspace/engine/falco_utils.h
userspace/engine/rule_loader_compiler.cpp
userspace/falco/app/actions/init_falco_engine.cpp
userspace/falco/app/actions/list_plugins.cpp
userspace/falco/app/actions/print_generated_gvisor_config.cpp
userspace/falco/app/actions/print_plugin_info.cpp
userspace/falco/app/actions/process_events.cpp

/kind cleanup
/area build
This is just a cleanup/refactor on some usages of smart pointers, plus a fix for a warning about a pessimizing `std::move` raised by Clang.
The changes might seem very diverse, but they are very simple and arranged into separate commits if the reviewer prefers to address the task for each topic separately.
Fixes #
```release-note
NONE
```

Cleanup warnings and smart ptrs

---

unit_tests/engine/test_rule_loader.cpp
userspace/engine/rule_loader_compiler.cpp

/kind bug
> /kind design
> /area build
/area engine
/area tests
> /area CI
Fixes handling of rules using exceptions and conditions with `or` operator
Fixes #
```release-note
fix(engine): logical issue in exceptions condition
```

fix(engine): logical issue in exceptions condition

---

userspace/falco/configuration.cpp

/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
The original code was using `follow_directory_symlink` twice, this patch fixes that.
That was detected by cppcheck.
Part of #3052
```release-note
fix(userspace/configuration): make sure that folders that would trigger permission denied are not traversed
```

Correct directory iteration options

---

falco.yaml
userspace/engine/falco_common.h
userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
We recently increased the default threadtable size to accommodate modern infrastructures better as we have observed drops related to a full internal thread table. This PR makes this setting configurable by the end user.
Fixes #
```release-note
new(config): add …
```

new(config): add `falco_libs.thread_table_size`

---

proposals/20231220-features-adoption-and-deprecation.md

/kind design
As discussed among maintainers and based on feedback, the need to balance quick project evolution and avoid frequent changes that can disrupt adopters' workflow has emerged. This proposal aims to find that balance in the long term. 
Although apparently well structured, the proposal must be considered as an RFC at the moment. The current goal is to ensure the proposed solution offers a good trade-off and will not introduce any unnecessary burden. Any aspect of the proposal can be changed at this stage. 
Tentatively for
/milestone 0.37.0 …

docs(proposal): 20231220-features-adoption-and-deprecation.md

---

.github/workflows/codeql.yaml
.github/workflows/reusable_build_dev.yaml
.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_fetch_version.yaml
.github/workflows/staticanalysis.yaml

/kind cleanup
/area build
/area CI
Simplifies a bit the configure/generate phase of CMake by letting it create the `build` directory.
Avoids invoking the command `make` directly and relying on CMake instead, thus preparing the build to be used with other build systems, such as Ninja.
Ninja could be easily used after this change just by adding the switch `-G Ninja` to the CMake configure/generate statement. For instance:
```
cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release -Dparameter=value
```
In a nutshell this PR realizes the following transformation:
Old:
```
mkdir build
pushd build
cmake -Dparameter=value ..
build -j4 my_exe
popd
```
New:
```
cmake -B …
```

refactor(ci): Avoid using command make directly

---

cmake/modules/cpp-httplib.cmake
cmake/modules/njson.cmake
cmake/modules/yaml-cpp.cmake
userspace/engine/CMakeLists.txt
userspace/falco/CMakeLists.txt
userspace/falco/webserver.h

/kind cleanup
/area build
Libraries `nlohmann-json`, `yaml-cpp`, and `cpp-httplib` in their "bundled" configuration are now integrated through the CMake construct `FetchContent` rather than `ExternalProject_Add`. This has the benefit of being treated in a way similar to integrating the library with `find_package`, thus making the bundled/non-bundled approach similar in the rest of the code.
One important beneficial consequence is the simplification in client code: new targets can reference `falco_engine` without having to specify these libs in their include path or explicitly link against it, because the target `falco_engine` brings all the needed properties on …

refactor: Use FetchContent for integrating three bundled libs

---

.github/workflows/codeql.yaml
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h

/kind feature
/area build
This PR bumps Falco with the latest libs
```release-note
NONE
```

chore: bump to latest libs commit

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/configuration.cpp
userspace/falco/stats_writer.cpp
userspace/falco/stats_writer.h

> /kind bug
/kind cleanup
/kind design
> /area build
/area engine
> /area tests
> /area CI
Sync libs
Includes a handful of naming changes. A notice to https://falco.org/docs/metrics/falco-metrics/ will be added well in advance of Falco 0.38.0.
```
falco.hostname -> evt.hostname to be consistent with the newer evt.hostname filtercheck
cpu_usage_perc_total_host -> host_cpu_usage_perc
memory_used_host -> host_memory_used_kb (or host_memory_used_mb)
procs_running_host -> host_procs_running …
```

feat(metrics): sync libs metrics collector refactor

---

unit_tests/CMakeLists.txt

/kind bug
/area build
Build was failing when both `USE_BUNDLED_DEPS=ON` and `BUILD_FALCO_UNIT_TESTS=ON` were enabled at the same time with linking errors on `absl` and `grpc`. This fixes it by reintroducing explicit library linking for the test suite. It is not 100% clear to me why we need this line but I noticed that before this patch the following files would _not_ be linked in the final executable, hence the errors:
```
../_deps/yamlcpp-build/libyaml-cppd.a
../grpc-prefix/src/grpc/libgrpc++.a
../grpc-prefix/src/grpc/libgrpc.a
../grpc-prefix/src/grpc/libgpr.a …
```

fix(cmake): fix USE_BUNDLED_DEPS=ON and BUILD_FALCO_UNIT_TESTS=ON

---

userspace/engine/rule_loader_compiler.cpp

/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Enables output substitutions for all sources. 
**Which issue(s) this PR fixes**: #2289 
Fixes #2289 
```release-note
fix(engine): apply output substitutions for all sources
```

fix(engine): apply output substitutions for all sources

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind cleanup
/area engine
Deprecates old 'rules_file' config option in favor of new 'rules_files'.
Old config option is still kept for backward compatiblity (and will possibly go away with Falco 1.0.0).
So:
* only `rules_files` present -> ok we use it
* only `rules_file` present -> ok we use it but give a warning about deprecation
* both keys used -> throw an exception
Example output:
* only `rules_file` present:
```
sudo ./userspace/falco/falco -c ../../falco.yaml  -r ../rules/falco_rules.yaml 
Wed Apr 10 17:26:45 2024: Using deprecated config key 'rules_file'. Please use new 'rules_files' config key.
Wed Apr 10 17:26:45 2024: Falco version: 0.38.0-182+e840a4a …
```

chore(userspace/falco): deprecate old 'rules_file' config key.

---

userspace/falco/CMakeLists.txt
userspace/falco/app/actions/actions.h
userspace/falco/app/actions/close_inspectors.cpp
userspace/falco/app/actions/process_events.cpp
userspace/falco/app/app.cpp

/kind cleanup
/area engine
See https://github.com/falcosecurity/falco/pull/3140#issuecomment-2059234096 , basically if we want to allow the server thread to access inspectors we need to close them as the last thing before shutting down which is what this patch proposes.
Fixes #
```release-note
NONE
```

update(app): close inspectors at teardown time

---

unit_tests/engine/test_filter_macro_resolver.cpp
unit_tests/engine/test_filter_warning_resolver.cpp
unit_tests/falco/app/actions/test_configure_syscall_buffer_num.cpp
unit_tests/falco/app/actions/test_load_config.cpp
unit_tests/falco/app/actions/test_select_event_sources.cpp
unit_tests/falco/test_atomic_signal_handler.cpp
unit_tests/falco/test_configuration.cpp

/kind cleanup
/area tests
Just found it funny :D
/milestone 0.38.0
Fixes #
```release-note
NONE
```

cleanup(docs): fix typo in license blocks

---

.github/workflows/codeql.yaml
.github/workflows/reusable_build_dev.yaml
.github/workflows/reusable_build_packages.yaml
CMakeLists.txt

/kind cleanup
/area build
Since modern-bpf is now the default driver, i think it should be built by default too!
Fixes #
```release-note
NONE
```

chore(cmake): enable modern bpf build by default.

---

falco.yaml
unit_tests/falco/test_configuration.cpp
userspace/falco/CMakeLists.txt
userspace/falco/app/actions/start_webserver.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco_metrics.cpp
userspace/falco/falco_metrics.h
userspace/falco/webserver.cpp
userspace/falco/webserver.h

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
This PR implements the `/metrics` endpoint in the webserver providing currently prometheus metrics.
Fixes #3131
Fixes #1772
```release-note
feat(webserver): a metrics endpoint has been added providing prometheus metrics.
It can be optionally enabled using the new …
```

feat(webserver): implement metrics endpoint

---

unit_tests/engine/test_alt_rule_loader.cpp
userspace/engine/evttype_index_ruleset.cpp
userspace/engine/falco_engine.cpp
userspace/engine/rule_loader.h
userspace/engine/stats_manager.cpp
userspace/falco/app/actions/init_inspectors.cpp
userspace/falco/app/actions/init_outputs.cpp
userspace/falco/app/actions/load_plugins.cpp
userspace/falco/app/actions/process_events.cpp
userspace/falco/app/state.h
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/grpc_request_context.cpp

/kind cleanup
No specific area.
There are some usages of smart pointers that can be simplified a but and, occasionally, made more efficient.
1. Use the overloaded dereference operator directly on the smart pointer without invoking get(), i.e. prefer *ptr rather than *(ptr.get()).
2. Create objects stored in smart pointers with make_unique or make_shared rather than using new. For shared_ptrs this has the performance advantage of storing the pointer's control block with the object itself, improving memory locality, beneficial for cache reasons, and using a single allocation call.
3. Prefer using automatic objects - i.e. stored on the stack - than heap allocated …

refactor: smart pointer usage

---

userspace/engine/falco_utils.cpp
userspace/engine/falco_utils.h
userspace/falco/app/actions/load_rules_files.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco_metrics.cpp
userspace/falco/stats_writer.cpp

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
This PR adds the sha256sum for each loaded config and rules file as individual metric. These metrics complement existing informational metrics such as the Falco version or kernelrelease of the host and especially help to track deployment upgrade convergence and integrity. When hot reloading Falco and having watch config files setting enabled, the state is re-initialized and as such the new …

new(metrics): add file sha256sum metrics for loaded config and rules files

---

falco.yaml
unit_tests/CMakeLists.txt
unit_tests/engine/test_alt_rule_loader.cpp
unit_tests/engine/test_enable_rule.cpp
unit_tests/engine/test_falco_utils.cpp
unit_tests/engine/test_rulesets.cpp
unit_tests/falco/test_configuration.cpp
unit_tests/falco/test_configuration_rule_selection.cpp
userspace/engine/evttype_index_ruleset.cpp
userspace/engine/evttype_index_ruleset.h
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_utils.cpp
userspace/engine/falco_utils.h
userspace/engine/filter_ruleset.h
userspace/falco/app/actions/load_config.cpp
userspace/falco/app/actions/load_rules_files.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/yaml_helper.h

/kind feature
/area engine
This is a rather straightforward implementation of https://github.com/falcosecurity/falco/issues/3174#issuecomment-2064152163 . Essentially, it introduces two new ways of enabling/disabling rules without changing the rule files. Following the example:
```yaml
rules:
- disable:
rule: *
- enable:
tag: network
- enable:
rule: Directory traversal monitored file
- enable:
rule: k8s_*
- disable:
rule: k8s_noisy_rule
```
This means: disable everything, enable all rules tagged `networking`, also enable the rule called `Directory traversal monitored file`, then …

new(falco): add rule selection configuration in falco.yaml

---

userspace/engine/evttype_index_ruleset.cpp
userspace/engine/evttype_index_ruleset.h

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
add print_enabled_rules_falco_logger when log_level debug similar to how we print the final set of syscalls of interest.
Fixes #
```release-note
new(engine): add print_enabled_rules_falco_logger when log_level debug
```

new(engine): add print_enabled_rules_falco_logger when log_level debug

---

docker/driver-loader-legacy/Dockerfile
docker/falco/Dockerfile

/kind bug
/area build
Recent ubuntu kernel headers packages are `zstd` compressed. We need `zstd` to be able to decompress them for the new `falcoctl driver kernel headers automatic download` logic.
Fixes #
```release-note
fix(docker): added zstd to driver loader images
```

fix(docker): added `zstd` dep to driver loader images

---

unit_tests/engine/test_rule_loader.cpp
userspace/engine/rule_loader_reader.cpp

/kind bug
/area engine
When replaced with the new `override` YAML construct, `exceptions` must not have any of their sub-fields as optional, just like when first defined in regular rules definitions.
```release-note
fix(userspace/engine): make sure exception fields are not optional in replace mode
```

fix(userspace/engine): make sure exception fields are not optional in replace mode

---

falco.yaml
unit_tests/engine/test_falco_utils.cpp
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_utils.cpp
userspace/engine/falco_utils.h
userspace/engine/stats_manager.h
userspace/falco/app/actions/process_events.cpp
userspace/falco/configuration.cpp
userspace/falco/falco_metrics.cpp
userspace/falco/stats_writer.cpp
userspace/falco/stats_writer.h

Intended to replace https://github.com/falcosecurity/falco-exporter when used with Prometheus output
> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
new(metrics): add rules_counters_enabled option
Intended to replace https://github.com/falcosecurity/falco-exporter when used with Prometheus output.
CC @leogr and @jasondellaluce (current maintainers of https://github.com/falcosecurity/falco-exporter).
Fixes …

new(metrics): add `rules_counters_enabled` option

---

userspace/falco/falco_metrics.cpp
userspace/falco/stats_writer.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
cleanup(metrics): add original rule name as label
https://github.com/falcosecurity/charts/issues/672#issuecomment-2118685055 @leogr 
Fixes #
```release-note
cleanup(metrics): add original rule name as label
```

cleanup(metrics): add original rule name as label

---

cmake/modules/rules.cmake

/kind feature
/area build
As per title, update to the latest released version.
Note that there is no need for systemd unit update because it already uses the `3` tag.
Fixes #
```release-note
update(rules): update falco-rules to 3.1.0
```

chore(build): bump rules to 3.1.0

---

userspace/falco/falco_metrics.cpp
userspace/falco/stats_writer.cpp

/kind bug
/area engine
This PR does 3 things:
* avoid crashing when scap_machine_info or scap_agent_info are NULL (ie: with non-linux scap platform, ie: while running plugins)
* properly use a `shared_ptr` for inspectors vector, so that we know they are kept alive while `to_text` runs and we can dereference the pointer
* only expose metrics for actually enabled sources (not loaded ones). Before, in `nodriver` mode with syscall source disabled, we would've tried to emit metrics for the syscall source/inspector too, but that is wrong since it is not enabled (and it would crash Falco too!)
Fixes #3229  …

fix(userspace/falco): fixed `falco_metrics::to_text` implementation when running with plugins

---

.github/workflows/reusable_test_packages.yaml

/kind cleanup
/area tests
/area CI
This will prevent future issues like https://github.com/falcosecurity/falco/issues/3229
Fixes #
```release-note
NONE
```

chore(ci): enable dummy tests on the testing framework.

---

userspace/engine/rule_loader_compiler.cpp

This reverts commit 4ef7c9553aaea2bfe75aa867650c7e9745c2909f.
> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
fix(engine): enable output substitution only for syscall rules, prevent engine from exiting with validation errors when a plugin is loaded and -pc/pk is specified
```

Revert #3135 "fix(engine): apply output substitutions for all sources"

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/falco_metrics.cpp
userspace/falco/stats_writer.cpp

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
new(metrics): enable plugins metrics
```

new(metrics): enable plugins metrics

---

userspace/engine/evttype_index_ruleset.cpp
userspace/engine/evttype_index_ruleset.h
userspace/engine/indexable_ruleset.h

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Now that custom rules loading implementations (and related, custom rulesets) can be swapped into falco in a customizable way, there is some functionality in evttype_index_ruleset that could be used by other rulesets, specifically the part that segregates filters by ruleset and enables/disables filters based on name substring + tags. This PR makes a base class for that. See the commit comments for …

new(userspace/engine): generalize indexable ruleset

---

userspace/engine/falco_engine.cpp

There's no need to populate rulesets with the output if compilation failed.
/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
If rule compilation fails, there's no need to pass any (partial) set of rules to the rulesets. Just return the (failing) result immediately.
Fixes #
```release-note
NONE
```

If rule compilation fails, return immediately

---

CHANGELOG.md
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h
userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/app/actions/init_inspectors.cpp

/kind cleanup
/area build
Fixes #
Also, this PR cherrypicks https://github.com/falcosecurity/falco/commit/7efabb7243fd741464ef446b359a0ec3643af123 from release/0.38.x branch.
```release-note
NONE
```

update(cmake,userspace): bump libs and driver to latest master.

---

.github/workflows/reusable_build_packages.yaml

/kind bug
/area CI
Enforce the usage of the vault.centos.org mirrors for centos:7 CI. This should fix the CI and let us gain time to design a proper solution to drop centos7.
Also, recently github actions enforced the usage of node20 runners, breaking our `actions/checkout` step when ran inside centos:7 container (glibc version mismatch); workaround that issue too, by adding the env `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true` to the workflow.
See https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/.
Fixes #
**Does this PR …

fix(ci): use vault.centos.org for centos:7 CI build.

---

OWNERS

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
As discussed during the community call, this follows the process to become part of the maintainers of falco.
Fixes #
```release-note
NONE
```

vote: add sgaist to OWNERS

---

userspace/falco/falco_metrics.cpp

/kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Fixes https://github.com/falcosecurity/falco/issues/3271
Fixes #
```release-note
fix(engine): fix metrics names to better adhere to best practices
```

fix(metrics/prometheus): adopt best prometheus practices for rules counters and sha256 file metrics

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
unit_tests/engine/test_rule_loader.cpp
userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/app/actions/init_inspectors.cpp
userspace/falco/falco_metrics.cpp

/kind cleanup
/area build
/area tests
Just updating libs and fix tests to catch warnings with new output messages.
```release-note
NONE
```

update(cmake): bump libs and driver to latest master 

---

cmake/modules/falcoctl.cmake
cmake/modules/rules.cmake

There are systems, like Nix derivations where the build process does not have network access in order to enforce reproducibility. This patch allows people building Falco to optionally skip the build of falcoctl with `-DADD_FALCOCTL_DEPENDENCY=OFF` and point to their own self-backed, or pre-fetched rules files with `-DFALCOSECURITY_RULES_FALCO_PATH=<some-path>` and `-DFALCOSECURITY_RULES_LOCAL_PATH=<some-path>`.
For context, I needed to apply these patches while building the project with Nix in https://github.com/tembleking/falco-nix but I think that would be benefitial for the community to have also these options open, and that would also make Falco feasible to be added to the nixpkgs repository at https://github.com/nixos/nixpkgs
/kind feature
/kind release
/area build
```release-note
- …
```

feat(cmake): add conditional builds for falcoctl and rules paths

---

README.md
docker/docker-compose/README.md
docker/docker-compose/config/http_output.yml
docker/docker-compose/docker-compose.yaml

This PR adds a docker-compose.yml file that new users can use to quickly stand up and test out falco, falcosidekick, and falcosidekick-ui.
None
Fixes #
NO
```release-note
NONE
```

Add demo environment instructions and docker-config files

---

.github/workflows/ci.yml
.github/workflows/codeql.yaml
.github/workflows/codespell.yml
.github/workflows/engine-version-weakcheck.yaml
.github/workflows/insecure-api.yaml
.github/workflows/master.yaml
.github/workflows/release.yaml
.github/workflows/reusable_build_dev.yaml
.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_fetch_version.yaml
.github/workflows/reusable_test_packages.yaml
.github/workflows/staticanalysis.yaml

/area CI
fixed the token-permission and pinned-dependencies issue which are reported by [scorecard](https://scorecard.dev/viewer/?uri=github.com/falcosecurity/falco).
Part of #3297 
```release-note
None
```

fixed the token-permission and pinned-dependencies issue

---

unit_tests/falco/test_configuration_rule_selection.cpp
userspace/falco/configuration.cpp
userspace/falco/yaml_helper.h

/kind feature
/area engine
In https://github.com/falcosecurity/falco/pull/3308 we add a new configuration option such as:
```yaml
append_output:
- source: syscall
tag: persistence
rule: some rule name
format: "gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4]"
```
Given its format, it is not possible to specify it on the command line with a `-o` option unless we enable a syntax like `-o key={object}`, or `-o key[]={object}`. Example: `-o append_output[]={"source": "syscall", "tag": "persistence", "rule": "some rule name", "format": "gparent=%proc.aname[2] …

new(falco): enable CLI options with -o key={object}

---

userspace/falco/app/actions/load_rules_files.cpp
userspace/falco/app/options.cpp
userspace/falco/app/options.h

/kind cleanup
/area engine
https://github.com/falcosecurity/falco/pull/3193 deprecated 3 options for 0.38.0.
It's time to drop them for the 0.39.0 release.
Refs https://github.com/falcosecurity/falco/issues/3045.
Fixes #
```release-note
cleanup(userspace/falco)!: drop deprecated -t,-T,-D options.
```

cleanup(userspace/falco)!: drop deprecated -t,-T,-D options.

---

userspace/falco/CMakeLists.txt
userspace/falco/app/actions/actions.h
userspace/falco/app/actions/print_config_schema.cpp
userspace/falco/app/app.cpp
userspace/falco/app/options.cpp
userspace/falco/app/options.h

/kind feature
/area engine
Fixes #
```release-note
new(userspace/falco): added --config-schema action to print config schema
```

new(userspace/falco): added `--config-schema` action to print config schema

---

.github/workflows/insecure-api.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area tests
/area CI
Fixes #
Semgrep has updated their official docker image to `semgrep/semgrep`
```release-note
NONE
```

ci(insecure-api): update semgrep docker image

---

.github/workflows/master.yaml
.github/workflows/release.yaml

/kind bug
/area CI
https://github.com/falcosecurity/falco/pull/3299 broke master CI triggering (if you see latest master commits did not trigger master CI, only codeql and scorecard).
This is an attempt to fix them.
Fixes #
```release-note
NONE
```

fix(ci): restore master and release CI workflow permissions.

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h

/kind release
/area build
Fixes #
```release-note
NONE
```

update(cmake): bump libs and driver to 0.18.0-rc1.

---

falco.yaml
userspace/falco/falco_metrics.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Discussed with Leo that rules_counters -> rules_matches is the better naming convention. It now also resembles better the JSON output rule naming convention.
Fixes #
```release-note
update(falco_metrics): change prometheus rules metric naming
```

update(falco_metrics): change prometheus rules metric naming

---

userspace/falco/app/options.cpp

/kind cleanup
/area engine
#3266 introduced a new config object for container_engines that allow to set socket paths and disable async for CRI.
Deprecate old CLI options.
Fixes #
```release-note
chore(userspace/falco): deprecate `cri` related CLI options.
```

chore(userspace/falco): deprecate `cri` related CLI options.

---

scripts/systemd/falco-bpf.service
scripts/systemd/falco-custom.service
scripts/systemd/falco-modern-bpf.service

/kind feature
/area engine
This PR allows to refer to the engine `systemd` services with a consistent unique alias `falco.service`. In addition, the alias `systemd` system helps to prevent from running more than one Falco instance with `systemd` at the time, since it is not possible to enable two `systemd` service, with the same alias, at the same time.
Fixes #
```release-note
update(systemd): users can refer to systemd falco services with a constistent unique alias falco.service
```

update(systemd): add falco.service alias to all systemd units

---

userspace/falco/app/actions/configure_interesting_sets.cpp
userspace/falco/app/actions/init_inspectors.cpp

/kind bug
/area engine
Previously, we were not accounting for plugins with parsing capability while computing the interesting sc set.
This means that we gave no guarantees to plugins writers that the required syscalls (for parsing by the plugin) were actually enabled in the drivers.
This PR fixes that.
Fixes #
```release-note
fix(userspace/falco): properly account for plugin with CAP_PARSING when computing interesting sc set
```

fix(userspace/falco): properly account for plugin with CAP_PARSING when computing interesting sc set

---

unit_tests/falco/test_configuration_schema.cpp
userspace/falco/config_json_schema.h

/kind bug
/area engine
It is possible to specify plugin init config like:
```yaml
plugins:
- name: k8saudit
library_path: libk8saudit.so
init_config:
maxEventSize: 262144
sslCertificate: /etc/falco/falco.pem
```
or
```yaml
plugins:
- name: k8saudit
library_path: libk8saudit.so
init_config: '{"maxEventSize": 262144, "sslCertificate": "/etc/falco/falco.pem"}'
```
But json schema didn't allow that and only accepted a string. This PR adds the map option to the schema.
Fixes # …

fix(falco): allow plugin init_config map in json schema

---

userspace/falco/falco_metrics.cpp
userspace/falco/stats_writer.cpp
userspace/falco/stats_writer.h

/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
This PR introduces the following changes:
- split `tags` label in `falcosecurity_falco_sha256_config_files_info` and `falcosecurity_falco_sha256_rules_files_info` gauges into multiple `tag_<tag>="true"` labels
- use full name for configs and rules files in metrics instead of using only filename stems
- remove ifinfo_json stat/metric
- remove unused falco_utils import …

fix(falco_metrics): fix prometheus metrics to be compliant with best practices

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/rule_json_schema.h
userspace/falco/app/options.cpp

/kind cleanup
Syncs 0.39.x release branch with latest master fixes, by cherrypicking:
* https://github.com/falcosecurity/falco/pull/3332
* https://github.com/falcosecurity/falco/pull/3334
* https://github.com/falcosecurity/falco/pull/3335
* https://github.com/falcosecurity/falco/pull/3337
* https://github.com/falcosecurity/falco/pull/3338
Fixes #
```release-note
NONE
```

sync: release 0.39.x

---

userspace/falco/stats_writer.cpp

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
This PR introduces `host_netinfo` stats family to hold information regarding host networking. At the moment, it only provides ipv4 and ipv6 addresses lists for each interface available on the host.
The naming schema for the introduced stats is `falco.host_netinfo.interfaces.<ifname>.protocols.<ipv4|ipv6>.addresses="<address_list>"`, where `address_list` is a comma separated list of network …

feat(stats): add host_netinfo networking information stats family

---

.clang-format-ignore

/kind cleanup
/area build
This PR avoids the following error https://lists.llvm.org/pipermail/llvm-bugs/2018-May/064824.html when running clang-format on these files
```release-note
NONE
```

chore: ignore_some_files for clang format

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
NONE
```

update(changelog): add changelog for falco 0.39.0

---

userspace/falco/app/actions/configure_interesting_sets.cpp

/kind bug
/area engine
Fix after #3334 . Refs https://github.com/falcosecurity/charts/issues/752
Fixes #
```release-note
fix(userspace/falco): fix event set selection for plugin with parsing capability
```

fix(userspace/falco): fix event set selection for plugin with parsing capability

---

.github/workflows/bump-libs.yaml

/kind feature
/area CI
This PR adds a workflow that creates  a PR on each monday to bump libs to latest master.
This is super useful together with the `zig` build, since the usage of a modern clang compiler helped us spot at least 3 UBs in the libs code; therefore by having an automatic PR, we can have helpful insights on the recent libs development.
Fixes #
```release-note
NONE
```

new(ci): add a workflow to automatically bump libs on each monday.

---

userspace/falco/app/options.cpp

/kind bug
/area engine
There was a missed configuration option in this PR https://github.com/falcosecurity/falco/pull/3310 , which sadly made the `-o append_output[]={"source": "syscall", "tag": "persistence", "rule": "some rule name", "format": "gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4]"}` style options non functional due to the fact that cxxopts is trying to parse commas in the json object. Sadly I only realized after release. This PR fixes it.
Fixes #
**Does this PR introduce …

fix(engine): disable comma separated vectors in cxxopts

---

.github/workflows/bump-libs.yaml

/kind bug
/area CI
Fixes #
```release-note
NONE
```

fix(ci): fixed bump-libs workflow syntax.

---

unit_tests/falco/test_configuration_schema.cpp
userspace/falco/config_json_schema.h

/kind bug
/area engine
As per title. See: https://github.com/falcosecurity/charts/issues/752
Fixes #
```release-note
fix(engine): allow null init_config for plugin info
```

fix(engine): allow null init_config for plugin info

---

CHANGELOG.md
unit_tests/falco/test_configuration_schema.cpp
userspace/falco/app/actions/configure_interesting_sets.cpp
userspace/falco/app/options.cpp
userspace/falco/config_json_schema.h

/kind release
/area engine
Cherry picks 
* https://github.com/falcosecurity/falco/pull/3363
* https://github.com/falcosecurity/falco/pull/3368
* https://github.com/falcosecurity/falco/pull/3372
from master
Plus, it updates the changelog in a standalone commit ready to be cherry picked on master.
Fixes #
```release-note
NONE
```

sync: release 0.39.1

---

.github/workflows/reusable_build_packages.yaml
cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/rule_loader.h
userspace/falco/stats_writer.cpp

/kind cleanup
/area CI
This PR drops centos7 from our CI by instead relying on zig compiler to provide glibc 2.17 compatible builds for us.
Fixes #3270
Linked libs PRs:
* https://github.com/falcosecurity/libs/pull/2034 -> new c-ares builds with zig 
* https://github.com/falcosecurity/libs/pull/2036 -> libanl is not present under zig; fixes build
* https://github.com/falcosecurity/libs/pull/2037 -> title says it all
* https://github.com/falcosecurity/libs/pull/2043 -> avoids Falco linking issue `undefined symbol: google::protobuf::internal::InternalMetadata::~InternalMetadata()`
* …

new(ci): use `zig` compiler instead of relying on centos7.

---

unit_tests/engine/test_alt_rule_loader.cpp
userspace/engine/falco_rule.h
userspace/engine/indexed_vector.h
userspace/engine/rule_loader_compile_output.h

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
This adds a clone() method for rule_loader::compile_output() that can be overridden by subclasses. This allows creating a mutable compile output in a polymorphic way.
Fixes #
```release-note
NONE
```

Compile output clone

---

.github/workflows/bump-libs.yaml

/kind bug
/area CI
As seen in #3378 , we are computing the wrong shasum in bump-libs CI; that is because we are computing the shasum of https://github.com/falcosecurity/libs/archive/refs/heads/master.tar.gz and not https://github.com/falcosecurity/libs/archive/${commit-hash}.tar.gz; even if commit hash is of course the same.
Fixes #
```release-note
NONE
```

fix(ci): fixed shasum computation for bump-libs CI.

---

unit_tests/engine/test_rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_loader_collector.cpp
userspace/engine/rule_loader_collector.h
userspace/engine/rule_loader_reader.cpp
userspace/engine/rule_loader_reader.h

/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
This fixes a bug where a second rule definition for a different source is mistakenly combined with the first rule definition of a different source. This now returns the same error as when defining a second rule.
Fixes https://github.com/falcosecurity/falco/issues/3382 …

Reject mismatched sources rules changes

---

.github/workflows/reusable_build_dev.yaml
.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_test_packages.yaml

/kind cleanup
/area build
CI/build infra change
Fixes #
```release-note
NONE
```

update(ci): use arm64 CNCF runners for GH actions

---

docker/falco/Dockerfile

/kind bug
/area build
Fixes the image `falcosecurity/falco:master` which is currently experimenting technical difficulties:
```
/usr/bin/falco: error while loading shared libraries: libbrotlienc.so.1: cannot open shared object file: No such file or directory
```
```
/ # ldd /usr/bin/falco
linux-vdso.so.1 (0x00007ffc3f1f9000)
libelf.so.1 => /usr/lib/libelf.so.1 (0x00007e2b45b03000)
libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007e2b45ae0000)
libbrotlienc.so.1 => not found
libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007e2b45ad3000)
libm.so.6 => …
```

fix(docker): add brotli to the Falco image

---

cmake/modules/cpp-httplib.cmake
docker/falco/Dockerfile

/kind cleanup
/area build
Since we started using ubuntu runner as builder (instead of relying on centos:7, see https://github.com/falcosecurity/falco/pull/3307), `cpp-httplib` started using `brotli` dep found in the system (that was not present on centos:7) since it defaults `HTTPLIB_USE_BROTLI_IF_AVAILABLE` to `ON`: https://github.com/yhirose/cpp-httplib/blob/master/CMakeLists.txt#L6
Disable this behavior since we do not want the added dep.
Fixes #
```release-note
NONE
```

fix(cmake,docker): avoid cpp-httplib requiring brotli.

---

falco.yaml

/kind bug
> /kind design
> /area build
> /area engine
> /area tests
/area CI
fix link which changed
Fixes #
```release-note
NONE
```

fix: update the url for the docs about the concurrent queue classes

---

falco.yaml
userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/config_json_schema.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind feature
/area engine
Fixes #3411
```release-note
new(userspace/falco): allow entirely disabling plugin hostinfo support.
```

new(userspace/falco): allow entirely disabling plugin hostinfo support.

---

falco.yaml
userspace/falco/app/actions/init_falco_engine.cpp
userspace/falco/config_json_schema.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind feature
/area engine
Since https://github.com/falcosecurity/libs/pull/2116, the plugin API now exposes a way for extractor plugins to declare that certain fields should be used as output formats.
Honor the request, and add a `suggested_formats` config option to eventually disable the suggested formats.
Fixes #
```release-note
new(userspace,cmake): honor new plugins exposed suggested output formats
```

new(userspace): honor new plugins exposed suggested output formats

---

falco.yaml

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
/milestone 0.40.0
```release-note
NONE
```

docs(falco.yaml): correct `buffered_outputs` description

---

userspace/engine/falco_utils.cpp

/kind cleanup
/area build
When building Falco with recent versions of OpenSSL all `SHA256_*` functions are reported as being deprecated. This PR uses a set of different functions to calculate a SHA256 checksum that avoids the deprecation. The behavior is the same.
None
No
```release-note
NONE
```

chore: avoid deprecated funcs to calculate sha256

---

cmake/modules/CPackConfig.cmake

Using Falco with the modern_ebpf driver does not require kernel build dependencies. This PR updates the cmake configuration to make the `dkms` and `kernel-devel` package requirements into suggestions.
/kind cleanup
/area build
This makes the `kernel-devel` and `dkms` dependencies optional when installing the `falco` package, significantly reducing the number of packages installed when running in modern_ebpf mode.
On Alma 8, installing Falco 0.39.2 from RPM requires `dkms` and `kernel-devel`, which adds many dependencies for a total of 76 packages on my minimal test VM. After converting the `dkms` and `kernel-devel` requirements to suggestions with rpmrebuild, no …

update(build): relax dkms dependencies to suggestions in DEB and RPM packages

---

.github/workflows/release.yaml
.github/workflows/reusable_build_packages.yaml

/kind cleanup
/area CI
https://github.com/falcosecurity/falco/pull/3440 allows us to build Falco in RelWithDebInfo target.
Use the new target and upload the debug symbols as github artifacts.
Then, as part of the release CI, use these artifacts and upload them as github assets.
Fixes #
```release-note
chore(ci): build Falco in RelWithDebInfo, and upload Falco debug symbols as github artifacts
```

chore(ci): build Falco in RelWithDebInfo, and upload Falco debug symbols as github artifacts

---

.github/workflows/format.yaml
.github/workflows/release.yaml
.github/workflows/reusable_build_dev.yaml
.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_publish_docker.yaml
.github/workflows/reusable_publish_packages.yaml
.github/workflows/reusable_test_packages.yaml
.github/workflows/scorecard.yaml
.github/workflows/staticanalysis.yaml

/kind cleanup
/area CI
In #3453 the CI is failing because we need to bump actions/{download,upload}-artifact actions.
See https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: a8a3f3ad30e3422c9c7b888a15615d19a852ae32`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Also, while at it, i ported our CI to use the shiny new github provided ARM runners: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-publ …

chore(ci): bumped actions/upload-download-artifact.

---

userspace/falco/configuration.cpp

/kind bug
/area engine
Since falco 0.39.0, the cri flag is deprecated but the recommended flag `-o container_engines.cri.sockets[]=<socket_path>` or the config file sockets values are not being applied since falco is trying to load the values from `container_engines.cri.cri`
None
Yes
```release-note
fix(userspace/falco): fix container_engines.cri.sockets not loading from config file
```

fix(userspace/falco): use container_engines.cri.sockets in load_yaml

---

.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_publish_docker.yaml
falco.yaml

/kind cleanup
Cherry picks from master:
* https://github.com/falcosecurity/falco/pull/3458
* https://github.com/falcosecurity/falco/pull/3459
Fixes #
```release-note
NONE
```

sync: release 0.40.0

---

CHANGELOG.md

/kind release
Cherry picks #3469  from release/0.40.x branch.
Fixes #
```release-note
NONE
```

chore(docs): updated changelog for 0.40.0

---

.github/release_template.md

/kind cleanup
/area CI
Fixes #
```release-note
NONE
```

chore: add back Falco static package to the release template.

---

userspace/falco/app/app.cpp

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area tests
> /area CI
This PR moves, before the `load_config` action, all actions not requiring the config to be loaded. This avoid resources waste. Notably, it promotes `print_help` as first executed action. Moreover, it sets actions lists to constant expressions.
Fixes #
```release-note
NONE
```

feat(falco/app): move actions not using config before `load_config`

---

userspace/falco/app/actions/init_falco_engine.cpp
userspace/falco/app/actions/init_inspectors.cpp
userspace/falco/app/actions/list_fields.cpp
userspace/falco/app/actions/list_plugins.cpp
userspace/falco/app/actions/load_plugins.cpp
userspace/falco/app/actions/pidfile.cpp
userspace/falco/app/actions/print_config_schema.cpp
userspace/falco/app/actions/print_generated_gvisor_config.cpp
userspace/falco/app/actions/print_help.cpp
userspace/falco/app/actions/print_kernel_version.cpp
userspace/falco/app/actions/print_page_size.cpp
userspace/falco/app/actions/print_plugin_info.cpp
userspace/falco/app/actions/print_rule_schema.cpp
userspace/falco/app/actions/print_support.cpp
userspace/falco/app/actions/print_syscall_events.cpp
userspace/falco/app/actions/print_version.cpp
userspace/falco/app/actions/start_grpc_server.cpp
userspace/falco/app/actions/start_webserver.cpp
userspace/falco/app/actions/validate_rules_files.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
This PR simplifies the falco app actions code by applying early return pattern.
Fixes #
```release-note
NONE
```

refactor(falco/app): apply early return pattern in actions code

---

cmake/modules/jemalloc.cmake

> /kind bug
> /area build
This PR adds support for 16k-sized kernel page for jemalloc, resolving an issue.
Fixes #3476
```release-note
fix(cmake): add support for 16K kernel page to jemalloc
```
/cc FedeDP

fix(cmake): add support for 16K kernel page to jemalloc

---

unit_tests/falco/test_configuration_config_files.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind bug
/area engine
Since I introduced Falco sub-config files, since sub-config files were loaded **after** considering the `-o` cmdline override flags, their overridden config entries would win on the `-o` flags.
This PR fixes the behavior.
Fixes #
```release-note
fix(userspace/falco): init cmdline options after loading all config files
```

fix(userspace/falco): init cmdline options after loading all config files

---

falco.yaml
unit_tests/falco/app/actions/test_configure_interesting_sets.cpp
userspace/falco/app/actions/configure_interesting_sets.cpp
userspace/falco/app/actions/init_inspectors.cpp
userspace/falco/app/options.cpp
userspace/falco/app/options.h

/kind cleanup
/area engine
0.40.0 deprecated 3 CLI flags: https://falco.org/blog/falco-0-40-0/#deprecations
Drop them for 0.41.0
Refs #3497 
Fixes #
```release-note
cleanup(userspace/falco)!: drop deprecated in 0.40.0 CLI flags.
```

cleanup(userspace/falco): drop deprecated in 0.40.0 CLI flags.

---

userspace/falco/app/actions/process_events.cpp

/kind bug
/area engine
When using `-M` flag with eg: a plugin (like the container plugin) that generates asyncevents during the startup phase, could set first `duration_start` to a value that would be lower than first event retrieved from scap.
Bug spotted by the container plugin CI and the Falco testing framework: https://github.com/FedeDP/container_plugin/actions/runs/13546519679?pr=21
```
TestFalco_Miscs_PrometheusMetricsNoDriver
{"deadline":300000000000,"level":"info","msg":"running falco with runner","time":"2025-02-26T14:50:59Z"}
{"cmd":"/usr/bin/falco -c /etc/falco/falco.yaml -o append_output.suggested_output=false -o metrics.enabled=true -o …
```

fix(userspace/falco): when counting `-M` timeout, do not account for async events

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
falco.yaml
userspace/falco/configuration.cpp

/kind cleanup
/area build
Next plugin release will make use of libs logger instead of spdlog; this means we don't need a different verbosity flag, we will just use `libs_logger.severity`.
Also, this PR aims at enabling `libs_logger` by default, with `info` level. This way, plugins that use the provided logger will see their messages logged by default.
Fixes #
```release-note
chore(falco.yaml): enable libs_logger by default with info level
```

cleanup(falco.yaml): drop `verbosity` from container plugin init config.

---

userspace/engine/rule_json_schema.h

/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Not really a bug, still.
Defining `exceptions` with empty `values` is a legitimate use case since the values can be added to another rules file. Even when values are not populated elsewhere, Falco can work without issues; that's the reason why the `values` field is not required. With this change, we avoid emitting useless validation warnings in situations where exceptions are just defined but not …

update(userspace/engine): relax validation for `values` in `exceptions`

---

.github/workflows/reusable_build_packages.yaml

/kind bug
/area CI
We need it because rpm pre/post install/remove scripts are evaluated at rpm package building time.
Bug introduced when porting the CI to zig: https://github.com/falcosecurity/falco/pull/3307
Fixes #3503 
```release-note
fix(ci): properly install rpm systemd-rpm-macro package on building packages pipeline
```

fix(ci): properly install rpm `systemd-rpm-macro` package on building packages pipeline

---

.github/workflows/reusable_build_packages.yaml

/kind cleanup
/area CI
Using fedora:latest enforced the usage of clang-20; see https://github.com/falcosecurity/falco/pull/3535#issuecomment-2821021823. It seems like clang-20 compiles a bytecode that is not accepted by at least ubuntu 6.8.x (the one used by gha runners) verifier.
For now, stick to fedora:41 with clang 19.
Fixes #
```release-note
NONE
```

fix(ci): use clang-19 to build modern_ebpf skeleton.

---

falco.yaml
userspace/falco/config_json_schema.h
userspace/falco/configuration.cpp
userspace/falco/outputs_http.cpp
userspace/falco/outputs_http.h

libcurl timeout prevent to send alert through http keep trying to send the alert
/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
this PR  ignore http_output libcurl timeout when network is not available, 
it allows to send the alert when network is back and to not lost it
Fixes #3522
```release-note
NONE
```

fix(userspace/falco): fix outputs_http timeout

---

userspace/engine/CMakeLists.txt
userspace/falco/CMakeLists.txt

/kind bug
/area engine
Fixes #3532 
```release-note
NONE
```

fix(userspace): fixed engine `openssl` dep.

---

falco.yaml
unit_tests/falco/test_configuration_config_files.cpp
userspace/engine/yaml_helper.h
userspace/falco/config_json_schema.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind release
/area engine
/area tests
By default we now use the `append` merge-strategy:
* existing sequence keys will be appended
* existing scalar keys will be overridden
* non-existing keys will be added
We also have an `override` merge-strategy:
* existing keys will be overridden
* non-existing keys will be added
Finally, there is an `add-only` merge-strategy:
* existing keys will be ignored
* non-existing keys will be added
To switch between strategies, one must prepend special characters to `config_files` entries: `@` to enable `append` strategy, or `+` to enable `add-only` strategy.
This is a breaking change because the old default behavior was `override` …

new(userspace,unit_tests)!: add a way to specify merge-strategy for `config_files`

---

CMakeLists.txt

/kind bug
/area build
Fixes `container` custom_target `sed` command to avoid each `make falco` in the build dir to append the plugin path to the plugin path.
Fixes #
```release-note
NONE
```

fix(build): fixed container custom_target `sed` command.

---

userspace/falco/app/actions/load_config.cpp
userspace/falco/configuration.h
userspace/falco/falco_metrics.cpp
userspace/falco/stats_writer.cpp
userspace/falco/stats_writer.h

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Fixes #
Proposing the following minor improvements:
- Introduce an immediate initial metrics msg (output_rule or output_file) upon start/restart/hot_reload -> this may be useful to directly inspect deployment convergence and eliminates the need to wait until the first two ticks happened
- Introduce a restart ts metric for all …

update(metrics): improve restart/hot_reload conditions inspection

---

userspace/falco/app/actions/process_events.cpp
userspace/falco/stats_writer.cpp
userspace/falco/stats_writer.h

/kind bug
/area engine
In case multiple sources are enabled, each source has its own `libs_metrics_collector` with correct flags, so that it can retrieve all metrics.
Fixes #3583
```release-note
fix(userspace/falco): when collecting metrics for stats_writer, create a `libs_metrics_collector` for each source
```

fix(userspace/falco): when collecting metrics for stats_writer, create a `libs_metrics_collector` for each source

---

cmake/modules/grpc.cmake

/kind bug
> /kind design
/area build
> /area engine
> /area tests
> /area CI
This PR fixes build on Alpine Linux.
Fixes #3594
```release-note
NONE
```

fix(cmake): fix abseil-cpp under alpine build

---

userspace/falco/app/restart_handler.cpp
userspace/falco/app/restart_handler.h

When there is no work to do, i.e. when all config watching is disabled, there is no need to keep the restart_handler running. Disable it in this case.
This is helpful to do on nodes where there is little to no headroom in terms of open inotify watches (as per the inotify/max_user_instances configuration), as can happen on nodes populated with other software that also watch the filesystem for changes. If Falco is run on such a node, it may fail to start due to functionality the app does not even intend on using.
This has one change in terms of behaviour, however: the dry-run restarts will no longer occur. As there is still never going to happen a real restart, I understand it as unlikely for there to be a proper need for dry-run restarts.
Fixes: #3639
/kind bug
/area engine
**Does this PR …

fix(restart_handler): disable if there is no work
