CHANGELOG.md
README.md

Add release notes for 0.2.0.

---

CMakeLists.txt

JQ was added to sysdig in
https://github.com/draios/sysdig/commit/20c20fc3a1afe21cfd9ef9a752c0efbcf55471d3,
so add it to the falco build.

Add jq library.

---

userspace/engine/falco_engine.cpp

Need to pop the results of process_event so the stack doesn't grow
without bound.

Fix lua stack leak.

---

docker/event-generator/event_generator.cpp

Add an exfiltration action that reads /etc/shadow and sends the contents
to a arbitrary ip address and port via a udp datagram.
Add the ability to specify actions via the environment instead of the
command line. If actions are specified via the environment, they replace
any actions specified on the command line.

Add exfiltration action, env-specified actions.

---

rules/falco_rules.yaml

Falco is allowed to spawn shells in containers as a part of its program
output method.

Allow falco to spawn shells in containers.

---

userspace/falco/falco.cpp

Bring over functionality from sysdig to write trace files. This is easy
as all of the code to actually write the files is in the inspector. This
just handles the -w option and arguments.
This can be useful to write a trace file in parallel with live event
monitoring so you can reproduce it later.

Add ability to write trace files.

---

userspace/falco/falco.cpp

Collect stats on the number of events processed and dropped. When run
with -v, print these stats. This duplicates syddig behavior and can be
useful when dianosing problems related to dropped events throwing off
internal state tracking.

Add stats on events processed/dropped.

---

CHANGELOG.md
README.md

CHANGELOG for release notes, README to update version.

Updating for 0.4.0.

---

CHANGELOG.md
README.md

New changelog and readme updates.

Updating docs for 0.5.0.

---

rules/falco_rules.yaml

Add confd as a program that can write files below /etc and fleetctl as a
program that can spawn shells.

Add confd/fleetctl as acceptable programs.

---

CMakeLists.txt
userspace/engine/falco_common.cpp

* enable HAS_CAPTURE and driver compilation only on Linux
* set linker flags to correctly compile luajit for os x (as done in sysdig)

Enable compilation on OS X

---

CHANGELOG.md
README.md
examples/k8s-using-daemonset/README.md

Updating with 0.6.0 featues/bug fixes.
Also update the formatting of README to honor github's new slightly
stricter markdown format.

Update changelog/readme for 0.6.0.

---

userspace/engine/token_bucket.cpp
userspace/engine/token_bucket.h

Add a method to fetch the current number of available tokens.

Add ability to get number of tokens.

---

userspace/engine/token_bucket.cpp
userspace/engine/token_bucket.h

This way you can use it as a form of bandwidth throttling.

Add ability to claim multiple tokens.

---

CHANGELOG.md
README.md

Update README/CHANGELOG for 0.6.1.

Update for 0.6.1.

---

README.md

Fix invalid spaces in markdown links

fix: invalid spaces in README markdown

---

CHANGELOG.md
README.md

Update README/CHANGELOG for 0.7.0.

Update for 0.7.0.

---

userspace/falco/falco.cpp

New argument -V validates a single rules file without any verbose
description of the rules and without reading the main falco config file
at all.
This fixes https://github.com/draios/falco/issues/194.

Add ability to validate rules file

---

CHANGELOG.md
README.md

Also fix the incorrect year for several prior releases.

Docs changes for 0.8.0

---

CHANGELOG.md
userspace/falco/config_falco.h.in

Also needed to be updated from /etc/ to /etc/falco.

Fix built-in falco config location.

---

README.md

Update README to drop mailing list

---

.travis.yml
userspace/falco/falco.cpp

This fixes https://github.com/draios/falco/issues/322.

Associate --validate with -V.

---

examples/bad-mount-cryptomining/README.md
examples/bad-mount-cryptomining/attacker-nginx.conf
examples/bad-mount-cryptomining/attacker_files/config_1.json
examples/bad-mount-cryptomining/attacker_files/logo3.jpg
examples/bad-mount-cryptomining/attacker_files/minerd
examples/bad-mount-cryptomining/demo.yml
examples/bad-mount-cryptomining/docker123321-mysql-container.json
examples/bad-mount-cryptomining/host-machine/Dockerfile
examples/bad-mount-cryptomining/host-machine/start-cron-and-dind.sh
examples/bad-mount-cryptomining/launch_malicious_container.sh

An example showing how an overly permissive container environment can be
exploited to install and run cryptomining software on a host system.

Add cryptomining example

---

userspace/engine/CMakeLists.txt

Falco counterpart of https://github.com/draios/sysdig/pull/1127.

Add libcurl include directory in CMakeLists

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

Add gcc-6 to Dockerfiles

---

CHANGELOG.md
README.md

Noting bug fix and bumping version.

Prepare for 0.11.1

---

CMakeLists.txt

The configure script in 7.60.0 has a regression.

Upgrade to curl 7.61.0

---

CHANGELOG.md
README.md

Prepare for 0.12.1

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

These are the same changes as https://github.com/draios/sysdig/pull/1229

Add dkms+xz dependencies to falco container

---

userspace/engine/formats.cpp
userspace/falco/falco.cpp

sysdig-CLA-1.0-signed-off-by: Yue Feng <ztz5651483@gmail.com>
falco-CLA-1.0-signed-off-by: Yue Feng <ztz5651483@gmail.com>

Add base64 encoding and snap length support

---

CODE_OF_CONDUCT
GOVERNANCE
MAINTAINERS
README.md

Fixing:
#434 #436 #437 
Also added a COC from the CNCF COC.

Clean up Readme, Add CNCF requested files for project.

---

integrations/kubernetes-response-engine/playbooks/README.md
integrations/kubernetes-response-engine/playbooks/capture.py
integrations/kubernetes-response-engine/playbooks/deploy_playbook
integrations/kubernetes-response-engine/playbooks/playbooks/__init__.py
integrations/kubernetes-response-engine/playbooks/playbooks/infrastructure.py
integrations/kubernetes-response-engine/playbooks/specs/infrastructure/kubernetes_client_spec.py
integrations/kubernetes-response-engine/playbooks/specs/playbooks/start_sysdig_capture_for_container_playbook_spec.py
integrations/kubernetes-response-engine/sysdig-capturer/Dockerfile
integrations/kubernetes-response-engine/sysdig-capturer/docker-entrypoint.sh

This PR adds a playbook to our response engine which starts to capture data from a pod using sysdig when Falco raises an alert.

Add a playbook which starts to capturing data using Sysdig and uploads capture to a s3 bucket

---

docker/dev/Dockerfile
docker/local/Dockerfile
docker/stable/Dockerfile

xref: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

fix deprecated statement.

---

integrations/kubernetes-response-engine/playbooks/README.md
integrations/kubernetes-response-engine/playbooks/phantom.py
integrations/kubernetes-response-engine/playbooks/playbooks/__init__.py
integrations/kubernetes-response-engine/playbooks/playbooks/infrastructure.py
integrations/kubernetes-response-engine/playbooks/specs/infrastructure/phantom_client_spec.py
integrations/kubernetes-response-engine/playbooks/specs/playbooks/create_container_in_phantom_playbook_spec.py

This PR adds a playbook to our response engine which creates an incident in Phantom when Falco raises an alert.

Add an integration with Phantom

---

test/falco_tests.yaml
test/rules/endswith.yaml
userspace/engine/lua/parser.lua

Add endswith as a symbol so it can be parsed in filter expressions.

Also add endswith to lua parser

---

integrations/kubernetes-response-engine/playbooks/deploy_playbook

fix deply_playbook option issue

---

CHANGELOG.md
README.md

Noting new features and bumping version.

Update CHANGELOG, README for 0.13.0

---

userspace/engine/formats.cpp
userspace/falco/falco.cpp

Hi,
I found some arguments was missed in `falco.cpp`, so I re-add it in `userspace/falco/falco.cpp` and `userspace/engine/formats.cpp`

Fix missing arguments

---

CHANGELOG.md
README.md

Update CHANGELOG/README for 0.13.1

---

examples/nodejs-bad-rest-api/README.md

Needed a space in the heading to display properly. Smallest commit ever!

Fixed Heading Formatting

---

examples/k8s_audit_config/README.md
integrations/k8s-using-daemonset/README.md

1) Changing ssh to minikube ssh in the readme
2) Noting the step to create /falco-config directory

Readme Changes

---

CHANGELOG.md
README.md

Update for 0.14.0

---

integrations/k8s-using-daemonset/README.md

Update output.
falco-CLA-1.0-signed-off-by: Xiang Dai <764524258@qq.com>

integrations/k8s-using-daemonset/README.md: update output

---

README.md

falco-CLA-1.0-signed-off-by: Xiang Dai <764524258@qq.com>

Update contribute doc

---

integrations/k8s-using-daemonset/README.md

falco-CLA-1.0-signed-off-by: Xiang Dai <764524258@qq.com>

fix k8s install issue (#506)

---

falco.yaml

falco-CLA-1.0-signed-off-by: Xiang Dai <764524258@qq.com>1

falco.yaml: change default program_output action (#507)

---

docker/rhel/Dockerfile
docker/rhel/docker-entrypoint.sh
docker/rhel/help.md

This PR adds packaging using Red Hat Enterprise Linux as base image. This will allow us to upload Falco the Red Hat certified images registry.

Adds packaging for RHEL

---

rules/falco_rules.yaml
rules/k8s_audit_rules.yaml

Latest batch of rules changes.

Rule updates 2019.02.v1

---

rules/falco_rules.yaml

Several changes to address FPs based on user feedback.

Rule updates 2019 04.v2

---

test/falco_traces.yaml.in
userspace/engine/falco_engine_version.h
userspace/falco/falco.cpp

New fields fd.dev.*, so updating the fields checksum.

Update engine fields checksum for fd.dev.*

---

integrations/anchore-falco/Pipfile
integrations/anchore-falco/Pipfile.lock

This PR updates the dependencies of the Anchore integration. This will fix some security issues found by GitHub.

Fix security issues reported by GitHub on Anchore integration

---

CHANGELOG.md
README.md

Prepare CHANGELOG/README for 0.15.0

---

MAINTAINERS

docs: add lorenzo and leonardo as maintainers

---

examples/mitm-sh-installer/README.md

Short markdown formatting patch

Markdown formatting

---

OWNERS
rules/OWNERS

>
> /kind bug
> /kind design
> /area engine
> /area rules
Initial owners file.
Will make it better on the go but for now it allows us to review PRs.
Fixes # …

new: initial owners files for Falco

---

CHANGELOG.md
README.md

Changelog, README.md.
>
> /kind bug
> /kind design
> /area engine
> /area rules
Updating docs for 0.15.2
Fixes #
```release-note
NONE
```

Prepare for 0.15.2

---

CHANGELOG.md
README.md

README, CHANGELOG.
>
> /kind bug
> /kind design
> /area engine
> /area rules
Fixes #
```release-note
NONE
```

Prepare for 0.15.3

---

rules/falco_rules.yaml

/area rules
NONE
It supersedes #695.
```release-note
k8s.gcr.io/kube-proxy addition to falco privileged images
```

allow k8s.gcr.io/kube-proxy image to run privileged

---

.gitignore
.luacheckrc

/kind feature
NONE
In order to have a coherent coding style and guideline for Lua code.
This PR introduces a basic configuration for the [luacheck tool](https://github.com/mpeterv/luacheck).
Refs #619.
Please notice the current `.luacheckrc` does not contain any particular customisation at the moment.
```release-note
NONE
```

Lua check setup

---

CHANGELOG.md
README.md

Bumping version, noting changes since last release.
> /kind bug
> /kind design
> /area engine
> /area rules
/area examples
Update CHANGELOG for 0.16.0.
Fixes #
```release-note
NONE
```

CHANGELOG/README changes for 0.16.0

---

rules/falco_rules.yaml

/area rules
It adds trusted_logging_images macro for rule Clear Log History as exception.
Add macro `trusted_logging_images` to rule `Clear Log History`
Fixes #732 
```release-note
Add macro `trusted_logging_images` to rule `Clear Log History`
Add netdata/netdata to `falco_sensitive_mount_images`
```

rules update 07.v1

---

CHANGELOG.md
README.md

New changelog, bump version.
/area deployment
Fixes #
```release-note
Update CHANGELOG for upcoming 0.17.0 release
```

Prepare for 0.17.0

---

OWNERS

Added Kris to owners and sorted 
NONE
```release-note
NONE
```

new: add Kris to owners

---

integrations/anchore-falco/README.md

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
/kind cleanup
fix typos in docs
Fixes #
```release-note
NONE
```

cleanup: fix misspelled words in readme.md

---

README.md

NONE
Just a few changes to match our new OSS policy
NONE
```release-note
NONE
```

Adding OSS changes to README

---

README.md

Co-authored-by: Lorenzo Fontana <lo@linxu.com>
/kind cleanup
NONE
Fix the office hours section of the README.
NONE
```release-note
NONE
```

fix: office hours are bi-weekly

---

CHANGELOG.md
README.md

NONE
Release preparation for 0.17.1
Fixes #849 
```release-note
NONE
```

update(changelog): prepare for v0.17.1

---

.github/PULL_REQUEST_TEMPLATE.md

NONE
NONE
I'm going to create the label in the meantime.
```release-note
NONE
```

proposals area into PR template

---

rules/falco_rules.yaml

/area rules
- This rule detects new raw packets creation in container
- Kubernetes set CAP_NET_RAW capability to container by default. so any pod can abuse raw packets like ARP Spoofing. This is a still threat on Kubernetes.
- Ref: https://blog.aquasec.com/dns-spoofing-kubernetes-clusters
- There is no rule for raw packet on Falco now. so I would like to add this rule. What do you think?
Fixes #
NONE
```release-note
rules: add rules to detect raw packets creation
```

rule update: Add rules to detect raw packets creation

---

CONTRIBUTING.md

Fixes #953
```release-note
NONE
```

docs(CONTRIBUTING): commit convention details

---

README.md

NONE
Removing confusion about community calls from the README.
Fix the mailing list URL.
NONE
```release-note
docs: better details about community calls
```

docs(README): community call + repo planning + correct mailing list URL

---

rules/falco_rules.yaml

/area rules
- Add network tool binaries to detect suspicious network process.
- I added some common tools which attackers often use.
Fixes #
@Kaizhe sorry, this is same PR as this.
https://github.com/falcosecurity/falco/pull/973#discussion_r358076868
```release-note
rule(list network_tool_binaries): Add some network tools to detect suspicious network activity.
```

rule(list network_tool_binaries): Add some network tools to detect suspicious network activity

---

cmake/modules/sysdig.cmake

Avoid building the dependencies (sysdig) unit tests.
/kind cleanup
/area build
Fixes #
```release-note
NONE
```

build: disable the tests of sinsp/scap deps

---

CHANGELOG.md
README.md
docker/kernel/linuxkit/Dockerfile
docker/minimal/Dockerfile
integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml

NONE
Updates the changelog, docker images arguments, etc. in order to release 0.19.0
NONE
NONE
```release-note
NONE
```

Changelog and updates for 0.19.0

---

cmake/modules/sysdig-repo/CMakeLists.txt

/kind cleanup
/area build
Enforce the version of one of our deps.
NONE
NONE
```release-note
NONE
```

build: fix dep version

---

docker/minimal/Dockerfile

/kind bug
/area build
Adds `libyaml` to falco minimal docker image.
Fixes #1016 
```release-note
NONE
```

fix(docker/minimal): libyaml

---

README.md

Signed-off-by: Kris Nova <kris@nivenly.com>
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

Updating logo and slogan to match branding guidelines

---

README.md

Pointing to the community repo as the source of truth
Signed-off-by: Kris Nova <kris@nivenly.com>
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Update to use the community repo as a source of truth
Fixes # …

Updating community section of README.md

---

README.md

> /kind bug
/kind cleanup
> /kind design
Fixes #
```release-note
NONE
```

docs: update references to branches into README

---

CHANGELOG.md
README.md
docker/kernel/linuxkit/Dockerfile
docker/minimal/Dockerfile
integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml

Signed-off-by: rajibmitra <fiorm.github@gmail.com>
> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

update: changelog 0.20.0

---

brand/README.md

Signed-off-by: Kris Nova <kris@nivenly.com>
> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

docs: updating branding

---

.circleci/config.yml

/kind bug
/area build
Avoids to use redirection to get the FALCO_VERSION env var.
Fixes #
```release-note
NONE
```

fix(.circleci): fix get falco version for image build

---

docker/event-generator/event-generator-k8saudit-deployment.yaml

I had a bug in https://github.com/falcosecurity/falco/pull/1088 where
the image name for the event generator was pointing to a temporary tag
instead of latest. This switches the image name back to latest.
/kind bug
> /kind design
> /area build
> /area engine
/area examples
> /area rules
> /area tests
**What this …

Fix image for event generator deployment yaml

---

CHANGELOG.md
README.md
docker/kernel/linuxkit/Dockerfile
integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml

NONE
Prepares the changelot for release 0.21.0
NONE
Did it live.
```release-note
NONE
```

CHANGELOG for 0.21.0

---

.circleci/config.yml

/kind bug
/area build
```release-note
NONE
```

fix(.circleci): bintray secret and user for creating stable versions

---

.circleci/config.yml

/kind bug
/area build
What the title says :)
```release-note
NONE
```

remove --labels flag from circleci

---

docker/tester/Dockerfile
docker/tester/root/usr/bin/usage
test/README.md
test/falco_test.py

/kind cleanup
/area tests
Fixes #1092 
```release-note
NONE
```

update(docker/tester): python 3 support for regression tests

---

README.md

Signed-off-by: Kris Nova <kris@nivenly.com>
> /kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
docs(readme): Adding new release …
```

docs(readme): adding new release archive

---

CMakeLists.txt
cmake/modules/DownloadCatch.cmake
cmake/modules/DownloadFakeIt.cmake
cmake/modules/OpenSSL.cmake
cmake/modules/cURL.cmake
cmake/modules/jq.cmake
cmake/modules/yaml-cpp.cmake

Signed-off-by: danmx <daniel@iziourov.info>
/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Updating hash algorithm to SHA256 from MD5 when pulling dependencies since MD5 is consider insecure.
Fixes # …

update(cmake): using sha256 instead of md5

---

README.md

NONE
It adds a table in the README showing and linking to the development (coming from the master branch) and the stable (released versions) of Falco.
The goal is to let users fastly reach the artifacts.
Also, this way the **latest Falco release** is automatically fetched from bintray and it does not have to be updated manually every time we release.
NONE
Just a bunch of markdown. Better than YAML, BTW 🤣 
```release-note
NONE
```

versions table for the README

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Prepares the changelog for release 0.22.0
Fixes #
Awaiting double check
/hold
**Does this PR …

CHANGELOG for 0.22.0

---

CHANGELOG.md

NONE
Changelog for the hotfix release 0.22.1
NONE
```release-note
NONE
```

docs: changelog for 0.22.1

---

examples/k8s_audit_config/audit-policy.yaml

/kind bug
> /kind design
> /area build
> /area engine
/area examples
> /area rules
> /area tests
Set the audit level to `Metadata` for object `secrets`. Or the secret data will be recorded in the audit log. 
Fixes # …

update audit level to Metadata for secrets

---

cmake/modules/DownloadCatch.cmake

/kind feature
/area tests
```release-note
NONE
```

update(cmake/modules): catch2 version bump to v2.12.1

---

RELEASE.md

> /kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
While making my first ever Falco release, I kept some notes.
> Verba volant, scripta manent
:smiley: 
Fixes #1144 …

docs: add release process

---

rules/falco_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Following the rule naming convention to fix the rule name.
Fixes # …

fix rule naming following naming convention

---

scripts/ignored-calls.sh

/kind bug
NONE
Fixes #
```release-note
NONE
```

fix(scripts): fix ignored calls script to use the new paths

---

.circleci/config.yml
docker/README.md
docker/driverloader/Dockerfile
docker/driverloader/docker-entrypoint.sh
docker/local/docker-entrypoint.sh
docker/stable/docker-entrypoint.sh

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
Fixes #1171 
/cc @leodido 
I used `falcosecurity/falco:${FALCO_VERSION}` as the base image in order to re-use the `stable` dockerfile and avoid duplication of …

driverloader docker image

---

cmake/modules/sysdig.cmake

…55aeb4d03046b8045
This driver version contains a fix for kernels < 3.17
/kind bug
/area build
Fixes #1189
```release-note
update: driver version bump to 96bd9bc560f67742738eb7255aeb4d03046b8045
```

update(cmake/modules): bump driver version to 96bd9bc

---

docker/tester/root/runners/tar.gz.Dockerfile
docker/tester/root/usr/bin/entrypoint
test/falco_tests_package.yaml

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area rules
/area tests
This PR adds a test for the `.tar.gz` package to the integration test suite.
Fixes #
Since …

test: add bin package (tar.gz) to integration test

---

docker/OWNERS

> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

add myself to approvers (docker directory)

---

.circleci/config.yml
scripts/falco-driver-loader
test/driver-loader/run_test.sh
test/driver-loader/runner/Dockerfile
test/driver-loader/runner/test.sh

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
/area tests
We need to be sure that every time we change `falco-driver-loader` nothing will be broken.
Fixes #
This …

test: add driver loader integration tests

---

.circleci/config.yml
docker/no-driver/Dockerfile

/kind bug
/area build
This PR fixes again the `docker/no-driver` image and its tagging that's currently [broken on master](https://app.circleci.com/pipelines/github/falcosecurity/falco/445/workflows/45b63957-8a54-44ee-9b08-79d10a08b913/jobs/2072/parallel-runs/0/steps/0-104) - sorry, my fault! :angel: 
Fixes #
/cc @fntlnz 
/cc @leodido 
```release-note
NONE
```

fix: docker/no-driver config and aliasing

---

RELEASE.md

> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

docs(RELEASE.md): correct typo

---

scripts/debian/falco
scripts/rpm/falco
test/falco_test.py

/kind bug
/area build
/area tests
`deb` and `rpm` were still using `falco-probe`. Since the kernel module is just called `falco`, the installation was broken.
Fixes #
No release note, since it was not broken in the last release.
/cc @leodido 
/cc @fntlnz 
```release-note
NONE
```

fix: kernel module name `falco-probe` => `falco`

---

CHANGELOG.md

Fixes #
```release-note
NONE
```

docs: changelog for 0.23.0

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Quick hotfix before releasing
Fixes #
```release-note
NONE
```

fix(.circleci): correct publishing command

---

.circleci/config.yml

/kind bug
/area build
Related to issue https://github.com/falcosecurity/falco/issues/1096
```release-note
NONE
```

build: use ubuntu focal instead of bionic during the ubuntu CI step

---

CONTRIBUTING.md

Quoting @leodido who explained the reason very well: 
> After a [very long discussion](https://github.com/falcosecurity/falco/issues/983) with CNCF, we finally decided to move the Slack community over the Kubernetes slack (as per Chris A. 's suggestion [here](https://github.com/falcosecurity/falco/issues/983#issuecomment-625901549)).
> 
> We are going to [officially announce the cutoff](https://github.com/falcosecurity/falco/issues/983#issuecomment-630980624) during today community call! 
> 
> And we already started putting documentation about the new channels (and the new slack) in place for the community (see …

docs(CONTRIBUTING.md): update slack channel URL

---

rules/falco_rules.yaml

/kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Fix a macro reference
Macro `remote_file_copy_procs` reference to macro `remote_file_copy_procs` with typo.
Fixes # …

rule update: fix macro reference

---

rules/falco_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Include another network tool in the list
https://github.com/zmap/zmap
N/A
Fixes #
```release-note …
```

rule(list network_tool_binaries): add zmap to the list

---

docker/tester/Dockerfile
test/confs/grpc_unix_socket.yaml
test/falco_test.py
test/falco_tests.yaml
test/requirements.txt
userspace/falco/falco.cpp

/kind feature
/area build
/area engine
/area tests
Since #1241 is almost ready, we need an integration test for the gRPC server.
Fixes #
This PR:
/cc @fntlnz 
/cc @leodido 
```release-note
fix(userspace/falco): honor -M also when using a trace file
```

integration tests for bidirectional gRPC

---

CMakeLists.txt
cmake/modules/OpenSSL.cmake
cmake/modules/cURL.cmake

/kind cleanup
All.
I remember an issue about this topic but can't find it right now (will update whenever I find it).
Fixes #
The same thing but for test traces and scap files will be done in a future separate PR.
```release-note
NONE
```

Get rid of downloads from draios S3 (build dependencies)

---

OWNERS

With this PR I'm proposing myself as maintainer of the main Falco project. This means that I'm asking to extend my ownership from the sole [docker](https://github.com/falcosecurity/falco/blob/master/docker/OWNERS) area to the project root.
For reference I already maintain:
- https://github.com/falcosecurity/falco-website
- https://github.com/falcosecurity/community
- https://github.com/falcosecurity/client-go
- https://github.com/falcosecurity/evolution
- https://github.com/falcosecurity/falco-exporter
- https://github.com/falcosecurity/charts
- https://github.com/falcosecurity/event-generator
- …

docs: add myself to owners

---

docker/falco/docker-entrypoint.sh

/kind bug
This PR fixes a syntax error introduced by mistake in #1297
Fixes #
https://github.com/falcosecurity/falco/issues/1198#issuecomment-655086059
No release note since this PR is just a follow up of #1297 
/cc @leodido 
/cc @fntlnz 
```release-note
NONE
```

fix(docker): correct syntax error in the entrypoint script

---

CHANGELOG.md
RELEASE.md

NONE.
Adds the changelog for the upcoming 0.24.0 release.
NONE
I'm happy we're about to release a huge Falco version 😃 
```release-note
NONE
```

docs: 0.24.0 changelog entries

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
In releases up to and including v0.21.0, the Change Log used the ISO 8601 date format, which is both logical and pleasant to look at. Beginning in v0.22.0, the Change Log's dates use an arcane format involving the most significant unit of time (the year) first, …

Use ISO 8601 format for changelog dates.

---

rules/k8s_audit_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Whitelist trusted k8s images.
Fixes #
```release-note
rule(Pod Created in Kube Namespace): add new …
```

macro(trusted_pod): add new list k8s_image_list

---

cmake/modules/sysdig.cmake
test/run_regression_tests.sh

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Because of https://github.com/draios/sysdig/pull/1679
Fixes #1362 
/cc @fntlnz 
/cc @leodido 
```release-note
NONE
```

Update sysdig version to ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7

---

CHANGELOG.md

Co-Authored-By: Leonardo Grasso <me@leonardograsso.com>
Fixes #
```release-note
NONE
```

docs: changelog for 0.25.0

---

README.md
RELEASE.md

Just very minor issues in the docs.
```release-note
NONE
```

docs: correct typos and URL

---

CHANGELOG.md
RELEASE.md

Cutting release for 0.26.0 and starting 0.27.0
Signed-off-by: Kris Nóva <kris@nivenly.com>
> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

feat(release): Release 0.26

---

brand/README.md

NONE
We need to document the Falco color scheme so that community is aware of it.
NONE
/milestone 0.26.0
```release-note
NONE
```

docs(brand): documenting Falco color scheme

---

rules/falco_rules.yaml

/kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Fixes #1418 
```release-note
rule(Delete or rename shell history): fix warnings/FPs + container teardown.
```

Fix rules warnings

---

CHANGELOG.md

NONE
- Release notes for 0.26.1
- Fix release notes for the previous release (0.26.0)
NONE
/milestone 0.26.1
```release-note
NONE
```

Release 0.26.1 changelog

---

RELEASE.md

Signed-off-by: Kris Nóva <kris@nivenly.com>
> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

feat(docs): Adding meeting notes step to RELASE.md

---

rules/falco_rules.yaml

/area rules
With this we will be able to create custom condition. We have a special use case with a tool called Rosco.
None
None
```release-note
rule(macro user_known_remote_file_copy_tools_in_container_conditions): Allow custom condition for remote file copy tools
```

rule(macro user_know_remote_file_copy_tools_in_container_conditions)

---

README.md

@d1vious brought up that it would be useful if a newcomer would be able to just find the slack channel and our community resources links in the main Falco repository.
I'm copying very clear in the README here all those resources links that we already have in falco.org and in https://github.com/falcosecurity/community with the hope to help new users when they want to reach out.
```release-note
NONE
```

docs: reach out documentation

---

.circleci/config.yml
test/run_regression_tests.sh

inspection via collect test data [0]
[0] https://circleci.com/docs/2.0/collect-test-data/
/kind cleanup
/area build
Fixes #
```release-note
NONE
```

build: make our integration tests report clear steps for CircleCI UI

---

userspace/falco/CMakeLists.txt

/kind cleanup
/area build
During review of #1442 I found a duplicate but then approved the PR rather than commenting it.
Thus, @poiana merged it before @fntlnz or I could apply this last fix.
NONE
```release-note
NONE
```

build: remove duplicate item from FALCO_SOURCES

---

README.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Broken link README.md
Fixes #
```release-note
NONE
```

fix(docs): Broken outputs.proto link

---

rules/falco_rules.yaml

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Fixes #
N/A
The rule is disabled by default as it is still common to run container with root user. …

rule(Container Run as Root User): new rule created

---

README.md

Some links pointing to the documentation were broken, just update them.
Fixes #
/milestone 0.27.0
```release-note
NONE
```

docs(README.md): correct broken links

---

README.md

Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>
/area build
There is a broken link in README.
Fixes #1515 
```release-note
NONE
```

docs: fix a broken link of README

---

.circleci/config.yml
CHANGELOG.md
RELEASE.md

Fixes #
```release-note
NONE
```
/milestone 0.27.0

Release notes for 0.27.0

---

userspace/falco/falco.cpp

Co-Authored-By: Leonardo Grasso <me@leonardograsso.com>
/kind bug
Quick fix for the release. We had an issue with the new outputs and daemon mode.
```release-note
NONE
```

fix(userspace/falco): output needs to be initialized after fork

---

test/README.md

Signed-off-by: Shane Lawrence <shane@lawrence.dev>
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
/area tests
This PR fixes broken links in the regression tests' README. The path to these pages in the official Falco docs changed slightly.
~Fixes #~
**Does …

Fix broken links to docs.

---

docker/tester/root/usr/bin/usage

Signed-off-by: Shane Lawrence <shane@lawrence.dev>
/kind bug
> /kind design
> /area build
> /area engine
> /area rules
/area tests
This fixes a small bug in the falco-tester container that causes an error when trying to display the avocado version.
Fixes #1564 
**Does this …

Use default pip version to get avocado version.

---

rules/falco_rules.yaml

Signed-off-by: stevenshuang <stevenshuang521@gmail.com>
> /kind bug
> /area rules
fix rule description.
```release-note
NONE
```

fix: update rule description

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
Follows up #1577 
```release-note
NONE
```

fix: publishing jobs

---

test/run_performance_tests.sh
test/run_regression_tests.sh

/kind cleanup
/area tests
Fixes #
```release-note
NONE
```

chore(test): replace bucket url with official distribution url

---

.circleci/config.yml

Co-authored-by: Leonardo Di Donato <leodidonato@gmail.com>
/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE …
```

build(.config): pin awscli version

---

RELEASE.md

NONE
Updates a link in RELEASE.md 
NONE
Found a reference to the previous HackMD we were using for Community Call notes while releasing Falco 0.28
This PR updates it to the new URL.
```release-note
NONE
```

docs: update link for HackMD community call notes

---

proposals/20210119-libraries-contribution.md

/kind cleanup
I noticed the libs contribution file name contained a wrong date, this PR fixes it.
NONE
I'm about to submit a PR to update the link in the Falco blog as soon this gets merged in.
```release-note
NONE
```

docs(proposals): fix libs contribution name

---

rules/falco_rules.yaml

/area rules
Noticed that this miners pool was not included in our detection. Added it
```release-note
rules(list miner_domains): add rx.unmineable.com for anti-miner detection
```

rules(list miner_domains): add rx.unmineable.com for anti-miner detection

---

CHANGELOG.md

Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
This PR adds the changelog for the 0.29.0 version
```release-note
NONE
```

docs(changelog.md): add release 0.29.0

---

.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: Thomas Spear <tspear@conquestcyber.com>
/kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
The link to the contributing guide is a vital one. 
Fixes #
```release-note
Fixes Pull …
```

Fix link to CONTRIBUTING.md in the Pull Request Template

---

CHANGELOG.md

Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
This PR notifies a rule change in the right section of the changelog.
```release-note
NONE
```

docs(changelog.md): update for release 0.29.0

---

CHANGELOG.md

NONE
Additions to the CHANGELOG for Falco 0.29.1
NONE
/milestone 0.29.1
```release-note
NONE
```

CHANGELOG for Falco 0.29.1 changeset

---

CHANGELOG.md

/kind cleanup
NONE
Fixes some left-overs in the CHANGELOG for Falco 0.29.1
NONE
NONE
```release-note
NONE
```

docs: CHANGELOG for 0.29.1 cleanup

---

CHANGELOG.md

Signed-off-by: Frederico Araujo <frederico.araujo@ibm.com>
NONE
Additions to the CHANGELOG for Falco 0.30.0
NONE
/milestone 0.30.0
```release-note
NONE
```

docs(changelog.md): update for release 0.30.0

---

.circleci/config.yml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
/area tests
Fixes #
```release-note
Update machine image for circleci EBPF tests to a newer version of ubuntu.
```

Update ubuntu image for driver-loader test

---

ADOPTERS.md

Signed-off-by: Akos Kaldy <kaldyka@gmail.com>
> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

add Phoenix to adopters list

---

cmake/modules/GetFalcoVersion.cmake

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
`git-describe` uses a number of hex digits to represent the current commit in abbreviated form which depends on the git version and number of objects in the repo (https://git-scm.com/docs/git-describe), this meant that …

fix(build): use consistent 7-character build abbrev sha

---

.gitignore
cmake/modules/falcosecurity-libs.cmake
cmake/modules/plugins.cmake
test/falco_tests_plugins.yaml
userspace/engine/falco_engine_version.h

`Signed-off-by: Federico Di Pierro <nierro92@gmail.com>`
> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

update(build): updated libs to latest master version; updated plugins versions

---

cmake/modules/plugins.cmake

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

build: updated cloudtrail plugin to latest version

---

rules/aws_cloudtrail_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Refs https://github.com/falcosecurity/falco/issues/1857#issuecomment-1021344794
Fixes #
```release-note
NONE
```

rules: update aws_cloudtrail_rules required plugin versions

---

CHANGELOG.md

NONE
Additions to the CHANGELOG for Falco 0.31.0
NONE
/milestone 0.31.0
```release-note
NONE
```

docs(changelog.md): update for release 0.31.0

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

build: hotfix for release 0.31.0

---

rules/aws_cloudtrail_rules.yaml

Signed-off-by: pablopez <pablo.lopezzaldivar@sysdig.com>
/kind cleanup
/area rules
Just a typo.
None.
No.
No.
```release-note
NONE
```

rule_output(Delete Bucket Public Access Block) typo

---

scripts/falco-driver-loader

/kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Just correct a typo in the script usage message.
Fixes #
```release-note
NONE
```

fix(scripts): correct typo in `falco-driver-loader` help message

---

userspace/falco/app_cmdline_options.cpp

Signed-off-by: Andrea Bonanno <andrea@bonanno.cloud>
/kind bug
Makes `--help` more clear.
Fixes #1914 
```release-note
NONE
```

chore(userspace/falco): fixes truncated -b option description.

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

docs(CHANGELOG.md): Changelog for 0.31.1

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Update the CHANGELOG with the Security Advisory link now that it is published.
Fixes # …

update(changelog): add link to security fix for 0.31.1

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Just remove a leftover.
Fixes #
/cc @jasondellaluce 
/cc @Kaizhe 
/milestone 0.32.0
```release-note
NONE
```

chore(rules): remove leftover

---

rules/okta_rules.yaml

Creating out of the box rules for the new OKTA Faclo plugins
Opened PR: https://github.com/falcosecurity/plugins/pull/81
This PR introduce the out of the box ruleset for the new OKTA Falco plugin created.
Reference https://github.com/falcosecurity/plugins/pull/81
> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
/area rules
> /area tests
> /area …

rules: Out of the box ruleset for OKTA Falco Plugin

---

rules/falco_rules.yaml

A recently added macro include values which aren't triggering the rule since the chars > and / aren't present in the proc.cmdline field so the rule won't trigger with this values.
Co-authored-by: Brucedh <alessandro.brucato@sysdig.com>
Co-authored-by: AlbertoPellitteri <alberto.pellitteri@sysdig.com>
> /kind bug
> /kind design
> /area build
> /area …

rule(falco_rules) Removed use cases not triggering macro curl_download

---

userspace/engine/rule_loader.cpp
userspace/engine/rule_reader.cpp

/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fix two small regressions related to exceptions parsing as a result of the lua-to-c++ rule loader conversion.
Fixes #1984
```release-note
NONE …
```

Fix exception parsing regressions

---

cmake/cpack/debian/conffiles

/kind cleanup
/area build
Users are not supposed to locally edit ruleset files. They should use local variants only (for example `falco_rules.local.yaml`).
For this reason, I believe we should not include them in `conffiles`.
PS
If you want to know more about *conffiles* :point_right: https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/
Fixes #
```release-note
NONE
```

build: correct conffiles for DEB packages

---

userspace/engine/rule_loader.cpp

/kind bug
/kind cleanup
/area engine
This PR improves rule loader source checks for macros and lists
```release-note
NONE
```

fix(userspace/engine): improve rule loader source checks

---

cmake/modules/falcosecurity-libs.cmake

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
update(build): set libs version to …
```

update(build): updated libs version for Falco 0.32.0 release.

---

cmake/modules/plugins.cmake
test/falco_k8s_audit_tests.yaml

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
/area tests
Fixes #
```release-note
update: updated plugins to latest stable released version
```

new: update plugins

---

cmake/modules/falcosecurity-libs.cmake

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
update(build): updated libs to …
```

update(build): updated libs to 1be924900a09cf2e4db4b4ae13d03d838959f350

---

userspace/falco/app_actions/process_events.cpp

```
```
> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

chore(userpace/falco): do not print error code in process_events.cpp

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

docs(changelog): added 0.32.0 release notes.

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

fix(build): use apt instead of apk when installing deps for aws ecr publish

---

docker/builder/Dockerfile
docker/builder/root/usr/bin/scl_enable

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
With @leogr , we already pushed the updated images  on dockerhub: https://hub.docker.com/r/falcosecurity/falco-builder/tags 
* …

update(docker): updated falco-builder to fix multiarch support.

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

fix(build): fixed circleCI artifacts publish for arm64.

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

fix(build): removed leftover line in circleci config.

---

.circleci/config.yml

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

fix(build): fixed publish-docker-dev job context.

---

scripts/publish-deb

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
It amends a wrong path issue in #2060 
Fixes #
```release-note
NONE
```

fix(scripts): fixed path in publish-deb script.

---

OWNERS

> /kind bug
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
As said in today's community call, i am volunteering as a maintainer for Falco core repo.
I have been highly involved in various activities linked to Falco and its surrounding projects; i tried my best to help reviewing code and help people all around the …

update(OWNERS): add Federico Di Pierro to owners.

---

rules/OWNERS

Signed-off-by: Kaizhe Huang <khuang@aurora.tech>
Decided to step down from the falco maintainer role but remain as a reviewer till the new Falco rule owner step up.
> /kind bug
/kind design
> /area build
> /area engine
/area rules
> /area tests
N/A
Fixes #
**Does this PR …

remove kaizhe from falco rule owner

---

docker/tester/root/runners/deb.Dockerfile

/kind bug
> /kind design
/area build
> /area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

fix(docker): fixed deb tester sub image.

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area rules
> /area tests
This PR updates Falco Libs with the following tags:
* libs: 0.7.0-RC2
* driver: 2.0.0-RC1+driver
These libs versions, when final, will be the ones for 0.32.1
Fixes #
**Special notes for …

update(falco): update libs to 0.7.0-rc2, 2.0.0-rc1+driver

---

cmake/modules/falcosecurity-libs.cmake

> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
> /area rules
> /area tests
Update Falco with the [latest released libs version](https://github.com/falcosecurity/libs/releases/tag/0.7.0).
Fixes # …

update(falco): update libs to 0.7.0

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Add changelog for 0.32.1
Fixes #
```release-note
NONE
```

update(docs): changelog for version 0.32.1

---

userspace/falco/app_actions/load_rules_files.cpp

```
```
> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Remove trailing colon from logs messages when loading rule files.
Fixes #
```release-note …
```

chore(engine): remove trailing colon from logs when loading rule files

---

rules/OWNERS

> /kind bug
> /kind design
> /area build
> /area engine
/area rules
> /area tests
Fixes #
I would like propose myself as a reviewer of rules in falcosecurity/falco.
After actively working and contributing to this …

Add darryk10 as rules OWNERS as reviewer

---

.circleci/config.yml

/kind bug
/area build
Fixes #
```release-note
NONE
```

fix(ci): fixed docker manifest circleci.

---

scripts/falco-driver-loader

/area engine
This PR enhances the information printed by the `falco-driver-loader` during the loading phase. This is just a proposal, i would love to hear some ideas on that
```release-note
docs(falco-driver-loader): add some comments in `falco-driver-loader`
```

docs(falco-driver-loader): add some comments in `falco-driver-loader`

---

CHANGELOG.md

/area engine
Add changelog for 0.32.2
```release-note
update(docs): changelog for version 0.32.2
```

update(docs): changelog for version 0.32.2

---

CHANGELOG.md
scripts/falco-driver-loader

/kind design
/kind feature
https://github.com/falcosecurity/falco/issues/2149
```release-note
NONE
```

Sync Release `0.32.2`

---

.github/PULL_REQUEST_TEMPLATE.md

/kind design
This PR tries to enrich the pull request template with some new labels
```release-note
NONE
```

Enrich pull request template

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/falco_load_result.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_reader.cpp
userspace/falco/app_actions/load_rules_files.cpp
userspace/falco/app_actions/validate_rules_files.cpp
userspace/falco/application.h

/kind bug
> /kind design
> /area build
/area engine
> /area rules
> /area tests
Fixes #
```release-note
NONE
```

Rules result handle multiple files

---

OWNERS

None
Hi folks :vulcan_salute:  As said in today's community call, I propose myself as a maintainer for Falco core repo.
I have been highly involved in various activities linked to Falco and its surrounding projects and I tried my best to help review code and help people all around the community, I'm looking forward to helping also here :)
Please if you have any suggestions or concerns feel free to share!
Thank you!
```release-note
NONE
```

vote: update(OWNERS): add Andrea Terzolo to owners

---

userspace/engine/filter_evttype_resolver.h

/kind bug
/area build
/area engine
Fixes #
```release-note
NONE
```

fix(userspace/engine): properly include stdexcept header to fix build.

---

OWNERS

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
> /area CI
The https://github.com/mfdii user is inactive.
Fixes #
```release-note
NONE
```

chore(OWNERS): cleanup inactive reviewer

---

userspace/engine/falco_engine.cpp
userspace/engine/filter_evttype_resolver.cpp
userspace/engine/filter_evttype_resolver.h
userspace/falco/app_actions/compute_syscall_buffer_size.cpp
userspace/falco/app_actions/create_requested_paths.cpp
userspace/falco/app_actions/create_signal_handlers.cpp
userspace/falco/app_actions/daemonize.cpp
userspace/falco/app_actions/load_config.cpp
userspace/falco/app_actions/open_inspector.cpp
userspace/falco/app_actions/print_page_size.cpp
userspace/falco/app_actions/print_support.cpp
userspace/falco/app_actions/process_events.cpp
userspace/falco/app_actions/select_event_sources.cpp
userspace/falco/application.h
userspace/falco/event_drops.h

/kind cleanup
/area engine
This adds a bunch of chores and minor changes to clean-up the code for the upcoming release. Goals are:
- Make log messages more uniform and consistent in formatting
- Minor performance improvement chores: passing string by reference, using unordered_set, etc...
```release-note
update(userspace): minor pre-release improvements
```

update(userspace): minor pre-release improvements

---

userspace/engine/rule_loader.cpp
userspace/falco/configuration.h

/kind bug
/area engine
This prevents out-of-bound string access from happening.
```release-note
NONE
```

fix(userspace): safely check string bounded access

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
This PR bumps the libs repo to the latest commit of the release branch 0.9.0
```release-note
NONE
```

chore: bump libs version

---

scripts/debian/falco_inject_kmod.service
scripts/rpm/falco_inject_kmod.service

/kind bug
/area build
The Falco inject script fails with some old systems versions
```release-note
NONE
```

fix(scripts): inject kmod script fails with some systemd versions

---

CHANGELOG.md

This adds a changelog entry for the upcoming v0.33.0
Fixes #2074
```release-note
NONE
```

update(changelog.md): add entry for Falco 0.33.0

---

CHANGELOG.md

/kind release
Synching release branch with https://github.com/falcosecurity/falco/pull/2261
```release-note
NONE
```

update(CHANGELOG.md): sync changelog changes

---

.circleci/config.yml

/kind bug
/area CI
Fixes #
```release-note
NONE
```

fix(ci): fixed version bucket for release jobs.

---

cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
Fixes #
```release-note
update(falco): bump libs to 0.9.2
```

update(build): bump libs to 0.9.2 for 0.33.1

---

CHANGELOG.md

Fixes #
```release-note
new(docs): add changelog for 0.33.1
```

new(docs): add entry for 0.33.1 changelog

---

CHANGELOG.md

/area engine
Port changes to master in the release notes file.
Fixes #
You are not seeing double, the other PR you might have approved was for the release branch.
```release-note
NONE
```

new(CHANGELOG): add entry for 0.33.1 (in master branch this time)

---

rules/falco_rules.yaml

Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area engine
/area rules
> /area tests
> /area CI
I have noticed that the rule `Linux Kernel Module Injection Detected` got triggered whenever `insmod` was performed inside a container. To have a successful kernel module injection …

update(rules): improve insmod detection within container using CAP_SYS_MODULE

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
tests/engine/test_filter_macro_resolver.cpp
userspace/engine/falco_engine_version.h
userspace/falco/app_actions/process_events.cpp

/kind cleanup
/area build
Bumps libs to latest RC: 0.10.0-rc1
Bumps driver to latest RC: 4.0.0-rc1+driver
NONE 
```release-note
update(cmake): bump libs and driver to latest RC.
```

update(cmake): update libs to latest RC

---

proposals/20221129-artifacts-distribution.md

This proposal aims to formalize the revamped way adopted by Falcosecurity to distribute artifacts. In fact, it reflects some topics widely discussed in the last few months, plus suggestions for some obvious action items to move forward.
Furthermore, most of the points reflect some already ongoing efforts, such as the revamp of falcoctl.
Any feedback is appreciated
Fixes #
/milestone 0.34.0
```release-note
NONE
```

docs(proposal): new artifacts distribution proposal

---

docker/builder/modern-falco-builder.Dockerfile

/kind feature
/area CI
Update the toolchain in the centos7 dockerfile used to build the modern probe
```release-note
NONE
```

update(CI): upgrade toolchain in modern falco builder dockerfile

---

.github/PULL_REQUEST_TEMPLATE.md

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area rules
> /area tests
> /area CI
/milestone 0.34.0
Fixes #
```release-note
NONE
```

docs(.github): rules are no longer in this repo

---

cmake/cpack/debian/conffiles
scripts/CMakeLists.txt
scripts/falcoctl/falcoctl.yaml

/kind feature
/area build
This PR adds the Falcoctl config into Falco package
```release-note
new(scripts): add `falcoctl` config into Falco package
```

new(scripts): add Falcoctl config into Falco package

---

cmake/modules/falcosecurity-libs.cmake

/kind cleanup
Fixes #
```release-note
update(cmake): bump libs to 0.10.3
```

update(cmake): bumped libs to 0.10.3

---

scripts/rpm/postinstall.in

/kind bug
Fixes #
```release-note
NONE
```

fix(scripts): force rpm postinstall script to always show dialog, even on upgrade

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Add v 0.34.0 release notes 📝
Fixes #
```release-note
NONE
```

new(docs): update Changelog for 0.34.0

---

cmake/modules/GetFalcoVersion.cmake

/kind bug
/area build
Fixes issue introduced by #2292 ; the fallback for the tag fetch was indeed not a real fallback :/
Fixes #
```release-note
NONE
```

fix(cmake): fixed tag fetching fallback (that is indeed needed)

---

RELEASE.md

Fixes #
```release-note
NONE
```

fix(release): fixed tag creation step in release doc.

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Add release notes for `0.34.1`.
Fixes #
```release-note
NONE
```

new(docs): update Changelog for 0.34.1

---

falco.yaml
userspace/falco/app/actions/helpers_interesting_sets.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h

> /kind bug
/kind cleanup
/kind design
> /area build
/area engine
> /area tests
> /area CI
See https://github.com/falcosecurity/falco/issues/2373 for context.
Fixes #
```release-note
new(app_actions): introduce base_syscalls user option
```

new(app_actions): introduce base_syscalls user option

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h
userspace/falco/app/actions/configure_interesting_sets.cpp
userspace/falco/app/actions/helpers_inspector.cpp
userspace/falco/app/state.h

/kind cleanup
/area build
/area engine
Bump to latest libs master (6c11056815b9eff787c69f9b2188a2ae503533c9)
Fixes #
```release-note
update(build,userspace): bumped libs and driver to 6c11056815b9eff787c69f9b2188a2ae503533c9
```

update(cmake,userspace): bumped to libs master.

---

.github/workflows/master.yaml

/kind bug
/area CI
as per title
Fixes #
```release-note
NONE
```

fix(ci): bucket -> bucket_suffix

---

.github/workflows/reusable_build_packages.yaml

/kind bug
/area CI
As per title
Fixes #
```release-note
NONE
```

fix(ci): enable toolset before every make command

---

.github/workflows/reusable_publish_packages.yaml

/kind bug
/area CI
The heredoc was taken from CircleCI but apparently the escaping rules are different from GHA, so we don't need the backslash there.
Fixes #
```release-note
NONE
```

fix(ci): escape heredoc

---

.github/workflows/reusable_publish_packages.yaml

/kind bug
/area CI
Add the CF Distribution ID to the workflows so we'll be able to invalidate cache entries if needed.
Fixes #
```release-note
NONE
```

fix(ci): add Cloudfront Distribution ID

---

.github/workflows/reusable_publish_docker.yaml

/kind bug
/area CI
Two changes:
* Set proper directory when downloading container images
* Remove redundant ECR login step
Fixes #
```release-note
NONE
```

fix(ci): falco images directory, ecr login

---

.github/workflows/reusable_publish_docker.yaml

/kind bug
/area CI
Configure the correct region which must be `us-east-1` for ECR public. See: https://github.com/aws-actions/amazon-ecr-login#configure-credentials
Fixes #
```release-note
NONE
```

fix(ci): configure ECR public region

---

falco.yaml
userspace/falco/app/options.cpp

/kind cleanup
The modern bpf probe is no more experimental so we need to update comments
```release-note
NONE
```

cleanup(config): modern bpf is no more experimental

---

.github/workflows/reusable_publish_docker.yaml

/kind bug
/area CI
The right command for crane was `copy`, not `tag` in that case
Fixes #
```release-note
NONE
```

fix(ci): correctly tag slim manifest

---

.github/workflows/release.yaml
.github/workflows/reusable_publish_docker.yaml

/kind feature
/area CI
Add signatures with cosign upon releases!
Fixes #
```release-note
new(release): released container images are now signed with cosign
```

new(ci): sign releases with cosign

---

.github/workflows/reusable_build_docker.yaml
docker/driver-loader/Dockerfile

/kind bug
/area CI
This: https://github.com/falcosecurity/falco/blob/master/docker/driver-loader/Dockerfile#L2 needs to be up to date before starting the release process.
I believe we still have a lot of room for improvement, but we're discussing and working on brand new images, meaning that those Dockerfiles will be restructured as well.
Fixes #
```release-note
NONE
```

fix(ci): load falco image before building falco-driver-loader

---

brand/README.md

/kind cleanup
It updates the branding guidelines to reference the new brand identity page in the website. The designs are shown on the attached file. Thanks!
[falco_brand_page (1).pdf](https://github.com/falcosecurity/falco/files/11226826/falco_brand_page.1.pdf)
```release-note
NONE
```

Updating Falco branding guidelines

---

.github/workflows/reusable_build_docker.yaml

/kind bug
/area CI
Use correct `TARGETARCH` name isntead of `TARGET_ARCH`.
Fixes #
```release-note
NONE
```

fix(ci): docker arg is named `TARGETARCH`.

---

.github/workflows/reusable_publish_docker.yaml

/kind bug
/area ci
As per title.
Fixes #
```release-note
NONE
```

fix(ci): get the manifest for the correct tag

---

userspace/falco/app/actions/helpers_generic.cpp

/kind cleanup
/area engine
The newest plugin caps where not accounted for when printing plugin infos.
```release-note
chore(userspace/falco/app): print all supported plugin caps
```

chore(userspace/falco/app): print all supported plugin caps

---

cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
as per title
Fixes #
```release-note
NONE
```

update(build): libs 0.11.0-rc2

---

cmake/modules/falcosecurity-libs.cmake
cmake/modules/plugins.cmake

/kind cleanup
/area build
Useful for testing purposes with the latest fixes.
```release-note
update(cmake): bump libs and plugins to latest dev versions
```

update(cmake): bump libs and plugins to latest dev versions 

---

proposals/20230511-roadmap-management.md

See https://github.com/falcosecurity/evolution/issues/259
Fixes https://github.com/falcosecurity/evolution/issues/259
```release-note
NONE
```

docs(proposals): Falco roadmap management

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind cleanup
/area build
Fixes #
```release-note
update(cmake): bump libs to 0.11.0-rc5 and driver to 5.0.1.
```

update(cmake): bumped libs to 0.11.0-rc5 and driver to 5.0.1.

---

cmake/modules/falcosecurity-libs.cmake

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
as per PR title
Fixes #
```release-note
update(cmake): bump libs to 0.11.0
```

update(cmake): bump libs to 0.11.0

---

cmake/modules/rules.cmake

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
update(cmake): bump falco rules to 1.0.0-rc1
```

update(cmake): bump falco rules to 1.0.0-rc1

---

cmake/modules/falcosecurity-libs.cmake

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
As per PR title
Fixes #
```release-note
update(cmake): bump libs to 0.11.1
```

update(cmake): bump libs to 0.11.1

---

README.md
cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
Cherrypicks:
[x] https://github.com/falcosecurity/falco/pull/2614
[x] https://github.com/falcosecurity/falco/pull/2611
Fixes #
```release-note
update(libs): bumped libs to 0.11.1.
```

sync(0.35.x): bump libs to 0.11.1

---

CHANGELOG.md
cmake/modules/rules.cmake

/kind release
/area build
* Cherry picks https://github.com/falcosecurity/falco/pull/2618
* Updated changelog for release 0.35.0
Fixes #
```release-note
new(docs): updated changelog for 0.35.0
```

Sync/release 0.35.0

---

CHANGELOG.md

/kind release
Cherry picks changelog update from release/0.35.x branch.
Fixes #
```release-note
NONE
```

sync(docs): update Changelog for 0.35.0.

---

.github/workflows/reusable_publish_packages.yaml
cmake/modules/falcosecurity-libs.cmake

/kind bug
/area build
/area ci
Changes for build issue identified on the Falco 0.35.x release branch
Fixes #
```release-note
NONE
```

fix(ci,build): fixes for 0.35.x release branch

---

.github/workflows/reusable_publish_packages.yaml
cmake/modules/falcosecurity-libs.cmake

/kind bug
/area ci
At some point, one day, I said "the only part of the release pipeline that we couldn't test is the final release".
We now noticed that when the release is final the `add_rpm` command will try to copy something from `/tmp/falco-rpm` into itself, failing.
Also, this updates libs to 0.11.2
This fixes it by changing the temp directory name.
Fixes #
```release-note
NONE
```

fix(falco): update libs, fix CI for release

---

.github/workflows/reusable_test_packages.yaml

/kind cleanup
/area CI
```release-note
NONE
```

fix(ci): skip plugins and falcoctl tests for static build

---

.github/workflows/reusable_test_packages.yaml

/kind bug
/area CI
```release-note
NONE
```

fix(.github): skip some regression tests in static build

---

cmake/modules/rules.cmake

/kind cleanup
/area build
```release-note
update(cmake): bump falco rules to v1.0.1
```

update(cmake): bump falco rules to v1.0.1

---

cmake/modules/falcosecurity-libs.cmake

/kind cleanup
/area build
```release-note
update(cmake): bump libs to 0.11.3
```

update(cmake): bump libs to 0.11.3

---

OWNERS

After driving various Falco releases and helping maintainers in several areas, including main code, security and CI/CD, I think I can help more closely with the maintenance of this repo! As per our discussion during the core maintainers planning meeting on 2023-06-08 and the community call on 2023-06-21. :)
```release-note
NONE
```

update(OWNERS): add LucaGuerra to owners

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
NONE
```

docs: update changelog for 0.35.1

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h

/kind feature
/area build
Update libs to the latest available version for testing and development.
```release-note
NONE
```

update(falco): update libs to dc02e50

---

cmake/modules/cpp-httplib.cmake

/kind feature
/area build
Update cpp-httplib, including the latest security fixes.
Note that the only two breaking changes that are documented here https://github.com/yhirose/cpp-httplib/releases do not seem to affect the way we use the library.
Fixes #
```release-note
NONE
```

update(cmake): update cpp-httplib to 0.13.1

---

README.md

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
/milestone 0.36.0
```release-note
NONE
```

docs(README.md): minor improvements

---

brand/README.md

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
/milestone 0.36.0
```release-note
NONE
```

docs(brand): remove redundancy with the website

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h

/kind feature
/area build
Engine version has been bumped to 20 accordingly.
```release-note
update(cmake): bump libs and driver to 0.12.0
```

update(cmake): bump libs to 0.12.0 and driver to 5.1.0+driver

---

userspace/falco/event_drops.cpp

/kind bug
/area engine
fix "ebpf_enabled" output stat
```release-note
NONE
```

fix: fix "ebpf_enabled" output stat

---

userspace/falco/event_drops.cpp

/kind feature
/area engine
Introduce new stats updated to the latest libs version: https://github.com/falcosecurity/libs/pull/1303#pullrequestreview-1590832523
```release-note
NONE
```

update: introduce new stats updated to the latest libs version

---

.github/workflows/reusable_test_packages.yaml

/kind bug
/kind cleanup
/area CI
disable `falco-driver-loader` tests on ARM64 since right now installing kernel-headers on the job container is quite complex
```release-note
NONE
```

ci: disable falco-driver-loader tests on ARM64

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
bump Falco to latest libs
```release-note
NONE
```

chore: bump Falco to latest libs

---

README.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
NONE
```

docs(README.md): correct URL

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind cleanup
/area build
Bumped libs to 0.13.0-rc2 and driver to 6.0.1+driver.
Fixes #
```release-note
update(cmake): bumped libs to 0.13.0-rc2 and driver to 6.0.1+driver
```

update(cmake): bumped libs to 0.13.0-rc2 and driver to 6.0.1+driver.

---

cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
bump to latest libs
```release-note
NONE
```

chore: bump to latest libs

---

cmake/modules/plugins.cmake

/kind release
/area build
Bumps plugins to latest stable for the upcoming Falco release.
Fixes #
```release-note
update(cmake): bumped plugins to latest stable versions
```

update(cmake): bumped plugins to latest stable versions.

---

.github/workflows/release.yaml

/kind cleanup
/area build
As per title.
Fixes #
```release-note
NONE
```

update(gha): add version for rn2md

---

cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
Fixes #
```release-note
update(cmake): bump libs to 0.13.1
```

chore(cmake): bumped libs to 0.13.1.

---

CHANGELOG.md

/kind release
Add changelog for Falco 0.36.0
Fixes #
```release-note
NONE
```

new(docs): add changelog for 0.36.0

---

CHANGELOG.md

> /kind bug
> /kind design
/kind release
> /area build
> /area engine
> /area tests
> /area CI
As per title (the release branch counterpart has already been published)
Fixes #
```release-note
NONE
```

update(docs): add changelog for 0.36.0

---

.github/workflows/release.yaml

/kind cleanup
/area CI
Bumps rn2md to latest master that fixes breaking change with "!" detection. (https://github.com/leodido/rn2md/pull/12)
Fixes #
```release-note
NONE
```

chore(ci): bumped rn2md to latest master.

---

.github/release_template.md

/kind feature
/area CI
Fixes #
```release-note
NONE
```

new(ci): properly link libs and driver releases linked to a Falco release

---

ADOPTERS.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
update(docs): add Wireshark/Logray as adopter
```

update(doc) Add Wireshark / Logray as adopters

---

cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
Fixes #
```release-note
update(cmake): bumped libs to 0.13.3
```

sync(release/0.36.x): update libs to 0.13.3

---

.github/workflows/scorecard.yaml

/kind feature
/area CI
To improve the Falco's supply chain security and monitor it through common and standardized metrics.
Open Source Security Foundation Scorecard [1] is an automated tool that assesses a number of important checks associated with software security and assigns each check a score of 0-10.
Also, the OSSF Scorecard is one of the metrics monitored by the CNCF CLO Monitor [2].
1. https://github.com/ossf/scorecard
2. https://github.com/cncf/clomonitor
Fixes #2887
NA
```release-note
NONE
```

Run OpenSSF Scorecard in pipeline

---

cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
Fixes #
```release-note
update(cmake): bumped libs to 0.13.4 tag.
```

update(cmake): bumped libs to 0.13.4 tag.

---

CHANGELOG.md

Fixes #
```release-note
new(docs): add changelog for 0.36.1 + 0.36.2.
```

new(docs): add changelog for 0.36.1 + 0.36.2.

---

CHANGELOG.md

/kind release
Sync CHANGELOG after 0.36.2 release.
Fixes #
```release-note
NONE
```

new(docs): sync changelog for 0.36.2.

---

.github/workflows/reusable_publish_docker.yaml

/kind cleanup
/area CI
As per title. Forgot to pin the version before.
Fixes #
```release-note
NONE
```

chore(gha): set cosign-installer to v3.1.2

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
As per title.
Fixes #
```release-note
NONE
```

chore(falco): update to libs on nov 28th

---

.github/workflows/reusable_test_packages.yaml

/kind cleanup
/area CI
Fixes #
```release-note
NONE
```

chore(ci): enable aarch64 falco driver loader tests.

---

cmake/modules/driver.cmake

/kind feature
/area build
This PR bumps the driver version to `7.0.0+driver`
```release-note
NONE
```

chore: bump driver version

---

cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
This PR bumps Falco to libs 0.14.1
```release-note
NONE
```

chore: bump Falco to libs 0.14.1

---

userspace/falco/stats_writer.cpp

/kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Minor fixes to new libsinsp state metrics handling. I am tracking them as I start the proper stats refactor for libs 0.15.0
Fixes #
```release-note
fix(userspace/metric): minor fixes in new libsinsp state metrics handling
```

fix(userspace/metric): minor fixes in new libsinsp state metrics handling

---

cmake/modules/rules.cmake

/kind cleanup
/area build
Fixes #
Note: `FALCOSECURITY_RULES_FALCO_CHECKSUM` is unchanged, since the file content is identical to last RC.
/milestone 0.37.0
```release-note
update: default ruleset upgrade to version 3.0
```

update(cmake/modules): bump Falco rules to 3.0

---

cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
As per title.
Fixes #
```release-note
update(build): update to libs 0.14.2
```

update(build): update libs to 0.14.2

---

CHANGELOG.md

/kind release
Add changelog for Falco 0.37.0
Fixes #
```release-note
NONE
```

new(docs): add changelog for 0.37.0

---

.github/workflows/release.yaml

/kind bug
/area CI
Actually parse `+driver` when generating release body.
Fixes #
```release-note
NONE
```

fix(ci): fixed release body driver version.

---

.github/workflows/reusable_publish_packages.yaml
scripts/publish-wasm

/kind feature
/area CI
**What this PR does / why we need it**: 
This `PR` will help add a new feature to [falco-playground ](https://github.com/falcosecurity/falco-playground) where a user can select multiple versions of `falco`.  Since we don't support `wasm` "officially" it is a `dev` only package for now.  
**Which issue(s) this PR fixes**:  https://github.com/falcosecurity/falco-playground/issues/13
Fixes #
```release-note
update(CI): publish wasm package as dev-wasm 
```

update(CI): Publish wasm package as wasm-dev

---

scripts/publish-deb
scripts/publish-rpm

/kind bug
/area CI
As per title.
Fixes #
```release-note
NONE
```

fix(ci): update sync in deb and rpm scripts with acl

---

CHANGELOG.md
docker/driver-loader-legacy/docker-entrypoint.sh
docker/driver-loader/docker-entrypoint.sh
docker/falco/docker-entrypoint.sh

/kind release
Cherry picks https://github.com/falcosecurity/falco/pull/3075 from master.
Moreover, bumps CHANGELOG with 0.37.1 entry.
Fixes #
```release-note
NONE
```

sync: release 0.37.x

---

README.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Have been wanting to sync styles between libs and falco readmes for a while and finally got to it, @leogr. 
Fixes #
```release-note
cleanup: minor adjustments to readme, add new testing section
```

cleanup: minor adjustments to readme, add new testing section

---

CHANGELOG.md

/kind release
This PR cherry picks CHANGELOG entry for 0.37.1 from release/0.37.x branch.
Fixes #
```release-note
NONE
```

sync(docs): cherrypick CHANGELOG entry for 0.37.1

---

userspace/falco/app/actions/process_events.cpp
userspace/falco/atomic_signal_handler.h

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
This PR fixes two issues detected around exception throwing:
- exception copy throwing
- throwing in a nothrow function
Reported by cppcheck
Fixes #3084 
```release-note
NONE
```

Improve exception throwing

---

.github/workflows/reusable_test_packages.yaml

/kind cleanup
/area CI
Fixes #
```release-note
NONE
```

cleanup(ci): make use of falcosecurity/testing provided composite action

---

.gitmodules

/kind cleanup
/area build
Fixes #
```release-note
NONE
```

cleanup(submodules): dropped testing submodule.

---

.github/workflows/ci.yml

/kind bug
/area CI
Fixes #
```release-note
NONE
```

fix(ci): test-dev-packages-arm64 needs build-dev-packages-arm64.

---

.github/workflows/codeql.yaml

/kind cleanup
/area CI
Fixes #
```release-note
NONE
```

chore(ci): bumped codeql actions.

---

.github/workflows/reusable_build_dev.yaml

/kind bug
/area CI
Fixes #
```release-note
NONE
```

fix(ci): enforce bundled deps OFF in build-dev CI

---

userspace/engine/falco_engine.cpp
userspace/engine/falco_engine.h
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader_compiler.cpp
userspace/engine/rule_loader_reader.cpp
userspace/falco/app/actions/init_inspectors.cpp
userspace/falco/app/actions/pidfile.cpp

This PR refactors the code around variable and function shadowing. While the code is working, shadowing makes reasoning about it harder.
As a drive by refactor, variables names have been improved around the code changed.
Reported by cppcheck.
> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Fixes #3122
```release-note
NONE …
```

fix(userspace): variable / function shadowing

---

README.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
@falcosecurity/core-maintainers :star_struck: 
```release-note
NONE
```

docs(README.md): Falco Graduates within the CNCF

---

scripts/falcoctl/falcoctl.yaml.in

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
This PR bumps the version of the falco rules installed by falcoctl when using the deb/rpm packages.
`falco-rules:0` lacks the signature, causing falcoctl to fail during the installation process.
Fixes #
```release-note
NONE
```

update(scrips/falcoctl): bump falco-rules version to 3

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h

/kind feature
/area build
As per title
Fixes #
```release-note
update(build): update libs to 026ffe1d8f1b25c6ccdc09afa2c02afdd3e3f672
```

update(build): bump libs to latest master

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
Update libs and driver
Fixes #
```release-note
chore(falco): update falco libs and driver to master (Apr 8th 2024)
```

chore(falco): update falco libs to latest master

---

userspace/falco/app/actions/create_signal_handlers.cpp
userspace/falco/configuration.cpp
userspace/falco/configuration.h

/kind cleanup
/area engine
Followup to #3024: properly watch all configs files.
Fixes #
```release-note
NONE
```

chore(userspace/falco): watch all configs files.

---

.github/workflows/ci.yml
.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_test_packages.yaml

/kind cleanup
/area CI
As per title.
Fixes #
```release-note
NONE
```

update(ci): build both release and debug versions

---

userspace/falco/app/state.h

/kind bug
/area engine
#3184 introduced a bug that causes Falco to segfault
Fixes #3188 
```release-note
fix(userspace/falco): fix state inizialization avoid a crash during hot reload
```

fix(userspace/falco): fix state inizialization.

---

scripts/publish-bin

/kind feature
/area CI
I am not sure why this wasn't done already, maybe someone has additional context?
Fixes #2950
```release-note
new(build): provide signatures for .tar.gz packages
```

new(ci): sign .tar.gz packages

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
Fixes #
```release-note
NONE
```

update(cmake): bump libs to 0.17.0-rc2

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
Fixes #
```release-note
update(cmake): bump libs to 0.17.0 and driver to 7.2.0+driver
```

update(cmake): bump libs and driver to latest release

---

CHANGELOG.md

/area engine
As per title
Fixes #
```release-note
NONE
```

update(docs): update CHANGELOG for 0.38.0

---

CHANGELOG.md

/area engine
As per release process
Fixes #
```release-note
NONE
```

update(docs): update CHANGELOG for 0.38.0 (master branch)

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
Bump libs and driver to [1d31ad615fde258a461da8bd2bee93bcbcbf9a65](https://github.com/falcosecurity/libs/commit/1d31ad615fde258a461da8bd2bee93bcbcbf9a65)
Fixes #
```release-note
NONE
```

update(cmake): bump libs and driver to master.

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/falco_engine_version.h

/kind cleanup
/area build
This PR bumps libs to master, fixing c-ares build error and thus fixing bundled-deps CI.
Fixes #3248 
```release-note
NONE
```

update(cmake): bump libs to master.

---

CHANGELOG.md

/kind cleanup
Fixes #
```release-note
NONE
```

update(docs): update CHANGELOG for 0.38.1

---

ADOPTERS.md

Adds Tulip Retail to the adopters list
NO
```release-note
NONE
```

Add Tulip Retail to adopters list

---

cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
drop the RC :)
Fixes #
```release-note
NONE
```

update(build): libs 0.17.3

---

CHANGELOG.md

/area engine
Getting ready for 0.38.2 release
Fixes #
```release-note
NONE
```

new(docs): add changelog for 0.38.2

---

CHANGELOG.md

/area engine
As per title
Fixes #
```release-note
NONE
```

update(docs): update changelog for 0.38.2 (master branch)

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake

/kind release
/area build
Fixes #
```release-note
update(cmake): bump libs to 0.18.0 and driver to 7.3.0+driver.
```

update(cmake): bump libs to 0.18.0 and driver to 7.3.0+driver.

---

cmake/modules/driver.cmake
cmake/modules/falcosecurity-libs.cmake
userspace/engine/rule_json_schema.h
userspace/falco/app/options.cpp

/kind release
/area build
Cherry picks from master:
* https://github.com/falcosecurity/falco/pull/3328
* https://github.com/falcosecurity/falco/pull/3329
* https://github.com/falcosecurity/falco/pull/3330
Fixes #
```release-note
NONE
```

sync: release 0.39.x

---

cmake/modules/falcosecurity-libs.cmake

/kind bug
/area build
As per title.
Fixes #
```release-note
update(build): update falco libs to 0.18.1
```

chore(build): update libs to 0.18.1

---

userspace/falco/stats_writer.cpp

/kind release
Cherry picks #3344 from master.
Fixes #
```release-note
NONE
```

sync: 0.39.x

---

cmake/modules/falcosecurity-libs.cmake

/kind feature
/area build
As per title
Fixes #
```release-note
update(falco): upgrade libs to 0.18.1
```

chore(build): update libs to 0.18.1 (master branch)

---

.git-blame-ignore-revs

/kind cleanup
/area engine
As per title.
Fixes #
```release-note
NONE
```

cleanup(falco): ignore lint commit

---

userspace/falco/app/options.cpp

/kind cleanup
/area engine
I mean, the default clang-format for this function is not very easy to work with :)
The only other thing we can do is truncate these lines to N characters but I think it's fine like this.
Fixes #
```release-note
NONE
```

cleanup(falco): reformat options::define

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
NONE
```

update(changelog): add changelog for falco 0.39.0

---

CHANGELOG.md

/kind release
Cherrypicks updated changelog from release/0.39.x branch for upcoming 0.39.1 Falco patch release.
Fixes #
```release-note
NONE
```

update(changelog): updated changelog for 0.39.1.

---

.github/workflows/reusable_publish_packages.yaml

/kind bug
/area CI
Should fix master ci.
Fixes #
```release-note
NONE
```

chore(ci): use redhat advised method to check rpmsign success.

---

userspace/engine/indexable_ruleset.h

Subclasses might want to also see when rules are enabled/disabled.
> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
> /area tests
> /area CI
Make enable()/disable() virtual so they can be overridden
Subclasses might want to also see when rules are enabled/disabled.
Fixes #
```release-note
NONE
```

Make enable()/disable() virtual so they can be overridden

---

cmake/modules/yaml-cpp.cmake

/kind release
/area build
Yaml-cpp incorporated 2 patches of mine: https://github.com/jbeder/yaml-cpp/pull/1318 and https://github.com/jbeder/yaml-cpp/pull/1319
While they are still not part of a release yet, i think it might be important to bump yaml-cpp to latest master to fix https://github.com/falcosecurity/falco/issues/3281
Fixes #3281
```release-note
update(cmake): bump yaml-cpp to latest master.
```

update(cmake): bump yaml-cpp to latest master.

---

CHANGELOG.md

/kind release
Fixes #
```release-note
NONE
```

update(changelog): updated changelog for 0.39.2.

---

.github/workflows/release.yaml
.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_publish_docker.yaml

/kind feature
/kind release
/area build
- add attestation for falco
we need to hold this PR until the action supports the pushes to non ghcr.io registries
see Issue https://github.com/actions/attest-build-provenance/issues/80
/hold
/assign @LucaGuerra @leogr 
Fixes #2649
```release-note
add attestation for falco
```

add attestation for falco

---

.github/workflows/reusable_build_packages.yaml

/kind cleanup
/area CI
Fixes #
```release-note
NONE
```

chore(ci): enable jemalloc in musl build.

---

.github/workflows/reusable_build_dev.yaml
.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_build_packages.yaml
.github/workflows/reusable_test_packages.yaml

/kind cleanup
/area CI
As per title
Fixes #
```release-note
NONE
```

update(ci): use 4cpu-16gb arm runners

---

docker/driver-loader-buster/Dockerfile
docker/driver-loader/Dockerfile
docker/falco-debian/Dockerfile
docker/falco/Dockerfile

> /kind bug
/kind cleanup
> /kind design
/area build
> /area engine
> /area tests
> /area CI
Clean-up following-up https://github.com/falcosecurity/libs/pull/2175
Fixes #
```release-note
NONE
```

chore(docker): drop unused libelf dep from container images

---

.github/workflows/reusable_build_docker.yaml
.github/workflows/reusable_publish_docker.yaml

/kind bug
/area CI
`upload-artifact` action since v4 does not allow to upload same artifact name multiple times: https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
Fixes #
```release-note
NONE
```

fix(ci): fixed reusable_build/publish_docker workflows.

---

falco.yaml

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Remove comment about `cri cli arguments`. See: https://github.com/falcosecurity/falco/pull/3329
Fixes #
```release-note
NONE
```

chore(falco.yaml): remove comments about cri cli arguments

---

CHANGELOG.md

/kind release
Fixes #
```release-note
NONE
```

update(docs): update changelog

---

userspace/falco/stats_writer.cpp

/kind bug
/area engine
Fixes #3474
```release-note
fix(userspace/falco): fix jemalloc enabled in minimal build.
```

fix(userspace/falco): fix jemalloc enabled in minimal build.

---

docker/driver-loader-buster/Dockerfile
docker/driver-loader/Dockerfile
docker/falco-debian/Dockerfile
docker/falco/Dockerfile

/kind bug
/area build
After https://github.com/falcosecurity/falco/pull/3488 we need to also change the various `COPY ./docker-entrypoint.sh` lines considering new docker context.
Fixes #
```release-note
NONE
```

fix(docker): fixed entrypoints paths with new docker context.

---

README.md

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
NONE
```

docs(README.md): cleanups and enhancements

---

userspace/falco/falco_metrics.cpp

/kind cleanup
/area engine
Fixes #
```release-note
NONE
```

cleanup(userspace/falco): drop unused `libs_metrics_collector` variable.

---

cmake/modules/rules.cmake

> /kind bug
> /kind design
/kind feature
/area build
> /area engine
> /area tests
> /area CI
Fixes #
TODO: we need to do this again, once we get the final tag. 
I'm using this PR mostly to test the workflow and the latest rules in the Falco Docker image.
```release-note
NONE
```

update(cmake/rules): bump to falco-rules-4.0.0-rc1

---

CHANGELOG.md
userspace/falco/app/actions/process_events.cpp
userspace/falco/falco_metrics.cpp
userspace/falco/falco_metrics.h
userspace/falco/webserver.cpp

/kind cleanup
Cherrypicks https://github.com/falcosecurity/falco/pull/3563 from master.
Fixes #
```release-note
NONE
```

sync: 0.41.0

---

CHANGELOG.md

Cherry-picks b94cda0b12e555051693214d88cf4f24a94e19b1 from `release/0.41.x` branch into master.
Fixes #
```release-note
NONE
```

update(docs): bumped changelog for release 0.41.0, master sync

---

CHANGELOG.md

Cherry picks changelog from release/0.41.x branch
Fixes #
```release-note
NONE
```

update(docs): cherry pick CHANGELOG.

---

falco.yaml

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
Fixes #
```release-note
NONE
```

chore(falco.yaml): clean up plugins config leftover

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
This PR updates the `CHANGELOG.md` file including release 0.41.2 changes.
Fixes #
/milestone 0.41.2
```release-note
NONE
```

update(CHANGELOG.md): release 0.41.2

---

RELEASE.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
This PR fixes the release note checking procedure by updating the filter links and re-words the sentences to make them more explicit. Moreover, it fixes the `rn2md` command documentation.
Fixes #
```release-note
NONE
```

docs(RELEASE.md): fix and reword some parts

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
This PR update `CHANGELOG.md` with changes included in release `0.41.3`.
Fixes #
```release-note
NONE
```

update(CHANGELOG.md): release 0.41.3

---

CHANGELOG.md

> /kind bug
> /kind design
> /area build
> /area engine
> /area tests
> /area CI
This cherry-picks the commit updating the changelog from https://github.com/falcosecurity/falco/pull/3633.
Fixes #
```release-note
NONE
```

update(CHANGELOG.md): release 0.41.3 (cherry-pick)

---

docker/driver-loader-buster/Dockerfile

/kind bug
> /kind design
/area build
> /area engine
> /area tests
> /area CI
As buster reached its EOL, the official debian repo URL doesn't host anymore buster packages info. For this reason, this PR changes, in `driver-loader-buster` Dockerfile, the URLs to point to the `20250630T203427Z` snapshot, which still contains them.
Fixes #
```release-note …
```

build: fix `debian:buster` apt debian repo URL in driver-loader-buster

---

.github/workflows/reusable_build_docker.yaml
docker/driver-loader-buster/Dockerfile
docker/driver-loader/Dockerfile
docker/falco-debian/Dockerfile
docker/falco/Dockerfile

/kind feature
> /area build
> /area CI
When creating docker images for branches e.g. master we cannot reference back the commit.
Fixes #
Nope
```release-note
new(docker): includes sha on the image labels
```

feat: includes sha on the image labels

---

.github/workflows/reusable_build_packages.yaml
unit_tests/falco/test_configuration_config_files.cpp
unit_tests/test_falco_engine.cpp
userspace/engine/evttype_index_ruleset.cpp
userspace/engine/evttype_index_ruleset.h
userspace/engine/falco_utils.cpp
userspace/engine/formats.cpp
userspace/engine/indexable_ruleset.h
userspace/engine/logger.cpp
userspace/engine/rule_loader.cpp
userspace/engine/rule_loader.h
userspace/engine/rule_loader_compiler.cpp
userspace/engine/rule_loader_compiler.h
userspace/engine/rule_loader_reader.cpp
userspace/engine/yaml_helper.h
userspace/falco/app/actions/list_plugins.cpp
userspace/falco/app/actions/load_rules_files.cpp
userspace/falco/app/options.h
userspace/falco/app/restart_handler.cpp
userspace/falco/atomic_signal_handler.h
userspace/falco/configuration.cpp
userspace/falco/grpc_context.h
userspace/falco/grpc_request_context.h
userspace/falco/outputs.h
userspace/falco/outputs_http.cpp
userspace/falco/stats_writer.cpp

> /kind bug
/kind cleanup
> /kind design
> /area build
/area engine
/area tests
> /area CI
This PR implements some of the suggested cleanups from cppchecks.
It's mainly to improve the code base state with regard to the C++ recommendations.
Part of #3082
Part of #3068
Part of #3073
```release-note
NONE
```

Refactor: cppcheck cleanups

---

userspace/engine/logger.cpp

/kind bug
> /kind design
> /area build
/area engine
> /area tests
> /area CI
PR https://github.com/falcosecurity/falco/pull/3649 broke logger date format. This PR fixes it.
Fixes #
```release-note
NONE
```

fix(userspace/engine): fix logger date format
